Repository GoogleChrome/web.dev, pull requests merged in 2019-08, with the labels that each got.

#1232 Disable scheduled posts.
  src/site/_filters/live-posts.js
Labels: cla: yes

#1233 Add missing `id` to `h2.clearfix`
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1236 Fixing some typos
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes

#1216 web-sparkline-chart
  src/lib/components/SparklineChart/_styles.scss
  src/lib/components/SparklineChart/index.js
  src/site/content/en/measure/index.njk
Labels: cla: yes, eng

#1239 katejeffreys add author image
  src/site/content/en/images/authors/katejeffreys.jpg
  src/site/content/en/images/authors/katejeffreys@2x.jpg
Labels: cla: yes

#1237 Replace StackBlitz demos with videos
  src/site/content/en/angular/faster-angular-change-detection/index.md
Labels: cla: yes

#1215 Add Image CDN article
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/image-cdns/image-cdn-requests.jpg
  src/site/content/en/fast/image-cdns/image-cdn-url.jpg
  src/site/content/en/fast/image-cdns/index.md
Labels: cla: no

#1241 Add new cases for the Instruction component
  src/site/_includes/components/Instruction.js
Labels: cla: yes

#1217 lighthouse-scores-stats element
  src/lib/app.js
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/LighthouseScoresContainer/index.js
  src/lib/components/LighthouseScoresMetrics/_styles.scss
  src/lib/components/LighthouseScoresMetrics/index.js
  src/lib/components/LighthouseScoresStats/_styles.scss
  src/lib/components/LighthouseScoresStats/index.js
  src/lib/components/_all.scss
  src/lib/lighthouse/index.js
  src/lib/lighthouse/mapping.js
  src/site/content/en/measure/index.njk
Labels: cla: yes, eng

#1256 Attempt to make Travis happy
  package.json
  src/lib/components/LighthouseScoresContainer/index.js
Labels: cla: yes

#1143 Add "Identify slow third-party JavaScript" post
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/identify-slow-third-party-javascript/audits-panel.png
  src/site/content/en/fast/identify-slow-third-party-javascript/badge-popup.png
  src/site/content/en/fast/identify-slow-third-party-javascript/badges.png
  src/site/content/en/fast/identify-slow-third-party-javascript/execution-time.png
  src/site/content/en/fast/identify-slow-third-party-javascript/hero.jpg
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/long-tasks.jpg
  src/site/content/en/fast/identify-slow-third-party-javascript/network-payloads.png
  src/site/content/en/fast/identify-slow-third-party-javascript/request-blocking.png
  src/site/content/en/fast/identify-slow-third-party-javascript/show-third-party.png
Labels: cla: yes

#1267 Filter draft posts out of topics and collection counts.
  .eleventy.js
  src/site/_filters/remove-drafts.js
  src/site/_includes/components/PathCard.js
  src/site/_includes/path.njk
Labels: cla: yes

#1258 Add support for specifying anchors in headers
  .eleventy.js
  package-lock.json
  package.json
Labels: cla: yes

#1264 Add nvmrc
  .nvmrc
Labels: cla: yes

#1261 /uses-rel-preconnect/ should include link to /preconnect-and-dns-pre…
  src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
Labels: cla: yes

#1273 Finishing touches to lazy load post
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#1275 Escape curly braces in Angular virtual list post.
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/index.md
Labels: cla: yes

#1277 Includes mention of auto lazy-loading with Lite Mode and updates bug link
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#1280 Updates auto lazy loading description in faq - native lazy loading
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#1266 Add Largest Contentful Paint article
  src/site/content/en/blog/largest-contentful-paint/hero.jpg
  src/site/content/en/blog/largest-contentful-paint/index.md
  src/site/content/en/blog/largest-contentful-paint/lcp-cnn-filmstrip.png
  src/site/content/en/blog/largest-contentful-paint/lcp-google-filmstrip.png
  src/site/content/en/blog/largest-contentful-paint/lcp-instagram-filmstrip.png
  src/site/content/en/blog/largest-contentful-paint/lcp-techcrunch-filmstrip.png
Labels: cla: yes

#1296 Update word list
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes

#1304 Escape asides in handbook.
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#1303 meta-description: add early mention of HTML tag
  src/site/content/en/lighthouse-seo/meta-description/index.md
Labels: cla: yes

#1308 Fix some incorrect information in the LCP article
  src/site/content/en/blog/largest-contentful-paint/index.md
Labels: cla: yes

#1309 Add analytics for sharing and tweeting articles.
  src/site/_includes/components/Actions.js
Labels: cla: yes

#1255 Wires up controller for v2
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/LighthouseScoresContainer/index.js
  src/lib/components/LighthouseScoresMeta/_styles.scss
  src/lib/components/LighthouseScoresMeta/index.js
  src/lib/components/LighthouseScoresStats/index.js
  src/lib/components/SparklineChart/index.js
  src/lib/components/UrlChooser/index.js
  src/lib/components/UrlChooserContainer/index.js
  src/lib/components/_all.scss
  src/lib/fb.js
  src/lib/lighthouse-service.js
  src/lib/store.js
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1310 Rename medianPathsPaths
  src/lib/components/SparklineChart/index.js
Labels: cla: yes

#1311 move state subscription to connected/disconnected
  src/lib/components/ProfileSwitcherContainer/index.js
  src/lib/components/UrlChooserContainer/index.js
Labels: cla: yes

#1214 Add 'How to Install Thumbor' blog post
  src/site/content/en/blog/install-thumbor/hero.jpg
  src/site/content/en/blog/install-thumbor/index.md
  src/site/content/en/blog/install-thumbor/systemd.jpg
Labels: cla: yes

#1276 Third-party JS wrap up
  src/site/_includes/components/Instruction.js
  src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/app.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/lazy-load-3g.mp4
  src/site/content/en/fast/codelab-optimize-third-party-javascript/lighthouse-audit.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/network.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/preconnect.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/render-blocking.png
  src/site/content/en/fast/codelab-optimize-third-party-javascript/success.png
  src/site/content/en/fast/efficiently-load-third-party-javascript/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/third-party-usage.png
Labels: cla: yes

#1321 Codelab: Use imgix to optimize images
  src/site/_data/contributors.json
  src/site/_includes/components/Instruction.js
  src/site/content/en/fast/codelab-imgix/imgix-url.png
  src/site/content/en/fast/codelab-imgix/index.md
  src/site/content/en/fast/codelab-imgix/lighthouse.png
  src/site/content/en/images/authors/sherwinski.jpg
  src/site/content/en/images/authors/sherwinski@2x.jpg
Labels: cla: yes

#1281 Tweak example for feature detection and using lazysizes
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#1314 Fix LCP code sample error
  src/site/content/en/blog/largest-contentful-paint/index.md
Labels: cla: yes

#1316 Add an ID to a manual `<h3>` header
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1323 Release image CDN content
  src/site/content/en/blog/install-thumbor/index.md
  src/site/content/en/fast/codelab-cloudinary/cloudname.mp4
  src/site/content/en/fast/codelab-cloudinary/cloudname.webm
  src/site/content/en/fast/codelab-cloudinary/images-not-optimized.png
  src/site/content/en/fast/codelab-cloudinary/index.md
  src/site/content/en/fast/codelab-cloudinary/optimized-images.png
  src/site/content/en/fast/codelab-imgix/index.md
  src/site/content/en/fast/image-cdns/index.md
Labels: cla: yes

#1315 Move articles to 'Build a performance culture' collection
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/how-can-performance-improve-conversion/funnel1.png
  src/site/content/en/fast/how-can-performance-improve-conversion/funnel2.png
  src/site/content/en/fast/how-can-performance-improve-conversion/ga_flow.png
  src/site/content/en/fast/how-can-performance-improve-conversion/hero.jpg
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
  src/site/content/en/fast/how-to-report-metrics/ghostery.png
  src/site/content/en/fast/how-to-report-metrics/hero.jpg
  src/site/content/en/fast/how-to-report-metrics/index.md
  src/site/content/en/fast/how-to-report-metrics/speed_report.png
  src/site/content/en/fast/value-of-speed/analytics-start-date.jpg
  src/site/content/en/fast/value-of-speed/conversion-rate.png
  src/site/content/en/fast/value-of-speed/export-google-sheets.jpg
  src/site/content/en/fast/value-of-speed/extra-revenue-formula.jpg
  src/site/content/en/fast/value-of-speed/hero.jpg
  src/site/content/en/fast/value-of-speed/index.md
  src/site/content/en/fast/value-of-speed/landing-pages-week.jpg
  src/site/content/en/fast/value-of-speed/mobile-versus-relative-chart.jpg
  src/site/content/en/fast/value-of-speed/period-revenue.jpg
  src/site/content/en/fast/value-of-speed/relative-rate-formula.jpg
  src/site/content/en/fast/value-of-speed/relative-versus-absolute.jpg
  src/site/content/en/fast/value-of-speed/revenue-would-have-been.jpg
  src/site/content/en/fast/value-of-speed/thanks-to-increased.jpg
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/funnel.png
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/ga_speed_repeat.png
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/hero.jpg
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/webpagetest_repeat.png
Labels: cla: yes

#1325 Remove link to non existant codelab
  src/site/content/en/blog/install-thumbor/index.md
Labels: cla: yes

#1328 [hot-fix] Update preconnect recommendations
  src/site/content/en/fast/efficiently-load-third-party-javascript/index.md
Labels: cla: yes

#1329 Deep merge tag data.
  .eleventy.js
  src/site/content/en/blog/index.njk
Labels: cla: yes

#1331 Avoid duplicating paths from merged data.
  src/site/_data/postHost.js
  src/site/content/en/en.11tydata.js
  src/site/content/en/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/learn/learn.11tydata.js
Labels: cla: yes

#1339 Add the PWA Angular post
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/creating-pwa-with-angular-cli/home.png
  src/site/content/en/angular/creating-pwa-with-angular-cli/icon.png
  src/site/content/en/angular/creating-pwa-with-angular-cli/index.md
  src/site/content/en/angular/creating-pwa-with-angular-cli/installable.jpg
Labels: cla: yes

#1336 Fix stat alignment
  src/styles/components/_stats.scss
Labels: cla: yes

#1335 Add Truebil Lite post
  src/site/content/en/blog/truebil-lite/chunking.png
  src/site/content/en/blog/truebil-lite/contextual-prompts.png
  src/site/content/en/blog/truebil-lite/default-banners.png
  src/site/content/en/blog/truebil-lite/first-meaningful-paint.png
  src/site/content/en/blog/truebil-lite/grayscale.png
  src/site/content/en/blog/truebil-lite/hero.png
  src/site/content/en/blog/truebil-lite/index.md
  src/site/content/en/blog/truebil-lite/notification.png
  src/site/content/en/blog/truebil-lite/preconnect.png
  src/site/content/en/blog/truebil-lite/prefetch.png
Labels: cla: yes

#1322 New blog post: "Progressive Web Apps in multi-origin sites"
  src/site/content/en/blog/multi-origin-pwas/hero.jpg
  src/site/content/en/blog/multi-origin-pwas/index.md
Labels: cla: yes

#1360 Add thumbnail option and example.
  src/site/_drafts/_template-post/index.md
  src/site/_includes/components/PostCard.js
  src/site/content/en/blog/truebil-lite/index.md
  src/site/content/en/blog/truebil-lite/thumbnail.png
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/markup-post-codelab/index.md
Labels: cla: yes

#1334 [b139150428]: Emerging markets illustration
  src/site/content/en/images/collections/emerging-markets.svg
Labels: cla: yes

#1363 Declutter eleventy's console output.
  package.json
Labels: cla: yes

#1365 Update index.md
  src/site/content/en/accessible/style-focus/index.md
Labels: cla: yes

#1381 Fix contributing issues link
  CONTRIBUTING.md
Labels: cla: yes

#1382 Add "by screenname" to tweets
  .eleventy.js
  package-lock.json
  package.json
  src/site/_filters/expand-contributors.js
  src/site/_includes/components/Actions.js
  src/site/_includes/partials/post.njk
Labels: cla: yes

#1380 Spell out “i.e.”, correct ”URL” character case
  src/site/content/en/blog/multi-origin-pwas/index.md
Labels: cla: yes

#1383 Migrate web-codelab element.
  src/lib/app.js
  src/lib/components/Codelab/_styles.scss
  src/lib/components/Codelab/index.js
  src/lib/components/_all.scss
  src/site/_drafts/_template-codelab/index.md
  src/site/_includes/codelab.njk
  src/styles/pages/_codelab.scss
Labels: cla: yes

#1379 Add guidance about thumbnail images
  src/site/content/en/handbook/use-media/index.md
Labels: cla: yes, task

#1362 Add collection proposal template.
  .github/ISSUE_TEMPLATE/collection_proposal.md
  .github/ISSUE_TEMPLATE/content_proposal.md
Labels: cla: yes

#1419 Add tag overrides to prevent landing pages from being indexed by algolia.
  src/site/content/en/accessible/index.njk
  src/site/content/en/angular/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/discoverable/index.njk
  src/site/content/en/fast/index.njk
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/installable/index.njk
  src/site/content/en/lighthouse-accessibility/index.njk
  src/site/content/en/lighthouse-best-practices/index.njk
  src/site/content/en/lighthouse-performance/index.njk
  src/site/content/en/lighthouse-pwa/index.njk
  src/site/content/en/lighthouse-seo/index.njk
  src/site/content/en/react/index.njk
  src/site/content/en/reliable/index.njk
  src/site/content/en/secure/index.njk
Labels: cla: yes

#1425 watch scss for changes
  package.json
Labels: cla: yes

#1428 Make a list not appear as a procedure.
  src/site/content/en/angular/creating-pwa-with-angular-cli/index.md
Labels: cla: yes

#1418 update axe links to axe 3.3
  src/site/content/en/lighthouse-accessibility/accesskeys/index.md
  src/site/content/en/lighthouse-accessibility/aria-allowed-attr/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-attr/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-children/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-parent/index.md
  src/site/content/en/lighthouse-accessibility/aria-roles/index.md
  src/site/content/en/lighthouse-accessibility/aria-valid-attr-value/index.md
  src/site/content/en/lighthouse-accessibility/aria-valid-attr/index.md
  src/site/content/en/lighthouse-accessibility/audio-caption/index.md
  src/site/content/en/lighthouse-accessibility/button-name/index.md
  src/site/content/en/lighthouse-accessibility/bypass/index.md
  src/site/content/en/lighthouse-accessibility/color-contrast/index.md
  src/site/content/en/lighthouse-accessibility/definition-list/index.md
  src/site/content/en/lighthouse-accessibility/dlitem/index.md
  src/site/content/en/lighthouse-accessibility/document-title/index.md
  src/site/content/en/lighthouse-accessibility/duplicate-id/index.md
  src/site/content/en/lighthouse-accessibility/frame-title/index.md
  src/site/content/en/lighthouse-accessibility/html-has-lang/index.md
  src/site/content/en/lighthouse-accessibility/html-lang-valid/index.md
  src/site/content/en/lighthouse-accessibility/image-alt/index.md
  src/site/content/en/lighthouse-accessibility/input-image-alt/index.md
  src/site/content/en/lighthouse-accessibility/label/index.md
  src/site/content/en/lighthouse-accessibility/layout-table/index.md
  src/site/content/en/lighthouse-accessibility/link-name/index.md
  src/site/content/en/lighthouse-accessibility/list/index.md
  src/site/content/en/lighthouse-accessibility/listitem/index.md
  src/site/content/en/lighthouse-accessibility/meta-refresh/index.md
  src/site/content/en/lighthouse-accessibility/meta-viewport/index.md
  src/site/content/en/lighthouse-accessibility/object-alt/index.md
  src/site/content/en/lighthouse-accessibility/tabindex/index.md
  src/site/content/en/lighthouse-accessibility/td-headers-attr/index.md
  src/site/content/en/lighthouse-accessibility/th-has-data-cells/index.md
  src/site/content/en/lighthouse-accessibility/valid-lang/index.md
  src/site/content/en/lighthouse-accessibility/video-caption/index.md
  src/site/content/en/lighthouse-accessibility/video-description/index.md
Labels: cla: yes

#1432 Added home screen to word list
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes

#1434 [ Bug 1433 ] - typo fixed calcualtes -> calculates
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes

#1447 add node-sass, make optional
  package-lock.json
  package.json
  sass.sh
Labels: cla: yes

#1458 Remove AskChrome banner.
  src/site/content/en/about/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1459 Fix broken mp4s and gif conversion instructions.
  src/site/content/en/blog/backdrop-filter/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/layout-instability-api/index.md
  src/site/content/en/fast/codelab-replace-gifs-with-video/index.md
  src/site/content/en/fast/replace-gifs-with-videos/index.md
Labels: cla: yes

#1464 Remove unrendered character entity
  src/site/content/en/blog/speed-at-scale/index.md
Labels: cla: yes

#1444 fix invalid var name for signed out case
  src/lib/actions.js
Labels: cla: yes

#1312 Normalize SEO audit posts
  src/site/_includes/content/lighthouse-pwa/scoring.njk
  src/site/_includes/content/lighthouse-seo/scoring.njk
  src/site/content/en/_redirects.yaml
  src/site/content/en/discoverable/discoverable.11tydata.js
  src/site/content/en/discoverable/fix-http-status-codes/index.md
  src/site/content/en/discoverable/fix-robot-errors/index.md
  src/site/content/en/discoverable/fix-small-fonts/index.md
  src/site/content/en/discoverable/fix-viewport-tag/index.md
  src/site/content/en/discoverable/pass-lighthouse-seo-audit/index.md
  src/site/content/en/discoverable/remove-browser-plugins/index.md
  src/site/content/en/discoverable/remove-code-blocking-indexing/index.md
  src/site/content/en/discoverable/tell-search-engine-canonical-url/index.md
  src/site/content/en/discoverable/tell-search-translated-pages-equal/index.md
  src/site/content/en/discoverable/write-descriptive-text/index.md
  src/site/content/en/en.11tydata.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/lighthouse-accessibility/document-title/document-title.png
  src/site/content/en/lighthouse-accessibility/document-title/index.md
  src/site/content/en/lighthouse-pwa/viewport/index.md
  src/site/content/en/lighthouse-pwa/viewport/viewport.png
  src/site/content/en/lighthouse-seo/canonical/canonical.png
  src/site/content/en/lighthouse-seo/canonical/index.md
  src/site/content/en/lighthouse-seo/font-size/font-size.png
  src/site/content/en/lighthouse-seo/font-size/index.md
  src/site/content/en/lighthouse-seo/hreflang/hreflang.png
  src/site/content/en/lighthouse-seo/hreflang/index.md
  src/site/content/en/lighthouse-seo/http-status-code/http-status-code.png
  src/site/content/en/lighthouse-seo/http-status-code/index.md
  src/site/content/en/lighthouse-seo/is-crawable/index.md
  src/site/content/en/lighthouse-seo/is-crawable/is-crawable.png
  src/site/content/en/lighthouse-seo/lighthouse-seo.11tydata.js
  src/site/content/en/lighthouse-seo/link-text/index.md
  src/site/content/en/lighthouse-seo/link-text/link-text.png
  src/site/content/en/lighthouse-seo/meta-description/index.md
  src/site/content/en/lighthouse-seo/meta-description/meta-description.png
  src/site/content/en/lighthouse-seo/plugins/index.md
  src/site/content/en/lighthouse-seo/plugins/plugins.png
  src/site/content/en/lighthouse-seo/robots-txt/index.md
  src/site/content/en/lighthouse-seo/robots-txt/robots-txt.png
  src/site/content/en/lighthouse-seo/structured-data/index.md
  src/site/content/en/lighthouse-seo/tap-targets/index.md
  src/site/content/en/lighthouse-seo/tap-targets/tap-targets.png
Labels: cla: yes
