Repository GoogleChrome/web.dev, pull requests merged in 2019-09, with the labels that each got.

#1474 Create a single entrypoint for banners. Enable CDS banner.
  src/site/_data/site.js
  src/site/_includes/components/Banner.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1475 [web.dev/prefers-color-scheme] Fix headings with inline code or clearfix
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1456 content: resource-summary audit reference
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-performance/resource-summary/index.md
  src/site/content/en/lighthouse-performance/resource-summary/resource-summary.jpg
Labels: cla: yes

#1467 Add basic video article.
  src/site/_data/contributors.json
  src/site/content/en/blog/video-basics/hero.jpg
  src/site/content/en/blog/video-basics/index.md
  src/site/content/en/blog/video-basics/no-poster.png
  src/site/content/en/blog/video-basics/poster.png
  src/site/content/en/images/authors/dougsillars.jpg
  src/site/content/en/images/authors/dougsillars@2x.jpg
Labels: cla: yes

#1465 Responsive side nav
  package-lock.json
  package.json
  rollup.config.js
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/Header/_styles.scss
  src/lib/components/Header/index.js
  src/lib/components/SideNav/_styles.scss
  src/lib/components/SideNav/index.js
  src/lib/components/_all.scss
  src/lib/store.js
  src/site/_includes/layout.njk
  src/styles/components/_actions.scss
  src/styles/generic/_all.scss
  src/styles/generic/_main.scss
  src/styles/generic/_shared.scss
Labels: cla: yes

#1471 Add Image and Figure custom tags.
  .eleventy.js
  src/site/_data/site.js
  src/site/_includes/components/helpers.js
  src/site/_includes/components/tags/Image.js
  src/site/_includes/components/tags/README.md
  src/styles/components/_images.scss
Labels: cla: yes

#1478 Fix typo in lighthouse-performance / redirects
  src/site/content/en/lighthouse-performance/redirects/index.md
Labels: cla: yes

#1457 add third-party-summary reference
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-performance/third-party-summary/index.md
  src/site/content/en/lighthouse-performance/third-party-summary/third-party-summary.png
Labels: cla: yes

#1477 update basic video article
  src/site/content/en/blog/video-basics/index.md
Labels: cla: yes

#1484 Make focus color contrast conformant
  src/styles/components/_author.scss
  src/styles/devsite/_vetos.scss
  src/styles/generic/_shared.scss
  src/styles/settings/_colors.scss
Labels: cla: yes

#1468 New blog post: "Prefetch resources to speed up future navigations"
  src/site/content/en/blog/link-prefetch/index.md
  src/site/content/en/blog/link-prefetch/prefetch.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/index.md
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-five.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-four.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-one.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-seven.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-six.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-three.png
  src/site/content/en/fast/codelab-two-ways-to-prefetch/network-panel-two.png
Labels: cla: yes

#1494 Fix comments typo in eleventy config
  .eleventy.js
Labels: cla: yes

#1506 Update the preload post
  src/site/content/en/fast/preload-critical-assets/console-warning.png
  src/site/content/en/fast/preload-critical-assets/index.md
  src/site/content/en/fast/preload-critical-assets/network-waterfall-after.png
  src/site/content/en/fast/preload-critical-assets/network-waterfall-before.png
  src/site/content/en/fast/third-party-javascript/index.md
Labels: cla: yes

#1508 Allow angle brackets, quotes, and markdown in post titles.
  .eleventy.js
  src/site/_filters/md.js
  src/site/_filters/posts-lighthouse-json.js
  src/site/_includes/codelab.njk
  src/site/_includes/components/CodelabsCallout.js
  src/site/_includes/components/PostCard.js
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/topic.njk
  src/site/content/en/fast/codelab-two-ways-to-prefetch/index.md
  src/site/content/en/lighthouse-accessibility/input-image-alt/index.md
Labels: cla: yes

#1378 Normalize "code splitting" punctuation
  src/site/content/en/angular/get-started-optimize-angular/index.md
  src/site/content/en/angular/route-level-code-splitting-in-angular/index.md
  src/site/content/en/angular/route-preloading-in-angular/index.md
  src/site/content/en/blog/predictive-prefetching/index.md
  src/site/content/en/blog/truebil-lite/index.md
  src/site/content/en/fast/codelab-code-splitting/index.md
  src/site/content/en/fast/codelab-preload-critical-assets/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/preload-critical-assets/index.md
  src/site/content/en/fast/reduce-javascript-payloads-with-code-splitting/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/handbook/word-list/index.md
  src/site/content/en/lighthouse-performance/bootup-time/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/mainthread-work-breakdown/index.md
  src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/react/prerender-with-react-snap/index.md
Labels: cla: yes

#1533 Update path link code styling
  src/styles/pages/_path.scss
Labels: cla: yes

#1499 Generate Algolia-compatible index, index all at once
  .eleventy.js
  package-lock.json
  package.json
  release.js
  src/site/_collections/algolia-posts.js
  src/site/content/en/algolia.njk
Labels: cla: yes, devsite-migration

#1487 Lighthouse seo updates
  src/site/_includes/content/lighthouse-pwa/scoring.njk
  src/site/_includes/content/lighthouse-seo/scoring.njk
  src/site/content/en/_redirects.yaml
  src/site/content/en/discoverable/discoverable.11tydata.js
  src/site/content/en/discoverable/fix-http-status-codes/index.md
  src/site/content/en/discoverable/fix-robot-errors/index.md
  src/site/content/en/discoverable/fix-small-fonts/index.md
  src/site/content/en/discoverable/fix-viewport-tag/index.md
  src/site/content/en/discoverable/pass-lighthouse-seo-audit/index.md
  src/site/content/en/discoverable/remove-browser-plugins/index.md
  src/site/content/en/discoverable/remove-code-blocking-indexing/index.md
  src/site/content/en/discoverable/tell-search-engine-canonical-url/index.md
  src/site/content/en/discoverable/tell-search-translated-pages-equal/index.md
  src/site/content/en/discoverable/write-descriptive-text/index.md
  src/site/content/en/en.11tydata.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/lighthouse-accessibility/document-title/document-title.png
  src/site/content/en/lighthouse-accessibility/document-title/index.md
  src/site/content/en/lighthouse-pwa/viewport/index.md
  src/site/content/en/lighthouse-pwa/viewport/viewport.png
  src/site/content/en/lighthouse-seo/canonical/canonical.png
  src/site/content/en/lighthouse-seo/canonical/index.md
  src/site/content/en/lighthouse-seo/font-size/font-size.png
  src/site/content/en/lighthouse-seo/font-size/index.md
  src/site/content/en/lighthouse-seo/hreflang/hreflang.png
  src/site/content/en/lighthouse-seo/hreflang/index.md
  src/site/content/en/lighthouse-seo/http-status-code/http-status-code.png
  src/site/content/en/lighthouse-seo/http-status-code/index.md
  src/site/content/en/lighthouse-seo/is-crawable/index.md
  src/site/content/en/lighthouse-seo/is-crawable/is-crawable.png
  src/site/content/en/lighthouse-seo/lighthouse-seo.11tydata.js
  src/site/content/en/lighthouse-seo/link-text/index.md
  src/site/content/en/lighthouse-seo/link-text/link-text.png
  src/site/content/en/lighthouse-seo/meta-description/index.md
  src/site/content/en/lighthouse-seo/meta-description/meta-description.png
  src/site/content/en/lighthouse-seo/plugins/index.md
  src/site/content/en/lighthouse-seo/plugins/plugins.png
  src/site/content/en/lighthouse-seo/robots-txt/index.md
  src/site/content/en/lighthouse-seo/robots-txt/robots-txt.png
  src/site/content/en/lighthouse-seo/structured-data/index.md
  src/site/content/en/lighthouse-seo/tap-targets/index.md
  src/site/content/en/lighthouse-seo/tap-targets/tap-targets.png
Labels: cla: yes

#1496 basic Analytics updates
  src/lib/analytics.js
  src/lib/app.js
  src/lib/router.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1493 Add personal staging npm script
  package.json
Labels: cla: yes

#1302 Consistently use trailing underscore for @private fields
  src/site/content/en/blog/more-capable-form-controls/index.md
Labels: cla: yes

#1538 Fix typo in the word "affect"
  src/site/content/en/lighthouse-performance/time-to-first-byte/index.md
Labels: cla: yes

#1481 [web.dev/hands-on-portals/] Add info about --user-data-dir recommendation
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#1541 Add w-footer.
  sass.sh
  src/site/_includes/layout.njk
  src/site/_includes/partials/footer.njk
  src/site/content/en/images/lockup-color.png
  src/styles/components/_all.scss
  src/styles/components/_footer.scss
  src/styles/generic/_main.scss
Labels: cla: yes

#1546 Update index.md
  src/site/content/en/blog/largest-contentful-paint/index.md
Labels: cla: yes

#1551 Update index.md
  src/site/content/en/lighthouse-performance/font-display/index.md
Labels: cla: yes

#1531 Proxx 1
  src/site/_data/contributors.json
  src/site/content/en/blog/load-faster-like-proxx/hero.jpg
  src/site/content/en/blog/load-faster-like-proxx/index.md
  src/site/content/en/blog/load-faster-like-proxx/proxx-first-render.jpg
  src/site/content/en/blog/load-faster-like-proxx/proxx-first-render.webp
  src/site/content/en/blog/load-faster-like-proxx/proxx-loaded.jpg
  src/site/content/en/blog/load-faster-like-proxx/proxx-loaded.webp
  src/site/content/en/blog/load-faster-like-proxx/proxx-unoptimized-timeline.png
  src/site/content/en/blog/load-faster-like-proxx/sourcemap.svg
  src/site/content/en/blog/load-faster-like-proxx/ttfb.svg
  src/site/content/en/blog/load-faster-like-proxx/waterfall_opt.png
Labels: cla: yes

#1490 Add "Use Thumbor" blog post
  src/site/content/en/blog/use-thumbor/Use-thumbor0.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor1.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor10.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor11.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor2.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor3.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor4.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor5.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor6.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor7.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor8.jpg
  src/site/content/en/blog/use-thumbor/Use-thumbor9.jpg
  src/site/content/en/blog/use-thumbor/hero.jpg
  src/site/content/en/blog/use-thumbor/index.md
Labels: cla: yes

#1554 [Virtualize large lists with react-window] Trivial typo fix
  src/site/content/en/react/virtualize-long-lists-react-window/index.md
Labels: cla: yes

#1552 V2 snackbar
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/Snackbar/_styles.scss
  src/lib/components/Snackbar/index.js
  src/lib/components/SnackbarContainer/_styles.scss
  src/lib/components/SnackbarContainer/index.js
  src/lib/components/_all.scss
  src/lib/store.js
  src/site/_includes/layout.njk
  src/styles/components/_buttons.scss
Labels: cla: yes

#1549 add compile-css script which runs autoprefixer
  compile-css.js
  package-lock.json
  package.json
  sass.sh
Labels: cla: yes

#1548 add custom Firebase loader
  package-lock.json
  package.json
  src/lib/fb.js
  src/lib/firestore-loader.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1547 include the webcomponents polyfill
  gulpfile.js
  package-lock.json
  package.json
  rollup.config.js
  src/lib/bootstrap-config.js
  src/lib/bootstrap.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1555 Add Preloading responsive images blog post
  src/site/_data/contributors.json
  src/site/content/en/blog/preload-responsive-images/example-1-after.png
  src/site/content/en/blog/preload-responsive-images/example-1-before.png
  src/site/content/en/blog/preload-responsive-images/example-2-after.png
  src/site/content/en/blog/preload-responsive-images/example-2-before.png
  src/site/content/en/blog/preload-responsive-images/example-3.png
  src/site/content/en/blog/preload-responsive-images/hero.jpg
  src/site/content/en/blog/preload-responsive-images/index.md
  src/site/content/en/images/authors/yoavweiss.jpg
  src/site/content/en/images/authors/yoavweiss@2x.jpg
Labels: cla: yes

#1560 Fixing layout instability blog post
  src/site/content/en/blog/fixing-layout-instability/index.md
  src/site/content/en/blog/fixing-layout-instability/layout-comparison.png
  src/site/content/en/blog/fixing-layout-instability/layout-placeholder.png
  src/site/content/en/blog/fixing-layout-instability/layout-shift1.png
  src/site/content/en/blog/fixing-layout-instability/layout-shift2.png
Labels: blog, cla: yes

#1556 Add Details component
  .eleventy.js
  src/site/_includes/components/Details.js
  src/site/_includes/components/DetailsSummary.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_all.scss
  src/styles/components/_details.scss
  src/styles/generic/_all.scss
  src/styles/generic/_details.scss
Labels: cla: yes

#1583 Make content URLs canonical
  server.js
Labels: cla: yes, devsite-migration

#1430 Update compare widget
  .eleventy.js
  src/site/_includes/components/Compare.js
  src/site/_includes/components/CompareCaption.js
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-code/index.md
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/style/index.md
  src/site/content/en/handbook/use-media/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_columns.scss
  src/styles/components/_compare.scss
Labels: cla: yes

#1585 add manifest
  gulpfile.js
  src/images/icon-128x128.png
  src/images/icon-144x144.png
  src/images/icon-152x152.png
  src/images/icon-192x192.png
  src/images/icon-384x384.png
  src/images/icon-512x512.png
  src/images/icon-72x72.png
  src/images/icon-96x96.png
  src/misc/manifest.webmanifest
  src/site/_includes/layout.njk
Labels: cla: yes, devsite-migration
