Repository GoogleChrome/web.dev, pull requests merged in 2019-11, with the labels that each got.

#1813 dedup scroll handler
  src/lib/utils/router.js
Labels: cla: yes

#1817 Collection for PWAs
  src/site/content/en/images/collections/pwa.svg
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/progressive-web-apps/index.njk
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
Labels: cla: yes

#1812 travis: adjust git depth
  .travis.yml
Labels: cla: yes, eng

#1820 Add code of conduct.
  .remarkignore
  CODE_OF_CONDUCT.md
Labels: cla: yes

#1816 /resource-summary/
  src/site/content/en/lighthouse-performance/resource-summary/index.md
Labels: cla: yes

#1822 Update codeowners.
  .github/CODEOWNERS
Labels: cla: yes

#1825 Add more file types to codeowners.
  .github/CODEOWNERS
Labels: cla: yes

#1798 Move w-blockquote styles to a generic blockquote el style. Fixes #1650
  src/site/_drafts/_template-post/index.md
  src/site/_drafts/intrinsic-layout-overview/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/opensooq-case-study/index.md
  src/site/content/en/blog/truebil-lite/index.md
  src/site/content/en/fast/why-speed-matters/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/sandbox/blockquote/index.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_all.scss
  src/styles/generic/_all.scss
  src/styles/generic/_blockquote.scss
  src/styles/settings/_type.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#1815 Fixes #1282. Output tags inside figcaption the same as pure text
  src/styles/components/_images.scss
Labels: cla: yes

#1814 send pageview for new pages
  src/lib/analytics.js
  src/lib/loader.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1830 Remove unused style include.
  src/site/_includes/styles.njk
Labels: cla: yes

#1831 Fix code in headers.
  src/styles/generic/_code.scss
Labels: cla: yes

#1660 Fix #1630
  src/site/content/en/lighthouse-performance/first-cpu-idle/index.md
  src/site/content/en/lighthouse-performance/first-meaningful-paint/index.md
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: DO NOT MERGE, cla: yes

#1744 Draft: Notification Triggers article
  src/site/content/en/blog/notification-triggers/demo.png
  src/site/content/en/blog/notification-triggers/devtools-displayed.png
  src/site/content/en/blog/notification-triggers/devtools-scheduled.png
  src/site/content/en/blog/notification-triggers/index.md
  src/site/content/en/blog/notification-triggers/record.png
Labels: DO NOT MERGE, capabilities, cla: yes, content proposal

#1763 Add Next.js dynamic imports post
  src/site/content/en/react/nextjs-dynamic-imports/index.md
  src/site/content/en/react/nextjs-dynamic-imports/loading.png
  src/site/content/en/react/nextjs-dynamic-imports/network1.png
  src/site/content/en/react/nextjs-dynamic-imports/network2.png
  src/site/content/en/react/nextjs-dynamic-imports/network3.png
  src/site/content/en/react/nextjs-dynamic-imports/network4.png
  src/site/content/en/react/nextjs-route-prefetching/index.md
  src/site/content/en/react/react.11tydata.js
Labels: cla: yes

#1819 Update installable-manifest post
  src/site/content/en/lighthouse-pwa/installable-manifest/index.md
Labels: cla: yes

#1840 Fix hero images on staging.
  package.json
  src/site/content/en/react/react.11tydata.js
Labels: cla: yes

#1796 Content: AirSHIFT case study
  src/site/_data/contributors.json
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/airshift_visual.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/hackathon.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/hero.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/index.md
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/kibana.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/main-thread-break-down.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/thumbnail.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/user_timing.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/virtualize_after.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/virtualize_before.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/virtualize_results_after.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/virtualize_results_before.png
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/worker.png
  src/site/content/en/images/authors/kento_tsuji.jpg
  src/site/content/en/images/authors/kento_tsuji@2x.jpg
  src/site/content/en/images/authors/satoshi_arai.jpg
  src/site/content/en/images/authors/satoshi_arai@2x.jpg
  src/site/content/en/images/authors/yosuke_furukawa.jpg
  src/site/content/en/images/authors/yosuke_furukawa@2x.jpg
Labels: cla: yes

#1743 Update Wake Lock article
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#1852 #1840 is a lie. This is the real fix.
  package.json
Labels: cla: yes

#1845 Fix v2 layout bugs
  src/lib/components/Header/_styles.scss
  src/lib/components/SigninButton/_styles.scss
  src/lib/components/_all.scss
  src/site/_includes/components/Instruction.js
  src/site/_includes/partials/footer.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_buttons.scss
  src/styles/components/_compare.scss
  src/styles/components/_footer.scss
  src/styles/generic/_blockquote.scss
  src/styles/generic/_code.scss
  src/styles/generic/_lists.scss
  src/styles/generic/_tables.scss
Labels: cla: yes

#1832 Content: OYO Case Study
  src/site/_data/contributors.json
  src/site/content/en/blog/oyo-case-study/index.md
  src/site/content/en/images/authors/ajain.jpg
  src/site/content/en/images/authors/ajain@2x.jpg
Labels: cla: yes

#1853 Fix browser support in OYO post
  src/site/content/en/blog/oyo-lite-twa/index.md
Labels: cla: yes

#1858 Update page description when we load new content.
  src/lib/loader.js
  src/site/_includes/components/Meta.js
Labels: cla: yes

#1826 Cookies without a `SameSite` default fix
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes

#1860 don't eat hash
  src/lib/loader.js
  src/lib/utils/router.js
Labels: cla: yes

#1854 Add the initial metrics section overview
  src/site/content/en/images/collections/metrics.svg
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/index.njk
  src/site/content/en/metrics/metrics.11tydata.js
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
Labels: cla: yes

#1829 Add new web share article.
  src/site/content/en/blog/share-like-a-native/hero.jpg
  src/site/content/en/blog/share-like-a-native/index.md
  src/site/content/en/blog/share-like-a-native/santa-phone.png
  src/site/content/en/blog/share-like-a-native/wst-send.png
Labels: cla: yes

#1828 Share target
  src/site/content/en/blog/receive-shared-data/hero.jpg
  src/site/content/en/blog/receive-shared-data/index.md
  src/site/content/en/blog/receive-shared-data/wst-receive.png
  src/site/content/en/blog/receive-shared-data/wst-send.png
Labels: cla: no

#1834 Page responds to user input in 50 milliseconds not 5 seconds
  src/site/content/en/lighthouse-performance/interactive/index.md
Labels: cla: yes

#1844 Add some extra information around views.
  src/site/content/en/blog/vr-comes-to-the-web/index.md
Labels: cla: yes

#1843 Writing teacher fixes.
  src/site/content/en/secure/security-not-scary/index.md
Labels: cla: yes

#1861 Launch the Next.js docs
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/index.md
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/loading.png
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/network1.png
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/network2.png
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/network3.png
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/network4.png
  src/site/content/en/react/how-amp-can-guarantee-fastness-in-your-nextjs-app/index.md
  src/site/content/en/react/how-to-use-amp-in-nextjs/index.md
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
  src/site/content/en/react/react.11tydata.js
  src/site/content/en/react/route-prefetching-in-nextjs/console.png
  src/site/content/en/react/route-prefetching-in-nextjs/index.md
  src/site/content/en/react/route-prefetching-in-nextjs/network1.png
  src/site/content/en/react/route-prefetching-in-nextjs/network2.png
  src/site/content/en/react/route-prefetching-in-nextjs/network3.png
  src/site/content/en/react/route-prefetching-in-nextjs/pages-directory.png
Labels: cla: yes

#1836 adaptive-service-based-on-network-quality url 404
  src/site/content/en/lighthouse-performance/time-to-first-byte/index.md
Labels: cla: yes

#1863 Update share article urls and swap in new hero.
  src/site/content/en/blog/share-like-a-native/hero.jpg
  src/site/content/en/blog/web-share-target/hero.jpg
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share-target/wst-receive.png
  src/site/content/en/blog/web-share-target/wst-send.png
  src/site/content/en/blog/web-share/hero.jpg
  src/site/content/en/blog/web-share/index.md
  src/site/content/en/blog/web-share/santa-phone.png
  src/site/content/en/blog/web-share/wst-send.png
Labels: cla: yes

#1827 Fix typo
  src/site/content/en/blog/samesite-cookie-recipes/index.md
Labels: cla: yes

#1856 Add all metrics docs
  src/lib/utils/router.js
  src/site/content/en/_redirects.yaml
  src/site/content/en/blog/layout-instability-api/hero.jpg
  src/site/content/en/blog/layout-instability-api/index.md
  src/site/content/en/images/collections/metrics.svg
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/cls/layout-shift-1.png
  src/site/content/en/metrics/cls/layout-shift-2.png
  src/site/content/en/metrics/cls/layout-shift-3.png
  src/site/content/en/metrics/cls/layout-shift-4.png
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/fcp/fcp-filmstrip.png
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/fid-base.svg
  src/site/content/en/metrics/fid/fid-fcp-tti.svg
  src/site/content/en/metrics/fid/fid-full.svg
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/hero.jpg
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/lcp/lcp-cnn-filmstrip.png
  src/site/content/en/metrics/lcp/lcp-google-filmstrip.png
  src/site/content/en/metrics/lcp/lcp-instagram-filmstrip.png
  src/site/content/en/metrics/lcp/lcp-techcrunch-filmstrip.png
  src/site/content/en/metrics/metrics.11tydata.js
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tbt/tbt-all-tasks.svg
  src/site/content/en/metrics/tbt/tbt-blocking-time.svg
  src/site/content/en/metrics/tti/index.md
  src/site/content/en/metrics/tti/tti-timeline.svg
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
Labels: cla: yes

#1864 Revert TTI doc changes for consistency
  src/site/content/en/metrics/tti/index.md
Labels: cla: yes

#1869 Remove Fig. from template post.
  src/site/_drafts/_template-post/index.md
Labels: cla: yes

#1865 Add Web Bundles article
  src/site/_data/contributors.json
  src/site/content/en/blog/web-bundles/chromeflag.png
  src/site/content/en/blog/web-bundles/hero.png
  src/site/content/en/blog/web-bundles/index.md
  src/site/content/en/blog/web-bundles/webbundle.png
  src/site/content/en/images/authors/kenjibaheux.jpg
  src/site/content/en/images/authors/kenjibaheux@2x.jpg
  src/site/content/en/tags.yml
Labels: CDS, cds wave 3, cla: yes

#1873 Web share article: Correct link to web share target article
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#1872 [Async Clipboard] Use modern syntax
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
Labels: cla: yes

#1835 Add new Periodic Background Sync article.
  src/site/content/en/blog/periodic-background-sync/1-record.png
  src/site/content/en/blog/periodic-background-sync/2-record-result.png
  src/site/content/en/blog/periodic-background-sync/3-sw-panel.png
  src/site/content/en/blog/periodic-background-sync/4-experiments.png
  src/site/content/en/blog/periodic-background-sync/5-settings.png
  src/site/content/en/blog/periodic-background-sync/6-checkbox.png
  src/site/content/en/blog/periodic-background-sync/7-panel.png
  src/site/content/en/blog/periodic-background-sync/hero.jpg
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: cla: yes

#1881 Add CDS day 1 livestream; YouTube lazy load iframe
  src/site/_includes/components/YouTube.js
  src/site/content/en/index.njk
Labels: cla: yes

#1892 flip CDS livestream to day 2
  src/site/content/en/index.njk
Labels: cla: yes

#1888 fix go/bundle example for current usage
  src/site/content/en/blog/web-bundles/index.md
Labels: cla: yes

#1894 fix typo
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/index.md
Labels: cla: yes

#1906 Fix typos in perception-toolkit
  src/site/content/en/blog/perception-toolkit/index.md
Labels: cla: yes

#1897 Fix a few editorial issues in the metrics docs
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
Labels: cla: yes

#1911 Typo fix in blog/web-bundles
  src/site/content/en/blog/web-bundles/index.md
Labels: cla: yes

#1890 Update the Lighthouse CI url
  src/site/content/en/fast/performance-budgets-101/index.md
Labels: cla: yes

#1884 Add await to PBS examples
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: cla: yes

#1912 Add blockquote shortcode
  .eleventy.js
  src/site/_includes/components/Blockquote.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/generic/_code.scss
Labels: cla: yes

#1913 Add wrap up text for CDS
  src/site/content/en/index.njk
Labels: cla: yes

#1887 misc: update lhci to 0.3.x
  tools/lhci/.lighthouserc
  tools/lhci/run-lighthouse-ci.sh
Labels: cla: yes

#1918 feat: add underline to links of codelab, learn and blog pages, fixes #1683
  .sasslintrc
  src/styles/generic/_links.scss
Labels: cla: yes

#1846 disallow www.web.dev, redirect to naked domain
  server.js
  src/misc/nuke-sw.js
Labels: cla: yes

#1921 Fix a typo.
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes

#1893 Change "What is a good TTI" to "What is a good TBT"
  src/site/content/en/metrics/tbt/index.md
Labels: cla: yes

#1919 chore: rev lighthouse-keeper version.
  src/lib/lighthouse-service.js
Labels: cla: yes

#1905 Update handbook components post
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#1920 feat: add support for `subtopics` inside of site content `topics`, fixes #1137
  src/site/_includes/components/ArticleNavigation.js
  src/site/_includes/components/PathCard.js
  src/site/_includes/partials/item.njk
  src/site/_includes/partials/topic.njk
  src/site/_includes/path.njk
  src/styles/components/_all.scss
  src/styles/components/_topic.scss
Labels: cla: yes

#1929 Add todomvc mp4 and some sample web bundles
  src/site/content/en/blog/web-bundles/hero.png
  src/site/content/en/blog/web-bundles/index.md
Labels: cla: yes

#1777 Added image optimization survey blog post
  src/site/content/en/blog/image-optimization-survey-2019/dimensions-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/dimensions.jpg
  src/site/content/en/blog/image-optimization-survey-2019/framework-or-library-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/framework-or-library.jpg
  src/site/content/en/blog/image-optimization-survey-2019/index.md
  src/site/content/en/blog/image-optimization-survey-2019/lazyload-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/lazyload.jpg
  src/site/content/en/blog/image-optimization-survey-2019/picture-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/picture.jpg
  src/site/content/en/blog/image-optimization-survey-2019/platform-or-cms-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/platform-or-cms.jpg
  src/site/content/en/blog/image-optimization-survey-2019/png-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/png.jpg
  src/site/content/en/blog/image-optimization-survey-2019/sector.jpg
  src/site/content/en/blog/image-optimization-survey-2019/service-or-cdn-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/service-or-cdn.jpg
  src/site/content/en/blog/image-optimization-survey-2019/srcset-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/srcset.jpg
  src/site/content/en/blog/image-optimization-survey-2019/webp-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/webp.jpg
Labels: cla: yes

#1904 [prefers-color-scheme article] Add info about DevTools debugging and Puppeteer testing
  src/site/content/en/blog/prefers-color-scheme/devtools-emulate.png
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1891 Update Poki description
  src/site/content/en/blog/ready-player-web/index.md
Labels: cla: yes

#1708 Fix typo
  src/site/_includes/content/origin-trials.njk
  src/site/content/en/fast/reduce-javascript-payloads-with-code-splitting/index.md
  src/site/content/en/fast/reduce-network-payloads-using-text-compression/index.md
  src/site/content/en/metrics/custom-metrics/index.md
Labels: cla: yes

#1945 Remove `truncate` from native file system post
  src/site/content/en/blog/native-file-system/index.md
Labels: capabilities, cla: yes

#1937 Remove occurrences of the `intrinsicsize` attribute (Fixes #1435)
  src/site/content/en/blog/native-lazy-loading/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes
