Repository GoogleChrome/web.dev, pull requests merged in 2019-06, with the labels that each got.

#960 Address Phil Walton's feedback (fixes #954)
  src/site/content/en/blog/long-tasks-devtools/index.md
Labels: cla: yes

#962 Fix for typo
  src/site/content/en/lighthouse-performance/mainthread-work-breakdown/index.md
Labels: cla: yes

#947 Blog: JS and Search (I/O 19)
  src/site/content/en/blog/javascript-and-google-search-io-2019/evergreen-googlebot.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/googlebot-process.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/hero.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/index.md
  src/site/content/en/blog/javascript-and-google-search-io-2019/lighthouse-seo-audit-report.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/mobile-friendly-test-js-error.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/mobile-friendly-test-rendered-html.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/search-console-url-inspection-tool.png
  src/site/content/en/blog/javascript-and-google-search-io-2019/spa-kittens.png
Labels: cla: yes

#992 Link "Defer unused CSS" guide to "Extract critical CSS" guide.
  src/site/content/en/fast/defer-non-critical-css/index.md
Labels: cla: no

#996 Add initial Layout Instability API draft
  src/site/content/en/blog/layout-instability-api/hero.jpg
  src/site/content/en/blog/layout-instability-api/index.md
  src/site/content/en/blog/layout-instability-api/layout-shift-1.png
  src/site/content/en/blog/layout-instability-api/layout-shift-2.png
  src/site/content/en/blog/layout-instability-api/layout-shift-3.png
Labels: DO NOT MERGE, cla: yes

#967 Add YouTube & Media Capabilities user study post
  src/site/content/en/blog/youtube-media-capabilities/hero.jpg
  src/site/content/en/blog/youtube-media-capabilities/index.md
Labels: cla: yes

#1002 Fix double sentence in youtube-media-capabilities
  src/site/content/en/blog/youtube-media-capabilities/index.md
Labels: cla: yes

#990 Add Instruction component.
  .eleventy.js
  src/site/_filters/capitalize.js
  src/site/_filters/title-case.js
  src/site/_includes/components/Aside.js
  src/site/_includes/components/Instruction.js
  src/site/content/en/images/glitch/fullscreen.svg
  src/site/content/en/sandbox/index.md
  src/site/content/en/sandbox/instruction/index.md
Labels: cla: no

#1006 Add YouTube shortcode.
  .eleventy.js
  src/site/_includes/components/YouTube.js
  src/site/content/en/sandbox/index.md
  src/site/content/en/sandbox/youtube/index.md
  src/styles/components/_all.scss
  src/styles/components/_youtube.scss
Labels: cla: yes

#999 Add LightWallet article
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/lightwallet.png
Labels: cla: yes

#1001 Blog(layout): Intrinsic layout overview
  src/site/_data/contributors.json
  src/site/_drafts/intrinsic-layout-overview/hero.jpg
  src/site/_drafts/intrinsic-layout-overview/index.md
  src/site/content/en/images/authors/adamargyle.jpg
Labels: cla: no

#1007 Web components @ I/O 2019 blog post.
  src/site/content/en/blog/web-components-io-2019/hero.jpg
  src/site/content/en/blog/web-components-io-2019/index.md
  src/site/content/en/blog/web-components-io-2019/material-design.png
  src/site/content/en/blog/web-components-io-2019/usage-graph.png
Labels: cla: yes

#1003 Update examples for "SameSite cookies explained blog"
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes

#1015 Don't increment numbered lists when there are nested lists.
  src/styles/generic/_lists.scss
Labels: cla: yes

#1019 Stopgap for nested list CSS bug
  src/site/content/en/blog/value-of-speed/index.md
Labels: cla: yes

#1022 fix: link to Lighthouse GitHub repo
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
Labels: cla: yes

#1024 fix typo: "elememnt" -> "element"
  src/site/content/en/lighthouse-accessibility/aria-allowed-attr/index.md
  src/site/content/en/lighthouse-accessibility/focus-traps/index.md
Labels: cla: yes

#989 "Bringing service workers to Google Search" case study
  src/site/content/en/blog/google-search-sw/hero.jpg
  src/site/content/en/blog/google-search-sw/index.md
  src/site/content/en/blog/google-search-sw/no-preload.png
  src/site/content/en/blog/google-search-sw/offline-screenshot.png
  src/site/content/en/blog/google-search-sw/with-preload.png
  src/site/content/en/images/authors/jeffposnick.jpg
Labels: cla: yes

#1029 Restore the edits to the Google Search case study
  src/site/content/en/blog/google-search-sw/index.md
Labels: cla: yes

#1031 Remove strong stags
  .gitignore
  src/site/content/en/fast/codelab-text-compression/index.md
Labels: cla: yes

#1032 Move devtools post to blog.
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-1.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-2.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-3.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-4.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-5.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-6.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-7.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/discover-performance-opportunities-with-lighthouse-8.png
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/hero.jpg
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/index.md
Labels: cla: yes

#1030 👌 IMPROVE: Valid SPDX License Expression
  package.json
Labels: cla: yes

#1043 Avoid 'the one on the left'
  src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md
Labels: cla: yes

#1037 Move perf budgets to start of /fast
  src/site/content/en/blog/speed-at-scale/index.md
  src/site/content/en/fast/fast.11tydata.js
Labels: cla: yes

#1042 Typo: optimzation
  src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md
Labels: cla: yes

#1021 `prefers-color-scheme` article for web.dev
  src/site/content/en/blog/prefers-color-scheme/android.png
  src/site/content/en/blog/prefers-color-scheme/closeview.png
  src/site/content/en/blog/prefers-color-scheme/dark-mode-toggle-dark.png
  src/site/content/en/blog/prefers-color-scheme/dark-mode-toggle-light.png
  src/site/content/en/blog/prefers-color-scheme/dark.png
  src/site/content/en/blog/prefers-color-scheme/green-screen.jpg
  src/site/content/en/blog/prefers-color-scheme/hero-dark.png
  src/site/content/en/blog/prefers-color-scheme/hero-light.png
  src/site/content/en/blog/prefers-color-scheme/hero.jpg
  src/site/content/en/blog/prefers-color-scheme/icons-dark.png
  src/site/content/en/blog/prefers-color-scheme/icons-light.png
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/prefers-color-scheme/ios.jpg
  src/site/content/en/blog/prefers-color-scheme/light.png
  src/site/content/en/blog/prefers-color-scheme/macosx.png
  src/site/content/en/blog/prefers-color-scheme/smartphone-in-bed.jpg
  src/site/content/en/blog/prefers-color-scheme/unsupported.png
  src/site/content/en/blog/prefers-color-scheme/windows10.png
  src/site/content/en/blog/prefers-color-scheme/word-processing.jpg
  src/site/content/en/blog/prefers-color-scheme/worldwideweb.png
  src/styles/overrides/_all.scss
  src/styles/overrides/_clearfix.scss
Labels: beta blog, cla: yes

#1049 Fix all instances of "resilient/resilience"
  src/site/content/en/about/index.njk
  src/site/content/en/reliable/codelab-service-workers/index.md
  src/site/content/en/reliable/reliable.11tydata.js
  src/site/content/en/reliable/runtime-caching-with-workbox/index.md
  src/site/content/en/reliable/service-workers-cache-storage/index.md
Labels: cla: yes

#1077 Show updates on posts/codelabs. Fixes #1036.
  src/site/_drafts/_template-codelab/index.md
  src/site/_drafts/_template-post/index.md
  src/site/_includes/codelab.njk
  src/site/_includes/partials/post.njk
Labels: cla: yes

#1078 Fix h4 size and color.
  src/styles/settings/_type.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#1079 Add referenced SVG tip to prefers-color-scheme article
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1040 Add getting started angular article
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/get-started-optimize-angular/get-started-optimize-angular.jpg
  src/site/content/en/angular/get-started-optimize-angular/index.md
Labels: cla: yes
