Repository GoogleChrome/web.dev, pull requests merged in 2019-12, with the labels that each got.

#1954 fix(Snackbar): set max-width to only on sizes larger than smart phones, fixes #1930
  src/lib/components/Snackbar/_styles.scss
Labels: cla: yes

#1956 fix(w-card): set fixed height of `.w-card` when on breakpoints smaller than smart phones, fixes #1653
  src/styles/components/_card.scss
Labels: cla: yes

#1938 feat(CopyCode): add custom element to allow code blocks to be copied, fixes #1871
  .eleventy.js
  src/images/icons/file_copy.svg
  src/lib/app.js
  src/lib/components/CopyCode/index.js
  src/lib/components/CopyCode/styles.scss
  src/lib/components/_all.scss
Labels: cla: yes

#1638 Fixes to Code splitting w/ React.lazy and Suspense
  src/site/content/en/react/code-splitting-suspense/index.md
Labels: cla: yes

#1942 Update release information re SameSite cookies.
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes

#1645 Fixes to Precaching in Create React App w/ Workbox
  src/site/content/en/react/precache-with-workbox-react/index.md
Labels: cla: yes

#1737 Updates Badging API article for new origin trial
  src/site/content/en/blog/badging-api/index.md
Labels: Chrome 79, capabilities, cla: yes

#1952 Remove list of image CDNs
  src/site/content/en/fast/image-cdns/index.md
Labels: cla: yes

#1949 [Notification Triggers] Update Chrome version for OT
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#1958 Add "prefers-color-scheme" to title
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1965 fix(footer): increase footer links' padding to 100% SEO on LH, fixes #1767
  src/styles/components/_footer.scss
Labels: cla: yes

#1957 feat(PostCard): display author(s) and date of post in a card, fixes #1330
  src/site/_includes/components/PostCard.js
  src/styles/components/_author.scss
  src/styles/components/_post-card.scss
Labels: cla: yes

#1970 fix(table): tables written in markdown are automatically wrapped by `<div class="w-table-wrapper">`, fixes #1917
  .eleventy.js
Labels: cla: yes

#1969 Update Word list
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes

#1977 Fix typo in what-is-speed graphic.
  src/site/content/en/fast/what-is-speed/speed-feedback.png
Labels: cla: yes

#1849 Migrate prefers-reduced-motion article from WebFu
  src/site/content/en/blog/prefers-reduced-motion/android-remove-animations.png
  src/site/content/en/blog/prefers-reduced-motion/hero.jpg
  src/site/content/en/blog/prefers-reduced-motion/ice-skating.jpg
  src/site/content/en/blog/prefers-reduced-motion/index.md
  src/site/content/en/blog/prefers-reduced-motion/macos-reduce-motion.png
  src/site/content/en/blog/prefers-reduced-motion/prefers-reduced-motion.png
  src/site/content/en/tags.yml
Labels: cla: yes

#1966 feat(SnackbarContainer): only allow PWA install prompt if cookies accepted, fixes #1771
  src/lib/components/SnackbarContainer/index.js
Labels: cla: yes

#1989 Remove survey reminder action.
  .github/workflows/issue-closed-workflow.yml
Labels: cla: yes

#1985 Top-align <td> elements
  src/site/content/en/blog/fast-ads-matter/index.md
  src/site/content/en/fast/codelab-density-descriptors/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/your-first-performance-budget/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/generic/_tables.scss
Labels: cla: yes

#1998 Fix multiple broken URLs that result in 404s
  src/site/content/en/lighthouse-accessibility/accessibility-scoring/index.md
  src/site/content/en/lighthouse-performance/critical-request-chains/index.md
  src/site/content/en/lighthouse-pwa/installable-manifest/index.md
  src/site/content/en/lighthouse-pwa/load-fast-enough-for-pwa/index.md
Labels: cla: yes

#1997 Remove link that 404s
  src/site/content/en/blog/stale-while-revalidate/index.md
Labels: cla: yes

#1996 Spelling error: change recevied to received
  src/site/content/en/blog/badging-api/index.md
Labels: cla: yes

#2003 Remove data from image optimization survey post
  src/site/content/en/blog/image-optimization-survey-2019/dimensions-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/dimensions.jpg
  src/site/content/en/blog/image-optimization-survey-2019/framework-or-library-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/framework-or-library.jpg
  src/site/content/en/blog/image-optimization-survey-2019/index.md
  src/site/content/en/blog/image-optimization-survey-2019/lazyload-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/lazyload.jpg
  src/site/content/en/blog/image-optimization-survey-2019/picture-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/picture.jpg
  src/site/content/en/blog/image-optimization-survey-2019/platform-or-cms-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/platform-or-cms.jpg
  src/site/content/en/blog/image-optimization-survey-2019/png-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/png.jpg
  src/site/content/en/blog/image-optimization-survey-2019/sector.jpg
  src/site/content/en/blog/image-optimization-survey-2019/service-or-cdn-which.jpg
  src/site/content/en/blog/image-optimization-survey-2019/service-or-cdn.jpg
  src/site/content/en/blog/image-optimization-survey-2019/srcset-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/srcset.jpg
  src/site/content/en/blog/image-optimization-survey-2019/webp-if-not.jpg
  src/site/content/en/blog/image-optimization-survey-2019/webp.jpg
Labels: cla: yes

#1979 Update 'SameSite cookies explained' for Chrome 80.
  src/site/content/en/blog/samesite-cookie-recipes/chrome-console-warning.png
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: Chrome 80, beta blog, cla: yes

#1987 [Wake Lock article] Add origin trial info
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#1902 Explain how to fix FOIT with Google fonts
  src/site/content/en/lighthouse-performance/font-display/index.md
Labels: cla: yes

#991 Instruction fixes
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/index.md
  src/site/content/en/discoverable/codelab-fix-sneaky-404/index.md
  src/site/content/en/discoverable/pass-lighthouse-seo-audit/index.md
  src/site/content/en/fast/apply-instant-loading-with-prpl/index.md
  src/site/content/en/fast/avoid-invisible-text/index.md
  src/site/content/en/fast/codelab-adapt-video-to-image-serving-based-on-network-quality/index.md
  src/site/content/en/fast/codelab-art-direction/index.md
  src/site/content/en/fast/codelab-avoid-invisible-text/index.md
  src/site/content/en/fast/codelab-cloudinary/index.md
  src/site/content/en/fast/codelab-code-splitting/index.md
  src/site/content/en/fast/codelab-density-descriptors/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/codelab-imagemin-grunt/index.md
  src/site/content/en/fast/codelab-imagemin-gulp/index.md
  src/site/content/en/fast/codelab-imagemin-webpack/index.md
  src/site/content/en/fast/codelab-preload-critical-assets/index.md
  src/site/content/en/fast/codelab-preload-web-fonts/index.md
  src/site/content/en/fast/codelab-remove-unused-code/index.md
  src/site/content/en/fast/codelab-replace-gifs-with-video/index.md
  src/site/content/en/fast/codelab-serve-images-correct-dimensions/index.md
  src/site/content/en/fast/codelab-serve-images-webp/index.md
  src/site/content/en/fast/codelab-serve-modern-code/index.md
  src/site/content/en/fast/codelab-setting-performance-budgets-with-webpack/index.md
  src/site/content/en/fast/codelab-specifying-multiple-slot-widths/index.md
  src/site/content/en/fast/codelab-text-compression-brotli/index.md
  src/site/content/en/fast/codelab-text-compression/index.md
  src/site/content/en/fast/codelab-use-lazysizes-to-lazyload-images/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/fast/remove-unused-code/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/installable/codelab-make-installable/index.md
  src/site/content/en/lighthouse-performance/uses-text-compression/index.md
  src/site/content/en/react/add-manifest-react/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/react/precache-with-workbox-react/index.md
  src/site/content/en/reliable/codelab-explore-network-panel/index.md
  src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md
  src/site/content/en/reliable/codelab-service-workers/index.md
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes, task

#2005 Fixes #2004
  src/site/content/en/handbook/audience/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/content-types/index.md
  src/site/content/en/handbook/effective-instruction/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
Labels: cla: yes

#1910 Don't use code character in titles and headings.
  src/site/content/en/blog/get-installed-related-apps/index.md
  src/site/content/en/handbook/content-checklist/index.md
Labels: cla: yes

#2007 Revert "Update 'SameSite cookies explained' for Chrome 80. (#1979)"
  src/site/content/en/blog/samesite-cookie-recipes/chrome-console-warning.png
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: Chrome 80, beta blog, cla: yes

#1968 Update Contact Picker article for Chrome 80.
  src/site/content/en/blog/contact-picker/index.md
Labels: Chrome 80, DO NOT MERGE, beta blog, cla: yes

#1982 Disallowing synchronous XMLHTTPRequest() during page dismissal
  src/site/content/en/blog/disallow-synchronous-xhr/hero.jpg
  src/site/content/en/blog/disallow-synchronous-xhr/index.md
Labels: Chrome 80, beta blog, cla: yes

#2001 Content Indexing API Origin Trial announcement
  src/site/content/en/blog/content-indexing-api/articles-for-you.png
  src/site/content/en/blog/content-indexing-api/delete-menu.png
  src/site/content/en/blog/content-indexing-api/downloads-menu.png
  src/site/content/en/blog/content-indexing-api/hero.jpg
  src/site/content/en/blog/content-indexing-api/index.md
Labels: cla: yes

#2006 Add Module Workers article
  src/site/_data/contributors.json
  src/site/content/en/blog/module-workers/hero.jpg
  src/site/content/en/blog/module-workers/index.md
Labels: cla: yes, content

#2019 Make cross-origin links safe
  src/site/content/en/blog/backdrop-filter/index.md
Labels: cla: yes

#1980 Update periodic bckgrnd article for Chrome 80.
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: Chrome 80, beta blog, cla: yes, content

#2020 Update Web Share and Web Share Target hero images
  src/site/content/en/blog/web-share-target/hero.jpg
  src/site/content/en/blog/web-share-target/hero.png
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/hero.jpg
  src/site/content/en/blog/web-share/hero.png
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#1955 Content: Main thread is overworked companion post
  src/site/content/en/blog/off-main-thread/index.md
Labels: cla: yes

#2022 Add CDS playlist to front page of site and deeplink id.
  src/site/content/en/index.njk
Labels: cla: yes

#1962 Speed tooling blog posts from CDS 2019
  src/site/content/en/blog/lighthouse-evolution-cds-2019/hero.jpg
  src/site/content/en/blog/lighthouse-evolution-cds-2019/index.md
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-ci.png
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-performance-score.png
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-plugin-devtools.png
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-plugin-icon.png
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-stack-packs.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/crux-data.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/hero.jpg
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/index.md
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/performance-metrics.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/psi-reanalyze.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/search-console-speed-report.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/tbt.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/tbt2.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/thumbnail.png
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/web-almanac-at-cds-2019.png
Labels: cla: yes

#2021 fix(CopyCode): fix style issues, fixes #2010 & fixes #2011
  src/lib/components/CopyCode/index.js
  src/lib/components/CopyCode/styles.scss
  src/styles/components/_compare.scss
  src/styles/devsite/_app.scss
Labels: cla: yes

#1963 Content: Add Next-gen web styling companion post
  src/site/_data/contributors.json
  src/site/content/en/blog/next-gen-css-2019/gap.png
  src/site/content/en/blog/next-gen-css-2019/hero.png
  src/site/content/en/blog/next-gen-css-2019/houdini.png
  src/site/content/en/blog/next-gen-css-2019/index.md
  src/site/content/en/blog/next-gen-css-2019/legacy-layout.png
  src/site/content/en/blog/next-gen-css-2019/logical-layout.png
  src/site/content/en/blog/next-gen-css-2019/menu-focus.png
  src/site/content/en/blog/next-gen-css-2019/prefers-media-queries.png
  src/site/content/en/images/authors/una.jpg
  src/site/content/en/images/authors/una@2x.jpg
Labels: cla: yes

#2000 Add Adaptive loading blog post
  src/site/content/en/blog/adaptive-loading-cds-2019/adaptive-code-splitting.png
  src/site/content/en/blog/adaptive-loading-cds-2019/hero.png
  src/site/content/en/blog/adaptive-loading-cds-2019/index.md
  src/site/content/en/blog/adaptive-loading-cds-2019/thumbnail.png
  src/site/content/en/blog/adaptive-loading-cds-2019/tinder.png
Labels: cla: yes

#1975 Content: Add maskable icon post
  src/site/_data/contributors.json
  src/site/content/en/blog/maskable-icon/devtools.png
  src/site/content/en/blog/maskable-icon/fugu-mask.mp4
  src/site/content/en/blog/maskable-icon/fugu-mask.webm
  src/site/content/en/blog/maskable-icon/hero.png
  src/site/content/en/blog/maskable-icon/homescreen-any.png
  src/site/content/en/blog/maskable-icon/index.md
  src/site/content/en/blog/maskable-icon/maskable-app-editor.png
  src/site/content/en/images/authors/tigeroakes.jpg
  src/site/content/en/images/authors/tigeroakes@2x.jpg
Labels: cla: yes

#2018 Correct spelling.
  src/site/content/en/blog/disallow-synchronous-xhr/index.md
Labels: cla: yes

#1595 Add Assessment Self-check component
  .eleventy.js
  src/lib/app.js
  src/lib/components/Tabs/_styles.scss
  src/lib/components/Tabs/index.js
  src/lib/components/_all.scss
  src/site/_includes/components/AssessmentCallout.js
  src/site/_includes/components/AssessmentHint.js
  src/site/_includes/components/CodelabsCallout.js
  src/site/_includes/components/Tab.js
  src/site/_includes/components/Tabs.js
  src/site/_includes/components/Tooltip.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_all.scss
  src/styles/components/_asides.scss
  src/styles/components/_buttons.scss
  src/styles/components/_callouts.scss
  src/styles/components/_details.scss
  src/styles/components/_self-assessment-hint.scss
  src/styles/components/_tooltips.scss
  src/styles/settings/_colors.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#2027 Make deep links scroll properly.
  src/styles/generic/_shared.scss
Labels: cla: yes

#1611 Add styling for external links
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/generic/_links.scss
Labels: cla: yes

#1678 Add getting started codelab
  src/site/_data/contributors.json
  src/site/content/en/notifications/codelab-notifications-get-started/console-output.png
  src/site/content/en/notifications/codelab-notifications-get-started/copy-live-app-url.png
  src/site/content/en/notifications/codelab-notifications-get-started/index.md
  src/site/content/en/notifications/codelab-notifications-get-started/live-app-new-tab.png
  src/site/content/en/notifications/codelab-notifications-get-started/remix-to-edit.png
  src/site/content/en/notifications/index.njk
  src/site/content/en/notifications/notifications.11tydata.js
Labels: cla: yes

#2029 Add missing maskable image
  src/site/content/en/blog/maskable-icon/homescreen-maskable.png
Labels: cla: yes

#1986 Cohere with the spec
  src/site/content/en/installable/add-manifest/index.md
Labels: cla: yes

#2032 Fix incorrect reference from FCP to LCP
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#1693 Add notifications service worker codelab
  src/site/content/en/notifications/codelab-notifications-get-started/index.md
  src/site/content/en/notifications/codelab-notifications-service-worker/index.md
Labels: cla: yes

#1730 Add article Use push notifications to engage users
  src/site/content/en/notifications/use-push-notifications-to-engage-users/index.md
  src/site/content/en/notifications/use-push-notifications-to-engage-users/predicaments-android.png
  src/site/content/en/notifications/use-push-notifications-to-engage-users/predicaments-macbook.png
Labels: cla: yes

#1933 Codelab: Build a push notifications server
  src/site/content/en/notifications/codelab-notifications-push-server/index.md
Labels: cla: yes

#2037 Fixed 404 for style guidelines
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes
