Repository GoogleChrome/web.dev, pull requests merged in 2019-07, with the labels that each got.

#1087 Let authors specify Glitch path.
  src/site/_includes/codelab.njk
Labels: cla: yes

#1095 Brotli fix
  src/site/content/en/fast/codelab-text-compression-brotli/index.md
Labels: cla: yes

#1099 content: Opensooq case study
  src/site/_data/contributors.json
  src/site/content/en/blog/opensooq-case-study/hero.jpg
  src/site/content/en/blog/opensooq-case-study/index.md
  src/site/content/en/blog/opensooq-case-study/lh-performance.png
  src/site/content/en/blog/opensooq-case-study/notifications.png
  src/site/content/en/images/authors/hbatra.jpg
  src/site/content/en/images/authors/hbatra@2x.jpg
Labels: cla: yes

#1052 Add Guess.js article from io19
  src/site/_data/contributors.json
  src/site/content/en/blog/predictive-prefetching/guess-0.png
  src/site/content/en/blog/predictive-prefetching/guess-1.png
  src/site/content/en/blog/predictive-prefetching/index.md
  src/site/content/en/blog/predictive-prefetching/predictive-prefetching-header.png
  src/site/content/en/images/authors/mgechev.jpg
  src/site/content/en/images/authors/mgechev@2x.jpg
Labels: cla: yes, fast

#1101 content: Updates to OpenSooq post
  src/site/content/en/blog/opensooq-case-study/index.md
Labels: cla: yes

#1111 Update OpenSooq hero.jpg
  src/site/content/en/blog/opensooq-case-study/hero.jpg
Labels: cla: yes

#1112 Hide codelab footer on devsite.
  src/site/_includes/codelab.njk
Labels: cla: yes

#1108 Normalize dashes
  src/site/content/en/accessible/keyboard-access/index.md
  src/site/content/en/accessible/semantics-and-screen-readers/index.md
  src/site/content/en/accessible/what-is-accessibility/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/how-to-report-metrics/index.md
  src/site/content/en/blog/javascript-and-google-search-io-2019/index.md
  src/site/content/en/blog/long-tasks-devtools/index.md
  src/site/content/en/blog/perception-toolkit/index.md
  src/site/content/en/blog/proxx-announce/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
  src/site/content/en/blog/service-worker-mindset/index.md
  src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md
  src/site/content/en/blog/web-payments-updates/index.md
  src/site/content/en/discoverable/codelab-fix-sneaky-404/index.md
  src/site/content/en/discoverable/how-search-works/index.md
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/index.md
  src/site/content/en/fast/codelab-art-direction/index.md
  src/site/content/en/fast/codelab-imagemin-gulp/index.md
  src/site/content/en/fast/codelab-preload-critical-assets/index.md
  src/site/content/en/fast/codelab-serve-images-correct-dimensions/index.md
  src/site/content/en/fast/how-to-stay-fast/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/fast/serve-images-webp/index.md
  src/site/content/en/fast/serve-images-with-correct-dimensions/index.md
  src/site/content/en/fast/serve-responsive-images/index.md
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
  src/site/content/en/fast/what-is-speed/index.md
  src/site/content/en/handbook/sandbox/tables/index.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/installable/add-manifest/index.md
  src/site/content/en/lighthouse-accessibility/aria-allowed-attr/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-attr/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-children/index.md
  src/site/content/en/lighthouse-accessibility/aria-required-parent/index.md
  src/site/content/en/lighthouse-accessibility/aria-roles/index.md
  src/site/content/en/lighthouse-accessibility/aria-valid-attr-value/index.md
  src/site/content/en/lighthouse-accessibility/aria-valid-attr/index.md
  src/site/content/en/lighthouse-accessibility/frame-title/index.md
  src/site/content/en/lighthouse-best-practices/errors-in-console/index.md
  src/site/content/en/lighthouse-performance/first-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/first-cpu-idle/index.md
  src/site/content/en/lighthouse-performance/first-meaningful-paint/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
  src/site/content/en/lighthouse-performance/uses-long-cache-ttl/index.md
  src/site/content/en/lighthouse-performance/uses-rel-preload/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
  src/site/content/en/secure/security-attacks/index.md
Labels: cla: yes

#1106 Normalize titles and subtitles
  src/site/content/en/accessible/what-is-accessibility/index.md
  src/site/content/en/blog/earth-webassembly/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/how-to-report-metrics/index.md
  src/site/content/en/blog/perception-toolkit/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/proxx-announce/index.md
  src/site/content/en/blog/speed-at-scale/index.md
  src/site/content/en/blog/web-components-io-2019/index.md
  src/site/content/en/blog/web-payments-updates/index.md
  src/site/content/en/blog/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/discoverable/pass-lighthouse-seo-audit/index.md
  src/site/content/en/fast/why-speed-matters/index.md
  src/site/content/en/installable/add-manifest/index.md
  src/site/content/en/react/get-started-optimize-react/index.md
  src/site/content/en/secure/same-origin-policy/index.md
  src/site/content/en/secure/security-attacks/index.md
Labels: cla: yes

#1093 Add performance budgets with Angular CLI
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-calculator.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-failure.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/index.md
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/performance-budgets-with-the-angular-cli.jpg
Labels: cla: yes

#1107 Normalize apostrophes and quotes
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/blog/earth-webassembly/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/layout-instability-api/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/proxx-announce/index.md
  src/site/content/en/blog/value-of-speed/index.md
  src/site/content/en/blog/web-components-io-2019/index.md
  src/site/content/en/blog/web-payments-updates/index.md
  src/site/content/en/blog/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/blog/youtube-media-capabilities/index.md
  src/site/content/en/fast/adaptive-serving-based-on-network-quality/index.md
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md
  src/site/content/en/fast/codelab-adapt-video-to-image-serving-based-on-network-quality/index.md
  src/site/content/en/fast/codelab-avoid-invisible-text/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/codelab-preload-web-fonts/index.md
  src/site/content/en/fast/codelab-setting-performance-budgets-with-webpack/index.md
  src/site/content/en/fast/codelab-text-compression-brotli/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/fast/extract-critical-css/index.md
  src/site/content/en/fast/how-to-measure-speed/index.md
  src/site/content/en/fast/how-to-stay-fast/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/fast/performance-budgets-101/index.md
  src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md
  src/site/content/en/fast/use-imagemin-to-compress-images/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
  src/site/content/en/fast/what-is-speed/index.md
  src/site/content/en/fast/why-speed-matters/index.md
  src/site/content/en/fast/your-first-performance-budget/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/installable/installable.11tydata.js
  src/site/content/en/lighthouse-accessibility/custom-control-roles/index.md
  src/site/content/en/lighthouse-accessibility/custom-controls-labels/index.md
  src/site/content/en/lighthouse-accessibility/focusable-controls/index.md
  src/site/content/en/lighthouse-accessibility/frame-title/index.md
  src/site/content/en/lighthouse-accessibility/logical-tab-order/index.md
  src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
Labels: cla: yes

#1100 Add accessibility with codelyzer
  src/site/_data/contributors.json
  src/site/content/en/angular/accessible-angular-with-codelyzer/accessible.jpg
  src/site/content/en/angular/accessible-angular-with-codelyzer/editor-template.png
  src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
  src/site/content/en/angular/accessible-angular-with-codelyzer/ng-lint.png
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/images/authors/mohamedzamakhan.jpg
  src/site/content/en/images/authors/mohamedzamakhan@2x.jpg
Labels: cla: yes

#1094 Introduce the precaching post
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/precaching-with-the-angular-service-worker.jpg
  src/site/content/en/angular/precaching-with-the-angular-service-worker/sample-app.png
Labels: cla: yes

#1117 Add Angular preloading strategies
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/route-preloading/index.md
  src/site/content/en/angular/route-preloading/route-preloading.jpg
Labels: cla: yes

#1135 Adds note about double fetching to serve modern code guide
  src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md
Labels: cla: yes

#1134 Introduce the change detection optimization article
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/faster-change-detection/app.png
  src/site/content/en/angular/faster-change-detection/change-detection.jpg
  src/site/content/en/angular/faster-change-detection/component-sub-tree-cd.png
  src/site/content/en/angular/faster-change-detection/component-tree.png
  src/site/content/en/angular/faster-change-detection/index.md
  src/site/content/en/angular/faster-change-detection/profiling.png
Labels: cla: yes

#1150 Clarify a versus button usage.
  src/site/content/en/accessible/use-semantic-html/index.md
Labels: cla: yes

#1113 Add the code-splitting article
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/route-level-code-splitting/code-splitting-network-tab.png
  src/site/content/en/angular/route-level-code-splitting/index.md
  src/site/content/en/angular/route-level-code-splitting/route-level-code-splitting.jpg
Labels: cla: yes

#1139 Virtualize lists cdk
  src/site/_data/contributors.json
  src/site/content/en/angular/virtualize-lists-with-cdk/hero.jpg
  src/site/content/en/angular/virtualize-lists-with-cdk/index.md
  src/site/content/en/angular/virtualize-lists-with-cdk/render-subset.mp4
  src/site/content/en/angular/virtualize-lists-with-cdk/render-subset.webm
  src/site/content/en/images/authors/sfluin.jpg
  src/site/content/en/images/authors/sfluin@2x.jpg
Labels: cla: yes

#1154 Change verb to correct grammar
  src/site/content/en/accessible/style-focus/index.md
Labels: cla: yes

#1155 Adding `perfers-reduced-motion` support
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#1158 Introduce web.dev/angular
  src/site/_data/contributors.json
  src/site/content/en/angular/accessible-angular-with-codelyzer/accessible.jpg
  src/site/content/en/angular/accessible-angular-with-codelyzer/editor-template.png
  src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
  src/site/content/en/angular/accessible-angular-with-codelyzer/ng-lint.png
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/angular/faster-angular-change-detection/app.png
  src/site/content/en/angular/faster-angular-change-detection/change-detection.jpg
  src/site/content/en/angular/faster-angular-change-detection/component-sub-tree-cd.png
  src/site/content/en/angular/faster-angular-change-detection/component-tree.png
  src/site/content/en/angular/faster-angular-change-detection/index.md
  src/site/content/en/angular/faster-angular-change-detection/profiling.png
  src/site/content/en/angular/get-started-optimize-angular/get-started-optimize-angular.jpg
  src/site/content/en/angular/get-started-optimize-angular/index.md
  src/site/content/en/angular/index.njk
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-calculator.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-failure.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/index.md
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/performance-budgets-with-the-angular-cli.jpg
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/precaching-with-the-angular-service-worker.jpg
  src/site/content/en/angular/precaching-with-the-angular-service-worker/sample-app.png
  src/site/content/en/angular/route-level-code-splitting-in-angular/code-splitting-network-tab.png
  src/site/content/en/angular/route-level-code-splitting-in-angular/index.md
  src/site/content/en/angular/route-level-code-splitting-in-angular/route-level-code-splitting.jpg
  src/site/content/en/angular/route-preloading-in-angular/index.md
  src/site/content/en/angular/route-preloading-in-angular/route-preloading.jpg
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/hero.jpg
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/index.md
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/render-subset.mp4
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/render-subset.webm
  src/site/content/en/images/authors/mohamedzamakhan.jpg
  src/site/content/en/images/authors/mohamedzamakhan@2x.jpg
  src/site/content/en/images/collections/angular.svg
  src/site/content/en/learn/learn.11tydata.js
Labels: cla: no

#1165 Origin Trials explainer include
  src/site/_includes/content/origin-trials.njk
Labels: cla: yes

#1169 Add scheduled and draft posts.
  .eleventy.js
  src/site/_collections/post-descending.js
  src/site/_collections/posts-with-lighthouse.js
  src/site/_collections/recent-posts.js
  src/site/_filters/live-posts.js
  src/site/_includes/components/ArticleNavigation.js
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/topic.njk
  src/site/_includes/path.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/feed.njk
Labels: cla: yes

#1160 docs: update route-preloading-in-angular
  src/site/content/en/angular/route-preloading-in-angular/index.md
Labels: cla: yes

#1173 Minor typo fixes to srcset blog post
  src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md
Labels: cla: yes

#1172 Update content template link in handbook
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes

#1168 Fix typos in the images in the change detection article
  src/site/content/en/angular/faster-angular-change-detection/component-sub-tree-cd.png
  src/site/content/en/angular/faster-angular-change-detection/component-tree.png
Labels: cla: yes

#1178 Add Banner component and add banner to all blog pages.
  .eleventy.js
  src/site/_includes/components/Banner.js
  src/site/_includes/styles.njk
  src/site/content/en/about/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/learn/index.njk
  src/site/content/en/measure/index.njk
  src/styles/components/_all.scss
  src/styles/components/_banner.scss
Labels: cla: yes

#1179 Update link formatting
  src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
  src/site/content/en/angular/get-started-optimize-angular/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
  src/site/content/en/blog/predictive-prefetching/index.md
  src/site/content/en/handbook/audience/index.md
  src/site/content/en/handbook/content-types/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-code/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/markup-sample-app/index.md
  src/site/content/en/handbook/quick-start/index.md
  src/site/content/en/handbook/style/index.md
  src/site/content/en/handbook/use-media/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/handbook/write-code-samples/index.md
  src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md
Labels: cla: yes

#1104 Update performance budgets tooling guide
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/lighthouse-scores.jpg
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/lighthouse-scores.png
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/lightwallet.png
Labels: cla: yes

#1196 V2+dart sass
  package-lock.json
  package.json
Labels: cla: yes

#1198 basic Firestore use
  src/lib/fb.js
  src/lib/store.js
Labels: cla: yes

#1197 add global signin class to page
  src/lib/app.js
Labels: cla: yes

#1171 Layout Instability API updates for Chrome 77
  src/site/_includes/styles.njk
  src/site/content/en/blog/layout-instability-api/index.md
  src/styles/components/_asides.scss
Labels: cla: no

#1159 Add note about raw and verbatim tags to handbook.
  src/site/content/en/handbook/markup-code/index.md
Labels: cla: no

#1200 Changed `content-heading` to `content-encoding`
  src/site/content/en/lighthouse-performance/uses-text-compression/index.md
Labels: cla: yes

#1201 Use the aside shortcodes consistently in the Layout Instability API article
  src/site/content/en/blog/layout-instability-api/index.md
Labels: cla: yes

#1164 Add info on 3rd party contributions
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/handbook/style/index.md
  src/site/content/en/handbook/third-party-contributions/index.md
  src/site/content/en/handbook/tooling-and-libraries/index.md
Labels: cla: yes

#1207 Add blurb for future Houdini articles.
  src/site/_includes/content/houdini.njk
Labels: beta blog, cla: yes

#1208 Add registration link to origin trial blurb.
  src/site/_includes/content/origin-trials.njk
Labels: cla: yes

#1210 Adds web-lighthouse-gauge
  src/lib/app.js
  src/lib/components/LighthouseGauge/_styles.scss
  src/lib/components/LighthouseGauge/index.js
  src/lib/components/_all.scss
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1203 Adds web-lighthouse-audits
  src/lib/app.js
  src/lib/components/LighthouseScoresAudits/_styles.scss
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/LighthouseScoresAudits/lighthouse.js
  src/lib/components/LighthouseScoresAudits/mapping.js
  src/lib/components/_all.scss
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1131 [Blog] New draft of backdrop-filter article.
  src/site/content/en/blog/backdrop-filter/hero.jpg
  src/site/content/en/blog/backdrop-filter/index.md
  src/site/content/en/blog/backdrop-filter/translucent-chrome.png
  src/site/content/en/blog/backdrop-filter/transparency-off.png
  src/site/content/en/blog/backdrop-filter/transparency-on.png
  src/site/content/en/blog/backdrop-filter/weather_app.jpg
Labels: cla: yes

#1041 📦 NEW: Codelab Cloudinary URL API
  src/site/_data/contributors.json
  src/site/content/en/fast/codelab-cloudinary-url-api/cloudname.mp4
  src/site/content/en/fast/codelab-cloudinary-url-api/cloudname.webm
  src/site/content/en/fast/codelab-cloudinary-url-api/images-not-optimized.png
  src/site/content/en/fast/codelab-cloudinary-url-api/index.md
  src/site/content/en/fast/codelab-cloudinary-url-api/optimized-images.png
  src/site/content/en/images/authors/ahmadawais.jpg
Labels: cla: no

#1202 add web-url-chooser{,-container} to choose audit URL
  src/lib/app.js
  src/lib/components/UrlChooser/_styles.scss
  src/lib/components/UrlChooser/index.js
  src/lib/components/UrlChooserContainer/index.js
  src/lib/components/_all.scss
  src/lib/fb.js
  src/lib/store.js
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1219 remove -webkit- references
  src/site/content/en/blog/backdrop-filter/index.md
Labels: blog, cla: yes

#1204 Disable image survey banner.
  src/site/content/en/about/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/measure/index.njk
Labels: DO NOT MERGE, cla: yes

#1228 Improve /measure spacing. Temporary fix for #1181 and #1206
  src/site/_includes/styles.njk
Labels: cla: yes

#1225 Add new instruction type
  src/site/_includes/components/Instruction.js
  src/site/content/en/images/icons/reload.svg
Labels: cla: yes

#1142 content: Add third-party JS intro post
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/third-party-javascript/index.md
  src/site/content/en/fast/third-party-javascript/third-party-examples.mp4
Labels: cla: no

#1016 Adds native lazy loading blog post
  src/site/content/en/blog/native-lazy-loading/hero.png
  src/site/content/en/blog/native-lazy-loading/index.md
  src/site/content/en/blog/native-lazy-loading/lazyload.mp4
  src/site/content/en/blog/native-lazy-loading/lazyload.webm
  src/site/content/en/blog/native-lazy-loading/range-request.png
  src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md
Labels: blog, cla: no, content proposal

#1235 Incremental handbook updates
  src/site/content/en/handbook/audience/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/content-types/index.md
  src/site/content/en/handbook/contributor-profile/index.md
  src/site/content/en/handbook/effective-instruction/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-code/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/markup-sample-app/index.md
  src/site/content/en/handbook/quick-start/index.md
  src/site/content/en/handbook/style/index.md
  src/site/content/en/handbook/use-media/index.md
  src/site/content/en/handbook/voice/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/handbook/word-list/index.md
  src/site/content/en/handbook/write-code-samples/index.md
Labels: cla: yes

#1234 Add markdown linting as a prepush hook.
  .huskyrc
  .lintstagedrc
  .remarkrc
  .sasslintrc
  gulpfile.js
  package-lock.json
  package.json
  tools/linting/no-dash-spaces.js
  tools/linting/no-smart-quotes.js
Labels: cla: yes
