Repository GoogleChrome/web.dev, pull requests merged in 2019-10, with the labels that each got.

#1598 Fix css property font-display in the article
  src/site/content/en/blog/fixing-layout-instability/index.md
Labels: cla: yes

#1597 fix image loading
  server.js
Labels: cla: yes

#1587 Lighthouse PWA audit post updates
  src/site/_includes/content/lighthouse-performance/improve.njk
  src/site/content/en/blog/google-search-sw/index.md
  src/site/content/en/handbook/sandbox/tables/index.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/images/includes/opportunities.png
  src/site/content/en/installable/add-manifest/index.md
  src/site/content/en/installable/discover-installable/index.md
  src/site/content/en/installable/installable.11tydata.js
  src/site/content/en/lighthouse-performance/critical-request-chains/index.md
  src/site/content/en/lighthouse-performance/redirects/index.md
  src/site/content/en/lighthouse-performance/redirects/redirects.png
  src/site/content/en/lighthouse-pwa/apple-touch-icon/apple-touch-icon.png
  src/site/content/en/lighthouse-pwa/apple-touch-icon/index.md
  src/site/content/en/lighthouse-pwa/codelab-apple-touch-icon/index.md
  src/site/content/en/lighthouse-pwa/content-width/content-width.png
  src/site/content/en/lighthouse-pwa/content-width/index.md
  src/site/content/en/lighthouse-pwa/installable-manifest/index.md
  src/site/content/en/lighthouse-pwa/installable-manifest/installable-manifest.png
  src/site/content/en/lighthouse-pwa/is-on-https/index.md
  src/site/content/en/lighthouse-pwa/is-on-https/is-on-https.png
  src/site/content/en/lighthouse-pwa/lighthouse-pwa.11tydata.js
  src/site/content/en/lighthouse-pwa/load-fast-enough-for-pwa/index.md
  src/site/content/en/lighthouse-pwa/load-fast-enough-for-pwa/load-fast-enough-for-pwa.png
  src/site/content/en/lighthouse-pwa/offline-start-url/index.md
  src/site/content/en/lighthouse-pwa/offline-start-url/offline-start-url.png
  src/site/content/en/lighthouse-pwa/pwa-cross-browser/index.md
  src/site/content/en/lighthouse-pwa/pwa-each-page-has-url/index.md
  src/site/content/en/lighthouse-pwa/pwa-page-transitions/index.md
  src/site/content/en/lighthouse-pwa/redirects-http/index.md
  src/site/content/en/lighthouse-pwa/redirects-http/redirects-http.png
  src/site/content/en/lighthouse-pwa/service-worker/index.md
  src/site/content/en/lighthouse-pwa/service-worker/service-worker.png
  src/site/content/en/lighthouse-pwa/splash-screen/index.md
  src/site/content/en/lighthouse-pwa/splash-screen/splash-screen.png
  src/site/content/en/lighthouse-pwa/themed-omnibox/index.md
  src/site/content/en/lighthouse-pwa/themed-omnibox/themed-omnibox.png
  src/site/content/en/lighthouse-pwa/viewport/index.md
  src/site/content/en/lighthouse-pwa/without-javascript/index.md
  src/site/content/en/lighthouse-pwa/without-javascript/without-javascript.png
  src/site/content/en/lighthouse-pwa/works-offline/index.md
  src/site/content/en/lighthouse-pwa/works-offline/works-offline.png
  src/site/content/en/react/add-manifest-react/index.md
  src/site/content/en/reliable/workbox/index.md
Labels: cla: yes

#1604 PWA audit fixes
  src/site/content/en/lighthouse-pwa/redirects-http/index.md
  src/site/content/en/lighthouse-pwa/themed-omnibox/index.md
Labels: cla: yes

#1473 Adding expressions which will indicate that Portals are still in a proposal phase
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#1605 fix: Use authors instead of author in content source file
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
Labels: cla: yes

#1607 Fixes to Get started: optimize your React app
  src/site/content/en/react/get-started-optimize-react/index.md
Labels: cla: yes

#1610 Add survey reminder action.
  .github/workflows/issue-closed-workflow.yml
Labels: cla: yes

#1606 fix: Remove td tag from yaml file
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
Labels: cla: yes

#1550 Adding SMS Receiver API draft
  src/site/content/en/blog/sms-receiver-announce/diagram.png
  src/site/content/en/blog/sms-receiver-announce/hero.png
  src/site/content/en/blog/sms-receiver-announce/index.md
Labels: cla: yes

#1613 Copyedit the SMS OTP post
  src/site/content/en/blog/sms-receiver-api-announcement/diagram.png
  src/site/content/en/blog/sms-receiver-api-announcement/hero.png
  src/site/content/en/blog/sms-receiver-api-announcement/index.md
Labels: cla: yes

#1640 Make inline code work in next article widget and headings.
  src/site/_includes/components/ArticleNavigation.js
  src/styles/components/_article-navigation.scss
  src/styles/generic/_code.scss
Labels: cla: yes

#1634 Update blog/css-props-and-vals/index.md
  src/site/content/en/blog/css-props-and-vals/index.md
Labels: cla: yes

#1649 Fix #1643
  src/site/_includes/content/lighthouse-performance/improve.njk
  src/site/content/en/lighthouse-performance/first-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/first-cpu-idle/index.md
  src/site/content/en/lighthouse-performance/first-meaningful-paint/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/max-potential-fid/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
Labels: CDS, cds wave 1, cla: yes, fast, lighthouse, p2

#1621 Add rel="noopener" to external links using target="_blank"
  src/site/_drafts/intrinsic-layout-overview/index.md
  src/site/content/en/blog/backdrop-filter/index.md
  src/site/content/en/blog/use-thumbor/index.md
Labels: cla: yes

#1654 Quick addition to make images lazy load.
  src/site/_includes/components/PathCard.js
  src/site/_includes/components/PostCard.js
Labels: cla: yes

#1614 Migration of Badging API article
  src/site/_includes/content/origin-trial-register.njk
  src/site/content/en/blog/badging-api/badges-on-windows.jpg
  src/site/content/en/blog/badging-api/hero.jpg
  src/site/content/en/blog/badging-api/index.md
Labels: cla: yes

#1636 Add Total Blocking Time documentation for Lighthouse
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-performance/lighthouse-total-blocking-time/index.md
  src/site/content/en/lighthouse-performance/lighthouse-total-blocking-time/total-blocking-time.jpg
Labels: cla: yes

#1647 Remove aside from ot include.
  src/site/_includes/content/origin-trials.njk
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
Labels: cla: yes

#1620 Migration of Contact Picker API article
  src/site/content/en/blog/contact-picker/contact-picker-demo.jpg
  src/site/content/en/blog/contact-picker/contact-picker-left.jpg
  src/site/content/en/blog/contact-picker/contact-picker-long-press.jpg
  src/site/content/en/blog/contact-picker/contact-picker-right.jpg
  src/site/content/en/blog/contact-picker/contact-picker-user-choice.jpg
  src/site/content/en/blog/contact-picker/hero.jpg
  src/site/content/en/blog/contact-picker/index.md
Labels: cla: yes

#1622 Migrate Native File System article
  src/site/content/en/blog/native-file-system/fs-open.jpg
  src/site/content/en/blog/native-file-system/fs-save-icon.jpg
  src/site/content/en/blog/native-file-system/fs-save-permission-crop.jpg
  src/site/content/en/blog/native-file-system/fs-save-permission.jpg
  src/site/content/en/blog/native-file-system/fs-save.jpg
  src/site/content/en/blog/native-file-system/hero.jpg
  src/site/content/en/blog/native-file-system/index.md
Labels: cla: yes

#1623 Migration of Shape Detection API article
  src/site/content/en/blog/shape-detection/hero.jpg
  src/site/content/en/blog/shape-detection/index.md
Labels: cla: yes

#1624 Migrate Async Clipboard article
  src/site/content/en/blog/image-support-for-async-clipboard/hero.jpg
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
Labels: cla: yes

#1665 Add Markdown to post subheads
  src/site/_includes/partials/post.njk
Labels: cla: yes

#1667 Remove devsite's CSS and fixup issues.
  src/lib/components/ProfileSwitcher/_styles.scss
  src/lib/components/UrlChooser/_styles.scss
  src/site/content/en/about/index.njk
  src/site/content/en/accessible/what-is-accessibility/index.md
  src/styles/all.scss
  src/styles/components/_buttons.scss
  src/styles/components/_grid.scss
  src/styles/devsite/_app.scss
  src/styles/devsite/_devsite_debug_info.scss
  src/styles/devsite/_devsite_heading.scss
  src/styles/devsite/_devsite_snackbar.scss
  src/styles/devsite/_devsite_tooltip.scss
  src/styles/devsite/_elements.scss
  src/styles/devsite/_vetos.scss
  src/styles/generic/_all.scss
  src/styles/generic/_buttons.scss
  src/styles/overrides/_all.scss
  src/styles/overrides/_hidden.scss
  src/styles/pages/_about.scss
Labels: cla: yes

#1652 Migrate getInstalledRelatedApps article
  src/site/_includes/content/origin-trial-register.njk
  src/site/_includes/content/origin-trials.njk
  src/site/content/en/blog/get-installed-related-apps/getinstalled-cropped.jpg
  src/site/content/en/blog/get-installed-related-apps/hero.jpg
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#1684 Force draft posts to show up in dev mode.
  src/site/_filters/live-posts.js
Labels: cla: yes

#1685 Re-enable draft for getInstalledRelatedApps
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#1686 Show banner for draft posts in dev mode.
  src/site/_includes/codelab.njk
  src/site/_includes/partials/post.njk
Labels: cla: yes

#1681 Tweaks style of search box
  src/lib/components/Search/_styles.scss
Labels: cla: yes

#1658 Add Next.js intro
  src/site/content/en/react/performance-as-a-default-with-nextjs/devtools.png
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
  src/site/content/en/react/react.11tydata.js
Labels: cla: yes

#1679 migrate to supporting /measure/ (trailing slash) pages
  server.js
  src/lib/router.js
Labels: cla: yes

#1582 Adds loading bar to v2
  src/lib/app.js
  src/lib/router.js
  src/lib/store.js
  src/site/_includes/layout.njk
  src/styles/components/_all.scss
  src/styles/components/_progress.scss
Labels: cla: yes

#1680 imperative Rollup build with dynamic import
  .eslintrc.js
  build.js
  package-lock.json
  package.json
  rollup.config.js
  src/lib/app.js
  src/lib/bootstrap.js
  src/lib/pages/default.js
  src/lib/pages/measure.js
  src/lib/router.js
  src/lib/sw.js
  src/lib/utils/underscore-import-polyfill.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1695 Fix works-offline audit source link
  src/site/content/en/lighthouse-pwa/works-offline/index.md
Labels: cla: yes

#1697 Update Next.js intro
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
Labels: cla: yes

#1655 Fix internal links
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
  src/site/content/en/angular/creating-pwa-with-angular-cli/index.md
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
  src/site/content/en/angular/route-level-code-splitting-in-angular/index.md
  src/site/content/en/blog/image-policies/index.md
  src/site/content/en/blog/install-thumbor/index.md
  src/site/content/en/blog/largest-contentful-paint/index.md
  src/site/content/en/blog/proxx-announce/index.md
  src/site/content/en/blog/service-worker-mindset/index.md
  src/site/content/en/blog/web-dev-io-2019/index.md
  src/site/content/en/fast/apply-instant-loading-with-prpl/index.md
  src/site/content/en/fast/chrome-ux-report/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/codelab-imgix/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
  src/site/content/en/fast/codelab-preload-web-fonts/index.md
  src/site/content/en/fast/codelab-setting-performance-budgets-with-webpack/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/fast/efficiently-load-third-party-javascript/index.md
  src/site/content/en/fast/extract-critical-css/index.md
  src/site/content/en/fast/how-to-stay-fast/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
  src/site/content/en/fast/image-cdns/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/fast/performance-budgets-101/index.md
  src/site/content/en/fast/third-party-javascript/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/fast/what-is-speed/index.md
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/fast/your-first-performance-budget/index.md
  src/site/content/en/lighthouse-best-practices/appcache-manifest/index.md
  src/site/content/en/lighthouse-performance/first-meaningful-paint/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/resource-summary/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
  src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
  src/site/content/en/lighthouse-pwa/redirects-http/index.md
  src/site/content/en/lighthouse-seo/font-size/index.md
Labels: CDS, cds wave 1, cla: yes, lighthouse, p0

#1699 Let paths be marked as drafts.
  src/site/_data/postHost.js
  src/site/_filters/live-paths.js
  src/site/_includes/path.njk
  src/site/content/en/en.11tydata.js
  src/site/content/en/learn/learn.11tydata.js
Labels: cla: yes

#1703 Fix router issue with SideNav links
  src/lib/components/SideNav/index.js
Labels: cla: yes

#1646 Add body variant to banner component
  src/site/_includes/components/Banner.js
  src/site/_includes/styles.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_banner.scss
Labels: cla: yes

#1688 Update Max Potential FID content
  src/site/content/en/lighthouse-performance/lighthouse-max-potential-fid/index.md
  src/site/content/en/lighthouse-performance/lighthouse-max-potential-fid/max-potential-fid.png
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-performance/max-potential-fid/index.md
Labels: cla: yes, fast, lighthouse, p1

#1712 catch /measure properly
  src/lib/router.js
Labels: cla: yes

#1698 Fix a broken link in the handbook
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#1706 Correct manual codelab markup in webp audit post
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes

#1717 _redirect.yaml support for v2
  package-lock.json
  package.json
  redirect-handler.js
  server.js
  src/site/content/en/_book.yaml
  src/site/content/en/_project.yaml
Labels: cla: yes

#1714 make Measure signin button work
  src/lib/components/BaseStateElement/index.js
  src/lib/components/SigninButton/index.js
  src/lib/pages/measure.js
  src/site/content/en/measure/index.njk
Labels: cla: yes

#1710 fix searching with no results
  src/lib/components/Search/index.js
Labels: cla: yes

#1709 Header style tweaks for v2
  src/lib/components/Header/_styles.scss
  src/lib/components/Header/index.js
  src/lib/components/ProfileSwitcher/_styles.scss
  src/lib/components/Search/_styles.scss
  src/lib/router.js
  src/lib/store.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1719 V2+sw stuff
  server.js
  src/lib/router.js
  src/lib/store.js
  src/lib/sw.js
  src/site/content/en/404.njk
  src/site/content/en/offline.njk
  src/styles/components/_page-header.scss
Labels: cla: yes

#1722 Update LH a11y navigation audit posts
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/lighthouse-accessibility/accesskeys/index.md
  src/site/content/en/lighthouse-accessibility/bypass/index.md
  src/site/content/en/lighthouse-accessibility/tabindex/index.md
Labels: cla: yes

#1696 Add Next.js route prefetching post
  src/site/content/en/react/nextjs-route-prefetching/console.png
  src/site/content/en/react/nextjs-route-prefetching/index.md
  src/site/content/en/react/nextjs-route-prefetching/network1.png
  src/site/content/en/react/nextjs-route-prefetching/network2.png
  src/site/content/en/react/nextjs-route-prefetching/network3.png
  src/site/content/en/react/nextjs-route-prefetching/pages-directory.png
  src/site/content/en/react/react.11tydata.js
Labels: cla: no

#1711 Lighthouse a11y best practices audit post updates
  src/site/content/en/lighthouse-accessibility/meta-refresh/index.md
  src/site/content/en/lighthouse-accessibility/meta-viewport/index.md
Labels: cla: yes

#1729 Add CDS promo module.
  src/site/content/en/images/modules/cds19-lockup-stack.svg
  src/site/content/en/index.njk
  src/styles/pages/_all.scss
  src/styles/pages/_home.scss
Labels: cla: yes

#1716 Add `web-actions` Web Component
  .eleventy.js
  src/lib/components/Actions/index.js
  src/lib/pages/default.js
  src/lib/utils/web-share.js
  src/site/_data/site.js
  src/site/_filters/expand-contributors.js
  src/site/_includes/components/Actions.js
  src/site/_includes/partials/post.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/handbook/sandbox/actions/index.njk
Labels: cla: yes

#1733 V2+historic data
  src/lib/actions.js
  src/lib/lighthouse-service.js
Labels: cla: yes

#1728 Remove 'draft' from Fugu articles
  src/site/content/en/blog/badging-api/index.md
  src/site/content/en/blog/contact-picker/index.md
  src/site/content/en/blog/get-installed-related-apps/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/native-file-system/index.md
  src/site/content/en/blog/shape-detection/index.md
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#1724 Prettify header and user image
  src/lib/app.js
  src/lib/bootstrap.js
  src/lib/components/ProfileSwitcher/_styles.scss
  src/lib/components/ProfileSwitcher/index.js
  src/lib/components/ProfileSwitcherContainer/index.js
  src/lib/components/Search/index.js
  src/lib/components/SigninButton/index.js
  src/lib/fb.js
  src/lib/store.js
  src/styles/components/_page-header.scss
Labels: cla: yes

#1735 retain previous URL on signin
  src/lib/actions.js
  src/lib/components/UrlChooserContainer/index.js
  src/lib/fb.js
Labels: cla: yes

#1702 nav tweaks
  src/lib/router.js
  src/styles/generic/_shared.scss
Labels: cla: yes

#1725 V2+replace navaid
  package-lock.json
  package.json
  src/lib/bootstrap.js
  src/lib/components/Search/index.js
  src/lib/loader.js
  src/lib/utils/router.js
Labels: cla: yes

#1740 fix typo
  src/lib/utils/router.js
Labels: cla: yes

#1739 Adds Terser minification for prod
  build.js
  package-lock.json
  package.json
Labels: cla: yes

#1558 [prefers-color-scheme article] Improve compatibility of fallback script
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#1756 Add sitemap.xml and fix errors.
  .eleventy.js
  src/site/_filters/html-date-string.js
  src/site/content/en/about/index.njk
  src/site/content/en/accessible/index.njk
  src/site/content/en/algolia.njk
  src/site/content/en/angular/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/discoverable/index.njk
  src/site/content/en/fast/codelab-adapt-video-to-image-serving-based-on-network-quality/index.md
  src/site/content/en/fast/index.njk
  src/site/content/en/feed.njk
  src/site/content/en/handbook/sandbox/tables/index.njk
  src/site/content/en/handbook/sandbox/typography/index.njk
  src/site/content/en/images/includes/README.md
  src/site/content/en/index.njk
  src/site/content/en/installable/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/lighthouse-accessibility/index.njk
  src/site/content/en/lighthouse-best-practices/index.njk
  src/site/content/en/lighthouse-performance/index.njk
  src/site/content/en/lighthouse-pwa/index.njk
  src/site/content/en/lighthouse-seo/index.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/react/index.njk
  src/site/content/en/reliable/index.njk
  src/site/content/en/secure/index.njk
  src/site/content/en/sitemap.xml.njk
  src/site/content/en/test/index.njk
Labels: cla: yes

#1754 add fonts and analytics to SW
  src/lib/sw.js
Labels: cla: yes

#1755 Add firebase performance monitoring
  src/lib/fb.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1758 Add custom dimensions to analytics.
  src/site/_data/site.js
  src/site/_includes/layout.njk
Labels: cla: yes

#1750 Makes offline page reload when back online
  server.js
  src/lib/bootstrap.js
  src/lib/loader.js
  src/lib/store.js
  src/lib/sw.js
  src/lib/utils/meta.js
  src/lib/utils/router.js
  src/site/_includes/layout.njk
  src/site/content/en/offline.njk
Labels: cla: yes

#1751 V2+cache more
  build.js
  compile-css.js
  package-lock.json
  package.json
  redirect-handler.js
  src/lib/sw.js
Labels: cla: yes

#1759 invert imgix condition
  src/site/_utils/get-image-path.js
Labels: cla: yes

#1760 V2+edge misc fixes
  src/lib/bootstrap-config.js
  src/lib/bootstrap.js
  src/lib/components/Header/_styles.scss
  src/lib/components/SideNav/_styles.scss
  src/lib/components/SideNav/index.js
  src/site/_includes/layout.njk
  src/styles/generic/_page.scss
Labels: cla: yes

#1761 Use compression on dev server.
  package-lock.json
  package.json
  server.js
Labels: cla: yes

#1757 Add Lighthouse CI
  .gitignore
  .travis.yml
  package.json
  tools/lhci/.lighthouserc
  tools/lhci/run-lighthouse-ci.sh
Labels: cla: yes

#1768 Fixes #1766. Set max-width on videos.
  src/styles/generic/_all.scss
  src/styles/generic/_video.scss
Labels: cla: yes

#1762 More unsupported browser fixes
  .gcloudignore
  build.js
  gulpfile.js
  src/lib/bootstrap-config.js
  src/lib/bootstrap.js
  src/lib/utils/router.js
  src/lib/utils/underscore-import-polyfill.js
  src/lib/webcomponents-config.js
  src/site/content/en/measure/index.njk
  src/styles/components/_page-header.scss
Labels: cla: yes

#1773 Fix RSS authors.
  src/site/content/en/feed.njk
Labels: cla: yes

#1775 Add firebase config to build.js
  build.js
  src/lib/fb.js
  src/site/_data/site.js
Labels: cla: yes

#1776 V2+reload pages new arch
  package-lock.json
  package.json
  src/lib/loader.js
  src/lib/sw.js
Labels: cla: yes

#1779 don't fetch results for empty URL
  src/lib/fb.js
Labels: cla: yes

#1765 Add ad speed blog post
  src/site/_data/contributors.json
  src/site/content/en/blog/fast-ads-matter/ad-latency-injected-vs-impressions-change.svg
  src/site/content/en/blog/fast-ads-matter/ad-latency-injected-vs-viewability-rate-change.svg
  src/site/content/en/blog/fast-ads-matter/desktop-leaderboard.svg
  src/site/content/en/blog/fast-ads-matter/index.md
  src/site/content/en/blog/fast-ads-matter/mobile-banner.svg
  src/site/content/en/images/authors/gernberg.jpg
  src/site/content/en/images/authors/gernberg@2x.jpg
  src/site/content/en/images/authors/jimper.jpg
  src/site/content/en/images/authors/jimper@2x.jpg
  src/site/content/en/images/authors/robhazan.jpg
  src/site/content/en/images/authors/robhazan@2x.jpg
  src/site/content/en/images/authors/thebengeu.jpg
  src/site/content/en/images/authors/thebengeu@2x.jpg
Labels: cla: yes

#1705 Add the AMP guide for Next.js
  src/site/content/en/react/how-amp-can-guarantee-fastness-in-your-nextjs-app/index.md
  src/site/content/en/react/how-to-use-amp-in-nextjs/amp.png
  src/site/content/en/react/how-to-use-amp-in-nextjs/ampimg.png
  src/site/content/en/react/how-to-use-amp-in-nextjs/hybrid.png
  src/site/content/en/react/how-to-use-amp-in-nextjs/index.md
  src/site/content/en/react/how-to-use-amp-in-nextjs/main.png
  src/site/content/en/react/how-to-use-amp-in-nextjs/mainimg.png
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
  src/site/content/en/react/react.11tydata.js
Labels: DO NOT MERGE, cla: yes

#1783 Add aria-current to active page.
  src/lib/components/Header/index.js
Labels: cla: yes

#1781 Updating the portals animation snippet to only use tranform and opacity
  src/site/content/en/blog/hands-on-portals/glitch.gif
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/hands-on-portals/portal-preview-demo.gif
Labels: cla: yes

#1723 Odds and ends in LH a11y cleanup
  src/site/content/en/lighthouse-accessibility/button-name/index.md
  src/site/content/en/lighthouse-accessibility/color-contrast/bg-color-picker.png
  src/site/content/en/lighthouse-accessibility/color-contrast/index.md
  src/site/content/en/lighthouse-accessibility/custom-control-roles/index.md
Labels: cla: yes

#1787 Don't use unistore devtools in prod.
  src/lib/store.js
Labels: cla: yes

#1788 Update deploy command.
  package.json
Labels: cla: yes

#1789 Clean up layout template. Add favicon. Remove outdated hash file.
  entrypoint.hashmanifest.json
  src/site/_includes/layout.njk
Labels: cla: yes

#1791 Fixes #1790. Let folks tab out of search box.
  src/lib/components/Search/index.js
Labels: cla: yes

#1367 Updates "SameSite cookies explainer" and adds "SameSite cookies recipes"
  src/site/content/en/blog/samesite-cookie-recipes/chrome-console-warning.png
  src/site/content/en/blog/samesite-cookie-recipes/cookie-hero.jpg
  src/site/content/en/blog/samesite-cookie-recipes/iframe.png
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookie-recipes/safe-navigation.png
  src/site/content/en/blog/samesite-cookie-recipes/samesite-devtools.png
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes, p0

#1793 Add policies redirect for Oauth
  src/site/content/en/_redirects.yaml
Labels: cla: yes

#1809 Corrections on browser behavior
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes

#1726 Add first article for WebXR.
  src/site/content/en/blog/vr-comes-to-the-web/hero.jpg
  src/site/content/en/blog/vr-comes-to-the-web/immersive-spectrum.png
  src/site/content/en/blog/vr-comes-to-the-web/index.md
  src/site/content/en/tags.yml
Labels: cla: yes

#1807 update/ .web-progress-bar (Progress bar in front of card dividers)
  src/styles/pages/_measure.scss
Labels: cla: yes

#1782 Fix typo in ad speed blog post
  src/site/content/en/blog/fast-ads-matter/mobile-banner.svg
Labels: cla: yes

#1786 Quick fix for semantics-and-screen-readers post.
  src/site/content/en/accessible/semantics-and-screen-readers/index.md
Labels: cla: yes

#1799 Typo fix
  src/site/content/en/blog/samesite-cookie-recipes/index.md
Labels: cla: yes

#1801 Add github link to contributors for gernberg
  src/site/_data/contributors.json
Labels: cla: yes

#1804 Add hero and thumbnail images to ad speed blog post
  src/site/content/en/blog/fast-ads-matter/hero.jpg
  src/site/content/en/blog/fast-ads-matter/index.md
  src/site/content/en/blog/fast-ads-matter/thumbnail.jpg
Labels: cla: yes

#1802 Change code font-size to rem
  src/styles/generic/_code.scss
Labels: cla: yes

#1800 Fixes 1772 - removes extra styles in LighthouseScores
  src/lib/components/LighthouseScoresStats/_styles.scss
Labels: cla: yes
