Repository GoogleChrome/web.dev, pull requests merged in 2020-01, with the labels that each got.

#2053 Add ci workflow.
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#2057 Some small language updates to the readme.
  README.md
Labels: cla: yes

#2056 Make sure ids are unique in custom elements
  src/lib/components/BaseElement/index.js
  src/lib/components/Tabs/index.js
Labels: cla: yes

#1842 Correct margins in buttons on mobile. Fixes #890
  src/lib/components/UrlChooser/_styles.scss
  src/styles/generic/_buttons.scss
Labels: cla: yes

#2059 Bug/fix broken images
  src/site/_drafts/_template-post/index.md
  src/site/content/en/blog/lighthouse-evolution-cds-2019/index.md
  src/site/content/en/handbook/markup-media/index.md
Labels: cla: yes

#1994 Add Share Targets in Workbox.
  src/site/content/en/blog/workbox-share-targets/hero.jpg
  src/site/content/en/blog/workbox-share-targets/index.md
  src/site/content/en/blog/workbox-share-targets/wst-send.png
Labels: cla: yes, post cds

#2052 Add self-assessments batch 1
  src/lib/components/Tabs/_styles.scss
  src/site/_includes/components/AssessmentHint.js
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/reliable/codelab-explore-network-panel/index.md
  src/site/content/en/secure/same-origin-policy/index.md
Labels: cla: yes

#2065 adds paragraph on loading images with picture tag
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#1999 feat(blog): add pagination to blog landing page, fixes #719
  .eleventy.js
  src/lib/components/Header/index.js
  src/site/_filters/paginate.js
  src/site/_includes/components/Meta.js
  src/site/content/en/blog/index.njk
  src/styles/components/_grid.scss
  src/styles/pages/_all.scss
  src/styles/pages/_pagination.scss
Labels: cla: yes

#2062 Clean up the "last audit" section on /measure on mobile.
  src/lib/components/LighthouseScoresMeta/_styles.scss
  src/lib/components/LighthouseScoresMeta/index.js
Labels: cla: yes

#2063 Fix code samples in RSS feed
  src/site/content/en/feed.njk
Labels: cla: yes

#2067 Address issues in 1st self-assessment sets
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/styles/components/_details.scss
  src/styles/components/_self-assessment-hint.scss
Labels: cla: yes

#2066 fix(SnackbarContainer): check`localStorage` before intercepting install prompt, fixes #2023
  src/lib/app.js
  src/lib/components/SnackbarContainer/index.js
Labels: cla: yes

#2060 Fix sticky hover and focus styles
  src/lib/components/CopyCode/styles.scss
  src/lib/components/Tabs/_styles.scss
  src/styles/components/_buttons.scss
  src/styles/components/_details.scss
  src/styles/components/_self-assessment-hint.scss
  src/styles/components/_tooltips.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#2073 Fix the updated date
  src/site/content/en/feed.njk
Labels: cla: yes

#2072 Small visual fixes to /measure at 360px
  src/lib/components/LighthouseScoresAudits/_styles.scss
  src/lib/components/LighthouseScoresMetrics/_styles.scss
Labels: cla: yes

#2061 Adds Advancing the Web Framework Ecosystem CDS article
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/babel-preset-env.png
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/barnebys.png
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/conformance.png
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/differential-loading-angular.png
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/framework-types.png
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/hero.jpg
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/index.md
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/thumbnail.jpg
Labels: cla: yes

#1639 Add Largest Contentful Paint documentation for Lighthouse
  src/site/content/en/lighthouse-performance/first-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/first-cpu-idle/index.md
  src/site/content/en/lighthouse-performance/first-meaningful-paint/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/largest-contentful-paint.png
  src/site/content/en/lighthouse-performance/lighthouse-max-potential-fid/index.md
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-performance/lighthouse-total-blocking-time/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
Labels: cla: yes

#2036 fix: Remove Strong tags from code
  src/site/content/en/fast/codelab-serve-modern-code/index.md
Labels: cla: yes

#2074 Switch to NetworkFirst sw strategy.
  src/lib/sw.js
Labels: cla: yes

#2082 Rev service worker version to force it to update.
  src/lib/sw.js
Labels: cla: yes

#2071 Update Contact Picker and Shape Detection origin trial information
  src/site/content/en/blog/contact-picker/index.md
  src/site/content/en/blog/shape-detection/index.md
Labels: cla: yes

#1988 Updates to "Multi origin PWA" article.
  src/site/content/en/blog/multi-origin-pwas/index.md
Labels: cla: yes

#1991 Add devtools-headsup include
  src/site/_drafts/_template-codelab/index.md
  src/site/_includes/content/devtools-headsup.njk
  src/site/content/en/fast/codelab-adapt-video-to-image-serving-based-on-network-quality/index.md
  src/site/content/en/fast/codelab-cloudinary/index.md
  src/site/content/en/fast/codelab-code-splitting/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/codelab-imgix/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
  src/site/content/en/fast/codelab-preload-critical-assets/index.md
  src/site/content/en/fast/codelab-preload-web-fonts/index.md
  src/site/content/en/fast/codelab-remove-unused-code/index.md
  src/site/content/en/fast/codelab-replace-gifs-with-video/index.md
  src/site/content/en/fast/codelab-serve-modern-code/index.md
  src/site/content/en/fast/codelab-text-compression-brotli/index.md
  src/site/content/en/fast/codelab-text-compression/index.md
  src/site/content/en/fast/codelab-two-ways-to-prefetch/index.md
  src/site/content/en/lighthouse-pwa/codelab-apple-touch-icon/index.md
  src/site/content/en/reliable/codelab-explore-network-panel/index.md
  src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md
  src/site/content/en/reliable/codelab-service-workers/index.md
Labels: cla: yes

#2008 Correct a technical error.
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#2048 Update Samesite cookie articles for Chrome 80.
  src/site/content/en/blog/samesite-cookie-recipes/chrome-console-warning.png
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
Labels: cla: yes, p0

#2075 Update FAQ section in native lazy loading article
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#2079 Adds note on module scripts default defer behavior
  src/site/content/en/fast/codelab-serve-modern-code/index.md
  src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md
Labels: cla: yes

#2084 Synchronize tags in fugu posts.
  src/site/content/en/blog/maskable-icon/index.md
  src/site/content/en/blog/periodic-background-sync/index.md
  src/site/content/en/blog/sms-receiver-api-announcement/index.md
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/index.md
  src/site/content/en/blog/workbox-share-targets/index.md
Labels: capabilities, cla: yes, task

#2038 Update Lighthouse logo hero image.
  src/site/content/en/blog/lighthouse-evolution-cds-2019/hero.jpg
  src/site/content/en/blog/lighthouse-evolution-cds-2019/index.md
  src/site/content/en/blog/lighthouse-evolution-cds-2019/lighthouse-logo.svg
Labels: cla: yes, content

#2068 chore: update dependencies from @11ty org
  package-lock.json
  package.json
  src/site/content/en/blog/index.njk
Labels: cla: yes

#2070 Issue 1290
  src/site/_includes/path.njk
Labels: cla: yes

#2100 [content] Adds eBay web performance case study
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content0.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content1.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content2.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content3.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content4.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content5.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/dev-content6.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/hero.png
  src/site/content/en/blog/shopping-for-speed-on-ebay/index.md
  src/site/content/en/blog/shopping-for-speed-on-ebay/thumbnail.png
Labels: cla: yes

#2095 Disable pointer events on action button children
  src/styles/components/_actions.scss
Labels: cla: yes

#2105 Remove CDS banner from homepage.
  src/site/content/en/index.njk
Labels: cla: yes

#2106 Fix focus behavior for side nav
  package-lock.json
  package.json
  src/lib/actions.js
Labels: cla: yes

#2088 Remove codelabs for proprietary tooling
  src/site/content/en/fast/codelab-cloudinary/cloudname.mp4
  src/site/content/en/fast/codelab-cloudinary/cloudname.webm
  src/site/content/en/fast/codelab-cloudinary/images-not-optimized.png
  src/site/content/en/fast/codelab-cloudinary/index.md
  src/site/content/en/fast/codelab-cloudinary/optimized-images.png
  src/site/content/en/fast/codelab-imgix/imgix-url.png
  src/site/content/en/fast/codelab-imgix/index.md
  src/site/content/en/fast/codelab-imgix/lighthouse.png
  src/site/content/en/fast/image-cdns/index.md
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#2087 update handbook policy re: open-source/proprietary tools
  src/site/content/en/handbook/tooling-and-libraries/index.md
Labels: cla: yes

#2101 Clarify CrUX bucketing for CLS
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#1984 Update lazysizes version to 5.1.2 (latest stable)
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes
