Repository GoogleChrome/web.dev, pull requests merged in 2020-10, with the labels that each got.

#3979 remove extra slashes when normalizing URL
  src/lib/urls.js
  test/unit/src/lib/urls.js
Labels: cla: yes

#3981 Declarative Shadow DOM: clarify nature of tentative release
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#3985 Add vanity url for scale on web case studies
  src/site/content/_redirects.yaml
Labels: cla: yes

#3976 Make code blocks larger on small screens
  src/styles/generic/_code.scss
Labels: cla: yes

#3989 Fix LCP fast threshold in LH doc
  src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md
Labels: cla: yes

#3967 [File System Access article] Native File System → File System Access
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#3986 Added post: What are third-party origin trials?
  src/site/content/en/blog/origin-trials/index.md
  src/site/content/en/blog/third-party-origin-trials/hero.jpg
  src/site/content/en/blog/third-party-origin-trials/index.md
  src/site/content/en/blog/third-party-origin-trials/thumbnail.jpg
  src/site/content/en/blog/third-party-origin-trials/with-and-without.png
Labels: cla: yes

#3947 Add Camera PTZ article
  src/site/content/en/blog/camera-pan-tilt-zoom/camera-ptz-user-prompt.jpg
  src/site/content/en/blog/camera-pan-tilt-zoom/hero.jpg
  src/site/content/en/blog/camera-pan-tilt-zoom/index.md
  src/site/content/en/blog/camera-pan-tilt-zoom/media-internals-page.jpg
  src/site/content/en/blog/camera-pan-tilt-zoom/thumbnail.jpg
  src/site/content/en/blog/fugu-status/index.md
Labels: DO NOT MERGE, capabilities, cla: yes, content

#4002 add gitlocalize yaml
  .gitlocalize.yml
Labels: cla: yes

#3971 Migrate offline cookbook
  src/site/_data/paths/reliable.json
  src/site/content/en/reliable/offline-cookbook/cm-on-activate.png
  src/site/content/en/reliable/offline-cookbook/cm-on-bg-sync.png
  src/site/content/en/reliable/offline-cookbook/cm-on-install-dep.png
  src/site/content/en/reliable/offline-cookbook/cm-on-install-not.png
  src/site/content/en/reliable/offline-cookbook/cm-on-network-response.png
  src/site/content/en/reliable/offline-cookbook/cm-on-push.png
  src/site/content/en/reliable/offline-cookbook/cm-on-user-interaction.png
  src/site/content/en/reliable/offline-cookbook/cm-stale-while-revalidate.png
  src/site/content/en/reliable/offline-cookbook/index.md
  src/site/content/en/reliable/offline-cookbook/ss-cache-and-network-race.png
  src/site/content/en/reliable/offline-cookbook/ss-cache-only.png
  src/site/content/en/reliable/offline-cookbook/ss-cache-then-network.png
  src/site/content/en/reliable/offline-cookbook/ss-falling-back-to-network.png
  src/site/content/en/reliable/offline-cookbook/ss-generic-fallback.png
  src/site/content/en/reliable/offline-cookbook/ss-network-falling-back-to-cache.png
  src/site/content/en/reliable/offline-cookbook/ss-network-only.png
  src/site/content/en/reliable/offline-cookbook/ss-sw-side-templating.png
Labels: cla: yes

#3993 [Idle Detection article] Add user gesture requirement
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4012 Update the content review checklists
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/policies/index.md
Labels: cla: yes, content update, handbook

#3996 Add a guard in the example with a message passing
  src/site/content/en/blog/detached-window-memory-leaks/index.md
Labels: cla: yes

#4015 New article: "Event Conversion Measurement API"
  src/site/content/en/blog/conversion-measurement/all-apis.jpg
  src/site/content/en/blog/conversion-measurement/diagram-overview.jpg
  src/site/content/en/blog/conversion-measurement/hero.jpg
  src/site/content/en/blog/conversion-measurement/index.md
  src/site/content/en/blog/conversion-measurement/report-timing.jpg
  src/site/content/en/blog/conversion-measurement/steps-1.jpg
  src/site/content/en/blog/conversion-measurement/steps-2.jpg
  src/site/content/en/blog/conversion-measurement/steps-3.jpg
  src/site/content/en/blog/conversion-measurement/with-api.jpg
  src/site/content/en/blog/conversion-measurement/with-cookies.jpg
Labels: Chrome 87, beta related, cla: yes, p0, privacy/security

#4017 Minor fixes on the conversion measurement article
  src/site/content/en/blog/conversion-measurement/index.md
Labels: cla: yes

#4013 Add Acknowledgements section to post template
  src/site/_drafts/_template-post/index.md
Labels: cla: yes

#4007 "Handling range requests in a service worker" post
  src/site/content/en/blog/sw-range-requests/hero.jpg
  src/site/content/en/blog/sw-range-requests/index.md
Labels: cla: yes

#4016 Update translated workflow
  .github/workflows/tranaslation-status-workflow.yml
  tools/update-translated/index.js
Labels: cla: yes

#4023 FileSystem Access: add TypeScript defs to "Helpful links"
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#3978 Add ZDF Offline Case Study
  src/images/authors/scottfriesen.jpg
  src/images/authors/scottfriesen@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/zdf/custom-prompt-after.jpg
  src/site/content/en/blog/zdf/custom-prompt-before.jpg
  src/site/content/en/blog/zdf/hero.jpg
  src/site/content/en/blog/zdf/index.md
  src/site/content/en/blog/zdf/offline-page.png
  src/site/content/en/blog/zdf/online-page.png
Labels: DO NOT MERGE, cla: yes

#4021 Update third-party origin trials post: example registration screenshot, hero image alt text
  src/site/content/en/blog/third-party-origin-trials/index.md
  src/site/content/en/blog/third-party-origin-trials/tpot-registration.png
Labels: cla: yes

#4030 Typo fix
  src/site/content/en/blog/zdf/index.md
Labels: cla: yes

#4032 [ZDF PWA article] Typo fix and two links
  src/site/content/en/blog/zdf/index.md
Labels: cla: yes

#4035 updates to animations guide
  src/site/content/en/animations/animations-guide/index.md
Labels: cla: yes

#4028 Fix a few typos.
  src/site/content/en/reliable/network-connections-unreliable/index.md
Labels: cla: yes

#3897 What is mixed content blog post
  src/site/_data/authorsData.json
  src/site/_data/paths/secure.json
  src/site/content/en/secure/what-is-mixed-content/active-mixed-content.jpg
  src/site/content/en/secure/what-is-mixed-content/index.md
  src/site/content/en/secure/what-is-mixed-content/passive-mixed-content.jpg
Labels: cla: yes

#4046 Add mdn survey banner.
  src/site/_data/site.js
Labels: cla: yes

#4039 Update example from makeRequest() to handle()
  src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md
Labels: cla: yes

#4043 [Origin Trial article] Add info that breakage period may be skipped
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#4060 Add Tokopedia case study
  src/site/_data/tagsData.json
  src/site/content/en/blog/goibibo/index.md
  src/site/content/en/blog/tokopedia/controller.png
  src/site/content/en/blog/tokopedia/hero.png
  src/site/content/en/blog/tokopedia/homepage.png
  src/site/content/en/blog/tokopedia/index.md
  src/site/content/en/blog/tokopedia/thumbnail.png
  src/site/content/en/blog/tokopedia/tti.png
Labels: cla: yes

#4054 How browsers handle updates to the web app manifest
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/progressive-web-apps/manifest-updates/index.md
Labels: cla: yes, content, new content, pwa

#3987 Update guidance around unload event
  src/site/content/en/blog/disallow-synchronous-xhr/index.md
Labels: cla: yes

#4018 Blog post for Chrome 87: flow relative shorthands [2020-10-14]
  src/site/content/en/blog/logical-property-shorthands/block-and-inline-visual.png
  src/site/content/en/blog/logical-property-shorthands/hero.png
  src/site/content/en/blog/logical-property-shorthands/index.md
  src/site/content/en/blog/logical-property-shorthands/thumb.png
Labels: Chrome 87, DO NOT MERGE, beta related, cla: yes

#4031 Add SXG article
  src/site/content/en/fast/signed-exchanges/hero.jpg
  src/site/content/en/fast/signed-exchanges/index.md
  src/site/content/en/fast/signed-exchanges/signed-exchange-network-panel.png
  src/site/content/en/fast/signed-exchanges/sxg-preview.png
Labels: cla: yes

#4024 [Post] min(), max(), clamp()
  src/site/content/en/blog/min-max-clamp/caniuse.png
  src/site/content/en/blog/min-max-clamp/hero.jpg
  src/site/content/en/blog/min-max-clamp/index.md
Labels: cla: yes

#3899 Create Web Vitals collection
  src/images/collections/web-vitals.svg
  src/site/_data/paths/index.js
  src/site/_data/paths/learn-web-vitals.json
  src/site/_data/paths/vitals.json
  src/site/_includes/page.njk
  src/site/content/en/en.11tydata.js
  src/site/content/en/learn-web-vitals/index.njk
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/vitals/index.md
  src/site/content/pl/pl.11tydata.js
Labels: cla: yes

#4066 Add cds banner.
  src/images/modules/cds20-wide_960.jpg
  src/site/_includes/homepage.njk
  src/styles/components/_all.scss
  src/styles/components/_promo-banner.scss
Labels: cla: yes

#4061 DevTools info
  src/site/content/en/animations/animations-guide/fps-after.jpg
  src/site/content/en/animations/animations-guide/fps-before.jpg
  src/site/content/en/animations/animations-guide/index.md
  src/site/content/en/animations/animations-overview/index.md
Labels: cla: yes

#4001 Tag devices related articles
  src/site/_data/tagsData.json
  src/site/content/en/blog/hid-examples/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#4072 [bugfix] Fix typo in min, max, clamp post code sample
  src/site/content/en/blog/min-max-clamp/index.md
Labels: bug, cla: yes

#4059 Added link to check latest
  README.md
Labels: cla: yes

#4022 Add WebCodecs article.
  src/site/content/en/blog/webcodecs/complete-drawing.png
  src/site/content/en/blog/webcodecs/consuming-frames-from-bitmaps.png
  src/site/content/en/blog/webcodecs/consuming-frames-from-tracks.png
  src/site/content/en/blog/webcodecs/hero.jpg
  src/site/content/en/blog/webcodecs/index.md
  src/site/content/en/blog/webcodecs/producing-frames.png
Labels: Chrome 87, DO NOT MERGE, beta related, cla: yes

#4065 adds more elaborate example for fallbacks
  src/site/content/en/blog/logical-property-shorthands/index.md
Labels: cla: yes

#4076 Add missing word 'of'
  src/site/content/en/fast/signed-exchanges/index.md
Labels: cla: yes

#4077 Webcodecs blogpost minor fixes
  src/site/content/en/blog/webcodecs/index.md
Labels: cla: yes

#4078 Fix rogue `s` in DSD article
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#4083 [Origin Trial article] Fix link in aside
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#4089 Add cds 2020 site banner.
  src/site/_data/site.js
Labels: cla: yes

#4071 Change RSS updated field to build date
  src/site/_data/site.js
  src/site/_includes/feed.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#4082 Add print styles
  src/lib/components/Feedback/_styles.scss
  src/styles/components/_actions.scss
  src/styles/components/_article-header.scss
  src/styles/components/_article-navigation.scss
  src/styles/components/_footer.scss
  src/styles/components/_header.scss
  src/styles/components/_toc.scss
  src/styles/generic/_main.scss
Labels: cla: yes

#4042 Update COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#4095 Convert WebUSB article from WebFu
  src/site/content/en/blog/usb/hero.jpg
  src/site/content/en/blog/usb/index.md
  src/site/content/en/blog/usb/thumbnail.jpg
  src/site/content/en/blog/usb/usb-device-chooser.png
  src/site/content/en/blog/usb/web-usb-device-log-page.png
  src/site/content/en/blog/usb/web-usb-internals-page.png
  src/site/content/en/blog/usb/web-usb-notification.png
Labels: CDS 2020, cla: yes

#4101 [Async Clipboard article] Fix iframe permissions policy attributes, add explanation
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4080 Note on WCAG risk for fluid type
  src/site/content/en/blog/min-max-clamp/index.md
Labels: cla: yes

#4098 Add PointerLock unadjustedMovement article
  src/site/content/en/blog/mouse-acceleration/hero.jpg
  src/site/content/en/blog/mouse-acceleration/index.md
  src/site/content/en/blog/mouse-acceleration/mouse-properties-dialog.png
  src/site/content/en/blog/mouse-acceleration/thumbnail.jpg
Labels: cla: yes

#4106 Revert "Add PointerLock unadjustedMovement article"
  src/site/content/en/blog/mouse-acceleration/hero.jpg
  src/site/content/en/blog/mouse-acceleration/index.md
  src/site/content/en/blog/mouse-acceleration/mouse-properties-dialog.png
  src/site/content/en/blog/mouse-acceleration/thumbnail.jpg
Labels: cla: yes

#4091 Add parens to method name.
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/blog/why-coop-coep/index.md
Labels: cla: yes, content update

#4103 [file a good bug article] add pointer to bisect-builds.py
  src/site/content/en/blog/how-to-file-a-good-bug/index.md
Labels: cla: yes

#4081 margin-inline isn't a potential physical cruft
  src/site/content/en/blog/logical-property-shorthands/index.md
Labels: cla: yes, content update, frontend

#4090 Convert Web Bluetooth article from WebFu
  src/site/content/en/blog/bluetooth/hero.jpg
  src/site/content/en/blog/bluetooth/index.md
  src/site/content/en/blog/bluetooth/thumbnail.jpg
Labels: CDS 2020, cla: yes

#4109 Link to Cache API guide from web.dev/reliable
  src/site/_data/paths/reliable.json
Labels: cla: yes

#3937 Add File Handling article
  src/site/content/en/blog/file-handling/context-menu.png
  src/site/content/en/blog/file-handling/finder.png
  src/site/content/en/blog/file-handling/hero.jpg
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#3980 Add devices learning area
  src/images/collections/devices.svg
  src/site/_data/paths/devices.json
  src/site/_data/paths/index.js
  src/site/content/en/devices/index.njk
  src/site/content/en/learn/learn.11tydata.js
Labels: CDS 2020, cla: yes

#4094 Update Web OTP article
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#4036 cls: add link to ad-specific mitigation guidance
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#4126 Add NDTV case study (WIP)
  src/site/content/en/blog/ndtv/bounce-rate.png
  src/site/content/en/blog/ndtv/cls.png
  src/site/content/en/blog/ndtv/hero.png
  src/site/content/en/blog/ndtv/index.md
  src/site/content/en/blog/ndtv/optimizations.png
  src/site/content/en/blog/ndtv/thumbnail.png
Labels: cla: yes

#4114 Add measure offline usage guide
  src/images/authors/giesau.jpg
  src/images/authors/giesau@2x.jpg
  src/images/authors/mschierle.jpg
  src/images/authors/mschierle@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/reliable.json
  src/site/content/en/reliable/measuring-offline-usage/hero.jpg
  src/site/content/en/reliable/measuring-offline-usage/index.md
Labels: cla: yes

#3863 Add Offline UX Considerations article
  src/site/_data/paths/progressive-web-apps.json
  src/site/_data/paths/reliable.json
  src/site/content/en/reliable/offline-ux-design-guidelines/accessibility_color7_do.png
  src/site/content/en/reliable/offline-ux-design-guidelines/accessibility_color8_dont.png
  src/site/content/en/reliable/offline-ux-design-guidelines/chome-offline.png
  src/site/content/en/reliable/offline-ux-design-guidelines/chrome-status-app-updated.png
  src/site/content/en/reliable/offline-ux-design-guidelines/download-icons-examples.png
  src/site/content/en/reliable/offline-ux-design-guidelines/download.png
  src/site/content/en/reliable/offline-ux-design-guidelines/emojoy-toast-message.png
  src/site/content/en/reliable/offline-ux-design-guidelines/index.md
  src/site/content/en/reliable/offline-ux-design-guidelines/io-offline-ready.png
  src/site/content/en/reliable/offline-ux-design-guidelines/io-toast-message.png
  src/site/content/en/reliable/offline-ux-design-guidelines/material-money-rates-out-of-date.png
  src/site/content/en/reliable/offline-ux-design-guidelines/material-money-rates-updated.png
  src/site/content/en/reliable/offline-ux-design-guidelines/service-worker-ready.png
  src/site/content/en/reliable/offline-ux-design-guidelines/tailpiece-normal.png
  src/site/content/en/reliable/offline-ux-design-guidelines/tailpiece-offline-sidebar.png
  src/site/content/en/reliable/offline-ux-design-guidelines/tailpiece-offline.png
  src/site/content/en/reliable/offline-ux-design-guidelines/tailpiece-skel-article.png
  src/site/content/en/reliable/offline-ux-design-guidelines/tailpiece-tap-to-update.png
  src/site/content/en/reliable/offline-ux-design-guidelines/weather-app.png
Labels: cla: yes, content update

#4100 Add note on WebKit to the referrer best practices guide
  src/site/content/en/blog/referrer-best-practices/index.md
  src/site/content/en/secure/same-site-same-origin/index.md
Labels: cla: yes, content update, privacy/security

#4113 [File Handling article] More accurate Blink component
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#4116 [File System Access article] showFileOpenPicker -> showOpenFilePicker
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4125 [Text Fragment article] Update article now that crbug.com/1055455 is fixed
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#4112 Update min-max-clamp for real.
  src/site/content/en/blog/min-max-clamp/index.md
Labels: cla: yes

#4127 Trivial update to Web OTP
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#4131 [Local Font Access articlw] Update now that origin trial has started
  src/site/content/en/blog/local-fonts/index.md
Labels: cla: yes

#4133 Remove references to index.html
  src/site/content/en/blog/link-prefetch/index.md
Labels: cla: yes, content

#4155 Ignore .vscode directory
  .gitignore
  .vscode/settings.json
Labels: cla: yes
