Repository GoogleChrome/web.dev, pull requests merged in 2020-11, with the labels that each got.

#4160 Revert "prefer redirect"
  redirect-handler.js
  server.js
Labels: cla: yes

#4142 [Offline UX Design Guidelines article] Use columns for comparisons
  src/site/content/en/reliable/offline-ux-design-guidelines/index.md
Labels: cla: yes

#4143 fix typo
  src/site/content/en/fast/defer-non-critical-css/index.md
Labels: cla: yes

#4141 [Declarative Shadow Root article] Make adoptedStyleSheets appear in code font
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#4164 [Clipboard article] Add missing `>`
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4148 Run SVGMOMG on SVG icons
  src/images/icons/a11y.svg
  src/images/icons/calendar.svg
  src/images/icons/github.svg
  src/images/icons/glitch.svg
  src/images/icons/language.svg
  src/images/icons/performance.svg
  src/images/icons/pwa.svg
  src/images/icons/reload.svg
  src/images/icons/rss.svg
  src/images/icons/seo.svg
  src/images/icons/share_white.svg
  src/images/icons/subscribe.svg
Labels: cla: yes

#4165 Use CDN for side nav logo
  src/lib/components/SideNav/index.js
  src/site/_includes/layout.njk
  src/site/_transforms/responsive-images/index.js
Labels: DO NOT MERGE, cla: yes

#4166 [File Handling article] Content clarity improvements
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#4167 [Screen Wake Lock article] Type is optional
  src/site/content/en/blog/wake-lock/index.md
Labels: cla: yes

#4154 Add gamepad article
  src/site/content/en/blog/gamepad/dino.png
  src/site/content/en/blog/gamepad/gamepad.svg
  src/site/content/en/blog/gamepad/hero.jpg
  src/site/content/en/blog/gamepad/index.md
Labels: cla: yes, new content

#4176 [Async Clipboard article] Prune unnecessary iframe `allow` values
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4178 [Declarative Shadow DOM article] Fix polyfill - add missing );
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#4179 fix failure
  src/site/content/en/blog/gamepad/index.md
Labels: cla: yes

#4174 [Text Fragments article] Add links to all browser versions of the extension
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#4182 fix typo in media accessibility page
  src/site/content/en/media/media-accessibility/index.md
Labels: cla: yes

#4181 [Gamepad article] Remove Switch references, add iframe embed instead
  src/site/content/en/blog/gamepad/index.md
Labels: cla: yes

#4186 Code snippets pass contrast accessibility scores
  src/styles/generic/_code.scss
Labels: accessible, cla: yes

#4191 Add devices tag to gamepad article
  src/site/content/en/blog/gamepad/index.md
Labels: cla: yes

#4192 Link to lazysizes library
  src/site/content/en/fast/browser-level-image-lazy-loading/index.md
Labels: cla: yes

#4200 Incorrect MDN link for Clipboard API
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4201 [File System Access article] s/opts/options/
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4203 Add ux banner
  src/site/_data/site.js
Labels: cla: yes

#4189 CORS-RFC1918 feedback article #3988
  src/site/content/en/blog/cors-rfc1918-feedback/console-error.png
  src/site/content/en/blog/cors-rfc1918-feedback/cors-error.png
  src/site/content/en/blog/cors-rfc1918-feedback/diagram.png
  src/site/content/en/blog/cors-rfc1918-feedback/hero.jpg
  src/site/content/en/blog/cors-rfc1918-feedback/index.md
Labels: cla: yes

#4207 Fix incorrect quote mark
  src/site/content/en/blog/speed-tooling-evolutions-cds-2019/index.md
Labels: cla: yes

#4196 [File System Access article] Add drag and drop integration
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4212 House the first 3 push notification docs temporarily in the blog directory
  src/images/authors/mattgaunt.jpg
  src/images/authors/mattgaunt@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/push-notifications-client-codelab/console-output.png
  src/site/content/en/blog/push-notifications-client-codelab/copy-live-app-url.png
  src/site/content/en/blog/push-notifications-client-codelab/index.md
  src/site/content/en/blog/push-notifications-client-codelab/live-app.jpg
  src/site/content/en/blog/push-notifications-client-codelab/remix-to-edit.png
  src/site/content/en/blog/push-notifications-overview/browser-to-server.svg
  src/site/content/en/blog/push-notifications-overview/examples.png
  src/site/content/en/blog/push-notifications-overview/index.md
  src/site/content/en/blog/push-notifications-overview/push-service-to-sw-event.svg
  src/site/content/en/blog/push-notifications-overview/server-to-push-service.svg
  src/site/content/en/blog/push-notifications-server-codelab/index.md
Labels: cla: yes

#4211 Remove _import polyfill
  build.js
  src/lib/loader.js
  src/lib/utils/underscore-import-polyfill.js
Labels: cla: yes

#4215 Corrects some spelling errors
  src/site/content/en/fast/browser-level-image-lazy-loading/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/pull-requests/index.md
  src/site/content/en/media/media-application-basics/index.md
  src/site/content/en/media/media-cheat-sheet/index.md
  src/site/content/en/media/media-experience/index.md
  src/site/content/en/media/video-and-source-tags/index.md
  src/site/content/en/notifications/codelab-notifications-push-server/index.md
  src/site/content/en/progressive-web-apps/drive-business-success/index.md
  src/site/content/en/react/accessibility-auditing-react/index.md
  src/site/content/en/react/how-amp-can-guarantee-fastness-in-your-nextjs-app/index.md
  src/site/content/en/react/precache-with-workbox-react/index.md
  src/site/content/en/react/prerender-with-react-snap/index.md
  src/site/content/en/react/virtualize-long-lists-react-window/index.md
  src/site/content/en/reliable/instant-navigation-experiences/index.md
  src/site/content/en/reliable/resilient-search-experiences/index.md
  src/site/content/en/reliable/runtime-caching-with-workbox/index.md
  src/site/content/en/secure/codelab-same-origin-iframe/codelab-same-origin-iframe.md
Labels: cla: yes

#4175 Lazyload algolia
  src/lib/components/Search/index.js
Labels: cla: yes

#4218 Preload app.css
  src/site/_includes/layout.njk
Labels: cla: yes

#4231 Article: Modern
  src/site/content/en/fast/publish-modern-javascript/index.md
Labels: CDS 2020, DO NOT MERGE, cla: yes, content, fast, performance

#4208 QuicTransport => WebTransport OT
  src/site/content/_redirects.yaml
  src/site/content/en/blog/webtransport/hero.jpg
  src/site/content/en/blog/webtransport/index.md
Labels: cla: yes

#4173 Remove "clipboard" and "vr" from default iframes allow
  src/site/_includes/components/Glitch.js
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#4122 chore: add eslint-plugin-lit-a11y
  .eslintrc.js
  package-lock.json
  package.json
  src/lib/components/Codelab/index.js
  src/lib/components/ProfileSwitcher/index.js
  src/lib/components/Search/index.js
  src/lib/components/SideNav/index.js
  src/lib/components/TableOfContents/index.js
  src/site/_includes/components/YouTube.js
Labels: cla: yes

#4230 Fix typo in tranaslation-status-workflow.yml file name
  .github/workflows/translation-status-workflow.yml
Labels: cla: yes

#4234 updated gcloud dep
  .github/workflows/cleanup-versions-workflow.yml
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/snapshot-firestore-workflow.yml
Labels: cla: yes

#4225 Fix the typo in file-handling.md
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#4226 [Async Clipboard article] Directly embed demo iframes
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4209 Add the back/forward cache article
  src/site/_includes/content/metrics/first-hidden-time.njk
  src/site/_includes/content/metrics/performance-observer-catch.njk
  src/site/_includes/content/metrics/performance-observer-init.njk
  src/site/_includes/content/metrics/performance-observer-try.njk
  src/site/_includes/content/metrics/send-to-analytics.njk
  src/site/content/en/blog/bfcache/hero.png
  src/site/content/en/blog/bfcache/index.md
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
Labels: DO NOT MERGE, cla: yes

#4210 Clarifying scrolling as non-excluded input
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#4204 add rakuten 24 case study
  src/site/content/en/blog/rakuten-24/a2hs.png
  src/site/content/en/blog/rakuten-24/hero.png
  src/site/content/en/blog/rakuten-24/impact.png
  src/site/content/en/blog/rakuten-24/index.md
  src/site/content/en/blog/rakuten-24/thumbnail.png
Labels: cla: yes, new content, pwa

#4257 reserve web.dev/nykaa
  src/site/content/en/blog/nykaa/index.md
Labels: cla: yes

#4227 Update webapk article link & remove DevTools note
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes, content update

#4239 Add Steven Bingler author entry
  src/images/authors/bingler.jpg
  src/images/authors/bingler@2x.jpg
  src/site/_data/authorsData.json
Labels: cla: yes

#4261 Change wording around Android zoom support.
  src/site/content/en/blog/camera-pan-tilt-zoom/index.md
Labels: cla: yes, content update

#4220 Add isInputPending guide
  src/images/authors/andrewcomminos.jpg
  src/images/authors/andrewcomminos@2x.jpg
  src/images/authors/nateschloss.jpg
  src/images/authors/nateschloss@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/isinputpending/diagram.png
  src/site/content/en/blog/isinputpending/hero.jpg
  src/site/content/en/blog/isinputpending/index.md
  src/site/content/en/blog/isinputpending/legend.png
Labels: cla: yes

#4265 Add missing screenshot
  src/site/content/en/blog/bluetooth/bluetooth-internals.jpg
Labels: cla: yes

#4269 [Local Fonts article] Correct Blink component
  src/site/content/en/blog/local-fonts/index.md
Labels: cla: yes

#4266 Mark font-display:optional for Material Icons font
  src/styles/fonts/_material-icons.scss
Labels: cla: yes

#4275 Fix layout shift in hamburger button
  src/styles/components/_header.scss
Labels: cla: yes

#4258 [CSS] Add table scroll hint shadow
  src/styles/generic/_tables.scss
Labels: cla: yes

#4262 Schemeful SameSite article and updated references
  src/site/_data/authorsData.json
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
  src/site/content/en/blog/schemeful-samesite/cross-scheme-form-submission.png
  src/site/content/en/blog/schemeful-samesite/cross-scheme-navigation.png
  src/site/content/en/blog/schemeful-samesite/cross-scheme-subresource.png
  src/site/content/en/blog/schemeful-samesite/index.md
  src/site/content/en/blog/schemeful-samesite/schemeful-samesite-hero.jpg
  src/site/content/en/blog/schemeful-samesite/schemeful-samesite-thumbnail.jpg
  src/site/content/en/secure/same-site-same-origin/index.md
Labels: cla: yes

#4232 Add "Browser level lazy loading for CMSs"
  src/images/authors/felixarntz.jpg
  src/images/authors/felixarntz@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/browser-level-lazy-loading-for-cmss/hero.jpg
  src/site/content/en/blog/browser-level-lazy-loading-for-cmss/index.md
Labels: cla: yes

#4277 pin our gcloud dep in GH Actions
  .github/workflows/cleanup-versions-workflow.yml
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/snapshot-firestore-workflow.yml
Labels: cla: yes

#4264 Use correct event in the article on bfcache
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#4267 [Fugu Status article] Make this less Google-centric
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#4286 Revert "Mark font-display:optional for Material Icon font (#4266)"
  src/styles/fonts/_material-icons.scss
Labels: cla: yes

#4287 add cds banner back
  src/site/_data/site.js
Labels: cla: yes

#4293 Add my author entry
  src/site/_data/authorsData.json
Labels: cla: yes

#4272 Remove redundant `=== true`
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#4270 Add JD.ID case study
  src/site/content/en/blog/jdid/hero.png
  src/site/content/en/blog/jdid/impact.png
  src/site/content/en/blog/jdid/index.md
  src/site/content/en/blog/jdid/install.jpg
  src/site/content/en/blog/jdid/offline.jpg
  src/site/content/en/blog/jdid/push.jpg
  src/site/content/en/blog/jdid/thumbnail.png
Labels: cla: yes

#4299 fix missing 'v'
  .github/workflows/cleanup-versions-workflow.yml
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/snapshot-firestore-workflow.yml
Labels: cla: yes

#2969 New Post: A Stories Component + Codelab
  src/site/content/en/blog/building-a-stories-component/carousel-of-carousels.png
  src/site/content/en/blog/building-a-stories-component/hero.jpg
  src/site/content/en/blog/building-a-stories-component/horizontal-scroll-with-grid.png
  src/site/content/en/blog/building-a-stories-component/index.md
  src/site/content/en/blog/building-a-stories-component/thumb.jpg
  src/site/content/en/blog/codelab-building-a-stories-component/horizontal-scroll-with-grid.png
  src/site/content/en/blog/codelab-building-a-stories-component/index.md
Labels: DO NOT MERGE, cla: yes

#4302 Updated profile photo
  src/images/authors/pjmclachlan.jpg
  src/images/authors/pjmclachlan@2x.jpg
Labels: cla: yes

#4236 Added "Using conversion measurement"
  src/site/content/en/blog/conversion-measurement/index.md
  src/site/content/en/blog/using-conversion-measurement/api-enable.jpg
  src/site/content/en/blog/using-conversion-measurement/hero.jpg
  src/site/content/en/blog/using-conversion-measurement/index.md
Labels: cla: yes, content update

#4107 Add PointerLock unadjustedMovement article
  src/site/content/en/blog/disable-mouse-acceleration/hero.jpg
  src/site/content/en/blog/disable-mouse-acceleration/index.md
  src/site/content/en/blog/disable-mouse-acceleration/mouse-properties-dialog.png
  src/site/content/en/blog/disable-mouse-acceleration/thumbnail.jpg
Labels: cla: yes

#4310 Add text description to conversion measurement diagram
  src/site/content/en/blog/using-conversion-measurement/index.md
Labels: cla: yes, content update

#4312 Adds 5 more aliases under /secure
  src/site/_data/paths/secure.json
Labels: cla: yes
