Repository GoogleChrome/web.dev, pull requests merged in 2020-05, with the labels that each got.

#2761 performance-scoring: add scorecalc screenshot
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
  src/site/content/en/lighthouse-performance/performance-scoring/score-calc.png
Labels: cla: yes

#2742 track signed-in state via Analytics
  build.js
  src/lib/analytics.js
  src/lib/app.js
  src/lib/fb.js
  src/lib/pageview.js
  src/site/_includes/layout.njk
Labels: cla: yes

#2763 Add dgrogan to contributors.json and images
  src/images/authors/dgrogan.jpg
  src/images/authors/dgrogan@2x.jpg
  src/site/_data/contributors.js
Labels: cla: yes

#2773 Ignore paths that were triggering percy.
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#2747 Properly feature-detect StorageManager
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: cla: yes, content update, pwa

#2768 use more chunks so we do less JS parsing on update
  build.js
Labels: cla: yes

#2775 Fix mistake in the example
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: cla: yes

#2705 Why you need "cross-origin isolated" for powerful features
  src/images/authors/domenic.jpg
  src/images/authors/domenic@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/why-coop-coep/browsing-context-group.png
  src/site/content/en/blog/why-coop-coep/coep.png
  src/site/content/en/blog/why-coop-coep/coop1.png
  src/site/content/en/blog/why-coop-coep/coop2.png
  src/site/content/en/blog/why-coop-coep/coop3.png
  src/site/content/en/blog/why-coop-coep/evil-actor.png
  src/site/content/en/blog/why-coop-coep/hero.jpg
  src/site/content/en/blog/why-coop-coep/index.md
Labels: cla: yes, content

#2782 add missing localStorage import
  src/lib/app.js
Labels: cla: yes

#2787 feat(contributors): give better feedback when contributor not in `_data/contributors.js`, fixes #2786
  src/site/_filters/expand-contributors.js
  src/site/_includes/components/Author.js
  src/site/_includes/components/BaseCard.js
Labels: cla: yes

#2764 Add Web Vitals landing page
  src/site/_data/postTags.js
  src/site/_includes/content/metrics/first-hidden-time.njk
  src/site/_includes/content/metrics/metrics-changelog.njk
  src/site/_includes/content/metrics/performance-observer-catch.njk
  src/site/_includes/content/metrics/performance-observer-init.njk
  src/site/_includes/content/metrics/performance-observer-try.njk
  src/site/_includes/content/metrics/send-to-analytics.njk
  src/site/_includes/page.njk
  src/site/content/en/en.11tydata.js
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
  src/site/content/en/vitals/cls_4x3.svg
  src/site/content/en/vitals/cls_8x2.svg
  src/site/content/en/vitals/cls_ux.svg
  src/site/content/en/vitals/fid_4x3.svg
  src/site/content/en/vitals/fid_8x2.svg
  src/site/content/en/vitals/fid_ux.svg
  src/site/content/en/vitals/index.md
  src/site/content/en/vitals/lcp_4x3.svg
  src/site/content/en/vitals/lcp_8x2.svg
  src/site/content/en/vitals/lcp_ux.svg
  src/site/content/en/vitals/vitals.11tydata.js
  src/site/content/en/vitals/web-vitals.svg
  src/styles/components/_all.scss
  src/styles/components/_stack.scss
Labels: cla: yes

#2715 Adds optimize CLS article
  src/site/_data/postTags.js
  src/site/content/en/blog/optimize-cls/Optimize-Cumulative11.jpg
  src/site/content/en/blog/optimize-cls/Optimize-Cumulative12.jpg
  src/site/content/en/blog/optimize-cls/Optimize-Cumulative3.png
  src/site/content/en/blog/optimize-cls/Optimize-Cumulative6.png
  src/site/content/en/blog/optimize-cls/Optimize-Cumulative9.png
  src/site/content/en/blog/optimize-cls/cls-graphic.svg
  src/site/content/en/blog/optimize-cls/hero.png
  src/site/content/en/blog/optimize-cls/index.md
  src/site/content/en/blog/optimize-cls/video-embed-iframe.jpg
  src/site/content/en/blog/optimize-cls/video-embeds-with-dimensions.jpg
  src/site/content/en/blog/optimize-cls/video-final-ads-no-dimensions.jpg
  src/site/content/en/blog/optimize-cls/video-image-dimensions-fixed.jpg
  src/site/content/en/blog/optimize-cls/video-image-dimensions.jpg
  src/site/content/en/blog/optimize-cls/video-related-articles-dynamic-content.jpg
  src/site/content/en/blog/optimize-cls/video-top-ad-after.jpg
Labels: cla: yes

#2701 Adds optimize LCP article
  src/site/content/en/blog/optimize-lcp/coverage-panel-css.png
  src/site/content/en/blog/optimize-lcp/coverage-panel-js.png
  src/site/content/en/blog/optimize-lcp/critical-css.png
  src/site/content/en/blog/optimize-lcp/hero.png
  src/site/content/en/blog/optimize-lcp/image-largest-element.png
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/en/blog/optimize-lcp/lcp-change-minify-css.png
  src/site/content/en/blog/optimize-lcp/lcp-changeify-css.png
  src/site/content/en/blog/optimize-lcp/lcp-chrome-devtools.png
  src/site/content/en/blog/optimize-lcp/lcp-code-splitting.png
  src/site/content/en/blog/optimize-lcp/lcp-compression.png
  src/site/content/en/blog/optimize-lcp/lcp-critical-css.png
  src/site/content/en/blog/optimize-lcp/lcp-defer-css.png
  src/site/content/en/blog/optimize-lcp/lcp-distributions.png
  src/site/content/en/blog/optimize-lcp/lcp-minify-js.png
  src/site/content/en/blog/optimize-lcp/lcp-prerendering.png
  src/site/content/en/blog/optimize-lcp/lcp-sw-caching.png
  src/site/content/en/blog/optimize-lcp/lcpify-js.png
  src/site/content/en/blog/optimize-lcp/lighthouse.jpg
Labels: cla: yes

#2767 load site code async, additional async firebase
  build.js
  src/lib/analytics.js
  src/lib/bootstrap.js
  src/lib/components/Search/index.js
  src/lib/entrypoint.js
  src/lib/fb.js
  src/lib/firestore-loader.js
  src/lib/loader.js
  src/lib/pageview.js
  src/lib/utils/firebase-loader.js
  src/lib/utils/sw-remove.js
  src/site/_includes/layout.njk
  test/integration/build-test.js
  test/unit/src/lib/index.js
  test/unit/src/lib/utils/firebase-loader.js
Labels: cla: yes

#2784 Adds optimize FID article
  src/site/content/en/blog/optimize-fid/coverage-panel-js.png
  src/site/content/en/blog/optimize-fid/hero.png
  src/site/content/en/blog/optimize-fid/index.md
  src/site/content/en/blog/optimize-fid/lighthouse.jpg
  src/site/content/en/blog/optimize-fid/long-task.png
  src/site/content/en/blog/optimize-fid/tbt-before-after-first-party.png
Labels: cla: yes

#2791 firebase loading fix
  src/lib/fb.js
  src/lib/utils/firebase-loader.js
  test/unit/src/lib/utils/firebase-loader.js
Labels: cla: yes

#2757 Add web audio profiling article
  src/site/_data/contributors.js
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/1-hello-audio-worklet.jpg
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/2e-box2d.jpg
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/3e-hello-audio-worklet.png
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/4e-pulse-audio.png
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/5e-render-budget.png
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/6e-garbage-collection.png
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/7e-devtools.jpg
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/8e-devtools.png
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/hero.jpg
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
Labels: cla: yes, media

#2794 Add analytics events to measure tool.
  src/lib/components/UrlChooser/index.js
Labels: cla: yes

#2793 Minor updates to "Optimize" articles
  src/site/content/en/blog/optimize-cls/cls-graphic.svg
  src/site/content/en/blog/optimize-cls/index.md
  src/site/content/en/blog/optimize-fid/hero.jpg
  src/site/content/en/blog/optimize-fid/hero.png
  src/site/content/en/blog/optimize-fid/index.md
  src/site/content/en/blog/optimize-lcp/coverage-panel-js.png
  src/site/content/en/blog/optimize-lcp/hero.jpg
  src/site/content/en/blog/optimize-lcp/hero.png
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/en/blog/optimize-lcp/lcp-changeify-css.png
  src/site/content/en/blog/optimize-lcp/lcp-code-splitting.png
  src/site/content/en/blog/optimize-lcp/lcp-distributions.png
  src/site/content/en/blog/optimize-lcp/lcp-minify-js.png
  src/site/content/en/blog/optimize-lcp/lcpify-js.png
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#2795 Fix broken link.
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#2797 Rename hero images to purge the imgix cache.
  src/site/content/en/blog/optimize-fid/hero2.jpg
  src/site/content/en/blog/optimize-fid/index.md
  src/site/content/en/blog/optimize-lcp/hero2.jpg
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes

#2800 fix(web-newsletter): ensure iframe has loaded before modifying it
  src/lib/components/Newsletter/index.js
Labels: cla: yes

#2801 Remove use of sizes in cards.
  src/site/_includes/components/BaseCard.js
Labels: cla: yes

#2771 Add guide for Lighthouse charset audit
  src/site/content/en/lighthouse-best-practices/charset/charset.png
  src/site/content/en/lighthouse-best-practices/charset/index.md
Labels: cla: yes

#2760 Added Google specifications for the SpecialAnnouncement
  src/site/content/en/blog/covid19/index.md
Labels: cla: yes

#2804 Typo fix.
  src/site/content/en/metrics/custom-metrics/index.md
Labels: cla: yes

#2802 remove lib/entrypoint.js, merge with lib/app.js
  build.js
  src/lib/app.js
  src/lib/components/Search/index.js
  src/lib/components/SelectGroup/index.js
  src/lib/components/Tabs/index.js
  src/lib/components/base.js
  src/lib/entrypoint.js
  src/lib/loader.js
  src/lib/pages/default.js
  src/lib/pages/measure.js
  src/lib/pages/newsletter.js
  src/lib/store.js
  src/lib/sw.js
  src/lib/urls-test.js
  test/integration/build-test.js
Labels: cla: yes

#2805 Add dimensions to masthead images.
  src/site/_includes/page.njk
Labels: cla: yes

#2808 [Optimize Largest Contentful Paint article] Fix link
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes, content update, performance

#2796 chore(redirect): send users from `/subscribe` to `/newsletter`, fixes #2724
  src/lib/components/Actions/index.js
  src/site/_data/site.js
  src/site/content/en/_redirects.yaml
Labels: cla: yes

#2811 Add guide for maskable icon audit
  src/site/content/en/lighthouse-pwa/maskable-icon-audit/index.md
  src/site/content/en/lighthouse-pwa/maskable-icon-audit/maskable-icon.jpg
Labels: cla: yes

#2812 Fix broken posts.
  src/site/_drafts/_template-self-assessment/index.md
  src/site/_drafts/digging-into-the-privacy-sandbox/index.md
  src/site/_drafts/intrinsic-layout-overview/index.md
  src/site/content/en/blog/cache-api-quick-guide/index.md
  src/site/content/en/blog/granular-chunking-nextjs/index.md
  src/site/content/en/blog/optimize-cls/index.md
  src/site/content/en/blog/optimize-fid/index.md
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
  src/site/content/en/blog/storage-for-the-web/index.md
  src/site/content/en/blog/test-post/index.md
  src/site/content/en/blog/why-coop-coep/index.md
  src/site/content/en/fast/extract-critical-css/index.md
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
  src/site/content/en/fast/how-to-report-metrics/index.md
  src/site/content/en/fast/third-party-javascript/index.md
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
  src/site/content/en/fast/value-of-speed/index.md
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
Labels: cla: yes

#2813 Fix broken svg path in promises post.
  src/site/content/en/blog/promises/index.md
Labels: cla: yes

#2759 New Post: Chromium Lands Flexbox Gap
  src/site/content/en/blog/flexbox-gap/devtools-gap.png
  src/site/content/en/blog/flexbox-gap/hero.jpg
  src/site/content/en/blog/flexbox-gap/index.md
Labels: Chrome 84, DO NOT MERGE, beta blog-related, cla: yes

#2820 Fix date.
  src/site/content/en/blog/flexbox-gap/index.md
Labels: cla: yes

#2463 Feat/scheduled posts
  package-lock.json
  package.json
  src/site/_collections/algolia-posts.js
  src/site/_collections/authors.js
  src/site/_collections/blog-posts-descending.js
  src/site/_collections/posts-with-lighthouse.js
  src/site/_collections/recent-blog-posts.js
  src/site/_collections/tags.js
  src/site/_drafts/_template-post/index.md
  src/site/_filters/live-posts.js
  src/site/_includes/components/BaseCard.js
  src/styles/components/_card.scss
  test/unit/src/site/_filters/capitalize.js
  test/unit/src/site/_filters/index.js
  test/unit/src/site/_filters/live-posts.js
  test/unit/src/site/index.js
Labels: cla: yes

#2818 redirect /foo => /foo/
  src/lib/sw.js
Labels: cla: yes

#2834 Set custom dimensions to strings.
  src/lib/analytics.js
  src/lib/bootstrap.js
Labels: cla: yes

#2847 Flexbox gap patch
  src/site/content/en/blog/flexbox-gap/index.md
Labels: cla: yes

#2819 [Content Index article] Fix links
  src/site/content/en/blog/content-indexing-api/index.md
Labels: cla: yes

#2781 covid banner
  src/site/content/en/blog/covid19/banner.jpg
  src/site/content/en/blog/covid19/hero.jpg
  src/site/content/en/index.njk
  src/styles/pages/_home.scss
Labels: cla: yes

#2832 Revisions to /read-files/
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/blog/read-files/squoosh.png
Labels: capabilities, cla: yes, content update, webfu-migration

#2829 Fixed the typo in the index.md for the blog native-file-system
  src/site/content/en/blog/native-file-system/index.md
Labels: capabilities, cla: yes

#2822 Add a post on why CommonJS modules are hard to optimize
  src/site/content/en/blog/commonjs-larger-bundles/hero.jpg
  src/site/content/en/blog/commonjs-larger-bundles/index.md
Labels: cla: yes

#2836 Remove unused Actions shortcode.
  src/site/_includes/components/Actions.js
Labels: cla: yes

#2821 Persistent storage article
  src/site/content/en/blog/persistent-storage/ff-persist-request.jpg
  src/site/content/en/blog/persistent-storage/hero.jpg
  src/site/content/en/blog/persistent-storage/index.md
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: cla: yes, content, pwa, webfu-migration

#2853 Additions related to dating and scheduling posts.
  src/site/content/en/handbook/markup-post-codelab/index.md
Labels: cla: yes

#2854 Fix a11y score by hiding decorative banner image.
  src/site/content/en/index.njk
Labels: cla: yes

#2844 Add variable fonts article (migrated from WebFu)
  src/images/authors/mustafa.jpg
  src/images/authors/mustafa@2x.jpg
  src/images/authors/mustafakurtuldu.jpg
  src/images/authors/mustafakurtuldu@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/variable-fonts/Amstelvar-Alpha-example.png
  src/site/content/en/blog/variable-fonts/Amstelvar-Ital-axis.png
  src/site/content/en/blog/variable-fonts/grass-mandy.png
  src/site/content/en/blog/variable-fonts/hero.jpg
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/variable-fonts/robot-specimen.png
  src/site/content/en/blog/variable-fonts/roboto-family.png
Labels: DO NOT MERGE, cla: yes, webfu-migration

#2835 fix(postTags): set title in default description to lower case, fixes #2785
  src/site/_data/postTags.js
Labels: cla: yes

#2861 refactor: move `site/en/images/rss-banner.png` to `src/images/rss-banner.png`
  src/images/rss-banner.png
Labels: cla: yes

#2856 Add author homepage and switch to flex layout
  src/site/_includes/components/AuthorInfo.js
  src/styles/components/_author.scss
Labels: cla: yes

#2842 Clarify what’s code and what’s not
  src/site/content/en/blog/flexbox-gap/index.md
Labels: cla: yes

#2859 Fix link to HTML5 Rocks
  src/site/content/en/lighthouse-performance/user-timings/index.md
Labels: cla: yes

#2852 Add feature support information.
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#2860 "How to define your install strategy" guide
  src/site/content/en/progressive-web-apps/define-install-strategy/a2hs-infobar.png
  src/site/content/en/progressive-web-apps/define-install-strategy/index.md
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
Labels: cla: yes

#2877 [Async Clipboard API article] Add prose why demo may fail
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
Labels: cla: yes

#2848 basic live page
  src/lib/loader.js
  src/lib/pages/live.js
  src/site/content/en/live/hero-bg.png
  src/site/content/en/live/hero.png
  src/site/content/en/live/index.njk
  src/site/content/en/live/live.mp4
  src/site/content/en/live/live.png
  src/styles/pages/_all.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#2851 fix(optimize-cls): update code so that do not trigger warning in Firefox
  src/site/content/en/blog/optimize-cls/index.md
Labels: cla: yes

#2875 Appcache removal blog post
  src/site/content/en/blog/appcache-removal/appcache-token.jpg
  src/site/content/en/blog/appcache-removal/hero.jpg
  src/site/content/en/blog/appcache-removal/index.md
Labels: cla: yes

#2878 webdev-live show sessions
  .eleventy.js
  .sasslintrc
  src/lib/components/Tabs/_styles.scss
  src/site/_collections/event-schedule.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
  src/styles/components/_author.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#2630 Add idle detection article
  src/site/content/en/blog/idle-detection/demo.png
  src/site/content/en/blog/idle-detection/hero.jpg
  src/site/content/en/blog/idle-detection/index.md
Labels: DO NOT MERGE, capabilities, cla: yes

#2880 web.dev/live local time component
  src/lib/components/EventTime/_styles.scss
  src/lib/components/EventTime/index.js
  src/lib/pages/live.js
  src/site/_collections/event-schedule.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#2897 remove post/author info requirement, uses titles for authors
  src/site/_data/contributors.js
  src/site/_filters/expand-contributors.js
  src/site/_includes/codelab.njk
  src/site/_includes/components/Author.js
  src/site/_includes/components/AuthorInfo.js
  src/site/_includes/components/EventTable.js
  src/site/_includes/partials/post.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#2664 Add synchronize to required checks event types.
  .github/workflows/required-checks-workflow.yml
Labels: cla: yes

#2912 Hide gap article without braking links.
  src/site/content/en/blog/flexbox-gap/index.md
Labels: cla: yes

#2883 Fix typo in handbook
  src/site/content/en/handbook/markup-post-codelab/index.md
Labels: cla: yes

#2905 web.dev/live content update
  src/images/authors/alexdanilo.jpg
  src/images/authors/aliceboxhall.jpg
  src/images/authors/demianrenzulli.jpg
  src/images/authors/demianrenzulli@2x.jpg
  src/images/authors/maudn.jpg
  src/images/authors/maudn@2x.jpg
  src/images/authors/morss.jpg
  src/images/authors/morss@2x.jpg
  src/images/authors/nattestad.jpg
  src/images/authors/nattestad@2x.jpg
  src/images/authors/samdutton.jpg
  src/images/authors/samdutton@2x.jpg
  src/images/authors/samthor.jpg
  src/images/authors/samthor@2x.jpg
  src/images/authors/sebabenz.jpg
  src/images/authors/sebabenz@2x.jpg
  src/images/authors/sfluin.jpg
  src/images/authors/sfluin@2x.jpg
  src/site/_data/contributors.js
  src/site/_data/event.js
Labels: cla: yes

#2898 web.dev/live PR fixes
  .eleventy.js
  src/lib/components/Tabs/index.js
  src/site/_collections/event-schedule.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#2906 [prefers-color-scheme article] Fix /color-scheme/ link
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#2917 [Idle Detection article] Explicitly call out top-level secure context requirement
  src/site/content/en/blog/idle-detection/index.md
Labels: capabilities, cla: yes, content update

#2890 new blog post: What's New in Lighthouse 6.0
  src/images/authors/cjamcl.jpg
  src/images/authors/cjamcl@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/lighthouse-whats-new-6.0/index.md
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-ci-1.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-ci-2.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-ci-3.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-logo.svg
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-motog4.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-new-metrics.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-scorecalc.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-sourcemaps-unusedjs.png
  src/site/content/en/blog/lighthouse-whats-new-6.0/lighthouse-weight-changes.png
Labels: cla: yes

#2919 [Idle Detection article] Update tag
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#2494 [Case Study] BettyCrocker wake lock case study
  src/site/_data/contributors.js
  src/site/content/en/blog/betty-crocker/doughy-fingers.jpg
  src/site/content/en/blog/betty-crocker/hero.jpg
  src/site/content/en/blog/betty-crocker/index.md
  src/site/content/en/blog/betty-crocker/www.bettycrocker.com.png
  src/site/content/en/blog/betty-crocker/www.pillsbury.com.png
  src/site/content/en/blog/betty-crocker/www.tablespoon.com.png
  src/site/content/en/images/authors/phillipkriegel.jpg
Labels: cla: yes

#2920 [Betty Crocker] Actually update widths
  src/images/authors/phillipkriegel.jpg
  src/site/content/en/blog/betty-crocker/index.md
Labels: cla: yes

#2914 multiple authors for web.dev/live
  src/images/authors/leszeks.jpg
  src/images/authors/leszeks@2x.jpg
  src/images/authors/nattestad.jpg
  src/images/authors/nattestad@2x.jpg
  src/lib/components/Subscribe/_styles.scss
  src/site/_data/contributors.js
  src/site/_data/event.js
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/components/BaseCard.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
  src/styles/components/_author.scss
  src/styles/components/_subscribe.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#2918 Add calendar link to /live page
  src/site/content/en/live/index.njk
Labels: cla: yes

#2879 Add app shortcuts blog post
  src/images/authors/jungkees.jpg
  src/images/authors/jungkees@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/app-shortcuts/app-shortcuts-devtools.png
  src/site/content/en/blog/app-shortcuts/app-shortcuts-menu-android.png
  src/site/content/en/blog/app-shortcuts/hero.jpg
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#2936 chore: update LHCI integration to use @lhci/cli@next
  .github/workflows/lighthouse-ci-workflow.yml
Labels: cla: yes

#2941 chore(ci): run lighthouse CI on master
  .github/workflows/lighthouse-ci-workflow.yml
Labels: cla: yes

#2799 feat(feedback): add custom element to take feedback on posts, fixes #2386
  src/images/icons/check_box.svg
  src/images/icons/check_box_outline_blank.svg
  src/lib/analytics.js
  src/lib/components/Feedback/_styles.scss
  src/lib/components/Feedback/index.js
  src/lib/components/Subscribe/index.js
  src/lib/pages/default.js
  src/site/_includes/partials/post.njk
  src/styles/components/_details.scss
  src/styles/generic/_input.scss
  src/styles/settings/_colors.scss
Labels: cla: yes

#2935 web.dev/live misc
  src/site/content/en/live/hero.png
  src/site/content/en/live/index.njk
Labels: cla: yes

#2933 subscribe copy just for live page
  src/site/_includes/partials/subscribe.njk
  src/site/content/en/live/index.njk
Labels: cla: yes

#2930 web.dev/live data update
  src/images/authors/crystallambert.jpg
  src/images/authors/crystallambert@2x.jpg
  src/images/authors/dalmaer.jpg
  src/images/authors/dalmaer@2x.jpg
  src/images/authors/nainar.jpg
  src/images/authors/nainar@2x.jpg
  src/images/authors/patrickkettner.jpg
  src/images/authors/patrickkettner@2x.jpg
  src/images/authors/syg.jpg
  src/images/authors/syg@2x.jpg
  src/site/_data/contributors.js
  src/site/_data/event.js
Labels: cla: yes

#2873 Blog rwd basics
  src/images/authors/rachelandrew.jpg
  src/images/authors/rachelandrew@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/responsive-web-design-basics/devtools-large-2.png
  src/site/content/en/blog/responsive-web-design-basics/devtools-large.png
  src/site/content/en/blog/responsive-web-design-basics/devtools-small-2.png
  src/site/content/en/blog/responsive-web-design-basics/devtools-small.png
  src/site/content/en/blog/responsive-web-design-basics/fixed-width-layout.jpg
  src/site/content/en/blog/responsive-web-design-basics/index.md
  src/site/content/en/blog/responsive-web-design-basics/readability-narrow.jpg
  src/site/content/en/blog/responsive-web-design-basics/readability-wide.jpg
  src/site/content/en/blog/responsive-web-design-basics/resize.mp4
  src/site/content/en/blog/responsive-web-design-basics/resize.webm
  src/site/content/en/blog/responsive-web-design-basics/weather-1-2x.png
  src/site/content/en/blog/responsive-web-design-basics/weather-2-2x.png
  src/site/content/en/blog/responsive-web-design-basics/weather-3-2x.png
  src/site/content/en/blog/responsive-web-design-basics/weather-4-l-2x.png
  src/site/content/en/blog/responsive-web-design-basics/weather-4-r-2x.png
  src/site/content/en/blog/responsive-web-design-basics/with-vp-meta.png
  src/site/content/en/blog/responsive-web-design-basics/without-vp-meta.png
Labels: cla: yes

#2923 [Shape Detection article] Make compatibility clearer
  src/site/content/en/blog/shape-detection/index.md
Labels: capabilities, cla: yes, content update

#2945 Calendar options
  src/images/icons/calendar.svg
  src/site/content/en/live/index.njk
  src/styles/components/_buttons.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#2946 add share area to web.dev/live
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#2950 Timezone hiccup
  src/site/_data/event.js
Labels: cla: yes

#2944 community guidelines page
  src/site/_includes/partials/footer.njk
  src/site/_includes/partials/text.njk
  src/site/_includes/text.njk
  src/site/content/en/community-guidelines/index.md
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#2951 Remove Francois talk
  src/site/_data/event.js
Labels: cla: yes

#2952 Update opener copy
  src/site/_data/event.js
Labels: cla: yes

#2953 Update Subscribe copy
  src/site/content/en/live/index.njk
Labels: cla: yes

#2955 Updates session titles copy
  src/site/_data/event.js
Labels: cla: yes

#2943 deals with fouc for web-tabs and web-event-time
  src/lib/components/BaseElement/index.js
  src/lib/components/EventTime/_styles.scss
  src/lib/components/Tabs/_styles.scss
  src/lib/components/Tabs/index.js
  src/site/_includes/components/EventTable.js
  src/styles/all.scss
  src/styles/overrides/_all.scss
  src/styles/overrides/_unresolved.scss
Labels: cla: yes

#2957 Session copy update
  src/site/_data/event.js
Labels: cla: yes

#2947 allow for ::before to push heading down
  src/styles/components/_topic.scss
Labels: cla: yes

#2958 Add Maud to privacy talk.
  src/site/_data/event.js
Labels: cla: yes

#2959 Make that time travel more obvious!
  src/site/content/en/live/index.njk
Labels: cla: yes

#2960 Get those LH scores up!
  src/lib/components/EventTime/_styles.scss
  src/site/_includes/partials/subscribe.njk
  src/site/content/en/live/index.njk
  src/styles/components/_subscribe.scss
Labels: cla: yes

#2966 Run lhci less often.
  .github/workflows/lighthouse-ci-workflow.yml
Labels: cla: yes

#2961 New Post: "More variable font options for the macOS `system-ui` font in Chromium 83"
  src/images/authors/drott.jpg
  src/images/authors/drott@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/hero.jpg
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/thumb.jpg
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/tight-chrome-spacing.jpg
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/weight-back.jpg
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/weight-loss.jpg
Labels: cla: yes

#2967 system-ui article thumbnail patch
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/thumb.jpg
Labels: cla: yes

#2964 Add the Core Web Vitals metrics thresholds post
  src/images/authors/bmcquade.jpg
  src/images/authors/bmcquade@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/defining-core-web-vitals-thresholds/hero.png
  src/site/content/en/blog/defining-core-web-vitals-thresholds/index.md
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/vitals/index.md
Labels: cla: yes

#2929 Add the Web Payments collection to /learn
  src/images/collections/payment.svg
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/payments/index.njk
  src/site/content/en/payments/payments.11tydata.js
Labels: cla: yes

#2970 Make kayce a codeowner for contributors and tags.
  .github/CODEOWNERS
Labels: cla: yes

#2974 Add missing body argument to banner.
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
Labels: cla: yes

#2981 use playsinline attribute on video elements
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
Labels: cla: yes

#2994 Split ShareAction into a separate component for reusability
  src/lib/components/Actions/index.js
  src/lib/components/ShareAction/index.js
  src/lib/pages/default.js
  src/lib/pages/live.js
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/subscribe-action.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/live/index.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
  src/styles/components/_actions.scss
Labels: cla: yes

#2998 Add "measure" app shortcut to web app manifest
  src/misc/manifest.webmanifest
Labels: cla: yes

#2996 ensure CSS padding at top for section
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#3001 Title change in /live
  src/site/_data/event.js
Labels: cla: yes

#3002 Move _redirects.yaml out of a language-specific folder
  gulpfile.js
  server.js
  src/site/content/_redirects.yaml
  test/integration/build-test.js
Labels: cla: yes

#2995 Add Live link in the header
  src/site/_includes/layout.njk
  src/site/content/en/live/index.njk
  src/styles/components/_header.scss
Labels: cla: yes

#3003 add lazy loading for avatars for perf
  src/site/_includes/components/AuthorsDate.js
Labels: cla: yes

#3004 Add message property to share button.
  src/lib/components/ShareAction/index.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#2963 Add homepage banners for live event.
  src/site/content/en/index.njk
  src/site/content/en/live/banner.png
Labels: cla: yes

#3006 Various small UI tweaks.
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/partials/subscribe.njk
  src/site/content/en/live/index.njk
  src/styles/overrides/_alignment.scss
  src/styles/overrides/_display.scss
  src/styles/overrides/_spacing.scss
Labels: cla: yes

#2977 Sw banner
  src/site/_data/site.js
  src/site/_includes/codelab.njk
  src/site/_includes/layout.njk
  src/site/content/en/index.njk
  src/site/content/en/live/index.njk
  src/site/content/sw-partial-layout.njk
  src/styles/components/_banner.scss
Labels: cla: yes

#3007 post patch: system ui
  src/site/_data/contributors.js
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
Labels: cla: yes

#3008 Nuke sw
  server.js
Labels: cla: yes

#3000 Add app shortcuts screenshot for Windows
  src/site/content/en/blog/app-shortcuts/app-shortcuts-menu-windows.png
  src/site/content/en/blog/app-shortcuts/index.md
Labels: capabilities, cla: yes, content update

#2999 Fix serlializing typo in NativeFS
  src/site/content/en/blog/native-file-system/index.md
Labels: capabilities, cla: yes, content update

#2993 disambiguation of Skia graphics lib and Skia font
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
Labels: cla: yes, content update, frontend

#2991 [Variable Fonts article] Add missing table wrapper
  src/site/content/en/blog/variable-fonts/index.md
Labels: cla: yes

#2988 Fix link to field metrics in FCP
  src/site/content/en/metrics/fcp/index.md
Labels: cla: yes, content update, performance

#2887 How PWAs Drive Business Success
  src/images/authors/sfourault.jpg
  src/images/authors/sfourault@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/progressive-web-apps/drive-business-success/img-1.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-10.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-11.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-12.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-13.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-14.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-2.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-3.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-4.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-5.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-6.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-7.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-8.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/img-9.jpg
  src/site/content/en/progressive-web-apps/drive-business-success/index.md
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
Labels: cla: yes, content, pwa

#3012 Make Safari happy again
  src/lib/sw.js
Labels: cla: yes

#3011 Analytics for PWA tweak
  src/site/content/en/progressive-web-apps/customize-install/index.md
Labels: cla: yes, content update, pwa

#3013 fix(analytics): prevent false triggering of `subscribe` event
  src/lib/components/Subscribe/index.js
  src/site/_includes/partials/subscribe-action.njk
Labels: cla: yes

#2938 Convert ResizeObserver article and update.
  src/site/content/en/blog/resize-observer/contentbox.png
  src/site/content/en/blog/resize-observer/hero.jpg
  src/site/content/en/blog/resize-observer/index.md
Labels: Chrome 84, beta blog-related, cla: yes, content update

#2940 Convert ReportingObserver article and update
  src/site/_data/contributors.js
  src/site/content/en/blog/reporting-observer/consolewarnings.png
  src/site/content/en/blog/reporting-observer/hero.jpg
  src/site/content/en/blog/reporting-observer/index.md
Labels: Chrome 84, beta blog-related, cla: yes, content update

#3015 Correct title
  src/site/content/en/blog/resize-observer/index.md
Labels: cla: yes

#3020 fix data issues and validate social link
  src/site/_collections/authors.js
  src/site/_data/contributors.js
  src/site/_data/event.js
  src/site/_filters/live-posts.js
  test/unit/src/site/_filters/live-posts.js
Labels: cla: yes

#2907 Add Web Payments collection to /learn
  src/images/authors/yaraki.jpg
  src/images/authors/yaraki@2x.jpg
  src/images/collections/payments.svg
  src/site/_data/contributors.js
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/payments/android-payment-app-developers-guide/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/index.njk
  src/site/content/en/payments/life-of-a-payment-transaction/123.svg
  src/site/content/en/payments/life-of-a-payment-transaction/4.svg
  src/site/content/en/payments/life-of-a-payment-transaction/5.svg
  src/site/content/en/payments/life-of-a-payment-transaction/6.svg
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
  src/site/content/en/payments/life-of-a-payment-transaction/payment-request-UI-mobile.png
  src/site/content/en/payments/life-of-a-payment-transaction/payment-request-UI.png
  src/site/content/en/payments/payments.11tydata.js
  src/site/content/en/payments/setting-up-a-payment-method/diagram_direct.png
  src/site/content/en/payments/setting-up-a-payment-method/diagram_indirect.png
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/payments/setting-up-a-payment-method/web-app-manifest.png
Labels: cla: yes

#3024 Change my name back
  src/site/_data/contributors.js
Labels: cla: yes

#3028 fix data web.dev/live
  src/site/_data/event.js
Labels: cla: yes

#3030 Add note that getInstalledRelatedApps is currently broken
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update, p0

#2670 Fix #2669
  locale-handler.js
Labels: cla: yes

#3032 Upgrade to eleventy v0.11
  package-lock.json
  package.json
Labels: cla: yes

#3039 Add guide on measuring Web Vitals
  src/site/content/en/blog/vitals-measurement-getting-started/hero.png
  src/site/content/en/blog/vitals-measurement-getting-started/index.md
Labels: cla: yes

#3034 Add a guide on field measurement best practices
  src/site/_includes/components/BaseCard.js
  src/site/content/_redirects.yaml
  src/site/content/en/blog/defining-core-web-vitals-thresholds/index.md
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
  src/site/content/en/blog/vitals-field-measurement-best-practices/lcp-histogram.png
  src/site/content/en/vitals/web-vitals-hero.png
Labels: cla: yes

#2962 Remove OT info from Content Index article.
  src/site/content/en/blog/content-indexing-api/index.md
Labels: Chrome 84, beta blog-related, cla: yes, content update

#2956 Web Animations API
  src/images/authors/kevinellis.jpg
  src/images/authors/kevinellis@2x.jpg
  src/site/_data/contributors.js
  src/site/_data/postTags.js
  src/site/content/en/blog/web-animations/hero.jpg
  src/site/content/en/blog/web-animations/index.md
  src/site/content/en/blog/web-animations/waapi-timeline.png
Labels: Chrome 84, beta blog-related, cla: yes, content

#3005 fix: remove bug notice from lighthouse offscreen images
  src/site/content/en/lighthouse-performance/offscreen-images/index.md
Labels: cla: yes, content update, lighthouse

#3027 [Wake Lock article] Add feature detection
  src/site/content/en/blog/wakelock/index.md
Labels: capabilities, cla: yes, content update

#3035 Update OT info in measureMemory() article.
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: capabilities, cla: yes, content update

#2727 add new metrics, show only if available
  src/lib/components/LighthouseScoresMetrics/_styles.scss
  src/lib/components/LighthouseScoresMetrics/index.js
  src/lib/lighthouse/index.js
  src/styles/settings/_colors.scss
Labels: cla: yes

#3048 Adds Core Web Vitals tools
  src/site/_data/contributors.js
  src/site/content/en/blog/vitals-tools/Vitals-Tools1.png
  src/site/content/en/blog/vitals-tools/Vitals-Tools10.png
  src/site/content/en/blog/vitals-tools/Vitals-Tools5.png
  src/site/content/en/blog/vitals-tools/Vitals-Tools7.png
  src/site/content/en/blog/vitals-tools/Vitals-Tools8.png
  src/site/content/en/blog/vitals-tools/crux-dashboard.png
  src/site/content/en/blog/vitals-tools/hero.png
  src/site/content/en/blog/vitals-tools/index.md
  src/site/content/en/blog/vitals-tools/lhci.png
  src/site/content/en/blog/vitals-tools/lighthouse.png
  src/site/content/en/blog/vitals-tools/pagespeed.png
  src/site/content/en/blog/vitals-tools/search-console.png
  src/site/content/en/blog/vitals-tools/thumbnail.png
  src/site/content/en/blog/vitals-tools/web-dev-measure.png
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/vitals/index.md
Labels: cla: no

#3057 Add additional note to vitals-tools post
  src/site/content/en/blog/vitals-tools/index.md
Labels: cla: yes
