Repository GoogleChrome/web.dev, pull requests merged in 2020-08, with the labels that each got.

#3623 Add survey banner.
  src/site/_data/site.js
Labels: cla: yes

#3620 feat(iframe): create iframe shortcode to enforce lazy loading of iframes, fixes #3154
  .eleventy.js
  src/site/_drafts/_template-post/index.md
  src/site/_includes/components/IFrame.js
  src/site/content/en/accessible/accessible-tap-targets/index.md
  src/site/content/en/accessible/content-reordering/index.md
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/keyboard-access/index.md
  src/site/content/en/accessible/style-focus/index.md
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/angular/route-level-code-splitting-in-angular/index.md
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/index.md
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/blog/appcache-removal/index.md
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
  src/site/content/en/blog/css-props-and-vals/index.md
  src/site/content/en/blog/drag-and-drop/index.md
  src/site/content/en/blog/fetch-upload-streaming/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/javascript-and-google-search-io-2019/index.md
  src/site/content/en/blog/keyboard-lock/index.md
  src/site/content/en/blog/module-workers/index.md
  src/site/content/en/blog/more-capable-form-controls/index.md
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
  src/site/content/en/blog/one-line-layouts/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/promises/index.md
  src/site/content/en/blog/proxx-announce/index.md
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
  src/site/content/en/blog/responsive-web-design-basics/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/speed-at-scale/index.md
  src/site/content/en/blog/stale-while-revalidate/index.md
  src/site/content/en/blog/test-post/index.md
  src/site/content/en/blog/user-agent-client-hints/index.md
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/web-animations/index.md
  src/site/content/en/blog/web-components-io-2019/index.md
  src/site/content/en/blog/websocketstream/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/fast/lazy-loading-images/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/lighthouse-accessibility/button-name/index.md
  src/site/content/en/lighthouse-accessibility/custom-control-roles/index.md
  src/site/content/en/lighthouse-accessibility/custom-controls-labels/index.md
  src/site/content/en/lighthouse-accessibility/focusable-controls/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/react/add-manifest-react/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/index.md
  src/site/content/en/react/get-started-optimize-react/index.md
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
  src/site/content/en/react/precache-with-workbox-react/index.md
  src/site/content/en/react/route-prefetching-in-nextjs/index.md
  src/site/content/en/react/virtualize-long-lists-react-window/index.md
  src/site/content/en/reliable/service-worker-caching-and-http-caching/index.md
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
Labels: cla: yes

#3622 Add aliases to /secure as per #3568
  src/site/_data/paths/secure.json
Labels: cla: yes, content update, privacy/security

#3624 feat(Glitch): add shortcode for glitch, fixes #3337
  .eleventy.js
  src/site/_drafts/_template-post/index.md
  src/site/_includes/components/Glitch.js
  src/site/_includes/components/IFrame.js
  src/site/content/en/accessible/accessible-tap-targets/index.md
  src/site/content/en/accessible/content-reordering/index.md
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/keyboard-access/index.md
  src/site/content/en/accessible/style-focus/index.md
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/blog/appcache-removal/index.md
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
  src/site/content/en/blog/css-props-and-vals/index.md
  src/site/content/en/blog/drag-and-drop/index.md
  src/site/content/en/blog/fetch-upload-streaming/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/keyboard-lock/index.md
  src/site/content/en/blog/module-workers/index.md
  src/site/content/en/blog/more-capable-form-controls/index.md
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
  src/site/content/en/blog/one-line-layouts/index.md
  src/site/content/en/blog/promises/index.md
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
  src/site/content/en/blog/responsive-web-design-basics/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/stale-while-revalidate/index.md
  src/site/content/en/blog/test-post/index.md
  src/site/content/en/blog/user-agent-client-hints/index.md
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/web-animations/index.md
  src/site/content/en/blog/web-components-io-2019/index.md
  src/site/content/en/blog/websocketstream/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/fast/lazy-loading-images/index.md
  src/site/content/en/fast/minify-css/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/lighthouse-accessibility/button-name/index.md
  src/site/content/en/lighthouse-accessibility/custom-control-roles/index.md
  src/site/content/en/lighthouse-accessibility/custom-controls-labels/index.md
  src/site/content/en/lighthouse-accessibility/focusable-controls/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/react/add-manifest-react/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/react/code-splitting-with-dynamic-imports-in-nextjs/index.md
  src/site/content/en/react/get-started-optimize-react/index.md
  src/site/content/en/react/performance-as-a-default-with-nextjs/index.md
  src/site/content/en/react/precache-with-workbox-react/index.md
  src/site/content/en/react/route-prefetching-in-nextjs/index.md
  src/site/content/en/react/virtualize-long-lists-react-window/index.md
  src/site/content/en/reliable/service-worker-caching-and-http-caching/index.md
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
Labels: cla: yes

#3629 [Badging API article] Add Push API link
  src/site/content/en/blog/badging-api/index.md
Labels: cla: yes

#3579 [Post] Content-Visibility
  src/images/authors/vladimirlevin.jpg
  src/images/authors/vladimirlevin@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/content-visibility/.index.md.swp
  src/site/content/en/blog/content-visibility/demo.jpg
  src/site/content/en/blog/content-visibility/hero.jpg
  src/site/content/en/blog/content-visibility/index.md
  src/site/content/en/blog/content-visibility/travelblog-chunked.jpg
  src/site/content/en/blog/content-visibility/travelblog.jpg
Labels: cla: yes

#3585 Fix the HID examples title
  src/site/content/en/blog/hid-examples/index.md
Labels: cla: yes

#3598 Updates to Privacy Sandbox article
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: DO NOT MERGE, cla: yes, content update, privacy/security

#3636 Add a hero image to the web-on-android blog post
  src/site/content/en/blog/web-on-android/hero.svg
  src/site/content/en/blog/web-on-android/index.md
Labels: cla: yes, content update

#3639 fix(Glitch): assign default `previewSize` value, fixes #3633
  src/site/_includes/components/Glitch.js
  src/site/content/en/accessible/accessible-tap-targets/index.md
  src/site/content/en/accessible/content-reordering/index.md
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/keyboard-access/index.md
  src/site/content/en/accessible/style-focus/index.md
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/blog/drag-and-drop/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/keyboard-lock/index.md
  src/site/content/en/blog/module-workers/index.md
  src/site/content/en/blog/one-line-layouts/index.md
  src/site/content/en/blog/promises/index.md
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
  src/site/content/en/blog/responsive-web-design-basics/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/stale-while-revalidate/index.md
  src/site/content/en/blog/user-agent-client-hints/index.md
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/web-animations/index.md
  src/site/content/en/blog/websocketstream/index.md
  src/site/content/en/fast/defer-non-critical-css/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/lighthouse-accessibility/custom-controls-labels/index.md
  src/site/content/en/lighthouse-accessibility/focusable-controls/index.md
  src/site/content/en/react/code-splitting-suspense/index.md
  src/site/content/en/react/precache-with-workbox-react/index.md
  src/site/content/en/react/virtualize-long-lists-react-window/index.md
  src/site/content/en/reliable/service-worker-caching-and-http-caching/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
Labels: cla: yes

#3640 Replace hero image on Badging API article
  src/site/content/en/blog/badging-api/hero-2.jpg
  src/site/content/en/blog/badging-api/hero.jpg
  src/site/content/en/blog/badging-api/index.md
Labels: capabilities, cla: yes

#3637 Update Web Share Target to recommend mime+extension
  src/site/content/en/blog/web-share-target/index.md
Labels: capabilities, cla: yes, content update

#3638 migrating resource prioritization
  src/site/_data/authorsData.json
  src/site/_data/paths/fast.json
  src/site/content/en/fast/prioritize-resources/index.md
  src/site/content/en/fast/prioritize-resources/res-prio-priorities.png
Labels: cla: yes, content update, performance

#3581 Corrections and updates to sign-in form post and codelab
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
  src/site/content/en/blog/sign-in-form-best-practices/chrome-signin-desktop.png
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes, content update, privacy/security

#3635 [Text Fragments article] Add `noopener` details
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3634 [Idle Detection article] Add DevTools support
  src/site/content/en/blog/idle-detection/devtools.mp4
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#3645 Correct cli command to start angular application
  src/site/content/en/angular/get-started-optimize-angular/index.md
Labels: cla: yes

#3627 Update instructions component to use Lighthouse.
  src/site/_includes/components/Instruction.js
  src/site/content/en/fast/apply-instant-loading-with-prpl/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
Labels: cla: yes

#3619 Updates to getInstalledRelatedApps
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update

#3628 Add manual build trigger and updated scheduled build cron to be hourly.
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#3647 Add deploy instructions to readme.
  README.md
Labels: cla: yes

#3653 Fix a11y screen reader issues.
  src/site/_includes/components/AuthorInfo.js
  src/site/_includes/components/Breadcrumbs.js
  src/styles/components/_breadcrumbs.scss
Labels: cla: yes

#3654 Clean up CLI output a bit.
  .eleventy.js
  package.json
  src/site/_filters/find-by-url.js
Labels: cla: yes

#3656 Add YAML front matter reference for Handbook
  src/site/_data/paths/handbook.json
  src/site/content/_redirects.yaml
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/tags/index.md
  src/site/content/en/handbook/yaml-front-matter/blog.jpg
  src/site/content/en/handbook/yaml-front-matter/codelab.jpg
  src/site/content/en/handbook/yaml-front-matter/codelabs.jpg
  src/site/content/en/handbook/yaml-front-matter/covid19.jpg
  src/site/content/en/handbook/yaml-front-matter/date-updated.jpg
  src/site/content/en/handbook/yaml-front-matter/description.jpg
  src/site/content/en/handbook/yaml-front-matter/draft.jpg
  src/site/content/en/handbook/yaml-front-matter/hero.jpg
  src/site/content/en/handbook/yaml-front-matter/index.md
  src/site/content/en/handbook/yaml-front-matter/post.jpg
  src/site/content/en/handbook/yaml-front-matter/related-post.jpg
  src/site/content/en/handbook/yaml-front-matter/subhead-blog.jpg
  src/site/content/en/handbook/yaml-front-matter/subhead.jpg
  src/site/content/en/handbook/yaml-front-matter/thumbnail.jpg
  src/site/content/en/handbook/yaml-front-matter/web-vitals.jpg
Labels: cla: yes, handbook, new content

#3658 Fixes broken redirects.
  src/site/content/_redirects.yaml
Labels: cla: yes

#3648 tweak to windows App id value
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update

#3661 [Text Fragments article] New fragmentDirective location
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3666 A tiny typo fix.
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#3613 [Shape Detection article] Move Barcode Detection up
  src/site/content/en/blog/shape-detection/index.md
Labels: capabilities, cla: yes, content update

#3614 [Screen Wake Lock article] Re-add OT link
  src/site/content/en/blog/wakelock/index.md
Labels: capabilities, cla: yes, content update

#3659 fix(authors): add fallback images in `prod` if authors don't have them, fixes #3318
  src/site/_collections/authors.js
Labels: cla: yes

#3660 feat(glitch): expose `allow` property
  src/site/_includes/components/Glitch.js
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#3681 Add authors to algolia posts
  src/site/_collections/algolia-posts.js
Labels: cla: yes

#3682 Don't fetch hero image if small screens
  src/site/_includes/components/Hero.js
Labels: cla: yes

#3679 Remove references to HTML imports
  src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
Labels: cla: yes

#3693 Add guide for Lighthouse's non-composited animations audit
  src/site/_data/paths/lighthouse-performance.json
  src/site/content/en/lighthouse-performance/non-composited-animations/index.md
  src/site/content/en/lighthouse-performance/non-composited-animations/rendering-pipeline.jpg
Labels: cla: yes

#3686 Feat/inclusive spellcheck lint
  .github/workflows/lint-and-test-workflow.yml
  package-lock.json
Labels: cla: yes

#3678 [Idle Detection article] Reflect permission changes
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#3664 New post: Debugging memory leaks in WebAssembly
  src/images/authors/rreverser.jpg
  src/images/authors/rreverser@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/tagsData.json
  src/site/content/en/blog/earth-webassembly/index.md
  src/site/content/en/blog/webassembly-memory-debugging/hero.jpg
  src/site/content/en/blog/webassembly-memory-debugging/index.md
  src/site/content/en/blog/webassembly-memory-debugging/leak1-dbg.png
  src/site/content/en/blog/webassembly-memory-debugging/leak1-nodbg.png
  src/site/content/en/blog/webassembly-memory-debugging/leak2.png
  src/site/content/en/blog/webassembly-memory-debugging/out-of-bounds.png
Labels: cla: yes

#3704 Don't index algolia if a build fails.
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#3706 Run linter and tests using pull_request_target
  .github/workflows/lint-and-test-workflow.yml
Labels: cla: yes

#3687 Remove unused percy paths. Make others more specific.
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#3708 Temporarliy remove path filters from workflow.
  .github/workflows/lint-and-test-workflow.yml
Labels: cla: yes

#3701 Add screenshot of a media notification in Windows 10
  src/site/content/en/blog/media-session/index.md
  src/site/content/en/blog/media-session/windows-10-media-notification.jpg
Labels: cla: yes

#3707 Add link to setting up a Thumbor configuration file.
  src/site/content/en/blog/install-thumbor/index.md
Labels: cla: yes

#3709 Rev dorny/path-filter.
  .github/workflows/lint-and-test-workflow.yml
Labels: cla: yes

#3712 Add missing filter steps back to workflow.
  .github/workflows/lint-and-test-workflow.yml
Labels: cla: yes

#3716 add puppeteer as explicit dep
  package-lock.json
  package.json
Labels: cla: yes

#3715 chokidar --silent fix
  package-lock.json
  package.json
Labels: cla: yes

#3671 Add a "translated" Github action
  .github/workflows/tranaslation-status-workflow.yml
  package.json
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/pl.11tydata.js
  tools/update-translated/index.js
Labels: cla: yes

#3718 Fix flaky test
  test/integration/src/site/_collections/index.js
  test/integration/src/site/_collections/recent-blog-posts/dev.js
Labels: cla: yes

#3690 Always link to /feature instead of /features
  src/site/content/en/blog/keyboard-lock/index.md
  src/site/content/en/blog/text-fragments/index.md
Labels: bug, cla: yes

#3719 [Progressively enhance your PWA article] Add YouTube video link
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
Labels: cla: yes

#3714 preload-optional-fonts: link up relevant crbug
  src/site/content/en/blog/preload-optional-fonts/index.md
Labels: cla: yes, content update, performance

#3692 Fix minimum bar for LCP
  src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md
Labels: cla: yes

#3731 Issue #3606 : <heading> should be <header> in Lighthouse docs
  src/site/content/en/lighthouse-accessibility/bypass/index.md
Labels: cla: yes

#3725 Fix Syntax and Reference errors in clipboard code snippet
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#3721 Add note about badging support in Edge
  src/site/content/en/blog/badging-api/index.md
Labels: capabilities, cla: yes, content update

#3717 [requestVideoFrameCallback article] Improve title
  src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
Labels: cla: yes

#3735 Take down survey banner.
  src/site/_data/site.js
Labels: cla: yes

#3737 Fix broken sitemap.
  src/site/content/sitemap.xml.njk
Labels: cla: yes

#3688 Add Serial API post
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/serial/aeroplane-factory.jpg
  src/site/content/en/blog/serial/hero.jpg
  src/site/content/en/blog/serial/index.md
  src/site/content/en/blog/serial/serial-port-prompt.jpg
  src/site/content/en/blog/serial/thumbnail.jpg
Labels: cla: yes

#3631 Add ARIA blog post
  src/images/authors/aaronlevanthal.jpg
  src/images/authors/aaronlevanthal@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/aria-poison-or-antidote/hero.jpg
  src/site/content/en/blog/aria-poison-or-antidote/index.md
Labels: cla: yes

#3670 Make translation link work with explicit language in path
  locale-handler.js
  src/site/_includes/components/Banner.js
  src/site/_includes/partials/translation-disclaimer.njk
Labels: cla: yes

#3739 [Origin Trials article] 2nd attempt: add downtime warning
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#3740 [Serial API article] Minor refinements
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#3738 refactor(collections): save processed 11ty collections, fixes #3532
  src/site/_collections/authors.js
  src/site/_collections/tags.js
Labels: cla: yes

#3743 Fix typo
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes

#3746 Add stale close comment.
  .github/stale.yml
Labels: cla: yes

#1983 feat(post): add table of contents to posts, fixes #1931
  .eleventy.js
  package-lock.json
  package.json
  src/lib/actions.js
  src/lib/components/TableOfContents/index.js
  src/lib/components/TableOfContentsButton/index.js
  src/lib/pages/default.js
  src/site/_filters/slugify.js
  src/site/_includes/partials/post.njk
  src/site/_transforms/responsive-images/index.js
  src/styles/components/_all.scss
  src/styles/components/_toc.scss
  src/styles/settings/_dimensions.scss
Labels: DO NOT MERGE, accepted, cla: yes

#3744 Updated Origin Trial date for HID examples post
  src/site/content/en/blog/hid-examples/index.md
Labels: cla: yes

#3615 Add Local Fonts API article
  src/site/content/en/blog/local-fonts/google-sans.png
  src/site/content/en/blog/local-fonts/hero.jpg
  src/site/content/en/blog/local-fonts/index.md
Labels: Chrome 86, beta blog-related, cla: yes, new content

#3755 Switch from Google Fonts to self hosted fonts.
  gulpfile.js
  src/fonts/google-sans/bold/cyrillic.woff2
  src/fonts/google-sans/bold/greek.woff2
  src/fonts/google-sans/bold/latin-ext.woff2
  src/fonts/google-sans/bold/latin.woff2
  src/fonts/google-sans/bold/vietnamese.woff2
  src/fonts/google-sans/regular/cyrillic.woff2
  src/fonts/google-sans/regular/greek.woff2
  src/fonts/google-sans/regular/latin-ext.woff2
  src/fonts/google-sans/regular/latin.woff2
  src/fonts/google-sans/regular/vietnamese.woff2
  src/fonts/material-icons/regular.woff2
  src/lib/sw.js
  src/site/_includes/layout.njk
  src/styles/all.scss
  src/styles/components/_asides.scss
  src/styles/fonts/_all.scss
  src/styles/fonts/_google-sans.scss
  src/styles/fonts/_material-icons.scss
  src/styles/settings/_type.scss
Labels: cla: yes

#3750 move large shared image so we don't cache it
  build-sw.js
  src/images/shared/rss-banner.png
  src/site/content/en/authors/feed.njk
  src/site/content/en/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#3749 trick eleventy into watching generated files
  .eleventy.js
  .eleventyignore
  .gitignore
  src/styles/.gitignore
Labels: cla: yes

#2798 Use the Content Indexing API
  src/lib/app.js
  src/lib/content-indexing.js
  src/lib/utils/router.js
  src/site/_includes/layout.njk
  src/site/_transforms/service-worker-partials/index.js
  test/integration/partials-test.js
  test/unit/src/site/_transforms/service-worker-partials/index.js
Labels: accepted, cla: no

#3747 [Update] WAAPI Post
  src/site/content/en/blog/web-animations/index.md
Labels: cla: yes, content update

#3752 Remove recent posts collection
  .eleventy.js
  src/site/_collections/hooks/recent-blog-posts.js
  src/site/content/en/index.11tydata.js
  src/site/content/en/index.njk
  src/site/content/pl/index.11tydata.js
  src/site/content/pl/index.njk
  test/integration/src/site/_collections/eleventy.js
  test/integration/src/site/_collections/fixtures/test-2.md
  test/integration/src/site/_collections/fixtures/test-3.md
  test/integration/src/site/_collections/fixtures/test-4.md
  test/integration/src/site/_collections/fixtures/test-5.md
  test/integration/src/site/_collections/index.js
  test/integration/src/site/_collections/recent-blog-posts/collection.md
  test/integration/src/site/_collections/recent-blog-posts/dev.js
  test/integration/src/site/_collections/recent-blog-posts/prod.js
  test/unit/src/site/_collections/hooks/index.js
  test/unit/src/site/_collections/hooks/recent-blog-posts.js
  test/unit/src/site/_collections/index.js
Labels: cla: yes

#3767 fix measuring what we delete
  tools/cleanup-versions/index.js
Labels: cla: yes

#3764 Add Idle Detection to the Fugu list
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#3763 Update Notification Triggers status
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#3748 remove partials from SW
  .eleventy.js
  build-sw.js
  build.js
  package.json
  src/build/hash.js
  src/lib/app.js
  src/lib/content-indexing.js
  src/lib/loader.js
  src/lib/sw.js
  src/site/_data/resource.js
  src/site/_includes/layout.njk
  src/site/_transforms/service-worker-partials/index.js
  src/site/content/sw-partial-layout.njk
  sw-manifest.js
  test/unit/src/site/_transforms/index.js
  test/unit/src/site/_transforms/service-worker-partials/index.js
Labels: cla: yes

#3772 [Local Font Access] Character case fixes
  src/site/content/en/blog/local-fonts/index.md
Labels: cla: yes

#3770 Update ARIA blog post
  src/site/_data/authorsData.json
  src/site/content/en/blog/aria-poison-or-antidote/index.md
Labels: cla: yes, content update

#3771 A proposal how to handle i18n messages
  src/site/_includes/homepage.njk
  src/site/content/en/index.md
  src/site/content/en/index.njk
  src/site/content/pl/index.md
Labels: cla: yes

#3753 feat(post): add table of contents to posts, fixes #1931
  .eleventy.js
  package-lock.json
  package.json
  src/lib/actions.js
  src/lib/components/TableOfContents/index.js
  src/lib/components/TableOfContentsButton/index.js
  src/lib/pages/default.js
  src/site/_filters/slugify.js
  src/site/_includes/partials/post.njk
  src/site/_transforms/responsive-images/index.js
  src/styles/components/_all.scss
  src/styles/components/_toc.scss
  src/styles/settings/_dimensions.scss
Labels: cla: yes

#3776 Fix broken integration tests.
  test/integration/build-test.js
  test/integration/index.js
  test/integration/partials-test.js
Labels: cla: yes

#3777 Move alex to a dedicated workflow.
  .github/workflows/alex-workflow.yml
  .github/workflows/lint-and-test-workflow.yml
Labels: cla: yes

#3779 Add missing alex steps.
  .github/workflows/alex-workflow.yml
Labels: cla: yes

#3781 Fix Aaron's author images
  src/images/authors/aaronleventhal.jpg
  src/images/authors/aaronleventhal@2x.jpg
Labels: cla: yes, content update, other

#3784 Fix a typo and add a bit about eTLD
  src/site/content/en/secure/same-site-same-origin/index.md
Labels: cla: yes

#3798 Fix copy button, hide ToC for now.
  src/lib/components/CopyCode/_styles.scss
  src/lib/components/CopyCode/index.js
  src/site/_includes/partials/post.njk
Labels: cla: yes

#3785 Add payments section to referrer best practices guide
  src/site/content/en/blog/referrer-best-practices/index.md
Labels: cla: yes

#3792 Track Table of Contents (ToC) opens and closes
  src/lib/components/TableOfContentsButton/index.js
Labels: cla: yes

#3789 Make note about where the feature was moved more specific.
  src/site/content/en/blog/text-fragments/index.md
Labels: Chrome 86, beta related, cla: yes

#3642 Add 2 new service worker guides for /payments
  src/site/_data/paths/payments.json
  src/site/content/en/payments/android-payment-apps-developers-guide/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/handling-optional-payment-information/diagram.png
  src/site/content/en/payments/handling-optional-payment-information/index.md
  src/site/content/en/payments/handling-optional-payment-information/paymentmethodchanged-ss.png
  src/site/content/en/payments/handling-optional-payment-information/paymentmethodchanged.png
  src/site/content/en/payments/handling-optional-payment-information/shippingaddresschanged-ss.png
  src/site/content/en/payments/handling-optional-payment-information/shippingaddresschanged.png
  src/site/content/en/payments/handling-optional-payment-information/shippingoptionchanged-ss.png
  src/site/content/en/payments/handling-optional-payment-information/shippingoptionchanged.png
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
  src/site/content/en/payments/orchestrating-payment-transactions/diagram.png
  src/site/content/en/payments/orchestrating-payment-transactions/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/payments/web-based-payment-apps-overview/index.md
Labels: cla: yes

#3799 New article about changing password URL
  src/site/_data/paths/secure.json
  src/site/content/en/blog/change-password-url/check-passwords.png
  src/site/content/en/blog/change-password-url/hero.jpg
  src/site/content/en/blog/change-password-url/index.md
Labels: cla: yes

#3804 test: Update `@percy/script` to avoid Percy SDK timeouts
  package-lock.json
  package.json
  tools/percy/.percy.conf.yml
  tools/percy/snapshots.js
Labels: cla: yes
