Repository GoogleChrome/web.dev, pull requests merged in 2020-07, with the labels that each got.

#3415 prefer playlist over videoId
  src/lib/components/EventCarousel/index.js
  src/site/_data/event.js
Labels: cla: yes

#3418 Update playlist id
  src/lib/components/EventCarousel/index.js
  src/site/_data/event.js
Labels: cla: yes

#3412 Update anchor on regional-events section
  src/site/content/en/live/index.njk
Labels: cla: yes

#3420 Force playlist to be clickable
  src/lib/components/EventCarousel/index.js
Labels: cla: yes

#3413 Update regional events for /live
  src/lib/components/EventMap/index.js
  src/site/_data/event.js
Labels: cla: yes

#3394 Add hero banner.
  src/site/content/en/index.njk
  src/styles/components/_all.scss
  src/styles/components/_hero-banner.scss
Labels: cla: yes

#3426 Inline style to fix hero banner.
  src/site/content/en/index.njk
  src/styles/components/_all.scss
  src/styles/components/_hero-banner.scss
Labels: cla: yes

#3424 Only update active tab if it's different.
  src/lib/components/EventSchedule/index.js
Labels: cla: yes

#3427 Post-day-3 updates
  src/site/_data/event.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#3430 Add first batch of QA
  src/site/_data/event.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#3433 Add country to eventMap
  src/lib/components/EventMap/_styles.scss
  src/lib/components/EventMap/index.js
  src/site/_data/event.js
Labels: cla: yes

#3434 Ship post event flag. Add note to Q&A
  src/site/_data/event.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#3442 Add the web.dev LIVE wrap-up post
  src/site/content/en/blog/live-wrap-up/audits.png
  src/site/content/en/blog/live-wrap-up/corewebvitals.png
  src/site/content/en/blog/live-wrap-up/emulator.png
  src/site/content/en/blog/live-wrap-up/hero.png
  src/site/content/en/blog/live-wrap-up/index.md
  src/site/content/en/blog/live-wrap-up/issues.png
  src/site/content/en/blog/live-wrap-up/thumbnail.png
  src/site/content/en/blog/live-wrap-up/toolingreport.png
Labels: cla: yes, new content, wdl

#3378 add cleanup versions script and workflow
  .github/workflows/cleanup-versions-workflow.yml
  package-lock.json
  package.json
  tools/cleanup-versions/index.js
Labels: cla: yes

#3395 use bootstrap.js/app.css again
  .eleventy.js
  build-sw.js
  build.js
  compile-css.js
  server.js
  src/build/hash.js
  src/build/resource-path.js
  src/lib/sw.js
  src/site/_filters/strip-query-params-dev.js
  src/site/_includes/layout.njk
  test/integration/build-test.js
Labels: cla: yes

#3443 post-event cleanup
  src/lib/components/EventScheduleModal/index.js
  src/lib/components/EventStore/index.js
  src/site/_data/event.js
  src/site/_data/site.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#3444 fix wdl copy
  src/site/content/en/live/index.njk
Labels: cla: yes

#3263 [Post] Ten modern layouts in one line of CSS
  src/site/content/en/blog/one-line-layouts/hero.png
  src/site/content/en/blog/one-line-layouts/index.md
Labels: cla: yes, wdl

#3282 Pixel-perfect rendering with devicePixelContentBox
  src/site/content/en/blog/device-pixel-content-box/dprs.png
  src/site/content/en/blog/device-pixel-content-box/fractional-pixels.png
  src/site/content/en/blog/device-pixel-content-box/index.md
  src/site/content/en/blog/device-pixel-content-box/pixels.jpg
  src/site/content/en/blog/device-pixel-content-box/side-by-side.png
Labels: cla: yes, frontend, new content

#3451 fix cleanup paths
  .github/workflows/cleanup-versions-workflow.yml
Labels: cla: yes

#3388 Update getInstalledRelatedApps() for Windows support.
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: Chrome 85, beta blog-related, cla: yes, content update

#3454 Revert "Update getInstalledRelatedApps() for Windows support."
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#3417 Add unit for Max-Age duration
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes

#3429 [Wake Lock article] Remove full screen references
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#3432 update link
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#3269 Migration of image optimization content
  src/site/_data/paths/fast.js
  src/site/content/en/fast/choose-the-right-image-format/css-vs-device-pixels.png
  src/site/content/en/fast/choose-the-right-image-format/index.md
  src/site/content/en/fast/choose-the-right-image-format/vector-raster-zoom.png
  src/site/content/en/fast/compress-images/artifacts.png
  src/site/content/en/fast/compress-images/index.md
Labels: cla: yes

#3458 [Bugfix] Fixes link on one line layouts article
  src/site/content/en/blog/one-line-layouts/index.md
Labels: cla: yes

#3453 update: tooling.report link
  src/site/content/en/blog/live-wrap-up/index.md
Labels: cla: yes

#3266 Add guide for "Remove unused JavaScript" audit
  src/site/content/en/lighthouse-performance/unused-javascript/index.md
  src/site/content/en/lighthouse-performance/unused-javascript/remove-unused-javascript.jpg
Labels: cla: yes, lighthouse, new content

#3461 Add playsinline attribute to videos and fix indentation
  src/site/content/en/blog/one-line-layouts/index.md
Labels: cla: yes, content update, frontend

#3261 Remove stripLanguage filter
  .eleventy.js
  src/site/_collections/algolia-posts.js
  src/site/_collections/authors.js
  src/site/_collections/tags.js
  src/site/_filters/posts-lighthouse-json.js
  src/site/_filters/strip-language.js
  src/site/_includes/components/BaseCard.js
  src/site/_includes/components/CodelabsCallout.js
  src/site/_includes/components/Meta.js
  src/site/_includes/handbook.njk
  src/site/_includes/layout.njk
  src/site/_includes/partials/item.njk
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/feed.njk
  src/site/content/en/newsletter/archive/2020/03/index.njk
  src/site/content/en/tags/feed.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
Labels: cla: yes

#2857 Adding origin trial info & prettier reformat
  src/site/content/en/blog/hands-on-portals/index.md
Labels: Chrome 85, beta blog-related, cla: yes, content update

#3484 use npm run for cleanup
  .github/workflows/cleanup-versions-workflow.yml
  package.json
Labels: cla: yes

#3467 Update origin trial end dates.
  src/site/content/en/blog/disallow-synchronous-xhr/index.md
Labels: cla: yes

#3481 Updates to native lazy-loading guide
  src/site/content/en/fast/native-lazy-loading/index.md
Labels: cla: yes

#3490 Provide a date for the end of the origin trial.
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#3489 Fixing origin trial links
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#3485 fix(feedback): move feedback widget after codelab callout, fixes #3189
  src/site/_includes/partials/post.njk
Labels: cla: yes

#3450 Add author slugs for mattreynolds
  src/images/authors/mattreynolds.jpg
  src/images/authors/mattreynolds@2x.jpg
Labels: cla: yes

#3449 Add mattreynolds to contributors
  src/site/_data/contributors.js
Labels: cla: yes

#3494 Add missing obvious steps to cleanup workflow
  .github/workflows/cleanup-versions-workflow.yml
  .github/workflows/snapshot-firestore-workflow.yml
Labels: cla: yes

#3354 fix(sitemap): use `canonicalUrl` for pages with a `url`, fixes #3352
  src/site/content/sitemap.xml.njk
Labels: cla: yes

#3495 Add content review guidelines to Handbook
  src/site/_data/paths/handbook.js
  src/site/content/en/handbook/reviews/index.md
Labels: cla: yes, new content

#3476 Cleanup of /en/ directory
  src/site/_includes/handbook.njk
  src/site/content/_redirects.yaml
  src/site/content/algolia.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/index.njk
  src/site/content/en/newsletter/index.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
Labels: cla: yes

#3330 explode on missing author posts/social
  src/site/_collections/authors.js
  src/site/_data/authorsData.json
Labels: cla: yes

#3497 refactor(authors): turn `_data/contributors.js` to `_data/authorsData.js` (#3339)
  .eleventy.js
  src/images/authors/ahmadawais@2x.jpg
  src/images/authors/aleshalamov@2x.jpg
  src/images/authors/lchansson.jpg
  src/images/authors/lchansson@2x.jpg
  src/site/_collections/authors.js
  src/site/_collections/hooks/utils.js
  src/site/_data/authorsData.json
  src/site/_data/contributors.js
  src/site/_data/paths/handbook.js
  src/site/_filters/expand-authors.js
  src/site/_filters/expand-contributors.js
  src/site/_includes/codelab.njk
  src/site/_includes/components/Author.js
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/partials/post.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/feed.njk
  src/site/content/en/handbook/author-profile/index.md
  src/site/content/en/handbook/author-profile/lockup.png
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#3480 Update PWA progressive enhancement article
  src/site/_data/paths/progressive-web-apps.js
  src/site/content/en/blog/progressively-enhance-your-pwa/hero.jpg
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
  src/site/content/en/blog/progressively-enhance-your-pwa/thumbnail.jpg
Labels: cla: yes

#3398 Migrating optimize webfonts article
  src/site/_data/paths/fast.js
  src/site/content/en/fast/optimize-webfont-loading/font-crp.png
  src/site/content/en/fast/optimize-webfont-loading/index.md
  src/site/content/en/fast/preload-critical-assets/index.md
  src/site/content/en/fast/reduce-webfont-size/font-synthesis.png
  src/site/content/en/fast/reduce-webfont-size/font-weights.png
  src/site/content/en/fast/reduce-webfont-size/glyphs.png
  src/site/content/en/fast/reduce-webfont-size/index.md
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes

#3471 Handling navigation requests for /reliable
  src/site/_data/paths/reliable.js
  src/site/content/en/reliable/handling-navigation-requests/hero.jpg
  src/site/content/en/reliable/handling-navigation-requests/index.md
Labels: cla: yes

#3493 Add CrUX API to CrUX guide index
  src/site/content/en/fast/chrome-ux-report/index.md
Labels: cla: yes

#3499 chore(codeowners): change `contributors.js` to `authorsData.json` and add @jpmedley as codeowner
  .github/CODEOWNERS
Labels: cla: yes

#3505 chore: add more codeowners
  .github/CODEOWNERS
Labels: cla: yes

#3501 Small but important update to a payment article
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
Labels: cla: yes

#3508 Add content PR guidelines
  src/site/_data/paths/handbook.js
  src/site/content/en/handbook/pull-requests/index.md
Labels: cla: yes, handbook, new content

#3509 chore: convert learning paths to json. update codeowners.
  .github/CODEOWNERS
  src/site/_data/paths/accessible.js
  src/site/_data/paths/accessible.json
  src/site/_data/paths/angular.js
  src/site/_data/paths/angular.json
  src/site/_data/paths/discoverable.js
  src/site/_data/paths/discoverable.json
  src/site/_data/paths/fast.js
  src/site/_data/paths/fast.json
  src/site/_data/paths/handbook.js
  src/site/_data/paths/handbook.json
  src/site/_data/paths/index.js
  src/site/_data/paths/lighthouse-accessibility.js
  src/site/_data/paths/lighthouse-accessibility.json
  src/site/_data/paths/lighthouse-best-practices.js
  src/site/_data/paths/lighthouse-best-practices.json
  src/site/_data/paths/lighthouse-performance.js
  src/site/_data/paths/lighthouse-performance.json
  src/site/_data/paths/lighthouse-pwa.js
  src/site/_data/paths/lighthouse-pwa.json
  src/site/_data/paths/lighthouse-seo.js
  src/site/_data/paths/lighthouse-seo.json
  src/site/_data/paths/metrics.js
  src/site/_data/paths/metrics.json
  src/site/_data/paths/notifications.js
  src/site/_data/paths/notifications.json
  src/site/_data/paths/payments.js
  src/site/_data/paths/payments.json
  src/site/_data/paths/progressive-web-apps.js
  src/site/_data/paths/progressive-web-apps.json
  src/site/_data/paths/react.js
  src/site/_data/paths/react.json
  src/site/_data/paths/reliable.js
  src/site/_data/paths/reliable.json
  src/site/_data/paths/secure.js
  src/site/_data/paths/secure.json
  src/site/_data/paths/vitals.js
  src/site/_data/paths/vitals.json
  src/site/content/en/handbook/sandbox/path-card/path-card.11tydata.js
Labels: cla: yes

#3507 Make the title consistent with our handbook.
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#3510 Fix typo
  src/site/content/en/blog/preload-responsive-images/index.md
Labels: cla: yes

#3503 Add language routing to internal navigation in SPA
  locale-handler.js
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/LanguageSelect/index.js
  src/lib/loader.js
  src/lib/store.js
  src/lib/urls.js
  src/lib/utils/language.js
  src/lib/utils/router.js
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/content/en/en.11tydata.js
  src/site/content/pl/pl.11tydata.js
Labels: cla: yes

#3474 Nested lists look ugly
  src/styles/generic/_lists.scss
Labels: cla: yes

#3498 fix(lighthouse): correct use responsive images threshold
  src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
Labels: cla: yes, content update, lighthouse, performance

#3517 Removes space in authorData.json homepage URLs
  src/site/_data/authorsData.json
Labels: cla: yes

#3516 Fixes #1651. Add missing syntax.
  src/site/content/en/react/accessibility-auditing-react/index.md
Labels: cla: yes

#3502 Add PageSpeed Insights
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes, content update, handbook

#3520 Revert "Add language routing to internal navigation in SPA (#3503)"
  locale-handler.js
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/LanguageSelect/index.js
  src/lib/loader.js
  src/lib/store.js
  src/lib/urls.js
  src/lib/utils/language.js
  src/lib/utils/router.js
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/content/en/en.11tydata.js
  src/site/content/pl/pl.11tydata.js
Labels: cla: yes

#3513 Updates to native lazy-load
  src/site/content/en/fast/native-lazy-loading/better-thresholds.png
  src/site/content/en/fast/native-lazy-loading/index.md
  src/site/content/en/fast/native-lazy-loading/lazysizes-threshold.png
Labels: cla: yes

#3526 Add service worker and HTTP caching pros and cons guide
  src/images/authors/jonchen.jpg
  src/images/authors/jonchen@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/reliable.json
  src/site/content/en/reliable/service-worker-caching-and-http-caching/caching-flow.png
  src/site/content/en/reliable/service-worker-caching-and-http-caching/index.md
  src/site/content/en/reliable/service-worker-caching-and-http-caching/workbox.png
Labels: cla: yes

#3527 Add site speed and business metrics guide
  src/images/authors/bpj.jpg
  src/images/authors/bpj@2x.jpg
  src/images/authors/msdikla.jpg
  src/images/authors/msdikla@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/fast.json
  src/site/content/en/blog/site-speed-and-business-metrics/index.md
  src/site/content/en/blog/site-speed-and-business-metrics/test-client-side.jpg
  src/site/content/en/blog/site-speed-and-business-metrics/test-server-side.jpg
Labels: cla: yes

#3514 Filter blog collection by language
  src/site/_collections/hooks/blog.js
  src/site/_filters/filter-by-lang.js
  src/site/content/en/blog/index.11tydata.js
  src/site/content/en/en.11tydata.js
  src/site/content/en/lang.js
Labels: cla: yes

#3521 Fix typo in "Cache-Control"
  src/site/content/en/reliable/handling-navigation-requests/index.md
Labels: cla: yes

#3524 chore: Enable scheduled builds
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#3528 Filter by lang tags and authors collections
  src/site/_collections/authors.js
  src/site/_collections/hooks/authors.js
  src/site/_collections/hooks/newsletter.js
  src/site/_collections/hooks/tags.js
  src/site/_collections/hooks/utils.js
  src/site/_collections/tags.js
  src/site/content/en/authors/individual.11tydata.js
  src/site/content/en/newsletter/index.11tydata.js
  src/site/content/en/tags/individual.11tydata.js
Labels: cla: yes

#3535 Fix searchbox
  src/lib/components/Search/_styles.scss
  src/lib/components/Search/index.js
  src/lib/components/UrlChooser/_styles.scss
  src/styles/generic/_all.scss
  src/styles/generic/_buttons.scss
Labels: cla: yes

#3408 Add Windows stable support for app shortcuts
  src/site/content/en/blog/app-shortcuts/index.md
Labels: Chrome 85, beta blog-related, capabilities, cla: yes, content update

#3522 Restore reverted #3503 and fix #3519 (lang bug)
  locale-handler.js
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/LanguageSelect/index.js
  src/lib/loader.js
  src/lib/store.js
  src/lib/urls.js
  src/lib/utils/language.js
  src/lib/utils/router.js
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/content/pl/pl.11tydata.js
Labels: cla: yes

#3486 Allow to build eleventy for only 1 target language at a time
  .eleventy.js
  src/site/_data/site.js
  src/site/_includes/components/Assessment.js
Labels: cla: yes

#3538 Clarify CWV assessment compliance
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
  src/site/content/en/vitals/index.md
Labels: cla: yes, content update

#3534 Disable updated hook.
  .huskyrc
  package.json
  tools/update-updated/index.js
Labels: cla: yes

#3472 New articles for /payments section
  src/images/authors/sahel.jpg
  src/images/authors/sahel@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/payments.json
  src/site/_includes/content/payments/browser-compatibility.njk
  src/site/content/_redirects.yaml
  src/site/content/en/payments/android-payment-apps-delegation/index.md
  src/site/content/en/payments/android-payment-apps-developers-guide/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/debug-payment-handler.png
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/payments/web-based-payment-apps-overview/index.md
Labels: cla: yes, content

#3448 [Post] @property
  src/site/content/en/blog/at-property/hero.jpg
  src/site/content/en/blog/at-property/index.md
Labels: Chrome 85, beta blog-related, cla: yes

#3539 Add hero image to 'Relating site speed and business metrics' article
  src/site/content/en/blog/site-speed-and-business-metrics/hero.jpeg
  src/site/content/en/blog/site-speed-and-business-metrics/index.md
Labels: cla: yes

#3479 Update getInstalledRelatedApps() for Windows support
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: Chrome 85, beta blog-related, cla: yes

#3545 Extend origin trial.
  src/site/content/en/blog/text-fragments/index.md
Labels: Chrome 85, cla: yes

#3399 Add rVFC article
  src/site/content/en/blog/requestvideoframecallback-rvfc/hero.jpg
  src/site/content/en/blog/requestvideoframecallback-rvfc/index.md
Labels: cla: yes

#3541 refactor(tags): turn tags data into a json file
  .github/CODEOWNERS
  .github/workflows/lighthouse-ci-workflow.yml
  .github/workflows/percy-workflow.yml
  src/site/_collections/tags.js
  src/site/_data/postTags.js
  src/site/_data/tagsData.json
  src/site/_filters/find-tags.js
  src/site/_includes/components/BaseCard.js
Labels: cla: yes

#3547 Use GIFs as temporary workaround for Safari issue
  src/site/content/en/blog/at-property/index.md
Labels: cla: yes, content update

#3533 Human Interface Device
  src/site/_data/authorsData.json
  src/site/content/en/blog/hid-examples/game-controller.jpg
  src/site/content/en/blog/hid-examples/index.md
Labels: Chrome 85, beta blog-related, cla: yes

#3525 Add upload streaming article.
  src/site/content/en/blog/fetch-upload-streaming/hero.jpg
  src/site/content/en/blog/fetch-upload-streaming/index.md
Labels: Chrome 85, beta blog-related, cla: yes, content review

#3549 chore(typo): megenta -> magenta
  src/site/content/en/blog/at-property/index.md
Labels: cla: yes

#3540 feat(q-and-a): add questions from day 2, fixes #3511
  src/lib/components/EventQandA/index.js
  src/site/_data/event.js
Labels: cla: yes

#3550 Remove required check action.
  .github/workflows/required-checks-workflow.yml
Labels: cla: yes

#3555 Fix @property post typos
  src/site/content/en/blog/at-property/index.md
Labels: cla: yes, content update

#3559 Add tags guide to handbook
  src/site/_data/paths/handbook.json
  src/site/content/en/handbook/tags/blog.jpg
  src/site/content/en/handbook/tags/covid19.jpg
  src/site/content/en/handbook/tags/index.md
  src/site/content/en/handbook/tags/web-vitals.jpg
Labels: cla: yes, handbook, new content

#3536 Adds iframe lazy-loading
  src/site/content/en/blog/iframe-lazy-loading/fblike.png
  src/site/content/en/blog/iframe-lazy-loading/hero.png
  src/site/content/en/blog/iframe-lazy-loading/iframe-chromecom.png
  src/site/content/en/blog/iframe-lazy-loading/iframe-lazyloading.png
  src/site/content/en/blog/iframe-lazy-loading/index.md
Labels: cla: no

#3556 merging in webfundamentals content
  src/site/content/en/fast/why-speed-matters/index.md
  src/site/content/en/fast/why-speed-matters/speed-comparison.png
Labels: cla: yes

#3515 Create separate performance section on /learn, update captions
  src/site/_data/paths/fast.json
  src/site/_data/paths/metrics.json
  src/site/_data/paths/vitals.json
  src/site/content/en/learn/index.njk
  src/site/content/en/learn/learn.11tydata.js
Labels: cla: yes

#3553 [Text Fragments article] Add opt-out steps
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3552 [App-like PWAs article] Add Vibration API idea
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes

#3563 [Notification Triggers article] Add "on-hold" info
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#3371 Add browser-nativefs article
  src/site/content/en/blog/browser-nativefs/caniuse.png
  src/site/content/en/blog/browser-nativefs/chrome-modify.png
  src/site/content/en/blog/browser-nativefs/chrome-oversave.png
  src/site/content/en/blog/browser-nativefs/chrome-save-as.png
  src/site/content/en/blog/browser-nativefs/hero.jpg
  src/site/content/en/blog/browser-nativefs/index.md
  src/site/content/en/blog/browser-nativefs/iphone-original.png
  src/site/content/en/blog/browser-nativefs/save-save-as.png
  src/site/content/en/blog/browser-nativefs/save.png
Labels: cla: yes

#3548 Lighthouse CI article
  src/site/_data/paths/fast.json
  src/site/content/en/blog/lighthouse-ci/github-action1.png
  src/site/content/en/blog/lighthouse-ci/github-action2.png
  src/site/content/en/blog/lighthouse-ci/github-action3.png
  src/site/content/en/blog/lighthouse-ci/github-action4.png
  src/site/content/en/blog/lighthouse-ci/hero.png
  src/site/content/en/blog/lighthouse-ci/index.md
  src/site/content/en/blog/lighthouse-ci/lhci-warning.png
  src/site/content/en/blog/lighthouse-ci/server1.png
  src/site/content/en/blog/lighthouse-ci/server2.png
Labels: cla: yes

#3582 [Text Fragments article] Update polyfill link
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3583 Adds PWA content to PWA landing page
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/blog/badging-api/index.md
  src/site/content/en/blog/multi-origin-pwas/index.md
  src/site/content/en/blog/web-share-target/index.md
Labels: cla: yes

#3586 Disable flaky test.
  test/unit/src/lib/components/LivestreamContainer/index.js
Labels: cla: yes

#3557 Add Keyboard Lock article
  src/site/content/en/blog/keyboard-lock/chrome-remote-desktop.png
  src/site/content/en/blog/keyboard-lock/hero.jpg
  src/site/content/en/blog/keyboard-lock/index.md
Labels: cla: yes

#3591 Update the location of the redirects file.
  src/site/content/en/handbook/redirects/index.md
Labels: cla: yes

#3592 [Keyboard Lock article] Fix issues
  src/site/content/en/blog/keyboard-lock/index.md
Labels: cla: yes

#3564 Add part 1 of Bulletin series
  src/images/authors/douglasparker.jpg
  src/images/authors/douglasparker@2x.jpg
  src/images/authors/joelriley.jpg
  src/images/authors/joelriley@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/building-a-pwa-at-google-part-1/hero.jpg
  src/site/content/en/blog/building-a-pwa-at-google-part-1/index.md
Labels: cla: yes

#3588 Migrate Drag and Drop guide
  src/site/content/en/blog/drag-and-drop/index.md
Labels: cla: yes

#3596 New article: "Referer and Referrer-Policy best practices"
  src/images/authors/maudnalpas.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/secure.json
  src/site/content/en/blog/referrer-best-practices/hero.jpg
  src/site/content/en/blog/referrer-best-practices/index.md
  src/site/content/en/blog/referrer-best-practices/referrer-basics.jpg
  src/site/content/en/blog/referrer-best-practices/referrer-data.jpg
  src/site/content/en/blog/referrer-best-practices/referrer-devtools.jpg
  src/site/content/en/blog/referrer-best-practices/referrer-policies.jpg
  src/site/content/en/blog/referrer-best-practices/referrer-urls.jpg
Labels: cla: yes

#3603 Make content team the owners for author images.
  .github/CODEOWNERS
Labels: cla: yes

#3597 [Building PWAs at Google] Direct source link for Safari policy
  src/site/content/en/blog/building-a-pwa-at-google-part-1/index.md
Labels: cla: yes

#3600 [docs] fix typo
  src/site/content/en/blog/iframe-lazy-loading/index.md
Labels: cla: yes

#3607 [Referrer best practices article] Inclusive language fix
  src/site/content/en/blog/referrer-best-practices/index.md
Labels: cla: yes

#3608 Fix code indentation for Trust Token examples
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#3610 [Text Fragments URL] Add bug link
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3611 [Idle Detection article] Fix OT end date
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#3612 [Notification Triggers article] Re-add OT link
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#3616 Small fix: referrer best practices article
  src/site/content/en/blog/referrer-best-practices/index.md
Labels: cla: yes, content update

#3599 Adds the Web on Android blogpost
  src/site/content/en/blog/web-on-android/index.md
Labels: cla: yes, new content

#3617 Updates to App Badging API
  src/site/content/en/blog/badging-api/index.md
Labels: capabilities, cla: yes, content update

#3618 Updates to Contact Picker API article
  src/site/content/en/blog/contact-picker/index.md
Labels: capabilities, cla: yes, content update
