Repository GoogleChrome/web.dev, pull requests merged in 2020-09, with the labels that each got.

#3811 Fixes #3800. Label should not overlap glitch embeds.
  src/styles/components/_label.scss
Labels: cla: yes

#3797 Update with COOP Reporting API
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes, content update, privacy/security

#3813 feat(web-feedback): check if form was likely filled by bot, fixes #3812
  src/lib/components/Feedback/index.js
Labels: cla: yes

#3745 Update pl directory with current en content
  src/lib/utils/language.js
  src/site/content/pl/accessible/accessible.11tydata.js
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/self-assessment.assess.yml
  src/site/content/pl/accessible/index.njk
  src/site/content/pl/feed.njk
  src/site/content/pl/lang.js
  src/site/content/pl/offline.njk
  src/site/content/pl/pl.11tydata.js
Labels: cla: yes

#3827 Fix URL link
  src/site/content/en/accessible/style-focus/index.md
Labels: cla: yes

#3826 Fix broken Glitch and nextjs.org links
  src/site/content/en/react/route-prefetching-in-nextjs/index.md
Labels: cla: yes

#3215 Add media learning area.
  src/images/collections/media.svg
  src/site/_data/paths/accessible.json
  src/site/_data/paths/index.js
  src/site/_data/paths/media.json
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/media/add-media/index.md
  src/site/content/en/media/bitrate/index.md
  src/site/content/en/media/containers-and-codecs/index.md
  src/site/content/en/media/containers-and-codecs/media-container-onion.png
  src/site/content/en/media/index.njk
  src/site/content/en/media/media-accessibility/chrome-android-track-landscape-5x3.jpg
  src/site/content/en/media/media-accessibility/index.md
  src/site/content/en/media/media-application-basics/index.md
  src/site/content/en/media/media-cheat-sheet/index.md
  src/site/content/en/media/media-experience/index.md
  src/site/content/en/media/media-file-basics/index.md
  src/site/content/en/media/media-file-basics/media-container-onion.png
  src/site/content/en/media/prepare-media/index.md
  src/site/content/en/media/resolution/index.md
  src/site/content/en/media/video-and-source-tags/accept-ranges-chrome-devtools.png
  src/site/content/en/media/video-and-source-tags/chrome-android-landscape-video-unstyled.png
  src/site/content/en/media/video-and-source-tags/chrome-android-portrait-video-unstyled.png
  src/site/content/en/media/video-and-source-tags/chrome-android-video-no-poster.png
  src/site/content/en/media/video-and-source-tags/chrome-android-video-poster.png
  src/site/content/en/media/video-and-source-tags/index.md
  src/site/content/en/media/video-and-source-tags/ipad-landscape-video-playing.png
  src/site/content/en/media/video-and-source-tags/iphone-video-playing-landscape.png
  src/site/content/en/media/video-and-source-tags/iphone-video-playing-portrait.png
Labels: cla: yes, new content, other

#3829 Fixes ::marker article tense
  src/site/content/en/blog/css-marker-pseudo-element/index.md
Labels: cla: yes

#3822 Move offline.njk content to a partial
  src/site/_includes/partials/offline.njk
  src/site/content/en/offline.md
  src/site/content/en/offline.njk
  src/site/content/pl/offline.md
  src/site/content/pl/offline.njk
Labels: cla: yes

#3684 Convert <model-viewer> from WebFu
  src/site/content/en/blog/model-viewer/hero.jpg
  src/site/content/en/blog/model-viewer/index.md
  src/site/content/en/blog/model-viewer/responsive-spacesuit.png
  src/site/content/en/blog/model-viewer/spacesuit.jpg
Labels: cla: yes

#3736 Add <model-viewer> 1.0 announcement
  src/site/content/en/blog/introducing-model-viewer/annotation.png
  src/site/content/en/blog/introducing-model-viewer/helmet.png
  src/site/content/en/blog/introducing-model-viewer/hero.jpg
  src/site/content/en/blog/introducing-model-viewer/index.md
Labels: DO NOT MERGE, cla: yes, new content, other

#3834 Fix size of video.
  src/site/content/en/blog/introducing-model-viewer/index.md
Labels: cla: yes

#3837 Temporarily disable content indexing.
  src/lib/app.js
Labels: cla: yes

#3817 Allow smart quotes as they are necessary in some languages
  tools/linting/no-smart-quotes.js
Labels: cla: yes

#3816 Move feed content to an include
  src/site/_includes/feed.njk
  src/site/content/en/feed.njk
Labels: cla: yes

#3844 Move 404 page to an include
  src/site/_includes/partials/404.njk
  src/site/content/en/404.md
  src/site/content/pl/404.md
  src/site/content/pl/404.njk
  src/site/content/pl/feed.njk
Labels: cla: yes

#3831 Update for Web OTP article
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#3842 Fix typo in sentence attributing author of Roboto typeface
  src/site/content/en/blog/variable-fonts/index.md
Labels: cla: yes

#3843 Fix broken anchor links on "Native image lazy-loading for the web" article
  src/site/content/en/fast/native-lazy-loading/index.md
Labels: cla: yes

#3839 More accurate storage info for Firefox
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: cla: yes

#3849 Get latest version of alex recommends
  .github/workflows/alex-workflow.yml
Labels: cla: yes

#3853 Fix a mistake in the CLS code sample
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#3852 Remove "Request an origin trial token" link
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#3856 Update index.md
  src/site/content/en/reliable/http-cache/index.md
Labels: cla: yes

#3833 Add Window Placement API article
  src/site/content/en/blog/multi-screen-window-placement/desk.jpg
  src/site/content/en/blog/multi-screen-window-placement/hero.jpg
  src/site/content/en/blog/multi-screen-window-placement/index.md
  src/site/content/en/blog/multi-screen-window-placement/panik.jpg
  src/site/content/en/blog/multi-screen-window-placement/tv.jpg
Labels: DO NOT MERGE, capabilities, cla: yes, content

#3832 [Text Fragment article] Add ModHeader opt-out option
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#3851 One more update to the Web OTP article
  src/site/content/en/blog/web-otp/index.md
Labels: DO NOT MERGE, cla: yes

#3866 [Window Placement article] Add spec draft link at bottom
  src/site/content/en/blog/multi-screen-window-placement/index.md
Labels: cla: yes

#3865 fix(toc): set overflow of TOC button to be hidden, fixes #3783
  src/lib/components/TableOfContents/index.js
  src/site/_includes/partials/post.njk
  src/styles/components/_toc.scss
Labels: cla: yes

#3803 Update Native File System article for stable release.
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/native-file-system/index.md
Labels: Chrome 86, DO NOT MERGE, beta related, cla: yes

#3742 Remove reference to ongoing trial.
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: cla: yes, content update

#3867 [Window Placement article] Correct terminology (event vs. event handler)
  src/site/content/en/blog/multi-screen-window-placement/index.md
Labels: capabilities, cla: yes, content update

#3698 Add WordPress guidance for iframes lazy-loading
  src/site/content/en/blog/iframe-lazy-loading/index.md
Labels: cla: yes

#3847 feat(feedback): allow conditional feedback questions to be enabled
  src/lib/components/BaseElement/index.js
  src/lib/components/Feedback/index.js
  src/site/_includes/partials/post.njk
  src/site/content/en/blog/change-password-url/index.md
  types/lib/components/Feedback.d.ts
  types/site/_collections/authors.d.ts
  types/site/_collections/newsletters.d.ts
  types/site/_collections/tags.d.ts
  types/site/_data/authorsData.d.ts
  types/site/_data/tagsData.d.ts
  types/site/_filters/paged-navigation.d.ts
  types/site/_includes/components/Glitch.d.ts
  types/site/_utils/add-pagination.d.ts
Labels: cla: yes

#3819 Masking and clipping articles
  src/site/content/en/blog/css-clipping/flat-edges.jpg
  src/site/content/en/blog/css-clipping/hero.jpg
  src/site/content/en/blog/css-clipping/index.md
  src/site/content/en/blog/css-masking/hero.jpg
  src/site/content/en/blog/css-masking/index.md
  src/site/content/en/blog/css-masking/svg-mask.jpg
  src/site/content/en/blog/hid-examples/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes

#3860 Add HID article
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/hid/device-log-page-screenshot.jpg
  src/site/content/en/blog/hid/hero.jpg
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/hid/joycon-switch-photo.jpg
  src/site/content/en/blog/hid/laptop-keyboard-photo.jpg
  src/site/content/en/blog/hid/thumbnail.jpg
  src/site/content/en/blog/hid/webhid-prompt.jpg
Labels: capabilities, cla: yes, content

#3883 Inline sw manifest to avoid weirdness with etags.
  src/lib/sw.js
  sw-manifest.js
Labels: cla: yes

#3885 feat(newsletter): add past editions
  src/site/content/en/newsletter/archive/2019/11/index.njk
  src/site/content/en/newsletter/archive/2019/11/thumbnail.png
  src/site/content/en/newsletter/archive/2020/07/index.njk
  src/site/content/en/newsletter/archive/2020/07/thumbnail.jpg
Labels: cla: yes

#3893 test conflicts in gitlocalize
  src/site/content/pl/index.md
Labels: cla: yes

#3894 fix: fix typo
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes

#3900 fix(analytics): track `ToC` event from actions rather than button component
  src/lib/actions.js
  src/lib/components/TableOfContentsButton/index.js
Labels: cla: yes

#3892 Update rec. to not use `any` paired with `maskable`
  src/site/content/en/blog/maskable-icon/index.md
Labels: cla: yes

#3445 Update variable fonts article
  src/images/authors/dcrossland.jpg
  src/images/authors/dcrossland@2x.jpg
  src/images/authors/roeln.jpg
  src/images/authors/roeln@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/variable-fonts/Amstelvar-Alpha-example.png
  src/site/content/en/blog/variable-fonts/Amstelvar-Ital-axis.png
  src/site/content/en/blog/variable-fonts/grass-mandy.png
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/variable-fonts/robot-specimen.png
  src/site/content/en/blog/variable-fonts/roboto-family-specimen.png
  src/site/content/en/blog/variable-fonts/roboto-family.png
  src/site/content/en/blog/variable-fonts/roboto-flex-aaaaaa.png
  src/site/content/en/blog/variable-fonts/roboto-flex-opsz.png
Labels: cla: yes, content update, frontend

#3904 Fix code example
  src/site/content/en/blog/css-clipping/index.md
Labels: cla: yes

#3814 content: How Mercado Libre optimized for Web Vitals (TBT, FID)
  src/images/authors/aranhacarlos.jpg
  src/images/authors/aranhacarlos@2x.jpg
  src/images/authors/demianrenzulli.jpg
  src/images/authors/demianrenzulli@2x.jpg
  src/images/authors/joanbaca.jpg
  src/images/authors/joanbaca@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/crux-progress.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/hero.jpg
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/lighthouse-iteration-1.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/lighthouse-iteration-2.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/lighthouse-unoptimized.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/main-thread-iteration-1-detail.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/main-thread-iteration-1.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/main-thread-iteration-2.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/main-thread-unoptimized.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/meli-pdp-desktop.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/meli-pdp-mobile.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/meli-pdp.png
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/tbt-blocking-time.svg
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/thumbnail.jpg
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/waterfall-unoptimized.png
Labels: cla: yes

#3828 Audit the codebase for inclusive language
  src/lib/app.js
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/UrlChooser/index.js
  src/site/_data/event.js
  src/site/_data/resource.js
  src/site/content/en/blog/media-session/index.md
  src/site/content/en/blog/service-worker-mindset/index.md
  src/site/content/en/blog/web-bundles/index.md
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
  src/site/content/en/lighthouse-accessibility/audio-caption/index.md
  src/site/content/en/lighthouse-accessibility/video-caption/index.md
  src/site/content/en/lighthouse-accessibility/video-description/index.md
  src/site/content/en/live/index.njk
  src/site/content/en/reliable/resilient-search-experiences/index.md
Labels: cla: yes

#3881 Fix link in multi-screen article.
  src/site/content/en/blog/multi-screen-window-placement/index.md
Labels: cla: yes

#3912 Force express to no-store our html.
  server.js
Labels: cla: yes

#3788 CDN article
  src/site/_data/paths/fast.json
  src/site/content/en/fast/content-delivery-networks/cdn1.png
  src/site/content/en/fast/content-delivery-networks/cdn2.png
  src/site/content/en/fast/content-delivery-networks/cdn3.png
  src/site/content/en/fast/content-delivery-networks/cdn4.png
  src/site/content/en/fast/content-delivery-networks/cdn5.png
  src/site/content/en/fast/content-delivery-networks/hero.jpg
  src/site/content/en/fast/content-delivery-networks/index.md
Labels: cla: yes

#3918 Add MDN compat survey banner.
  src/site/_data/site.js
Labels: cla: yes

#3915 [Idle Detection article] Add Puppeteer testing info
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#3920 Add isolate feature
  .huskyrc
  README.md
  package-lock.json
  package.json
  src/site/_collections/authors.js
  tools/isolate/index.js
Labels: cla: yes

#3919 Remove web.dev LIVE banner
  src/site/_includes/homepage.njk
  src/site/_includes/layout.njk
  src/site/content/en/index.md
Labels: cla: yes

#3875 Move experimental-web-platform-features flag section
  src/site/content/en/blog/fetch-upload-streaming/index.md
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/serial/index.md
Labels: cla: yes, content update

#3914 [Wake Lock article] Document new WakeLockSentinel.released
  src/site/content/_redirects.yaml
  src/site/content/en/blog/wake-lock/hero.jpg
  src/site/content/en/blog/wake-lock/index.md
Labels: cla: yes

#3926 [Idle Detection article] Remove fuzzing mitigation
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#3929 Fix broken links
  src/site/content/en/blog/browser-nativefs/index.md
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/drag-and-drop/index.md
  src/site/content/en/blog/granular-chunking-nextjs/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/preload-responsive-images/index.md
  src/site/content/en/blog/reporting-observer/index.md
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
  src/site/content/en/fast/content-delivery-networks/index.md
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
  src/site/content/en/fast/prioritize-resources/index.md
  src/site/content/en/fast/reduce-webfont-size/index.md
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/handbook/resolving-glitch-issues/index.md
  src/site/content/en/handbook/tooling-and-libraries/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
  src/site/content/en/lighthouse-seo/hreflang/index.md
  src/site/content/en/media/media-file-basics/index.md
  src/site/content/en/media/video-and-source-tags/index.md
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
Labels: cla: yes

#3932 [typo] Add missing bracket
  src/site/content/en/blog/trusted-types/index.md
Labels: cla: yes

#3927 Fix figure description in Mercade Libre case study
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md
Labels: cla: yes

#3931 Add general alternatives to `Referer`
  src/site/content/en/blog/referrer-best-practices/index.md
Labels: cla: yes

#3896 Fix Chrome's quota numbers.
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: cla: yes

#3934 Chore/resize image
  src/site/content/en/blog/workbox-share-targets/hero.jpg
  src/site/content/en/blog/workbox-share-targets/hero2.jpg
  src/site/content/en/blog/workbox-share-targets/index.md
Labels: cla: yes

#3862 Add offline fallback page article
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/progressive-web-apps/offline-fallback-page/assistant.jpg
  src/site/content/en/progressive-web-apps/offline-fallback-page/chrome-ios.png
  src/site/content/en/progressive-web-apps/offline-fallback-page/chrome.png
  src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
  src/site/content/en/progressive-web-apps/offline-fallback-page/slack.jpg
  src/site/content/en/progressive-web-apps/offline-fallback-page/trivago.png
  src/site/content/en/progressive-web-apps/offline-fallback-page/zoom.jpg
Labels: cla: yes

#3940 Remove self-referencing tag from /tags/* page
  src/site/content/en/metrics/index.njk
  src/site/content/en/notifications/index.njk
  src/site/content/en/payments/index.njk
  src/site/content/en/progressive-web-apps/index.njk
Labels: cla: yes

#3923 Add camera PTZ article
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/ptz/camera-ptz-user-prompt.jpg
  src/site/content/en/blog/ptz/hero.jpg
  src/site/content/en/blog/ptz/index.md
  src/site/content/en/blog/ptz/media-internals-page.jpg
  src/site/content/en/blog/ptz/thumbnail.jpg
Labels: DO NOT MERGE, capabilities, cla: yes, content

#3943 Respect screenshot image widths from markup
  src/styles/components/_images.scss
Labels: cla: yes

#3945 Detached window memory leaks
  src/site/content/en/blog/detached-window-memory-leaks/heap-snapshot.png
  src/site/content/en/blog/detached-window-memory-leaks/hero.jpg
  src/site/content/en/blog/detached-window-memory-leaks/index.md
  src/site/content/en/blog/detached-window-memory-leaks/performance-memory.png
Labels: cla: yes

#3952 Detached Windows: fix table
  src/site/content/en/blog/detached-window-memory-leaks/index.md
Labels: cla: yes

#3936 [Notification Triggers article] Revive Notification Triggers
  src/site/content/en/blog/notification-triggers/index.md
Labels: DO NOT MERGE, cla: yes

#3925 Rename "Native File System" to "File System Access"
  src/site/_data/event.js
  src/site/content/_redirects.yaml
  src/site/content/en/blog/async-clipboard/index.md
  src/site/content/en/blog/browser-nativefs/index.md
  src/site/content/en/blog/file-system-access/fs-open.jpg
  src/site/content/en/blog/file-system-access/fs-save-icon.jpg
  src/site/content/en/blog/file-system-access/fs-save-permission-crop.jpg
  src/site/content/en/blog/file-system-access/fs-save-permission.jpg
  src/site/content/en/blog/file-system-access/fs-save.jpg
  src/site/content/en/blog/file-system-access/hero.jpg
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/live-wrap-up/index.md
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/blog/storage-for-the-web/index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
Labels: cla: yes, content update

#3968 [Notification Triggers article ] Remove stray ')'
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#3941 Fix links.
  src/site/content/en/accessible/accessible-responsive-design/index.md
  src/site/content/en/blog/change-password-url/index.md
  src/site/content/en/blog/next-gen-css-2019/index.md
  src/site/content/en/fast/codelab-preload-critical-assets/index.md
  src/site/content/en/fast/codelab-preload-web-fonts/index.md
  src/site/content/en/fast/codelab-two-ways-to-prefetch/index.md
  src/site/content/en/media/containers-and-codecs/index.md
  src/site/content/en/media/media-application-basics/index.md
  src/site/content/en/media/media-cheat-sheet/index.md
Labels: cla: yes

#3942 Update titles of SXG articles
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes

#3973 Declarative Shadow DOM article
  src/images/authors/masonfreed.jpg
  src/images/authors/masonfreed@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/declarative-shadow-dom/hero.jpg
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes, content

#3922 Add the Goibibo case study
  src/images/tags/scale-on-web.svg
  src/site/_data/tagsData.json
  src/site/content/en/blog/goibibo/conversions.png
  src/site/content/en/blog/goibibo/funnel.png
  src/site/content/en/blog/goibibo/hero.png
  src/site/content/en/blog/goibibo/index.md
  src/site/content/en/blog/goibibo/logins.png
  src/site/content/en/blog/goibibo/mobile.png
  src/site/content/en/blog/goibibo/seamless.png
  src/site/content/en/blog/goibibo/thumbnail.png
  src/site/content/en/blog/goibibo/web-share.png
  src/site/content/en/tags/individual.njk
  src/styles/pages/_tags.scss
Labels: cla: yes

#3970 (Detached Windows) Add step-by-step walkthrough
  src/site/content/en/blog/detached-window-memory-leaks/index.md
Labels: cla: yes

#3977 Add bartek as author to Detached Windows article
  src/images/authors/bartekn.jpg
  src/images/authors/bartekn@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/detached-window-memory-leaks/index.md
Labels: cla: yes

#3975 Add serial dev tip
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/serial/device-log-page-screenshot.jpg
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#3946 Fix undefined codelab paths
  src/site/_filters/get-paths.js
  src/site/_includes/codelab.njk
  test/unit/src/site/_filters/getPaths.js
Labels: cla: yes
