Repository GoogleChrome/web.dev, pull requests merged in 2020-02, with the labels that each got.

#2124 Update index.md
  src/site/content/en/lighthouse-performance/mainthread-work-breakdown/index.md
Labels: cla: yes

#2125 Add fallback size to hero so it doesn't shift.
  src/site/_includes/components/Hero.js
Labels: cla: yes

#2128 Center misaligned image
  src/site/content/en/blog/content-indexing-api/index.md
Labels: cla: yes

#2119 Update .gitlocalize.yml
  .gitlocalize.yml
Labels: cla: yes

#2103 Update link to multi-origin TWA solution
  src/site/content/en/blog/multi-origin-pwas/index.md
Labels: cla: yes

#2051 PWA Check List
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
  src/site/content/en/progressive-web-apps/pwa-checklist/index.md
Labels: DO NOT MERGE, cla: yes, content, pwa

#2085 Improve and correct WebXR article.
  src/site/content/en/blog/vr-comes-to-the-web/index.md
Labels: cla: yes, content

#2140 Remove old, unused devsite css.
  src/styles/devsite/_app.scss
  src/styles/devsite/_vetos.scss
Labels: cla: yes

#2150 Update content process documentation
  .github/ISSUE_TEMPLATE/collection_proposal.md
  .github/ISSUE_TEMPLATE/content.md
  .github/ISSUE_TEMPLATE/content_proposal.md
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes, content, handbook

#2145 Add Percy snapshot testing.
  .github/workflows/percy-workflow.yml
  package-lock.json
  package.json
  src/lib/actions.js
  src/lib/store.js
  src/site/_collections/post-descending.js
  src/site/_collections/recent-posts.js
  src/site/content/en/blog/off-main-thread/index.md
  src/site/content/en/blog/samesite-cookie-recipes/index.md
  src/site/content/en/blog/shopping-for-speed-on-ebay/index.md
  src/site/content/en/blog/workbox-share-targets/index.md
  tools/percy/snapshots.js
Labels: cla: yes

#2148 flip prod auth domain
  src/site/_data/site.js
Labels: cla: yes

#2146 Add Web NFC post
  src/site/content/en/blog/nfc/chrome-flag.png
  src/site/content/en/blog/nfc/hero.jpg
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/nfc/ndef-message-diagram.png
  src/site/content/en/blog/nfc/nfc-inventory-management.png
  src/site/content/en/blog/nfc/nfc-operation-diagram.png
  src/site/content/en/blog/nfc/nfc-prompt.png
  src/site/content/en/blog/nfc/nfc-tag.jpg
  src/site/content/en/blog/nfc/thumbnail.jpg
Labels: cla: yes

#2160 Clarify that NFC is only available on Chrome for Android
  src/site/content/en/blog/nfc/index.md
Labels: cla: yes

#2156 fix(web-side-nav): add signal for current page in side nav, fixes #1784
  src/lib/components/SideNav/_styles.scss
  src/lib/components/SideNav/index.js
  src/site/_includes/layout.njk
Labels: cla: yes

#2143 First commit of augmented reality article.
  src/site/content/en/blog/web-ar/hero.jpg
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2158 Fix math error
  src/site/content/en/fast/codelab-serve-images-correct-dimensions/index.md
Labels: cla: yes

#2163 Hide AR article temporarily.
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2167 Hide yt iframe during screenshot tests.
  src/site/_includes/components/YouTube.js
Labels: cla: yes

#2154 fix(Meta): use `path.title` and `path.description` in `getMetaByPlatform`, fixes #2002
  src/site/_includes/components/Meta.js
Labels: cla: yes

#2151 add Firestore backup workflow
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/snapshot-firestore.yml
Labels: cla: yes

#2168 performance-scoring: update LH v5 and v6 weights
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes

#2120 VR comes to the web, part II.
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/hero.jpg
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/players.png
  src/site/content/en/blog/vr-comes-to-the-web/index.md
Labels: DO NOT MERGE, blog, cla: yes

#2149 Add hit test article.
  src/site/content/en/blog/ar-hit-test/hero.jpg
  src/site/content/en/blog/ar-hit-test/index.md
  src/site/content/en/blog/ar-hit-test/reticles.png
Labels: cla: yes

#2049 What Are PWAs - intro doc
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
  src/site/content/en/progressive-web-apps/what-are-pwas/capabilities-reach.svg
  src/site/content/en/progressive-web-apps/what-are-pwas/index.md
Labels: DO NOT MERGE, cla: yes, pwa

#2169 Publish augmented reality articles
  src/site/content/en/blog/ar-hit-test/index.md
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2009 A11y tips for web dev
  src/site/content/en/blog/a11y-tips-for-web-dev/a11y-tree-chrome.png
  src/site/content/en/blog/a11y-tips-for-web-dev/a11y-tree-ff.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/angular-a11y-testing.png
  src/site/content/en/blog/a11y-tips-for-web-dev/aria-expanded.gif
  src/site/content/en/blog/a11y-tips-for-web-dev/chromelens.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/dos-donts.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/hero.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/index.md
  src/site/content/en/blog/a11y-tips-for-web-dev/inspect-element.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/lh-a11y-audit.png
  src/site/content/en/blog/a11y-tips-for-web-dev/manage-focus.png
  src/site/content/en/blog/a11y-tips-for-web-dev/pie-chart.png
  src/site/content/en/blog/a11y-tips-for-web-dev/react-a11y-testing.png
  src/site/content/en/blog/a11y-tips-for-web-dev/screen-reader.jpg
  src/site/content/en/blog/a11y-tips-for-web-dev/slider.png
  src/site/content/en/blog/a11y-tips-for-web-dev/web-dev-a11y.jpg
Labels: cla: yes

#2170 Add the right hero image.
  src/site/content/en/blog/web-ar/hero.jpg
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2181 Only run Percy on certain file types.
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#2183 Fix nit.
  src/site/content/en/blog/nfc/index.md
Labels: cla: yes

#2184 Add explicit --project to gcloud run
  .github/workflows/snapshot-firestore.yml
Labels: cla: yes

#2182 fix typo
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
Labels: cla: yes

#2186 make subscribe link open in new window
  src/lib/components/Actions/index.js
Labels: cla: yes

#2139 Add a feature card class to 1st post on homepage.
  src/site/_collections/recent-posts.js
  src/site/_includes/components/PostCard.js
  src/site/content/en/index.njk
  src/styles/components/_grid.scss
  src/styles/components/_post-card.scss
  src/styles/tools/_breakpoints.scss
Labels: cla: yes

#2188 Make nested handbook links work again.
  src/site/_includes/handbook.njk
  src/site/content/en/handbook/handbook.11tydata.js
Labels: cla: yes

#1992 Prepare getInstalledRelatedApps() article for shipping.
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: beta blog-related, blocked, cla: yes, content

#2179 content: Add web app manifest doc
  src/site/content/en/installable/add-manifest/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
  src/site/content/en/progressive-web-apps/add-manifest/lh-manifest.png
Labels: cla: yes, content, devsite-migration, dgc-migration, installable, pwa

#2178 content: promote pwa install
  src/site/_data/contributors.json
  src/site/content/en/images/authors/pjmclachlan.jpg
  src/site/content/en/images/authors/pjmclachlan@2x.jpg
  src/site/content/en/progressive-web-apps/promote-install/banner.png
  src/site/content/en/progressive-web-apps/promote-install/game-over.png
  src/site/content/en/progressive-web-apps/promote-install/game-start.png
  src/site/content/en/progressive-web-apps/promote-install/header.png
  src/site/content/en/progressive-web-apps/promote-install/in-feed.png
  src/site/content/en/progressive-web-apps/promote-install/index.md
  src/site/content/en/progressive-web-apps/promote-install/journey.png
  src/site/content/en/progressive-web-apps/promote-install/landing.png
  src/site/content/en/progressive-web-apps/promote-install/nav.png
  src/site/content/en/progressive-web-apps/promote-install/plp.png
  src/site/content/en/progressive-web-apps/promote-install/pwa-omnibox-install.jpg
  src/site/content/en/progressive-web-apps/promote-install/sign-up.png
Labels: cla: yes

#2196 Update content issue templates
  .github/ISSUE_TEMPLATE/propose-new-content.md
  .github/ISSUE_TEMPLATE/update-existing-content.md
Labels: cla: yes

#2193 Move install codelab to PWA directory
  src/site/content/en/progressive-web-apps/codelab-make-installable/index.md
Labels: cla: yes, pwa

#1995 Sanity check Notification Triggers article.
  src/site/content/en/blog/notification-triggers/index.md
Labels: beta blog-related, cla: yes, content

#2172 Capabilities status blog post
  src/site/content/en/blog/fugu-status/index.md
Labels: capabilities, cla: yes, content, devsite-migration, dgc-migration

#2198 Add case study template
  src/site/_drafts/_template-case-study/index.md
Labels: cla: yes

#2197 Remove unnecessary favicons, add Apple specific ones
  src/images/android-chrome-192x192.png
  src/images/android-chrome-512x512.png
  src/images/apple-touch-icon.png
  src/images/favicon-16x16.png
  src/images/favicon-32x32.png
  src/images/favicon.ico
  src/images/favicon@2x.png
  src/images/icon-128x128.png
  src/images/icon-144x144.png
  src/images/icon-152x152.png
  src/images/icon-192x192.png
  src/images/icon-384x384.png
  src/images/icon-512x512.png
  src/images/icon-72x72.png
  src/images/icon-96x96.png
  src/images/safari-pinned-tab.svg
  src/images/touchicon-180.png
  src/misc/manifest.webmanifest
  src/site/_includes/layout.njk
Labels: cla: yes

#2203 feat: add tags to certain posts
  src/site/content/en/blog/earth-webassembly/index.md
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/index.md
  src/site/content/en/blog/google-search-sw/index.md
  src/site/content/en/blog/opensooq-case-study/index.md
  src/site/content/en/blog/shopping-for-speed-on-ebay/index.md
  src/site/content/en/blog/truebil-lite/index.md
Labels: cla: yes

#2202 Add hero image to wake lock article
  src/site/content/en/blog/wakelock/hero.jpg
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#2205 Remove UI cruft on mobile.
  src/site/_data/site.js
  src/styles/components/_banner.scss
  src/styles/components/_images.scss
Labels: cla: yes

#2201 Make fugu-status live
  src/site/content/en/blog/fugu-status/index.md
Labels: capabilities, cla: yes

#2223 Force percy to scroll page to load lazy images.
  package-lock.json
  package.json
  tools/percy/snapshots.js
Labels: cla: yes

#2224 Update bio for petele
  src/site/_data/contributors.js
Labels: cla: yes

#2212 Add 'fugu' to tags file.
  src/site/_data/postTags.js
Labels: cla: yes

#2200 Publish brand new Progressive Web App section
  src/site/content/en/_redirects.yaml
  src/site/content/en/en.11tydata.js
  src/site/content/en/installable/discover-installable/hero.png
  src/site/content/en/installable/discover-installable/index.md
  src/site/content/en/installable/discover-installable/lighthouse.png
  src/site/content/en/installable/index.njk
  src/site/content/en/installable/installable.11tydata.js
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/en/progressive-web-apps/add-manifest/index.md
  src/site/content/en/progressive-web-apps/codelab-make-installable/index.md
  src/site/content/en/progressive-web-apps/customize-install/index.md
  src/site/content/en/progressive-web-apps/index.njk
  src/site/content/en/progressive-web-apps/install-criteria/index.md
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
  src/site/content/en/progressive-web-apps/promote-install/index.md
  src/site/content/en/progressive-web-apps/pwa-checklist/index.md
  src/site/content/en/progressive-web-apps/what-are-pwas/index.md
Labels: cla: yes, pwa

#2199 Fix a few items.
  src/site/content/en/blog/ar-hit-test/index.md
Labels: cla: yes

#2206 Add MDN survey banner.
  src/site/_data/site.js
  src/site/_includes/codelab.njk
  src/site/_includes/partials/banner.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/path.njk
  src/site/content/en/about/index.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/tags/index.njk
Labels: cla: yes

#2231 Disabled indented code blocks
  .eleventy.js
  src/site/content/en/handbook/markup-code/index.md
Labels: cla: yes

#2222 Remove Details animation
  src/styles/components/_details.scss
Labels: cla: yes

#2208 disable scroll restoration for async loader
  src/lib/utils/router.js
Labels: cla: yes

#2209 don't include SW on bad hostnames, redirect from appengine-test
  server.js
  src/lib/bootstrap.js
Labels: cla: yes

#2213 Add a console dump filter.
  .eleventy.js
  src/site/_filters/console-dump.js
Labels: cla: yes

#2236 fix(mdn): put banner in `layout.njk`
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/path.njk
  src/site/content/en/about/index.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/learn/index.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/tags/index.njk
Labels: cla: yes

#2210 strip utm_ from Workbox
  src/lib/sw.js
Labels: cla: yes

#2233 [add-manifest] Fix minimal-ui nits and add screenshots
  src/site/content/en/progressive-web-apps/add-manifest/index.md
  src/site/content/en/progressive-web-apps/add-manifest/minimal-ui-pwa-window.png
  src/site/content/en/progressive-web-apps/add-manifest/standalone-pwa-window.png
  src/site/content/en/progressive-web-apps/add-manifest/theme_color-pwa-window.png
Labels: cla: yes

#2232 pwa checklist: fix typo
  src/site/content/en/progressive-web-apps/pwa-checklist/index.md
Labels: cla: yes

#2250 Update all metrics docs with threshold guidance
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
Labels: cla: yes

#2249 Remove `draft` from Notification Triggers article
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/notification-triggers/index.md
Labels: capabilities, cla: yes

#2243 Small edits to clipboard article.
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
Labels: cla: yes

#2248 Link update
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2211 Add "Web NFC" to "New capabilities status" page
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/nfc/index.md
Labels: capabilities, cla: yes

#2246 workbox to 5.0.0, inline
  build.js
  package-lock.json
  package.json
  src/lib/sw.js
Labels: cla: yes

#2253 fix broken sw
  src/lib/bootstrap.js
  src/lib/sw.js
Labels: cla: yes
