Repository GoogleChrome/web.dev, pull requests merged in 2020-12, with the labels that each got.

#4319 Fixed error in code for Step 3
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
Labels: cla: yes

#4317 Add macOS and Chrome OS support for barcode detection
  src/site/content/en/blog/shape-detection/index.md
Labels: capabilities, cla: yes, content update

#4316 Add third-party facades audit doc
  src/site/_data/paths/lighthouse-performance.json
  src/site/content/en/lighthouse-performance/third-party-facades/audit.jpg
  src/site/content/en/lighthouse-performance/third-party-facades/index.md
  src/site/content/en/lighthouse-performance/third-party-facades/loadYouTube.jpg
Labels: cla: yes

#4305 SMS OTP form best practices
  src/site/content/en/blog/sms-otp-form/hero.jpg
  src/site/content/en/blog/sms-otp-form/index.md
Labels: DO NOT MERGE, cla: yes

#4328 Revert "SMS OTP form best practices"
  src/site/content/en/blog/sms-otp-form/hero.jpg
  src/site/content/en/blog/sms-otp-form/index.md
Labels: cla: yes

#4290 Use event.target for connect/disconnect serial events
  src/site/content/en/blog/serial/index.md
Labels: capabilities, cla: yes, content update

#4329 SMS OTP form best practices
  src/site/content/en/blog/sms-otp-form/hero.jpg
  src/site/content/en/blog/sms-otp-form/index.md
Labels: DO NOT MERGE, cla: yes

#4330 Revert "SMS OTP form best practices"
  src/site/content/en/blog/sms-otp-form/hero.jpg
  src/site/content/en/blog/sms-otp-form/index.md
Labels: cla: yes

#4324 Stories Codelab Patch #1
  src/site/content/en/blog/codelab-building-a-stories-component/index.md
  src/site/content/en/blog/codelab-building-a-stories-component/thumb.jpg
Labels: cla: yes, content update

#4259 Update NFC article with spec changes
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/nfc/index.md
Labels: DO NOT MERGE, cla: yes, content update

#4327 Stories post - community submission
  src/site/content/en/blog/building-a-stories-component/index.md
Labels: cla: yes, content update

#4240 Move "Building a device for WebUSB" from WebFu to web.dev
  src/images/authors/reillyg.jpg
  src/images/authors/reillyg@2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/devices.json
  src/site/content/en/blog/build-for-webusb/index.md
  src/site/content/en/blog/build-for-webusb/notification.png
Labels: CDS 2020, capabilities, cla: yes, content

#4296 Extending Workbox blog post
  src/site/_data/paths/reliable.json
  src/site/content/en/blog/extending-workbox/hero.png
  src/site/content/en/blog/extending-workbox/index.md
  src/site/content/en/blog/extending-workbox/thumbnail.png
Labels: cla: yes

#4347 Tweak for new PWA installability requirements check.
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/progressive-web-apps/install-criteria/index.md
Labels: cla: yes, content update, pwa

#4163 [Idle Detection article] Add info about ended OT (Merge on Nov. 11, 2020)
  src/site/content/en/blog/idle-detection/index.md
Labels: Chrome 88, beta related, cla: yes

#4253 question - What is "DOM Storage"?
  src/site/content/en/blog/persistent-storage/index.md
Labels: cla: yes

#4338 Add Gravit case study
  src/images/authors/rezakazemi.jpg
  src/images/authors/rezakazemi@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/gravit-designer/dark.png
  src/site/content/en/blog/gravit-designer/hero.png
  src/site/content/en/blog/gravit-designer/index.md
  src/site/content/en/blog/gravit-designer/light.png
  src/site/content/en/blog/gravit-designer/thumbnail.png
Labels: cla: yes

#4337 update Lighthouse a11y docs
  src/site/content/_redirects.yaml
  src/site/content/en/lighthouse-accessibility/aria-input-field-name/aria-input-field-name.png
  src/site/content/en/lighthouse-accessibility/aria-input-field-name/index.md
  src/site/content/en/lighthouse-accessibility/aria-name/aria-toggle-field-name.png
  src/site/content/en/lighthouse-accessibility/aria-name/index.md
  src/site/content/en/lighthouse-accessibility/aria-toggle-field-name/index.md
  src/site/content/en/lighthouse-accessibility/layout-table/index.md
  src/site/content/en/lighthouse-accessibility/video-description/index.md
Labels: CDS 2020, cla: yes

#4228 Edited codelab for CDS
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
Labels: cla: yes

#4336 Add Clipchamp case study
  src/images/authors/sorenbalko.jpg
  src/images/authors/sorenbalko@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/clipchamp/hero.jpg
  src/site/content/en/blog/clipchamp/index.md
  src/site/content/en/blog/clipchamp/installs.png
  src/site/content/en/blog/clipchamp/performance.png
  src/site/content/en/blog/clipchamp/thumbnail.jpg
Labels: cla: yes

#4340 Window to worker communication series
  src/images/authors/andrewguan.jpg
  src/images/authors/andrewguan2x.jpg
  src/site/_data/authorsData.json
  src/site/_data/paths/reliable.json
  src/site/content/en/reliable/broadcast-updates-guide/broadcast-updates-diagram.png
  src/site/content/en/reliable/broadcast-updates-guide/index.md
  src/site/content/en/reliable/broadcast-updates-guide/squoosh-screenshot.png
  src/site/content/en/reliable/broadcast-updates-guide/tinder-screenshot.png
  src/site/content/en/reliable/imperative-caching-guide/1-800-flowers-logo.png
  src/site/content/en/reliable/imperative-caching-guide/1-800-flowers-prefetching.png
  src/site/content/en/reliable/imperative-caching-guide/imperative-caching-diagram-1.png
  src/site/content/en/reliable/imperative-caching-guide/index.md
  src/site/content/en/reliable/two-way-communication-guide/broadcast-channel.png
  src/site/content/en/reliable/two-way-communication-guide/client-api.png
  src/site/content/en/reliable/two-way-communication-guide/communication-apis.png
  src/site/content/en/reliable/two-way-communication-guide/google-search-background-sync.png
  src/site/content/en/reliable/two-way-communication-guide/index.md
  src/site/content/en/reliable/two-way-communication-guide/message-channel.png
  src/site/content/en/reliable/two-way-communication-guide/podcast-pwa.png
  src/site/content/en/reliable/two-way-communication-guide/two-way-communication-diagram.png
  src/site/content/en/reliable/two-way-communication-guide/workbox-window-diagram.png
  src/site/content/en/reliable/workers-overview/comlink-workbox.png
  src/site/content/en/reliable/workers-overview/hero.jpeg
  src/site/content/en/reliable/workers-overview/index.md
  src/site/content/en/reliable/workers-overview/podcast-pwa.png
  src/site/content/en/reliable/workers-overview/proxx.png
  src/site/content/en/reliable/workers-overview/window-service-worker.png
  src/site/content/en/reliable/workers-overview/window-web-worker.png
  src/site/content/en/reliable/workers-overview/window-worker.png
Labels: cla: yes

#4346 Push Notifications article and codelabs: minor fixes
  src/site/content/en/blog/push-notifications-client-codelab/index.md
  src/site/content/en/blog/push-notifications-overview/index.md
  src/site/content/en/blog/push-notifications-server-codelab/index.md
Labels: cla: yes

#4351 Add AutoWebPerf intro
  src/site/content/en/blog/autowebperf/architecture.png
  src/site/content/en/blog/autowebperf/data-studio.png
  src/site/content/en/blog/autowebperf/index.md
Labels: DO NOT MERGE, cla: yes

#4331 Sms otp form
  src/site/content/en/blog/sms-otp-form/hero.jpg
  src/site/content/en/blog/sms-otp-form/index.md
Labels: cla: yes

#4341 squoosh-v2 blog post
  src/site/content/en/blog/squoosh-v2/hero.jpg
  src/site/content/en/blog/squoosh-v2/index.md
  src/site/content/en/blog/squoosh-v2/thumb.jpg
Labels: cla: yes

#4354 Bump the publish date of SMS OTP form best practices article
  src/site/content/en/blog/sms-otp-form/index.md
Labels: cla: yes

#4320 Codelab for review: Sign up form best practices
  src/site/content/en/blog/codelab-sign-up-form-best-practices/index.md
Labels: DO NOT MERGE, cla: yes, privacy/security

#4288 Ready for review: Sign-up form best practices
  src/site/content/en/blog/sign-up-form-best-practices/images/federated-login.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-account-switching.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-activity.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-sign-up-create-account.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/hero.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/obvious-sign-in.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/thumbnail.jpg
  src/site/content/en/blog/sign-up-form-best-practices/index.md
Labels: DO NOT MERGE, cla: yes, privacy/security

#4280 Ready for review: Payment and address form best practices
  src/site/content/en/blog/payment-and-address-form-best-practices/images/browserstack.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/credit-card-number-multiple-inputs.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/custom-element-date-glitch.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/enterkeyhint.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/free-stickers.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/hero.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/input-type.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/images/invalid-email.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/john-lewis.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/remove-distractions.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/returning-user.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/review-order.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/shopping-cart-abandonment.png
  src/site/content/en/blog/payment-and-address-form-best-practices/images/thumbnail.jpg
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
Labels: DO NOT MERGE, cla: yes, e-commerce, privacy/security

#4314 Codelabs for review: Payment form best practices, Address form best practices
  src/site/content/en/blog/codelab-address-form-best-practices/images/autofill-autocomplete.jpg
  src/site/content/en/blog/codelab-address-form-best-practices/images/enterkeyhint.png
  src/site/content/en/blog/codelab-address-form-best-practices/index.md
  src/site/content/en/blog/codelab-payment-form-best-practices/images/credit-card-autofill.png
  src/site/content/en/blog/codelab-payment-form-best-practices/index.md
Labels: cla: yes, e-commerce, privacy/security

#4356 Trust tokens update
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#4188 Update index.md
  src/site/content/en/blog/min-max-clamp/index.md
Labels: cla: yes, content update

#4360 add draft love your cache post
  src/site/content/en/blog/love-your-cache/hero.jpg
  src/site/content/en/blog/love-your-cache/index.md
Labels: cla: yes

#4359 Update thumbnail guidance
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/markup-media/thumbnails.jpg
Labels: cla: yes, content update, handbook

#4361 Update titles of clipping and masking guides
  src/site/content/en/blog/css-clipping/index.md
  src/site/content/en/blog/css-masking/index.md
Labels: cla: yes

#4362 Update SMS OTP form article
  src/site/content/en/blog/sms-otp-form/index.md
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#4350 Add publish-modern-javascript article
  src/site/_data/paths/fast.json
  src/site/content/en/fast/publish-modern-javascript/estimator-screenshot.png
  src/site/content/en/fast/publish-modern-javascript/hero.jpg
  src/site/content/en/fast/publish-modern-javascript/index.md
Labels: DO NOT MERGE, cla: yes

#4323 [Post] Cross-browser paint worklets and Houdini.how
  src/site/content/en/blog/houdini-how/angled-demo.mp4
  src/site/content/en/blog/houdini-how/caniuse-paint.png
  src/site/content/en/blog/houdini-how/hero.jpg
  src/site/content/en/blog/houdini-how/houdini.jpg
  src/site/content/en/blog/houdini-how/index.md
  src/site/content/en/blog/houdini-how/worklet-page.png
Labels: cla: yes, sum

#4365 Add YouTube video to paths landing pages
  src/site/_data/paths/devices.json
  src/site/_includes/path.njk
Labels: cla: yes

#4366 Add YouTube video to paths landing pages
  src/site/_data/paths/devices.json
  src/site/_includes/path.njk
Labels: cla: yes

#4371 Removed duplicate youtube video at the bottom
  src/site/_includes/path.njk
Labels: cla: yes

#4364 love your cache post
  src/site/_data/paths/reliable.json
  src/site/content/en/blog/love-your-cache/cache.png
  src/site/content/en/blog/love-your-cache/index.md
  src/site/content/en/reliable/http-cache/index.md
Labels: cla: yes

#4376 Add YouTube video: Payment and address form best practices
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
Labels: cla: yes

#4373 Workbox CDS article tweaks
  src/site/content/en/blog/extending-workbox/index.md
Labels: cla: yes

#4377 Syntactically fix json example (modern js article)
  src/site/content/en/fast/publish-modern-javascript/index.md
Labels: cla: yes

#4372 Adds video to Houdini.how post
  src/site/content/en/blog/houdini-how/index.md
Labels: cla: yes

#4374 [Shape Detection article] Better describe feature detection
  src/site/content/en/blog/shape-detection/index.md
Labels: cla: yes

#4384 Smart-poster records are supported since Chrome 82
  src/site/content/en/blog/nfc/index.md
Labels: cla: yes

#4379 Building a stories component - community remix patch
  src/site/content/en/blog/building-a-stories-component/index.md
Labels: cla: yes

#4213 Indicate that noopener behavior is now default
  src/site/content/en/lighthouse-best-practices/external-anchors-use-rel-noopener/index.md
Labels: cla: yes

#4301 Fix debugging npm command to debug eleventy
  README.md
Labels: cla: yes

#4300 Set width & height attributes images
  package-lock.json
  package.json
  src/site/_transforms/responsive-images/index.js
Labels: cla: yes

#3685 New Post: Centering in CSS
  src/site/content/en/blog/centering-in-css/hero.png
  src/site/content/en/blog/centering-in-css/index.md
  src/site/content/en/blog/centering-in-css/legend.png
  src/site/content/en/blog/centering-in-css/thumb.png
  src/site/content/en/blog/codelab-centering-in-css/index.md
Labels: DO NOT MERGE, cla: yes

#4375 Add YouTube video: Sign-up form best practices
  src/site/content/en/blog/sign-up-form-best-practices/index.md
Labels: cla: yes

#4387 update date
  src/site/content/en/blog/centering-in-css/index.md
  src/site/content/en/blog/codelab-centering-in-css/index.md
Labels: cla: yes

#4357 Updating authors and hero image for blog article: https://web.dev/autowebperf/
  src/images/authors/antoinebisch.jpg
  src/images/authors/antoinebisch@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/autowebperf/hero.jpg
  src/site/content/en/blog/autowebperf/index.md
  src/site/content/en/blog/autowebperf/thumbnail.jpg
Labels: cla: yes

#4401 Don't compute image sizes if there's already a dimension.
  src/site/_transforms/responsive-images/index.js
Labels: cla: yes

#4402 Stories blog post patch: adds community submission
  src/site/content/en/blog/building-a-stories-component/index.md
Labels: cla: yes
