Repository GoogleChrome/web.dev, pull requests merged in 2020-06, with the labels that each got.

#3070 Lighthouse docs: switch from kilobytes to kibibytes
  src/site/content/en/lighthouse-performance/offscreen-images/index.md
  src/site/content/en/lighthouse-performance/total-byte-weight/index.md
  src/site/content/en/lighthouse-performance/unminified-css/index.md
  src/site/content/en/lighthouse-performance/unminified-javascript/index.md
  src/site/content/en/lighthouse-performance/unused-css-rules/index.md
  src/site/content/en/lighthouse-performance/uses-optimized-images/index.md
  src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
  src/site/content/en/lighthouse-performance/uses-text-compression/index.md
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
  src/site/content/en/lighthouse-seo/robots-txt/index.md
Labels: cla: yes, content update, lighthouse

#3077 Add comment with link to r/webdev discussion
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes

#3093 Update talk title.
  src/site/_data/event.js
Labels: cla: yes

#3085 Fix broken gulp image output.
  gulpfile.js
  package.json
Labels: cla: yes

#3098 feat(log-errors): log errors from subscribe form
  src/lib/components/Subscribe/index.js
  src/site/_includes/partials/subscribe.njk
  src/site/content/en/live/index.njk
Labels: cla: yes

#3092 Update index.js
  src/lib/components/UrlChooser/index.js
Labels: cla: yes

#3099 Turn off the service worker kill switch.
  server.js
Labels: cla: yes

#3091 Added app shortcut icon quality measure on Android
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes

#3054 Migrate a11y article
  src/site/_data/contributors.js
  src/site/content/en/accessible/accessible-responsive-design/index.md
  src/site/content/en/accessible/accessible-responsive-design/udacity-100.jpg
  src/site/content/en/accessible/accessible-responsive-design/udacity-400.jpg
  src/site/content/en/accessible/accessible-tap-targets/firefox-layout.jpg
  src/site/content/en/accessible/accessible-tap-targets/index.md
  src/site/content/en/accessible/accessible.11tydata.js
  src/site/content/en/accessible/color-and-contrast/accessibility-audit.png
  src/site/content/en/accessible/color-and-contrast/contrast-ratios.jpg
  src/site/content/en/accessible/color-and-contrast/emulate.jpg
  src/site/content/en/accessible/color-and-contrast/fastpass-contrast.jpg
  src/site/content/en/accessible/color-and-contrast/high-contrast.jpg
  src/site/content/en/accessible/color-and-contrast/index.md
  src/site/content/en/accessible/color-and-contrast/input-form1.png
  src/site/content/en/accessible/color-and-contrast/input-form2.png
  src/site/content/en/accessible/color-and-contrast/tab-contrast.png
  src/site/content/en/accessible/content-reordering/a11y-insights.jpg
  src/site/content/en/accessible/content-reordering/index.md
  src/site/content/en/blog/responsive-web-design-basics/index.md
  src/site/content/en/lighthouse-seo/tap-targets/index.md
Labels: cla: yes

#3107 Update color and contrast a11y article URL to match title
  src/site/content/en/accessible/accessible.11tydata.js
  src/site/content/en/accessible/color-and-contrast-accessibility/accessibility-audit.png
  src/site/content/en/accessible/color-and-contrast-accessibility/contrast-ratios.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/emulate.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/fastpass-contrast.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/high-contrast.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/index.md
  src/site/content/en/accessible/color-and-contrast-accessibility/input-form1.png
  src/site/content/en/accessible/color-and-contrast-accessibility/input-form2.png
  src/site/content/en/accessible/color-and-contrast-accessibility/tab-contrast.png
Labels: cla: yes

#3105 Fix broken link in setting up a payment method
  src/site/content/en/payments/setting-up-a-payment-method/index.md
Labels: cla: yes

#3114 Fix broken link in LCP article
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#3124 Fixes #3109. Redirect 404ing LH learn more link.
  src/site/content/_redirects.yaml
Labels: cla: yes

#3125 Update "What to expect" language.
  src/site/content/en/live/index.njk
Labels: cla: yes

#3056 Add a language switch element
  package-lock.json
  package.json
  src/lib/actions.js
  src/lib/components/LanguageSelect/index.js
  src/lib/components/base.js
  src/lib/store.js
  src/lib/utils/language.js
  src/site/_includes/partials/footer.njk
  src/site/_includes/partials/subscribe.njk
  src/styles/components/_subscribe.scss
  src/styles/generic/_all.scss
  src/styles/generic/select
Labels: cla: yes

#3137 Fix usage of Compare components
  src/site/content/en/lighthouse-seo/robots-txt/index.md
Labels: cla: yes, content update, lighthouse

#3138 Add verbatim messages from Chrome and Firefox Consoles
  src/site/content/en/lighthouse-best-practices/no-document-write/index.md
Labels: cla: yes, content update, lighthouse

#3139 Update the text compression guidance
  src/site/content/en/lighthouse-performance/uses-text-compression/index.md
Labels: cla: yes, content update, lighthouse

#3144 Update title of CORS guide and embed Glitch
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes

#3127 feat(subscribe-analytics): add tracking for clicking subscribe/newsletter buttons, fixes #3106
  src/site/_includes/partials/subscribe-action.njk
  src/site/content/en/live/index.njk
Labels: cla: yes

#3145 Replace image with table
  src/site/content/en/fast/how-to-stay-fast/index.md
  src/site/content/en/fast/how-to-stay-fast/performance-budget-example.png
Labels: cla: yes

#3146 [Pre-event] Add link to community guidelines
  src/site/content/en/live/index.njk
Labels: cla: yes

#3135 Simplify ArticleNavigation
  src/site/_includes/codelab.njk
  src/site/_includes/components/ArticleNavigation.js
  src/site/_includes/partials/post.njk
Labels: cla: yes

#2788 Add RUM for all Core Web Vitals metrics
  package-lock.json
  package.json
  src/lib/analytics.js
  src/lib/bootstrap.js
Labels: cla: yes

#3156 Add web-vitals tag to landing page.
  src/site/content/en/vitals/index.md
Labels: cla: yes

#2939 Fetch Metadata article for web.dev
  src/images/authors/lwe.jpg
  src/images/authors/lwe@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/fetch-metadata/cross-origin-request.png
  src/site/content/en/blog/fetch-metadata/hero.jpg
  src/site/content/en/blog/fetch-metadata/index.md
  src/site/content/en/blog/fetch-metadata/same-origin-request.png
Labels: cla: yes

#3104 QuicTransport origin trial post
  src/site/content/en/blog/quictransport/hero.jpg
  src/site/content/en/blog/quictransport/index.md
Labels: cla: yes

#2762 fix scroll-position for in-page links relative to fixed header
  src/styles/components/_header.scss
  src/styles/generic/_shared.scss
  src/styles/settings/_dimensions.scss
Labels: cla: yes

#3165 chore(gcloud): update to node 12
  app.yaml
Labels: cla: yes

#3169 Skip waiting for load event to load app.js
  src/lib/bootstrap.js
Labels: cla: yes

#3142 Fixes Chrome version mention
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes, content update

#3168 docs: add missing param in script
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
Labels: cla: yes

#3173 Move all of Workbox to 5.1.3
  package-lock.json
  package.json
Labels: cla: yes

#3141 Fix Lighthouse TTI score threshold
  src/site/content/en/lighthouse-performance/interactive/index.md
Labels: cla: yes, content update, lighthouse, performance

#3175 [prefers-color-scheme article] Remove references to `no-preference`
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#3126 Fix inconsistency in manifest file name
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes, content update, pwa

#3148 Add icon requirement for bubblewrap
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes, content update, pwa

#3192 Add links for servers
  src/site/content/en/lighthouse-pwa/redirects-http/index.md
Labels: cla: yes, content update, lighthouse, privacy/security

#3187 Fix broken link to command menu page
  src/site/content/en/fast/defer-non-critical-css/index.md
Labels: cla: yes

#3182 Update "Current status" table.
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: cla: yes, content update

#3181 [Fetch Metadata article] Improve typography
  src/site/content/en/blog/fetch-metadata/index.md
Labels: cla: yes

#3179 Update same-site/same-origin article
  src/site/content/en/secure/same-site-same-origin/index.md
Labels: cla: yes

#3193 Update the service worker audit guide
  src/site/_includes/content/reliable/workbox.njk
  src/site/content/en/lighthouse-pwa/offline-start-url/index.md
  src/site/content/en/lighthouse-pwa/service-worker/index.md
  src/site/content/en/lighthouse-pwa/works-offline/index.md
Labels: content update, lighthouse, pwa

#3201 Remove broken warning on getInstalledRelatedApps
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update, p0

#3199 Updates codeowners for PWA 11tydata.js to add petele
  .github/CODEOWNERS
Labels: cla: yes

#3205 Add link to community guidelines form.
  src/site/content/en/community-guidelines/index.md
Labels: cla: yes

#3202 Reorders topics on home & learn page
  src/site/content/en/en.11tydata.js
  src/site/content/en/learn/learn.11tydata.js
Labels: cla: yes

#3158 Add unit tests for posts-with-lighthouse collection.
  .eleventy.js
  src/site/_collections/posts-with-lighthouse.js
  test/integration/src/site/_collections/eleventy.js
  test/unit/src/site/_collections/index.js
  test/unit/src/site/_collections/posts-with-lighthouse.js
  test/unit/src/site/index.js
Labels: cla: yes

#3206 Make petele codeowner of PWA
  .github/CODEOWNERS
Labels: cla: yes

#3198 Update Web OTP article
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#3190 Add CommonJS overview to /fast
  src/site/_data/paths/fast.js
Labels: cla: yes, content update, fast, performance

#3184 [Update] Mention `minsize` value and point to full config in granular chunking article
  src/site/content/en/blog/granular-chunking-nextjs/index.md
Labels: cla: yes

#3177 [Codelab]: Prefetching in create-react-app with quicklink
  src/site/content/en/react/codelab-quicklink/cdt-blog-optimized.png
  src/site/content/en/react/codelab-quicklink/cdt-blog-unoptimized.png
  src/site/content/en/react/codelab-quicklink/cdt-home-optimized.png
  src/site/content/en/react/codelab-quicklink/cdt-home-unoptimized.png
  src/site/content/en/react/codelab-quicklink/index.md
Labels: cla: yes

#3162 [Guide]: Speed up navigations in React SPAs with quicklink
  src/site/_data/paths/react.js
  src/site/content/en/react/quicklink/hero.png
  src/site/content/en/react/quicklink/index.md
Labels: cla: yes

#3219 Fixes #3204
  src/site/_data/event.js
Labels: cla: yes

#3220 Remove talk #3208
  src/site/_data/event.js
Labels: cla: yes

#2731 Add App-like PWA article
  src/site/_data/paths/progressive-web-apps.js
  src/site/content/en/progressive-web-apps/app-like-pwas/image0.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image1.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image10.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image11.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image12.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image13.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image14.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image15.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image16.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image17.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image18.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image19.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image2.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image20.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image21.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image22.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image3.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image4.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image5.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image6.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image7.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image8.png
  src/site/content/en/progressive-web-apps/app-like-pwas/image9.png
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes

#3061 Update CrUX guides with Core Web Vitals
  src/site/content/en/fast/chrome-ux-report-bigquery/index.md
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_connector.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_cwv.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_cwv_tablet.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_device.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_ect.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_embed.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_error.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_fcp.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_lcp.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/dash_schema.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/hero.png
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/index.md
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/psi.png
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/psi_no_data.png
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/psi_origin.png
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/psi_page.png
  src/site/content/en/fast/chrome-ux-report-pagespeed-insights/psi_url.png
Labels: cla: yes, content update, performance

#3207 Update handbook guidance for YouTube component.
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#3216 Fix to "Defer non-critical CSS" guide
  src/site/content/en/fast/defer-non-critical-css/index.md
Labels: cla: yes, content update, fast, performance

#3218 Fixed the in-the-field link
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes, content update, performance

#3224 Fix typo and missing text
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes

#3227 Update WebOTP blog to clarify that "host" should be used
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#3174 Stories codelab edits
  src/site/content/en/blog/codelab-stories-component/index.md
  src/site/content/en/blog/stories-component/index.md
Labels: cla: yes

#3232 Error correction
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes

#3230 Fixed some 404 error URLs, due to branch name changes
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes

#3223 performance-scoring: tweaks for LH v6
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes, content update, lighthouse, performance

#3196 schedule modal
  src/lib/components/BaseModalElement/index.js
  src/lib/components/EventSchedule/index.js
  src/lib/components/EventScheduleModal/_styles.scss
  src/lib/components/EventScheduleModal/index.js
  src/lib/pages/live.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/styles/pages/_live.scss
Labels: cla: yes

#3245 Cache bust css.
  src/site/_includes/layout.njk
Labels: cla: yes

#3249 Add live page event data and bootstrap code.
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#3251 Add blurbs to schedule. Improve styling of live page.
  src/lib/components/EventScheduleModal/_styles.scss
  src/lib/components/EventScheduleModal/index.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
  src/styles/components/_author.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#2503 Add Text Fragments article
  src/site/content/en/blog/text-fragments/blog-red-ids.png
  src/site/content/en/blog/text-fragments/correct-text.png
  src/site/content/en/blog/text-fragments/extension.png
  src/site/content/en/blog/text-fragments/first-text.png
  src/site/content/en/blog/text-fragments/google-help.png
  src/site/content/en/blog/text-fragments/google-serp.png
  src/site/content/en/blog/text-fragments/hero.jpg
  src/site/content/en/blog/text-fragments/id-html1.png
  src/site/content/en/blog/text-fragments/id-missing.png
  src/site/content/en/blog/text-fragments/index.md
  src/site/content/en/blog/text-fragments/syntax-end-wrong.png
  src/site/content/en/blog/text-fragments/syntax-end.png
  src/site/content/en/blog/text-fragments/syntax-simple.png
  src/site/content/en/blog/text-fragments/text-feedback.png
  src/site/content/en/blog/text-fragments/text-fragments.png
  src/site/content/en/blog/text-fragments/three-text-fragments.png
Labels: cla: yes

#3258 Standardize on `capabilities` for tags
  src/site/_data/postTags.js
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/blog/badging-api/index.md
  src/site/content/en/blog/betty-crocker/index.md
  src/site/content/en/blog/contact-picker/index.md
  src/site/content/en/blog/content-indexing-api/index.md
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/get-installed-related-apps/index.md
  src/site/content/en/blog/idle-detection/index.md
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
  src/site/content/en/blog/maskable-icon/index.md
  src/site/content/en/blog/native-file-system/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/notification-triggers/index.md
  src/site/content/en/blog/periodic-background-sync/index.md
  src/site/content/en/blog/shape-detection/index.md
  src/site/content/en/blog/text-fragments/index.md
  src/site/content/en/blog/wakelock/index.md
  src/site/content/en/blog/web-otp/index.md
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/index.md
  src/site/content/en/blog/websocketstream/index.md
  src/site/content/en/blog/workbox-share-targets/index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: capabilities, cla: yes

#3240 Remove flex layout from details widget
  src/styles/components/_details.scss
Labels: cla: yes

#3246 Allow staging our sw.
  src/lib/app.js
Labels: cla: yes

#3203 Add the Milliseconds Make Millions case study
  src/images/authors/olgademidova.jpg
  src/images/authors/olgademidova@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/milliseconds-make-millions/hero.png
  src/site/content/en/blog/milliseconds-make-millions/index.md
  src/site/content/en/blog/milliseconds-make-millions/lead-gen.jpg
  src/site/content/en/blog/milliseconds-make-millions/luxury.jpg
  src/site/content/en/blog/milliseconds-make-millions/retail.jpg
  src/site/content/en/blog/milliseconds-make-millions/summary.jpg
  src/site/content/en/blog/milliseconds-make-millions/travel.jpg
Labels: cla: yes

#3236 Add overflowing thumbnail carousel.
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#3252 Update service workies game link
  src/site/content/en/reliable/service-workers-cache-storage/index.md
Labels: cla: yes

#3244 Migrates How to File A Bug from WebFu
  src/images/authors/robertnyman.jpg
  src/images/authors/robertnyman@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/blog/how-to-file-a-good-bug/index.md
Labels: cla: yes, content, new content, other, webfu-migration

#3241 [color-scheme article] Remove `light only` references completely
  src/site/content/en/blog/color-scheme/index.md
Labels: cla: yes

#3265 fix busted css build
  compile-css.js
  src/styles/generic/_all.scss
  src/styles/generic/_select.scss
Labels: cla: yes

#3262 Move language-agnostic files out of /en
  src/site/content/robots.txt
  src/site/content/sitemap.xml.njk
  test/integration/build-test.js
Labels: cla: yes

#3140 Quick and dirty player and chat embed.
  src/lib/components/LivestreamContainer/_styles.scss
  src/lib/components/LivestreamContainer/index.js
  src/lib/pages/live.js
  src/site/content/en/live/index.njk
  src/styles/components/_all.scss
  src/styles/components/_livestream-container.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#3280 Replace a Google-internal link with a public one.
  src/site/content/en/blog/web-bundles/index.md
Labels: cla: yes

#3267 feat(subscribe): add warning when javascript is disabled
  src/site/_includes/partials/subscribe.njk
Labels: cla: yes

#3176 migrating lazy-loading content
  src/site/_data/contributors.js
  src/site/_data/paths/fast.js
  src/site/content/en/blog/native-lazy-loading/lazyload.mp4
  src/site/content/en/blog/native-lazy-loading/lazyload.webm
  src/site/content/en/fast/lazy-loading-best-practices/index.md
  src/site/content/en/fast/lazy-loading-images/index.md
  src/site/content/en/fast/lazy-loading-video/index.md
  src/site/content/en/fast/lazy-loading/index.md
  src/site/content/en/fast/lazy-loading/lazy-loading-example.jpg
  src/site/content/en/fast/lazy-loading/offscreen-audit.png
  src/site/content/en/fast/native-lazy-loading/hero.png
  src/site/content/en/fast/native-lazy-loading/index.md
  src/site/content/en/fast/native-lazy-loading/range-request.png
  src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md
Labels: cla: yes

#3235 Updates to install promo content for PWAs
  src/site/content/en/progressive-web-apps/customize-install/index.md
  src/site/content/en/progressive-web-apps/install-criteria/how-does-it-work_desktop.png
  src/site/content/en/progressive-web-apps/install-criteria/how-does-it-work_mobile.png
  src/site/content/en/progressive-web-apps/install-criteria/index.md
  src/site/content/en/progressive-web-apps/promote-install/after-conversion_desktop.png
  src/site/content/en/progressive-web-apps/promote-install/after-conversion_mobile.png
  src/site/content/en/progressive-web-apps/promote-install/elevated-install_desktop.png
  src/site/content/en/progressive-web-apps/promote-install/elevated-install_mobile.png
  src/site/content/en/progressive-web-apps/promote-install/how-does-it-work_desktop.png
  src/site/content/en/progressive-web-apps/promote-install/how-does-it-work_mobile.png
  src/site/content/en/progressive-web-apps/promote-install/index.md
  src/site/content/en/progressive-web-apps/promote-install/simple-button_desktop.png
  src/site/content/en/progressive-web-apps/promote-install/simple-button_mobile-crop.png
  src/site/content/en/progressive-web-apps/promote-install/temporary-ui_desktop.png
  src/site/content/en/progressive-web-apps/promote-install/temporary-ui_mobile.png
Labels: cla: yes, content update, pwa

#3268 web-event-store for time management
  src/lib/components/EventSchedule/index.js
  src/lib/components/EventStore/index.js
  src/lib/components/EventTime/index.js
  src/lib/components/Tabs/index.js
  src/lib/pages/live.js
  src/lib/store.js
  src/lib/utils/time-offset.js
  src/site/_data/event.js
  src/site/_includes/components/EventTable.js
  src/site/content/en/live/index.njk
Labels: cla: yes

#3287 Fix EventTime. Add percy to live page.
  src/lib/components/EventTime/index.js
  tools/percy/.percy.conf.yml
  tools/percy/snapshots.js
Labels: cla: yes

#3294 Make EventStore a bit more stateless. Get LiveStream working with unistore.
  src/lib/components/EventStore/index.js
  src/lib/components/LivestreamContainer/_styles.scss
  src/lib/components/LivestreamContainer/index.js
  src/lib/store.js
Labels: cla: yes

#3304 silence require warning in compile-css
  compile-css.js
Labels: cla: yes

#3303 Fixed URL of serve-responsive-images
  src/site/content/en/blog/optimize-cls/index.md
Labels: cla: yes

#3178 Add Progressively Enhance your PWA article
  src/site/content/en/blog/progressively-enhance-your-pwa/1000000000000438000008AC945569E52CE934FA.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000000000009C400000304A19EF0FF1D72987D.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000000000009C40000039EF0A6FE5C50E42DEA.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000002E6000001C0855AA2DF1E30228C.png
  src/site/content/en/blog/progressively-enhance-your-pwa/1000020100000356000001C434F5DD5D64721768.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000003E4000008004D3AEA65DB2ABA6C.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000003E400000800AD376E3B4B3386C6.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000003E400000800D873C982E6D44C89.png
  src/site/content/en/blog/progressively-enhance-your-pwa/100002010000053C000003E8B978FE17E590BC9A.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000005800000012430B7B8786BF315DD.png
  src/site/content/en/blog/progressively-enhance-your-pwa/100002010000058C000000CA65613FEC1D7FB3E2.png
  src/site/content/en/blog/progressively-enhance-your-pwa/1000020100000640000003E810E16D93C747B2D5.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000006FC0000021AD16A28BA8F5CBF1A.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005A941A3287F1A5052A8.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DB01941257D7BE6A85.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DB0D42F493ACFD1B53.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DB39851711E3CB3BF0.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DBB930B1D3F8F5D1DA.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DBCBE1B58EC828BB29.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DBCD9D10DD0A745315.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005DBE9BF427ABD63947A.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005E0B042853D0E77C224.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005E0B042853D0E77C225.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000005FB1EF077CDF01B8588.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000006A2F58B840608CEA761.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000006A2FE8CEB5EE2FB3F83.png
  src/site/content/en/blog/progressively-enhance-your-pwa/10000201000009C4000006E8D776365D6B538C9A.png
  src/site/content/en/blog/progressively-enhance-your-pwa/android.png
  src/site/content/en/blog/progressively-enhance-your-pwa/chrome.png
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
  src/site/content/en/blog/progressively-enhance-your-pwa/safari.png
Labels: cla: yes, web.dev live

#3295 Anton's Karlovskiy profile
  src/images/authors/antonkarlovskiy.jpg
  src/images/authors/antonkarlovskiy@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/react/codelab-quicklink/index.md
  src/site/content/en/react/quicklink/index.md
Labels: cla: yes

#3305 missed unistore cleanup
  src/lib/components/EventStore/index.js
Labels: cla: yes

#3308 Origin trials blog post
  src/site/content/en/blog/origin-trials/hero.jpg
  src/site/content/en/blog/origin-trials/index.md
  src/site/content/en/blog/origin-trials/thumbnail.jpg
Labels: cla: yes

#3307 Trust Tokens blog post
  src/site/_data/postTags.js
  src/site/content/en/blog/trust-tokens/hero.jpg
  src/site/content/en/blog/trust-tokens/index.md
  src/site/content/en/blog/trust-tokens/thumbnail.jpg
Labels: cla: yes

#3255 Consolidate tags
  src/site/_includes/layout.njk
  src/site/content/en/accessible/accessible.11tydata.js
  src/site/content/en/angular/angular.11tydata.js
  src/site/content/en/discoverable/discoverable.11tydata.js
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/lighthouse-accessibility/lighthouse-accessibility.11tydata.js
  src/site/content/en/lighthouse-best-practices/lighthouse-best-practices.11tydata.js
  src/site/content/en/lighthouse-performance/lighthouse-performance.11tydata.js
  src/site/content/en/lighthouse-pwa/lighthouse-pwa.11tydata.js
  src/site/content/en/lighthouse-seo/lighthouse-seo.11tydata.js
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/index.njk
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/metrics.11tydata.js
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
  src/site/content/en/newsletter/newsletter.11tydata.js
  src/site/content/en/notifications/codelab-notifications-get-started/index.md
  src/site/content/en/notifications/codelab-notifications-push-server/index.md
  src/site/content/en/notifications/codelab-notifications-service-worker/index.md
  src/site/content/en/notifications/index.njk
  src/site/content/en/notifications/notifications.11tydata.js
  src/site/content/en/notifications/use-push-notifications-to-engage-users/index.md
  src/site/content/en/payments/android-payment-apps-overview/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/index.njk
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
  src/site/content/en/payments/payments.11tydata.js
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
  src/site/content/en/progressive-web-apps/codelab-make-installable/index.md
  src/site/content/en/progressive-web-apps/customize-install/index.md
  src/site/content/en/progressive-web-apps/define-install-strategy/index.md
  src/site/content/en/progressive-web-apps/drive-business-success/index.md
  src/site/content/en/progressive-web-apps/index.njk
  src/site/content/en/progressive-web-apps/install-criteria/index.md
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
  src/site/content/en/progressive-web-apps/promote-install/index.md
  src/site/content/en/progressive-web-apps/pwa-checklist/index.md
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/en/progressive-web-apps/what-are-pwas/index.md
  src/site/content/en/react/react.11tydata.js
  src/site/content/en/reliable/reliable.11tydata.js
  src/site/content/en/secure/codelab-same-origin-fetch/codelab-same-origin-fetch.md
  src/site/content/en/secure/codelab-same-origin-iframe/codelab-same-origin-iframe.md
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
  src/site/content/en/secure/index.njk
  src/site/content/en/secure/same-origin-policy/index.md
  src/site/content/en/secure/same-site-same-origin/index.md
  src/site/content/en/secure/secure.11tydata.js
  src/site/content/en/secure/security-attacks/index.md
  src/site/content/en/secure/security-not-scary/index.md
  src/site/content/en/vitals/vitals.11tydata.js
Labels: cla: yes

#3313 Add exterkamp to contributors.
  src/images/authors/exterkamp.jpg
  src/images/authors/exterkamp@2x.jpg
  src/site/_data/contributors.js
Labels: cla: yes

#3317 Fix error where we check for PERCY mode
  src/site/_collections/authors.js
Labels: cla: yes

#3319 Don't let carousel parent break layout.
  src/styles/pages/_live.scss
Labels: cla: yes

#3277 Add community events section to /live
  src/lib/components/EventMap/_styles.scss
  src/lib/components/EventMap/index.js
  src/lib/components/EventStore/index.js
  src/lib/pages/live.js
  src/site/_data/event.js
  src/site/_data/site.js
  src/site/content/en/live/index.njk
  src/styles/generic/_select.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#3315 Origin/webdev live ui polish
  src/lib/components/EventScheduleModal/_styles.scss
  src/lib/components/EventTime/_styles.scss
  src/styles/components/_author.scss
  src/styles/overrides/_unresolved.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#3293 List the CrUX Dash guide in the blog
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md
Labels: cla: yes

#3316 Additions and clarifications to the origin trial article.
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#3302 [Guide]: App shell UX with service workers and streams
  src/site/content/en/reliable/app-shell-ux-with-service-workers/dev-architecture.png
  src/site/content/en/reliable/app-shell-ux-with-service-workers/homepage.jpg
  src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md
Labels: cla: yes

#3300 [Guide]: Instant navigation experiences
  src/images/authors/gilbertococchi.jpg
  src/images/authors/gilbertococchi@2x.jpg
  src/site/_data/contributors.js
  src/site/content/en/reliable/instant-navigation-experiences/index.md
  src/site/content/en/reliable/instant-navigation-experiences/mercadolibre-prefetch.png
  src/site/content/en/reliable/instant-navigation-experiences/page-to-sw.png
  src/site/content/en/reliable/instant-navigation-experiences/virgilio-sport-logo.png
  src/site/content/en/reliable/instant-navigation-experiences/virgilio-sport-prefetch.png
Labels: cla: yes

#3301 [Guide]: Adaptive loading with service workers
  src/site/content/en/reliable/adaptive-loading-with-service-workers/cloudinary-workbox.png
  src/site/content/en/reliable/adaptive-loading-with-service-workers/index.md
  src/site/content/en/reliable/adaptive-loading-with-service-workers/terra-adaptive-amp.png
  src/site/content/en/reliable/adaptive-loading-with-service-workers/terra-adaptive-images.png
Labels: cla: yes

#3260 [Codelab]: Building a resilient search experience with Workbox
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/index.md
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/offline-ux-custom.png
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/offline-ux-default.png
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/offline-ux-flow.png
Labels: cla: yes

#3248 [Guide]: Resilient search experiences
  src/site/_data/paths/reliable.js
  src/site/content/en/reliable/resilient-search-experiences/index.md
  src/site/content/en/reliable/resilient-search-experiences/search-offline-flow.png
  src/site/content/en/reliable/resilient-search-experiences/search-offline-screen.png
  src/site/content/en/reliable/resilient-search-experiences/workbox-background-sync.png
Labels: cla: yes

#3333 Add tags and fix date for advanced PWA collection
  src/site/content/en/reliable/adaptive-loading-with-service-workers/index.md
  src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/index.md
  src/site/content/en/reliable/instant-navigation-experiences/index.md
  src/site/content/en/reliable/resilient-search-experiences/index.md
Labels: cla: yes

#3334 Update Trust Tokens article
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#3306 Control video tiles carousel
  src/lib/components/EventCarousel/index.js
  src/lib/components/EventSchedule/index.js
  src/lib/components/EventStore/index.js
  src/lib/pages/live.js
  src/lib/utils/time-offset.js
  src/site/_data/event.js
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#3349 Update time for day 3.
  src/site/_data/event.js
Labels: cla: yes

#3238 Metrics updates
  src/site/_includes/content/metrics/performance-observer-init.njk
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
Labels: cla: yes

#3288 Updates serve modern code to include bugfixes property
  src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md
Labels: cla: yes

#3284 Flex gap proper release
  src/site/content/en/blog/flexbox-gap/index.md
Labels: cla: yes

#3310 [Wake Lock article] Add launched info
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#3342 [Fugu Status] Move wake lock to launched section
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#3343 Origin Trials wording tweaks
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#3347 [chore] Fix typo (use plural)
  src/site/content/en/vitals/index.md
Labels: cla: yes, content update, performance

#3358 hashes JS/CSS source
  .eleventy.js
  .gitignore
  build-sw.js
  build.js
  compile-css.js
  package.json
  src/build/common.js
  src/build/hash.js
  src/build/minify-js.js
  src/lib/sw.js
  src/site/_includes/layout.njk
  test/integration/build-test.js
Labels: cla: yes

#3359 disable web.dev/LIVE partial to force online-only
  src/site/_transforms/service-worker-partials/index.js
  test/integration/build-test.js
Labels: cla: yes

#3351 Add author images for rkochman
  src/images/authors/rkochman.jpg
  src/images/authors/rkochman@2x.jpg
Labels: cla: yes

#3364 always write dist/app.css
  compile-css.js
Labels: cla: yes

#3360 [Wake Lock article] Add link to Betty Crocker case study
  src/site/content/en/blog/wakelock/index.md
Labels: cla: yes

#3353 Add Google Search debugging guide
  src/site/_data/paths/discoverable.js
  src/site/content/en/blog/google-search-tools/core-web-vitals.png
  src/site/content/en/blog/google-search-tools/coverage.png
  src/site/content/en/blog/google-search-tools/hero.png
  src/site/content/en/blog/google-search-tools/index.md
  src/site/content/en/blog/google-search-tools/lighthouse.png
  src/site/content/en/blog/google-search-tools/mobile-friendly-test.png
  src/site/content/en/blog/google-search-tools/thumbnail.png
  src/site/content/en/blog/google-search-tools/url-inspection-tool.png
Labels: cla: yes

#3344 Added hero image dimensions to _template-post
  src/site/_drafts/_template-post/index.md
Labels: cla: yes

#3340 Update styles for isPreEvent, isDuringEvent, and isPostEvent phases
  src/lib/components/EventMap/_styles.scss
  src/lib/components/LivestreamContainer/_styles.scss
  src/lib/components/LivestreamContainer/index.js
  src/site/_data/event.js
  src/site/content/en/live/index.njk
  src/styles/components/_livestream-container.scss
  src/styles/generic/_shared.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#3373 fix(rss): fix author title in feeds, fixes #3365
  src/site/content/en/authors/feed.njk
  src/site/content/en/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#3321 CrUX API announcement
  src/site/content/en/fast/chrome-ux-report-api/hero.png
  src/site/content/en/fast/chrome-ux-report-api/index.md
Labels: cla: yes, new content, performance

#3379 Add q and a section.
  src/lib/components/EventMap/_styles.scss
  src/lib/components/EventQandA/_styles.scss
  src/lib/components/EventQandA/index.js
  src/lib/pages/live.js
  src/site/_data/event.js
  src/site/content/en/live/index.njk
  src/styles/pages/_live.scss
Labels: cla: yes

#3380 List CrUX API guide on /fast
  src/site/_data/paths/fast.js
Labels: cla: yes

#3367 Add tooling.report announcement
  src/site/_data/postTags.js
  src/site/content/en/blog/introducing-tooling-report/hero.jpg
  src/site/content/en/blog/introducing-tooling-report/index.md
  src/site/content/en/blog/introducing-tooling-report/overview.jpg
Labels: cla: yes

#3370 Sign-in form best practice article and codelab
  src/site/content/en/blog/codelab-sign-in-form-best-practices/email-keyboard.png
  src/site/content/en/blog/codelab-sign-in-form-best-practices/index.md
  src/site/content/en/blog/sign-in-form-best-practices/amazon-signin-mobile.png
  src/site/content/en/blog/sign-in-form-best-practices/amazon-signin.png
  src/site/content/en/blog/sign-in-form-best-practices/autofocus.png
  src/site/content/en/blog/sign-in-form-best-practices/chrome-signin-desktop.png
  src/site/content/en/blog/sign-in-form-best-practices/firefox-password-manager.png
  src/site/content/en/blog/sign-in-form-best-practices/hero.jpg
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/sign-in-form-best-practices/invalid-email.png
  src/site/content/en/blog/sign-in-form-best-practices/iphone-keyboard.png
  src/site/content/en/blog/sign-in-form-best-practices/keyboard-not-ok.png
  src/site/content/en/blog/sign-in-form-best-practices/keyboard-ok.png
  src/site/content/en/blog/sign-in-form-best-practices/label-position.png
  src/site/content/en/blog/sign-in-form-best-practices/missing-field-firefox-android.png
  src/site/content/en/blog/sign-in-form-best-practices/safari-password-suggest.png
  src/site/content/en/blog/sign-in-form-best-practices/safari-password-suggestion.png
  src/site/content/en/blog/sign-in-form-best-practices/safari-signin-desktop.png
  src/site/content/en/blog/sign-in-form-best-practices/show-password-google.png
  src/site/content/en/blog/sign-in-form-best-practices/show-password.png
  src/site/content/en/blog/sign-in-form-best-practices/styled-signin-form.png
  src/site/content/en/blog/sign-in-form-best-practices/unstyled-form-text.png
  src/site/content/en/blog/sign-in-form-best-practices/unstyled-form.png
Labels: cla: yes

#3385 Rev vitals talk title.
  src/site/_data/event.js
Labels: cla: yes

#3387 Small improvements to get our lh scores up.
  src/lib/components/EventTime/_styles.scss
  src/lib/components/LivestreamContainer/index.js
  src/site/content/en/live/index.njk
  src/styles/components/_subscribe.scss
Labels: cla: yes

#3391 Make select look all pretty and stuff.
  src/site/_includes/partials/subscribe.njk
  src/styles/components/_subscribe.scss
  src/styles/generic/_forms.scss
  src/styles/generic/_select.scss
Labels: cla: yes

#3392 fallback to loading other css/js
  server.js
Labels: cla: yes

#3393 Tweak html to test caching.
  src/site/content/en/live/index.njk
Labels: cla: yes

#3386 Fix typo
  .github/stale.yml
Labels: cla: yes

#3381 support no-hash in dev for css, better source map support, cleanup 'dev' use
  .eleventy.js
  README.md
  compile-css.js
  package.json
  server.js
  src/site/_collections/hooks/utils.js
  test/integration/build-test.js
  test/integration/src/site/_collections/index.js
Labels: cla: yes

#3346 User-Agent Client Hints blog
  src/site/content/en/blog/user-agent-client-hints/index.md
  src/site/content/en/blog/user-agent-client-hints/uach-hero.jpg
  src/site/content/en/blog/user-agent-client-hints/uach-thumbnail.jpg
Labels: blog, cla: yes, privacy/security

#3401 Updated photo credit for sign-in form post
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes, content update

#3375 Use standard idoms and language for flags and origin trials.
  src/site/content/en/blog/hands-on-portals/index.md
Labels: capabilities, cla: yes, content update

#3382 Fix Typo - add missing space
  src/site/content/en/blog/commonjs-larger-bundles/index.md
Labels: cla: yes

#3397 Fix typo.
  src/site/content/en/blog/service-worker-mindset/index.md
Labels: cla: yes, content update, pwa

#3400 Update index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes, content update, pwa

#3384 Mention PWABuilder support for app shortcuts
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes, content update

#3292 Update Optimize FID guide
  src/site/content/en/blog/optimize-fid/index.md
Labels: cla: yes, content update, performance
