Repository GoogleChrome/web.dev, pull requests merged in 2020-03, with the labels that each got.

#2255 Terser rollup comment and dev/production
  build.js
  package-lock.json
  package.json
Labels: cla: yes

#2244 clear scroll restoration before unload
  src/lib/utils/router.js
Labels: cla: yes

#2271 Clarify that the p75 threshold is for mobile users
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
Labels: cla: yes

#2278 Take down mdn banner.
  src/site/_data/site.js
Labels: cla: yes

#2277 Add missing meta theme-color
  src/site/_includes/layout.njk
Labels: cla: yes

#2276 Add rel="noreferrer" to twitter share button
  src/lib/components/Actions/index.js
Labels: cla: yes

#2280 remove noisy warning
  src/site/_filters/html-date-string.js
Labels: cla: yes

#2282 Rev updated fields for metrics docs.
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
Labels: cla: yes

#2235 Snap after layout blog post
  src/site/_data/contributors.js
  src/site/content/en/blog/snap-after-layout/css-scroll-snap-example.png
  src/site/content/en/blog/snap-after-layout/index.md
  src/site/content/en/images/authors/alsan.jpg
  src/site/content/en/images/authors/alsan@2x.jpg
  src/site/content/en/images/authors/yigu.jpg
  src/site/content/en/images/authors/yigu@2x.jpg
Labels: cla: yes

#2260 native lazy loading support stats
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes

#2261 [Shape Detection article] Add launch information for barcode detection
  src/site/content/en/blog/shape-detection/index.md
Labels: capabilities, cla: yes

#2263 Enhance feature detection description.
  src/site/content/en/blog/vr-comes-to-the-web/index.md
  src/site/content/en/reliable/service-workers-cache-storage/index.md
Labels: capabilities, cla: yes

#2270 Make caches named & bounded
  src/lib/sw.js
Labels: cla: yes

#2245 ships CSS-in-JS as part of each Web Component's dep graph
  build.js
  compile-css.js
  src/lib/components/Codelab/index.js
  src/lib/components/CopyCode/_styles.scss
  src/lib/components/CopyCode/index.js
  src/lib/components/Header/index.js
  src/lib/components/LighthouseGauge/index.js
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/LighthouseScoresMeta/_styles.scss
  src/lib/components/LighthouseScoresMeta/index.js
  src/lib/components/LighthouseScoresMetrics/index.js
  src/lib/components/LighthouseScoresStats/index.js
  src/lib/components/ProfileSwitcher/index.js
  src/lib/components/ProgressBar/index.js
  src/lib/components/Search/index.js
  src/lib/components/SideNav/_styles.scss
  src/lib/components/SideNav/index.js
  src/lib/components/SigninButton/index.js
  src/lib/components/Snackbar/index.js
  src/lib/components/SnackbarContainer/_styles.scss
  src/lib/components/SnackbarContainer/index.js
  src/lib/components/SparklineChart/index.js
  src/lib/components/Tabs/index.js
  src/lib/components/UrlChooser/_styles.scss
  src/lib/components/UrlChooser/index.js
  src/lib/components/_all.scss
  src/site/_includes/layout.njk
  src/styles/all.scss
  src/styles/components/_all.scss
  src/styles/components/_header.scss
Labels: cla: yes

#2273 Update chrome flag for Web NFC
  src/site/content/en/blog/nfc/chrome-flag.jpg
  src/site/content/en/blog/nfc/chrome-flag.png
  src/site/content/en/blog/nfc/index.md
Labels: capabilities, cla: yes

#2254 generate/serve partials
  .eleventy.js
  build.js
  netlify.toml
  package.json
  server.js
  src/lib/loader.js
  src/lib/sw.js
  src/lib/utils/meta.js
  src/lib/utils/sw-match.js
  src/site/_includes/layout.njk
  src/site/_utils/build-partial.js
  src/site/content/sw-partial-layout.njk
Labels: cla: yes

#2305 Fix #2302
  src/site/content/en/handbook/index.njk
Labels: cla: yes

#2288 Add stale-while-revalidate ads performance case study blog post
  src/site/content/en/blog/ads-case-study-stale-while-revalidate/change-in-number-of-ad-script-loads-vs-ad-script-load-time.svg
  src/site/content/en/blog/ads-case-study-stale-while-revalidate/hero.jpg
  src/site/content/en/blog/ads-case-study-stale-while-revalidate/index.md
  src/site/content/en/blog/ads-case-study-stale-while-revalidate/thumbnail.jpg
Labels: cla: yes

#2281 Add linter for wiki MDN links
  .remarkrc.js
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
  src/site/content/en/blog/web-ar/index.md
  tools/linting/bad-urls.js
Labels: cla: yes

#2297 fix watch js/css after css-in-js flip
  package.json
Labels: cla: yes

#2252 Mention `DO NOT MERGE` label in PR template
  .github/pull_request_template.md
Labels: cla: yes

#2298 Add aria-label for CopyCode button
  src/lib/components/CopyCode/index.js
Labels: cla: yes

#2295 explode when using an invalid author
  src/site/_collections/paginated-posts-by-author.js
Labels: cla: yes

#2308 fix hamburger shift on desktop
  src/styles/components/_header.scss
Labels: cla: yes

#2309 fixes title generation issues re: Service Worker and partials
  src/lib/sw.js
  src/site/_includes/components/Meta.js
  src/site/_includes/layout.njk
  src/site/_utils/build-partial.js
Labels: cla: yes

#2313 fix 404
  src/site/content/en/blog/web-ar/index.md
Labels: cla: yes

#2258 feat(canonical): add support for canonical tags on pages, fixes #1035, fixes #2204
  src/site/_includes/components/Meta.js
Labels: cla: yes

#2320 Add accessible focus ring to w-button
  src/styles/components/_buttons.scss
Labels: cla: yes

#2314 fix another 404
  src/site/content/en/fast/efficiently-load-third-party-javascript/index.md
Labels: cla: yes

#2259 New content: Fixing website speed cross-functionally
  src/site/_data/contributors.js
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/fixing-website-speed-cross-functionally/index.md
  src/site/content/en/images/authors/lchansson.jpg
  src/site/content/en/images/authors/lchansson@2x.jpg
Labels: DO NOT MERGE, cla: no, content, fast

#2284 Add dates to status page
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#2318 Update outdated link URL
  src/site/content/en/lighthouse-pwa/apple-touch-icon/index.md
Labels: cla: yes

#2315 Update Module Workers article with Shared Workers section
  src/site/content/en/blog/module-workers/index.md
Labels: Chrome 82, cla: yes, content

#2325 Add segmention rec for mobile and desktop
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes, content, performance

#2338 Add redirect for /pwa/ to PWA content
  src/site/content/en/_redirects.yaml
Labels: cla: yes

#1720 Make ul bullet color match text color
  src/styles/generic/_lists.scss
Labels: cla: yes

#2157 feat(SignPost): add SignPost for pages in collections, fixes #1193
  .eleventy.js
  src/site/_collections/post-to-collections.js
  src/site/_includes/components/SignPosts.js
  src/site/_includes/partials/post.njk
  src/styles/components/_article-header.scss
  src/styles/pages/_post.scss
Labels: cla: yes

#2345 remove a left-over smart quote
  src/site/content/en/blog/css-props-and-vals/index.md
Labels: cla: yes

#2349 New content: How to set up SXG
  src/site/_data/contributors.js
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/sxg-check.png
  src/site/content/en/images/authors/kumagi.jpg
  src/site/content/en/images/authors/kumagi@2x.jpg
Labels: cla: yes

#2352 New content: Distributing SXG
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/anchor.png
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/linking.png
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/rewritten.png
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes

#2333 cache partials for PWA readyness
  src/lib/bootstrap.js
  src/lib/loader.js
  src/lib/sw.js
Labels: cla: yes

#2310 Add Media Session article
  src/site/content/en/blog/media-session/contexts.jpg
  src/site/content/en/blog/media-session/hero.jpg
  src/site/content/en/blog/media-session/index.md
  src/site/content/en/blog/media-session/thumbnail.jpg
  src/site/content/en/blog/media-session/tldr.jpg
Labels: cla: yes, media

#2290 Updates to getInstalledRelatedApps for m81 and 82
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: Chrome 81, Chrome 82, capabilities, cla: yes, pwa

#2312 Add missing "await" to chooseFileSystemEntries
  src/site/content/en/blog/native-file-system/index.md
Labels: capabilities, cla: yes

#2357 Fix 404 in first contentful paint article
  src/site/content/en/metrics/fcp/index.md
Labels: cla: yes, content, content update, performance

#2359 [Wake Lock article] Make releasing options clearer
  src/site/content/en/blog/wakelock/index.md
Labels: capabilities, cla: yes

#2229 Update Tabs component [Self-assessments]
  src/lib/components/BaseElement/index.js
  src/lib/components/Tabs/_styles.scss
  src/lib/components/Tabs/index.js
  src/lib/utils/check-overflow.js
  src/lib/utils/generate-salt.js
  src/site/_includes/components/Tab.js
  src/styles/generic/_code.scss
  src/styles/settings/_colors.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#2356 Lazy load Google Developers footer image
  src/site/_includes/devsite/devsite-footer.njk
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#2362 fix autoformat
  src/site/_data/contributors.js
Labels: cla: yes

#2348 upgrade to Algolia SDK 4+
  package-lock.json
  package.json
  src/lib/components/Search/index.js
Labels: cla: yes

#2350 encode url
  src/lib/components/LighthouseScoresMeta/index.js
Labels: cla: yes

#2353 cache JS in SW payload
  build.js
Labels: cla: yes

#2339 use explicit path.join rather than passing slash to fs.readFile
  build.js
Labels: cla: yes

#2363 Deeplinks
  src/lib/loader.js
  src/lib/utils/abort-controller-polyfill.js
  src/lib/utils/router.js
Labels: cla: yes

#2371 Set dimensions on footer lazyloaded image
  src/site/_includes/devsite/devsite-footer.njk
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#2303 Update the name of the SMS Receiver API WebOTP API and revise supporting material
  src/site/content/en/_redirects.yaml
  src/site/content/en/blog/web-otp/diagram.png
  src/site/content/en/blog/web-otp/hero.png
  src/site/content/en/blog/web-otp/index.md
Labels: DO NOT MERGE, capabilities, cla: yes

#2354 Fix search widget accessibility issues
  src/lib/components/Search/index.js
Labels: cla: yes

#2369 feat(stripTitle): add filter to remove forbidden characters from string, fixes #1993
  .eleventy.js
  src/site/_filters/strip.js
  src/site/_includes/components/Meta.js
  src/site/_utils/build-partial.js
Labels: cla: yes

#2373 Revert "upgrade to Algolia SDK 4+ (#2348)"
  package-lock.json
  package.json
  src/lib/components/Search/index.js
Labels: cla: yes

#2376 fix(measure): disable report downloads, fixes #1224
  src/lib/components/LighthouseScoresMeta/index.js
Labels: cla: yes

#2375 upgrade Algolia in search and index
  build.js
  index-algolia.js
  package-lock.json
  package.json
  src/lib/components/Search/index.js
Labels: cla: yes

#2321 Update Badging article for stable version.
  src/site/content/en/blog/badging-api/index.md
  src/site/content/en/blog/fugu-status/index.md
Labels: Chrome 82, cla: yes, new content

#2360 [Notification Triggers article] Add hero image
  src/site/content/en/blog/notification-triggers/hero.jpg
  src/site/content/en/blog/notification-triggers/index.md
Labels: capabilities, cla: yes

#2306 "Optimize CSS background images with media queries" guide
  src/site/content/en/fast/fast.11tydata.js
  src/site/content/en/fast/optimize-css-background-images-with-media-queries/cdt-background-optimized.png
  src/site/content/en/fast/optimize-css-background-images-with-media-queries/cdt-background-unoptimized.png
  src/site/content/en/fast/optimize-css-background-images-with-media-queries/index.md
Labels: cla: yes

#2366 [Media Session API article] Fix typo
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes, content update

#2367 Post-OT updates to the PBS article
  src/site/content/en/blog/periodic-background-sync/index.md
Labels: capabilities, cla: yes, content update

#2381 Fix typo
  src/site/content/en/blog/nfc/index.md
Labels: capabilities, cla: yes, content update

#2382 Minor fixes
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes, content update, privacy/security

#2361 Fix internal dead URLs
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
  src/site/content/en/blog/native-file-system/index.md
  src/site/content/en/blog/next-gen-css-2019/index.md
  src/site/content/en/fast/chrome-ux-report-data-studio-dashboard/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-sample-app/index.md
Labels: cla: yes

#2387 Add "Label" web.dev component
  .eleventy.js
  src/site/_includes/components/Label.js
  src/site/content/en/blog/module-workers/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_all.scss
  src/styles/components/_label.scss
Labels: cla: yes

#2396 Fix images and focus management in loader.js
  src/lib/loader.js
Labels: cla: yes

#2398 Fix formatting of 11ty file to make prettier happy.
  src/site/content/en/fast/fast.11tydata.js
Labels: cla: yes

#2397 Fix warning in Firefox related to querying null
  src/lib/utils/router.js
Labels: cla: yes

#2393 [Async Clipboard article] Remove superfluous try...catch block
  src/site/content/en/blog/image-support-for-async-clipboard/index.md
Labels: capabilities, cla: yes

#2389 hide Glitch on codelabs on mobile
  src/lib/components/Codelab/_styles.scss
  src/lib/components/Codelab/index.js
Labels: cla: yes

#2340 Fix external dead URLs
  src/site/content/en/blog/a11y-tips-for-web-dev/index.md
  src/site/content/en/blog/ar-hit-test/index.md
  src/site/content/en/blog/perception-toolkit/index.md
  src/site/content/en/blog/vr-comes-to-the-web/index.md
  src/site/content/en/handbook/contributor-profile/index.md
  src/site/content/en/lighthouse-accessibility/audio-caption/index.md
  src/site/content/en/lighthouse-accessibility/duplicate-id/index.md
  src/site/content/en/reliable/workbox/index.md
Labels: cla: yes

#2399 simplify var
  src/lib/loader.js
Labels: cla: yes

#2377 reorder caching so images are cached after 1st load
  src/lib/sw.js
Labels: cla: yes

#2411 fix router not setting correct URL on failure
  src/lib/utils/router.js
Labels: cla: yes

#2191 Add disclaimer banner to translated posts.
  .eleventy.js
  locale-handler.js
  src/lib/utils/locale.js
  src/site/_data/site.js
  src/site/_filters/gitlocalize-link.js
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/pl.11tydata.js
  src/styles/components/_banner.scss
Labels: cla: yes, i18n

#2414 Revert "Add disclaimer banner to translated posts. (#2191)"
  .eleventy.js
  locale-handler.js
  src/lib/utils/locale.js
  src/site/_data/site.js
  src/site/_filters/gitlocalize-link.js
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/pl.11tydata.js
  src/styles/components/_banner.scss
Labels: cla: yes

#2413 Move locale.js to backend directory
  locale-handler.js
  shared/locale.js
  src/lib/utils/router.js
  src/site/_data/site.js
  src/site/_filters/gitlocalize-link.js
Labels: cla: yes

#2383 Account for index.json partial files when serving localized content
  locale-handler.js
Labels: cla: yes

#2419 Fixed typo
  src/site/content/en/lighthouse-accessibility/meta-viewport/index.md
Labels: cla: yes

#2423 Readd translations banner
  .eleventy.js
  build.js
  karma.conf.js
  src/lib/components/LighthouseGauge/test.js
  src/lib/test/index.js
  src/site/_data/site.js
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/en/handbook/markup-post-codelab/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/pl.11tydata.js
  src/styles/components/_banner.scss
Labels: cla: yes

#2230 Add Assessment component [Self-assessments]
  .eleventy.js
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/Assessment/_styles.scss
  src/lib/components/Assessment/index.js
  src/lib/components/BaseModalElement/_styles.scss
  src/lib/components/BaseModalElement/index.js
  src/lib/components/Tabs/_styles.scss
  src/lib/components/Tabs/index.js
  src/lib/loader.js
  src/lib/pages/default.js
  src/lib/store.js
  src/site/_drafts/_template-self-assessment/bigbird.jpg
  src/site/_drafts/_template-self-assessment/cookiemonster.jpg
  src/site/_drafts/_template-self-assessment/elmo.jpg
  src/site/_drafts/_template-self-assessment/ernie.jpg
  src/site/_drafts/_template-self-assessment/grover.jpg
  src/site/_drafts/_template-self-assessment/index.md
  src/site/_drafts/_template-self-assessment/my-first-self-assessment.assess.yml
  src/site/_drafts/_template-self-assessment/webby.png
  src/site/_filters/md-block.js
  src/site/_includes/components/Assessment.js
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/handbook/self-assessment-components/bigbird.jpg
  src/site/content/en/handbook/self-assessment-components/cookiemonster.jpg
  src/site/content/en/handbook/self-assessment-components/elmo.jpg
  src/site/content/en/handbook/self-assessment-components/ernie.jpg
  src/site/content/en/handbook/self-assessment-components/grover.jpg
  src/site/content/en/handbook/self-assessment-components/index.md
  src/site/content/en/handbook/self-assessment-components/self-assessment.assess.yml
  src/site/content/en/handbook/self-assessment-components/webby.png
  src/styles/components/_callouts.scss
  src/styles/tools/_breakpoints.scss
Labels: cla: yes

#2424 Disable lazy loaded images when percy runs.
  .eleventy.js
  package-lock.json
  package.json
  src/site/_transforms/disable-lazy-load.js
  tools/percy/snapshots.js
Labels: cla: yes

#2427 fix SW redirect and normalizing URLs
  src/lib/components/LighthouseGauge/test.js
  src/lib/loader.js
  src/lib/sw.js
  src/lib/test/index.js
  src/lib/urls-test.js
  src/lib/urls.js
Labels: cla: yes

#2435 Remove staging action as its having cred issues and is making PRs fail.
  .github/workflows/gcloud-staging.yml
Labels: cla: yes

#2372 Draft article for Trusted Types
  src/site/_data/contributors.js
  src/site/content/en/blog/trusted-types/hero.png
  src/site/content/en/blog/trusted-types/index.md
  src/site/content/en/images/authors/koto.jpg
  src/site/content/en/images/authors/koto@2.jpg
Labels: cla: yes

#2378 Add try/catch blocks for better cross-browser support
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/custom-metrics/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#2374 adds article for preloading optional fonts
  src/site/content/en/blog/preload-optional-fonts/hero.jpg
  src/site/content/en/blog/preload-optional-fonts/index.md
  src/site/content/en/blog/preload-optional-fonts/new-behavior-fail.png
  src/site/content/en/blog/preload-optional-fonts/new-behavior-pass.png
  src/site/content/en/blog/preload-optional-fonts/previous-behavior-fail.png
  src/site/content/en/blog/preload-optional-fonts/previous-behavior-pass.png
Labels: cla: yes

#2388 Adds "Using a PWA in your Android app" article
  src/site/_data/contributors.js
  src/site/content/en/images/authors/andreban.jpg
  src/site/content/en/images/authors/andreban@2x.jpg
  src/site/content/en/progressive-web-apps/progressive-web-apps.11tydata.js
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/lh-score.png
Labels: cla: yes, content, pwa

#2421 adds note on iframe and auto value not being in spec
  src/site/content/en/blog/native-lazy-loading/index.md
Labels: cla: yes, content, performance

#2394 update the AR Hit Test article.
  src/site/content/en/blog/ar-hit-test/index.md
Labels: cla: yes, content update, media

#2430 Fix broken HTML
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#2432 Set origin trial URL for Web NFC
  src/site/content/en/blog/nfc/index.md
Labels: capabilities, cla: yes, content update

#2401 update web-codelab and include notice on mobile
  build.js
  src/lib/components/Codelab/_styles.scss
  src/lib/components/Codelab/index.js
  src/site/_includes/codelab.njk
  src/styles/generic/_page.scss
  src/styles/pages/_all.scss
  src/styles/pages/_codelab.scss
  tools/percy/snapshots.js
Labels: cla: yes

#2440 fix not clearing hash on nav
  src/lib/utils/router.js
Labels: cla: yes

#2355 Deprecate audio-caption accessibility audit
  src/site/content/en/lighthouse-accessibility/audio-caption/index.md
Labels: cla: yes

#2426 Add multiple-choice questions [Self-assessments]
  src/lib/components/Assessment/_styles.scss
  src/lib/components/Assessment/index.js
  src/lib/components/AssessmentQuestion/_styles.scss
  src/lib/components/AssessmentQuestion/index.js
  src/lib/components/BaseResponseElement/_styles.scss
  src/lib/components/BaseResponseElement/index.js
  src/lib/components/ResponseMultipleChoice/_styles.scss
  src/lib/components/ResponseMultipleChoice/index.js
  src/lib/components/SelectGroup/_styles.scss
  src/lib/components/SelectGroup/index.js
  src/lib/components/Tabs/index.js
  src/lib/pages/default.js
  src/site/_drafts/_template-self-assessment/my-first-self-assessment.assess.yml
  src/site/content/en/handbook/self-assessment-components/bigbird.jpg
  src/site/content/en/handbook/self-assessment-components/cookiemonster.jpg
  src/site/content/en/handbook/self-assessment-components/elmo.jpg
  src/site/content/en/handbook/self-assessment-components/ernie.jpg
  src/site/content/en/handbook/self-assessment-components/grover.jpg
  src/site/content/en/handbook/self-assessment-components/index.md
  src/site/content/en/handbook/self-assessment-components/self-assessment.assess.yml
  src/site/content/en/handbook/self-assessment-components/webby.png
Labels: cla: yes

#2441 Add WebSocketStream article
  src/site/content/en/blog/websocketstream/hero.jpg
  src/site/content/en/blog/websocketstream/index.md
Labels: cla: yes

#2453 remove mkdirp
  compile-css.js
  package-lock.json
  package.json
Labels: cla: yes

#2431 Link actual Web Share Target demo
  src/site/content/en/blog/web-share-target/index.md
Labels: capabilities, cla: yes, content update

#2444 Add think-and-check
  .eleventy.js
  src/lib/components/ResponseThinkAndCheck/_styles.scss
  src/lib/components/ResponseThinkAndCheck/index.js
  src/lib/pages/default.js
  src/site/_drafts/_template-self-assessment/index.md
  src/site/_includes/components/AssessmentCallout.js
  src/site/_includes/components/AssessmentHint.js
  src/site/_includes/components/Tab.js
  src/site/_includes/components/Tabs.js
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/control-focus-with-tabindex/self-assessment.assess.yml
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/self-assessment.assess.yml
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/accessible/use-semantic-html/self-assessment.assess.yml
  src/site/content/en/handbook/self-assessment-components/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/secure/same-origin-policy/index.md
  src/site/content/en/secure/same-origin-policy/self-assessment.assess.yml
  src/site/content/pl/accessible/control-focus-with-tabindex/index.md
  src/site/content/pl/accessible/control-focus-with-tabindex/self-assessment.assess.yml
Labels: cla: yes

#2460 Add node_modules caching to speed up Actions.
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#2438 Migrate the "Read local files" guide from H5R
  src/site/content/en/blog/read-files/index.md
Labels: cla: yes, frontend, new content

#2459 Make tabs selectable on mobile
  src/lib/components/Tabs/index.js
Labels: cla: yes

#2458 Get us a 100 accessibility score on the homepage.
  src/site/_includes/components/PostCard.js
  src/site/content/en/blog/preload-optional-fonts/index.md
Labels: cla: yes

#2457 Revert "Link actual Web Share Target demo"
  src/site/content/en/blog/web-share-target/index.md
Labels: cla: yes

#2466 Auto-update updated field on commits.
  .huskyrc
  package-lock.json
  package.json
  tools/update-updated/index.js
Labels: cla: yes

#2465 Redirect focus on incorrect question submit
  src/lib/components/AssessmentQuestion/index.js
Labels: cla: yes

#2464 Fix dup focus rings on icon buttons
  src/styles/components/_buttons.scss
Labels: cla: yes

#2478 Add staging check to ci.
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#2264 Privacy sandbox: intro/overview blog post draft
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: DO NOT MERGE, cla: yes

#2486 Remove duplicate eslintrc.
  .eslintrc
Labels: cla: yes
