Repository GoogleChrome/web.dev, pull requests merged in 2020-04, with the labels that each got.

#2418 Add cross-browser support section to SameSite recipes
  src/site/content/en/blog/samesite-cookie-recipes/index.md
Labels: cla: yes, content update, privacy/security

#2479 Blog post: "Fix an overloaded server"
  src/site/content/en/blog/overloaded-server/effective-use-of-cdn.jpg
  src/site/content/en/blog/overloaded-server/index.md
Labels: cla: yes

#2437 fix: Typo in article title
  src/site/content/en/blog/preload-optional-fonts/index.md
Labels: cla: yes

#2480 [Shape Detection] Update launch info: 82 → 83
  src/site/content/en/blog/shape-detection/index.md
Labels: cla: yes, content update

#2496 Add hero image notice.
  src/site/_drafts/_template-case-study/index.md
  src/site/_drafts/_template-post/index.md
  src/site/content/en/handbook/markup-media/index.md
Labels: cla: yes

#2497 Add hero image to overloaded-server post
  src/site/content/en/blog/overloaded-server/hero.jpg
  src/site/content/en/blog/overloaded-server/index.md
Labels: cla: yes

#2485 Add horizontal scrollbar on tables.
  src/lib/components/Codelab/_styles.scss
  src/site/content/en/blog/fast-ads-matter/index.md
  src/site/content/en/fast/codelab-density-descriptors/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/generic/_lists.scss
  src/styles/generic/_shared.scss
  src/styles/generic/_tables.scss
  src/styles/settings/_dimensions.scss
  tools/percy/snapshots.js
Labels: cla: yes

#2498 Clean up percy.
  src/site/_data/site.js
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#2502 Task/add integration test
  package.json
  test/index.js
  test/integration/build-test.js
  test/integration/index.js
Labels: cla: yes

#2506 Fix 'September' typo
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#2492 Module Workers release: m82 -> m83
  src/site/content/en/blog/module-workers/index.md
Labels: cla: yes

#2507 Mention Lighthouse SEO audits and remove comment
  src/site/content/en/blog/covid19/index.md
Labels: cla: yes, content update, discoverable

#2520 Update A/B testing & personalization guidance
  src/site/content/en/blog/covid19/index.md
Labels: cla: yes, content update, performance

#2482 Update the Launch field for Content Indexing
  src/site/content/en/blog/content-indexing-api/index.md
Labels: DO NOT MERGE, capabilities, cla: yes

#2491 Update release version for optional fonts article
  src/site/content/en/blog/preload-optional-fonts/index.md
Labels: cla: yes, content update

#2495 Change Chrome 82 to Chrome 83 in getInstalledRelatedApps article.
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update

#2518 Hide post card image from screen readers.
  src/site/_includes/components/PostCard.js
Labels: cla: yes

#2481 Add color-scheme article
  src/site/content/en/blog/color-scheme/dark-computed.png
  src/site/content/en/blog/color-scheme/dark-styles.png
  src/site/content/en/blog/color-scheme/demo-dark.png
  src/site/content/en/blog/color-scheme/demo-light.png
  src/site/content/en/blog/color-scheme/hero.jpg
  src/site/content/en/blog/color-scheme/index.md
  src/site/content/en/blog/color-scheme/light-buttonface.png
  src/site/content/en/blog/color-scheme/light-computed.png
  src/site/content/en/blog/color-scheme/light-styles.png
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes, new content

#2533 Privacy Sandbox post
  src/site/content/en/_redirects.yaml
  src/site/content/en/blog/digging-into-the-privacy-sandbox/hero.jpg
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: cla: yes

#2528 Migrate the webfu promises guide to web.dev/promises
  src/site/content/en/blog/promises/index.md
  src/site/content/en/blog/promises/promise-flow.svg
Labels: DO NOT MERGE, cla: yes

#2531 Migrate the HTTPS overview from developers.google.com/web
  src/site/content/en/images/authors/kaycebasques.jpg
  src/site/content/en/images/authors/kaycebasques@2x.jpg
  src/site/content/en/secure/secure.11tydata.js
  src/site/content/en/secure/why-https-matters/index.md
Labels: cla: yes

#2451 Add SXG testing instructions
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes, privacy/security

#2454 Correct window to navigator in supporting section
  src/site/content/en/blog/badging-api/index.md
Labels: cla: yes

#2467 Fix SXG debian package urls
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes, content update, privacy/security

#2456 Add some missing detail to badging article.
  src/site/content/en/blog/badging-api/index.md
Labels: capabilities, cla: yes, content update

#2469 [H5R File article, Native File System article] Add pointers to new features
  src/site/content/en/blog/native-file-system/index.md
  src/site/content/en/blog/read-files/index.md
Labels: capabilities, cla: yes, content update

#2490 Update release timing information.
  src/site/content/en/blog/samesite-cookie-recipes/index.md
Labels: cla: yes, content update, privacy/security

#2509 web.dev Engineering Blog 1
  src/site/_data/contributors.js
  src/site/_data/postTags.js
  src/site/content/en/blog/how-we-build-webdev-and-use-web-components/hero.jpg
  src/site/content/en/blog/how-we-build-webdev-and-use-web-components/index.md
  src/site/content/en/blog/how-we-build-webdev-and-use-web-components/state-and-elements.png
  src/site/content/en/images/authors/samthor.jpg
  src/site/content/en/images/authors/samthor@2x.jpg
Labels: cla: yes

#2515 Remove draft.
  src/site/content/en/blog/websocketstream/index.md
Labels: cla: yes

#2540 Fixes to 'Find out more' links
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: cla: yes

#2532 [color-scheme Article] Publish it
  src/site/content/en/blog/color-scheme/index.md
Labels: cla: yes

#2524 Update imagemin code samples
  src/site/content/en/fast/serve-images-webp/index.md
  src/site/content/en/fast/use-imagemin-to-compress-images/index.md
Labels: cla: yes

#2508 Update LightWallet article
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/lightwallet.png
Labels: cla: yes, content update, performance

#2546 Add task to lint and test PRs.
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/lint-and-test-workflow.yml
  package.json
  src/site/content/en/secure/secure.11tydata.js
Labels: cla: yes

#2550 Install deps for ci workflow.
  .github/workflows/continuous-integration-workflow.yml
Labels: cla: yes

#2568 Fix a HTTP caching codelab Glitch embed
  src/site/content/en/reliable/codelab-http-cache/codelab-http-cache.md
Labels: cla: yes

#2559 Replace placeholder with actual name of the API
  src/site/content/en/blog/websocketstream/index.md
Labels: cla: yes

#2552 Add Glitch guidance to handbook
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#2548 Add `updated` field to markdown frontmatter
  src/site/content/en/fast/serve-images-webp/index.md
  src/site/content/en/fast/use-imagemin-to-compress-images/index.md
Labels: cla: yes

#2553 Add percy test for tablets. Fix PostCards on tablet.
  package.json
  src/styles/components/_all.scss
  tools/percy/.percy.conf.yml
Labels: cla: yes

#2555 Only render subhead if text exists.
  src/site/_includes/components/BaseCard.js
Labels: cla: yes

#2556 Add preconnects to firebase.
  src/site/_includes/layout.njk
Labels: cla: yes

#2557 optimize text for speed versus legibility.
  src/styles/settings/_type.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#2368 Podcast lander page
  src/site/_data/podcasts.js
  src/site/_includes/partials/footer.njk
  src/site/content/en/images/podcasts/css-podcast.jpg
  src/site/content/en/images/podcasts/designer-vs-developer.jpg
  src/site/content/en/images/podcasts/http203.jpg
  src/site/content/en/images/podcasts/state-of-the-web.jpg
  src/site/content/en/podcasts/index.njk
  src/styles/components/_path-card.scss
  tools/percy/snapshots.js
Labels: cla: yes

#2525 Add web.dev/monitor-total-page-memory-usage
  src/site/_data/contributors.js
  src/site/content/en/blog/monitor-total-page-memory-usage/hero.jpg
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/images/authors/ulan.jpg
  src/site/content/en/images/authors/ulan@2x.jpg
Labels: Chrome 83, cla: yes

#2536 wrap localStorage to deal with Firefox issues
  src/lib/actions.js
  src/lib/fb.js
  src/lib/store.js
  src/lib/utils/storage.js
Labels: cla: yes

#2580 make 404s always go to network
  server.js
  src/lib/loader.js
  src/lib/sw.js
  src/site/content/en/_redirects.yaml
Labels: cla: yes

#2442 Update Web OTP for origin trial graduation
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/web-otp/diagram.png
  src/site/content/en/blog/web-otp/index.md
Labels: DO NOT MERGE, cla: yes, content update

#2587 Fix typo, designer vs developer
  src/site/_data/podcasts.js
Labels: cla: yes

#2585 Link to new home of HTTP203
  src/site/_data/podcasts.js
Labels: cla: yes

#2589 See if cranking up percy snapshot wait time helps with flakiness.
  tools/percy/snapshots.js
Labels: cla: yes

#2379 Draft addition of getProperties() to Contacts API article.
  src/site/content/en/blog/contact-picker/index.md
Labels: DO NOT MERGE, capabilities, cla: yes, content update

#2590 Don't make percy go through redirects.
  tools/percy/snapshots.js
Labels: cla: yes

#2581 add service-worker kill switch
  server.js
  src/misc/nuke-sw.js
Labels: cla: yes

#2541 simply first example in WebSocketStream post
  src/site/content/en/blog/websocketstream/index.md
Labels: capabilities, cla: yes, content update

#2551 Remove mention of Intersection Observer
  src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md
Labels: cla: yes, content update, performance

#2543 Update Native File System article
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/native-file-system/fs-save-permission-crop.jpg
  src/site/content/en/blog/native-file-system/index.md
Labels: Chrome 83, capabilities, cla: yes, content update

#2571 performance-scoring: add CLS into lh v6 scores
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes

#2584 Clarify P2P is not supported in Web NFC
  src/site/content/en/blog/nfc/index.md
Labels: cla: yes

#2576 SXG: mention support from other Chromium browsers
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes

#2592 Only run percy against PRs.
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#2595 search tab index bug
  src/lib/components/Search/index.js
Labels: cla: yes

#2586 [Wake Lock article] Incorporate latest spec changes
  src/site/content/en/blog/wakelock/index.md
Labels: capabilities, cla: yes, content update

#2596 Updates to Privacy Sandbox post
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: cla: yes

#2237 feat(subscribe): add element to subscribe to newsletter to the bottom of posts, fixes #2109
  src/images/icons/check_box.svg
  src/images/icons/check_box_outline_blank.svg
  src/lib/components/Subscribe/_styles.scss
  src/lib/components/Subscribe/index.js
  src/lib/loader.js
  src/lib/pages/newsletter.js
  src/site/_data/countries.js
  src/site/_data/site.js
  src/site/_includes/partials/subscribe.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/newsletter/index.njk
  src/styles/all.scss
  src/styles/components/_all.scss
  src/styles/components/_checkbox.scss
  src/styles/components/_subscribe.scss
  src/styles/generic/_all.scss
  src/styles/generic/_input.scss
  src/styles/overrides/_all.scss
  src/styles/overrides/_display.scss
  src/styles/tools/_helpers.scss
  tools/percy/snapshots.js
Labels: cla: yes

#2594 disable iframing
  server.js
Labels: cla: yes

#2603 fix(description): allow for character escaping in descriptions
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
Labels: cla: yes

#2602 Make percy wait for network idle.
  package-lock.json
  package.json
  tools/percy/snapshots.js
Labels: cla: yes

#2579 Understanding "same-site" and "same-origin"
  src/site/content/en/secure/same-site-same-origin/eTLD+1.png
  src/site/content/en/secure/same-site-same-origin/index.md
  src/site/content/en/secure/same-site-same-origin/same-origin.png
  src/site/content/en/secure/same-site-same-origin/same-site.png
  src/site/content/en/secure/same-site-same-origin/schemeful-same-site.png
  src/site/content/en/secure/secure.11tydata.js
Labels: cla: yes

#2537 build script cleanup + virtual imports
  build.js
  src/build/virtual-json.js
  src/lib/bootstrap.js
  src/lib/components/Codelab/index.js
  src/lib/fb.js
  src/lib/store.js
Labels: cla: yes

#2526 Feat/cdn all the things
  .eleventy.js
  .gitignore
  package.json
  src/site/_includes/components/BaseCard.js
  src/site/_includes/components/Hero.js
  src/site/_includes/components/tags/README.md
  src/site/_includes/layout.njk
  src/site/_includes/partials/post.njk
  src/site/_transforms/responsive-images/helpers.js
  src/site/_transforms/responsive-images/index.js
  src/site/_transforms/service-worker-partials/index.js
  test/README.md
  test/integration/build-test.js
  test/integration/index.js
  test/site/_transforms/index.js
  test/site/_transforms/responsive-images/helpers.js
  test/site/_transforms/responsive-images/index.js
  test/site/_transforms/service-worker-partials/index.js
  test/site/index.js
Labels: DO NOT MERGE, cla: yes

#2493 Add a workflow to catch the DO NOT MERGE label.
  .github/workflows/required-checks-workflow.yml
Labels: cla: yes

#2599 Add stale bot config.
  .github/stale.yml
Labels: cla: yes

#2593 fix: typo in srcset blog
  src/site/content/en/blog/use-srcset-to-automatically-choose-the-right-image/index.md
Labels: cla: yes

#2606 Remove launch number from Web OTP article.
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#2607 Task/pr required checks
  .github/workflows/lint-and-test-workflow.yml
  .github/workflows/required-checks-workflow.yml
Labels: cla: yes

#2610 Fix broken algolia build.
  .github/workflows/continuous-integration-workflow.yml
  src/site/_transforms/responsive-images/index.js
  test/site/_transforms/responsive-images/index.js
Labels: cla: yes

#2545 Initial commit for COOP+COEP article
  src/site/content/en/blog/coop-coep/browsing-context-group.png
  src/site/content/en/blog/coop-coep/devtools1.jpg
  src/site/content/en/blog/coop-coep/devtools2.jpg
  src/site/content/en/blog/coop-coep/hero.jpg
  src/site/content/en/blog/coop-coep/index.md
Labels: Chrome 83, SAFE TO MERGE, beta blog-related, blog, cla: yes, content

#2614 Exempt issues with assignees from stalebot.
  .github/stale.yml
Labels: cla: yes

#2613 Ignore more files so we do not deploy them.
  .gcloudignore
Labels: cla: yes

#2612 fix(newsletter): update copy
  src/site/_includes/partials/subscribe.njk
  src/styles/components/_subscribe.scss
  src/styles/overrides/_display.scss
Labels: cla: yes

#2615 Add accepted label. Remove assignee exemption.
  .github/stale.yml
Labels: cla: yes

#2616 Exempt epics from stalebot.
  .github/stale.yml
Labels: cla: yes

#2617 Change `update` to `updated`
  src/site/content/en/blog/vr-comes-to-the-web/index.md
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#2608 refactor(collections): create collections for `tags` and `authors` that derivative collections reference
  .eleventy.js
  src/site/_collections/authors.js
  src/site/_collections/paginated-authors.js
  src/site/_collections/paginated-posts-by-author.js
  src/site/_collections/paginated-posts-by-tag.js
  src/site/_collections/paginated-tags.js
  src/site/_collections/tags.js
Labels: cla: yes

#2619 Make percy record new snapshots for master.
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#2621 refactor(collections): update based on @samthor's feedback in #2608
  src/site/_collections/authors.js
  src/site/_collections/tags.js
Labels: cla: yes

#2623 Wrap code in headings.
  src/styles/generic/_code.scss
Labels: cla: yes

#2632 Shorten performance.measureMemory title.
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#2624 chore(subscribe): update copy
  src/site/_includes/partials/subscribe.njk
Labels: cla: yes

#2631 Add glitch link for petele in contributors.js
  src/site/_data/contributors.js
Labels: cla: yes

#2635 fix(meta): remove double quote from text in meta attributes, fixes #2627
  src/site/_filters/strip.js
  src/site/_includes/components/Meta.js
Labels: cla: yes

#2636 refactor(meta): use `&quot;` replaceValue for `"`
  src/site/_includes/components/Meta.js
Labels: cla: yes

#2567 Clarify Shape Detection APIs statuses.
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/shape-detection/index.md
Labels: Chrome 83, beta blog-related, cla: yes

#2597 Content Indexing update: launchUrl is now url
  src/site/content/en/blog/content-indexing-api/index.md
Labels: capabilities, cla: yes, content update

#2600 Add note that the Contact Picker is available on mobile only
  src/site/content/en/blog/contact-picker/index.md
Labels: capabilities, cla: yes, content update

#2639 Fix closing figure tags
  src/site/content/en/fast/preload-critical-assets/index.md
Labels: cla: yes

#2642 Fix acknowledgements section in measureMemory
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#2647 Include more page types in percy tests.
  src/site/content/en/blog/test-post/a.jpg
  src/site/content/en/blog/test-post/hero.jpg
  src/site/content/en/blog/test-post/image-inline.png
  src/site/content/en/blog/test-post/image-screenshot.png
  src/site/content/en/blog/test-post/image-small.png
  src/site/content/en/blog/test-post/img1.png
  src/site/content/en/blog/test-post/img2.png
  src/site/content/en/blog/test-post/index.md
  tools/percy/snapshots.js
Labels: cla: yes

#2656 Update husky comment.
  .huskyrc
Labels: cla: yes

#2651 Delete unused build-partial.js
  src/site/_utils/build-partial.js
Labels: cla: yes

#2657 Update SotW podcast link
  src/site/_data/podcasts.js
Labels: cla: yes

#2653 Workbox service worker tweaks
  build.js
  package-lock.json
  package.json
Labels: cla: yes

#2644 Remove the `fbzx` query param from the new content form
  .github/ISSUE_TEMPLATE/propose-new-content.md
Labels: cla: yes

#2665 test(partial): test a fully generated partial json against the HTML
  test/integration/partials-test.js
Labels: cla: yes

#2643 Migrate cache api intro doc
  src/site/content/en/blog/cache-api-quick-guide/index.md
  src/site/content/en/reliable/service-workers-cache-storage/index.md
Labels: cla: yes, content, content update, pwa, reliable

#2640 Add tests for postsWithLighthouse collection
  test/integration/index.js
  test/integration/src/site/_collections/eleventy.js
  test/integration/src/site/_collections/fixtures/test-1.md
  test/integration/src/site/_collections/fixtures/test-2.md
  test/integration/src/site/_collections/fixtures/test-3.md
  test/integration/src/site/_collections/fixtures/test-4.md
  test/integration/src/site/_collections/fixtures/test-5.md
  test/integration/src/site/_collections/fixtures/test-6.md
  test/integration/src/site/_collections/fixtures/test-7.md
  test/integration/src/site/_collections/index.js
  test/integration/src/site/_collections/posts-with-lighthouse/collection.md
  test/integration/src/site/_collections/posts-with-lighthouse/dev.js
  test/integration/src/site/_collections/posts-with-lighthouse/prod.js
  test/integration/src/site/_collections/recent-posts/collection.md
  test/integration/src/site/_collections/recent-posts/dev.js
  test/integration/src/site/_collections/recent-posts/prod.js
  test/integration/src/site/_collections/runEleventy.js
Labels: cla: yes

#2654 feat(author): add image and social to author pages, fixes #2274
  src/images/icons/github.svg
  src/images/icons/glitch.svg
  src/images/icons/language.svg
  src/images/icons/rss.svg
  src/images/icons/twitter.svg
  src/site/_collections/authors.js
  src/site/_collections/paginated-authors.js
  src/site/_data/contributors.js
  src/site/content/en/authors/feed.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/fast/fixing-website-speed-cross-functionally/index.md
  src/site/content/en/tags/individual.njk
  src/styles/pages/_all.scss
  src/styles/pages/_author.scss
  src/styles/pages/_tags.scss
  tools/percy/snapshots.js
Labels: cla: yes

#2671 Link to v8.dev feature explainer for numeric separators
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#2662 Add some tests to _filters
  src/site/_filters/contains-tag.js
  src/site/_includes/partials/post.njk
  test/site/_filters/capitalize.js
  test/site/_filters/index.js
Labels: cla: yes

#2708 [Handbook] Use correct times symbol '×' instead of 'x'
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#2719 Fixing typo in "first-meaningful-paint" metric
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
Labels: cla: yes

#2706 Add tomayac's Glitch
  src/site/_data/contributors.js
Labels: cla: yes

#2691 Storage for the web
  src/site/content/en/blog/storage-for-the-web/hero.jpg
  src/site/content/en/blog/storage-for-the-web/index.md
  src/site/content/en/blog/storage-for-the-web/storage-test-tool.png
Labels: cla: yes

#2676 Adds page to handbook on resolving common glitch issues
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/handbook/resolving-glitch-issues/directories.png
  src/site/content/en/handbook/resolving-glitch-issues/disk-limit.png
  src/site/content/en/handbook/resolving-glitch-issues/git-committed-files.png
  src/site/content/en/handbook/resolving-glitch-issues/index.md
  src/site/content/en/handbook/resolving-glitch-issues/suspended-project.png
Labels: cla: yes

#2733 Mention preload in FOIT audit guide
  src/site/content/en/lighthouse-performance/font-display/index.md
Labels: cla: yes

#2736 Link to aspect ratio explanation and mention image CDNs
  src/site/content/en/lighthouse-best-practices/image-aspect-ratio/index.md
Labels: cla: yes

#2738 Mention Workbox in offline audit guide
  src/site/content/en/lighthouse-pwa/offline-start-url/index.md
Labels: cla: yes

#2625 Update the HTTP Cache guide
  src/site/_data/contributors.js
  src/site/content/en/reliable/http-cache/flowchart.png
  src/site/content/en/reliable/http-cache/index.md
Labels: cla: yes, content update, performance

#2637 Add code coverage.
  .nycrc
  build.js
  package-lock.json
  package.json
Labels: cla: yes

#2534 Next.js and Gatsby + Granular chunking article
  src/site/content/en/blog/granular-chunking-nextjs/commons-pattern-diagram.png
  src/site/content/en/blog/granular-chunking-nextjs/hero.png
  src/site/content/en/blog/granular-chunking-nextjs/index.md
  src/site/content/en/blog/granular-chunking-nextjs/js-payload-num-requests.png
  src/site/content/en/blog/granular-chunking-nextjs/outputted-chunks.png
  src/site/content/en/blog/granular-chunking-nextjs/performance-num-requests-1.png
  src/site/content/en/blog/granular-chunking-nextjs/performance-num-requests-2.png
Labels: cla: yes

#2707 [prefers-color-scheme Article] Add CSS tag
  src/site/content/en/blog/prefers-color-scheme/index.md
Labels: cla: yes

#2711 Fix masthead on mobile.
  src/styles/components/_mastheads.scss
Labels: cla: yes

#2741 Document redirects in the Handbook
  src/site/content/en/handbook/handbook.11tydata.js
  src/site/content/en/handbook/redirects/index.md
Labels: cla: yes

#2743 Update image guidelines in the Handbook
  src/site/content/en/handbook/markup-media/index.md
Labels: cla: yes

#2744 Remove 3P badging content
  src/site/content/en/fast/identify-slow-third-party-javascript/badge-popup.png
  src/site/content/en/fast/identify-slow-third-party-javascript/badges.png
  src/site/content/en/fast/identify-slow-third-party-javascript/execution-time.png
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
  src/site/content/en/fast/identify-slow-third-party-javascript/long-tasks.jpg
Labels: cla: yes

#2734 Tiny fix to getInstalledRelatedApps sample code
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: capabilities, cla: yes, content update

#2672 Adds note on Play for Family policy for Trusted Web Activity
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
Labels: cla: yes, content update, pwa

#2753 Add aside beforeinstallprompt event is still recommended
  src/site/content/en/progressive-web-apps/customize-install/index.md
Labels: cla: yes, content update, pwa

#2746 fix web-codelab fouc
  src/lib/components/Codelab/_styles.scss
  src/styles/pages/_all.scss
  src/styles/pages/_codelab.scss
Labels: cla: yes

#2745 Mention browser compatibility for Bundles
  src/site/content/en/blog/web-bundles/index.md
Labels: cla: yes

#2752 Clarify storage limits in Safari
  src/site/content/en/blog/storage-for-the-web/index.md
Labels: capabilities, cla: yes, content update

#2601 Added warning re native lazy loading
  src/site/content/en/lighthouse-performance/offscreen-images/index.md
Labels: cla: yes

#2574 performance-scoring: flesh out weighting/scoring curve details
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
  src/site/content/en/lighthouse-performance/performance-scoring/scoring-curve.png
Labels: cla: yes
