Repository GoogleChrome/web.dev, pull requests merged in 2021-11, with the labels that each got.

#6578 Fixing my bio
  src/site/_data/i18n/authors.yml
Labels: cla: yes

#6587 Learn forms: Tweaks for CodePen embeds, correct URLs
  src/site/content/en/learn/forms/accessibility/index.md
  src/site/content/en/learn/forms/attributes/index.md
  src/site/content/en/learn/forms/auto/index.md
  src/site/content/en/learn/forms/autofill/index.md
  src/site/content/en/learn/forms/conclusion/index.md
  src/site/content/en/learn/forms/cross-platform-testing/index.md
  src/site/content/en/learn/forms/data/index.md
  src/site/content/en/learn/forms/design-basics/index.md
  src/site/content/en/learn/forms/form-fields/index.md
  src/site/content/en/learn/forms/form/index.md
  src/site/content/en/learn/forms/identity/index.md
  src/site/content/en/learn/forms/internationalization/index.md
  src/site/content/en/learn/forms/javascript/index.md
  src/site/content/en/learn/forms/styling-form-controls/index.md
  src/site/content/en/learn/forms/styling/index.md
  src/site/content/en/learn/forms/testing/index.md
  src/site/content/en/learn/forms/validation/index.md
Labels: cla: yes

#6584 Two more Learn Design modules
  src/site/content/en/learn/design/intro/intro.assess.yml
  src/site/content/en/learn/design/macro-layouts/index.md
  src/site/content/en/learn/design/macro-layouts/macro-layouts.assess.yml
  src/site/content/en/learn/design/media-queries/media-queries.assess.yml
  src/site/content/en/learn/design/micro-layouts/index.md
  src/site/content/en/learn/design/micro-layouts/micro-layouts.assess.yml
Labels: cla: yes

#6588 makes browserCompat a sync shortcode
  .eleventy.js
  src/site/_includes/components/BrowserCompat.js
  src/site/_utils/browserCompat.js
Labels: cla: yes

#6538 feat(learn): use new design system, fixes #6391
  src/lib/components/LearnFilter/index.js
  src/scss/next.scss
  src/scss/pages/_learn.scss
  src/site/content/en/learn-next/index.njk
  src/site/content/en/learn-next/learn-next.11tydata.js
  test/unit/src/lib/components/LearnFilter/index.js
Labels: cla: yes

#6558 Adds Search Off The Record podcast
  src/images/podcasts/search-off-the-record.jpg
  src/site/_data/podcasts.js
Labels: cla: yes, $-presubmit

#6594 fix(share-action): corrupted hover style
  src/lib/components/ShareAction/_styles.scss
Labels: cla: yes, $-presubmit

#6602 Update copy
  src/site/_includes/about-next.njk
  src/site/content/en/about/next.md
  src/site/content/en/home/index.md
  src/site/content/en/measure-psi/index.njk
Labels: cla: yes

#6599 Intro and coming soon text.
  src/site/_data/i18n/courses.yml
  src/site/content/en/learn/design/accessibility/index.md
  src/site/content/en/learn/design/icons/index.md
  src/site/content/en/learn/design/index.md
  src/site/content/en/learn/design/interaction/index.md
  src/site/content/en/learn/design/macro-layouts/index.md
  src/site/content/en/learn/design/media-features/index.md
  src/site/content/en/learn/design/picture-element/index.md
  src/site/content/en/learn/design/responsive-images/index.md
  src/site/content/en/learn/design/screen-configurations/index.md
  src/site/content/en/learn/design/theming/index.md
  src/site/content/en/learn/design/typography/index.md
  src/site/content/en/learn/design/ui-patterns/index.md
Labels: cla: yes

#6604 enable shortcodes on some sections of patterns
  src/site/_includes/pattern-set.njk
Labels: cla: yes

#6600 Design update snags
  src/component-library/feature-card/feature-card.json
  src/component-library/feature-card/feature-card.njk
  src/scss/blocks/_feature-card.scss
  src/scss/blocks/_hero.scss
  src/scss/pages/_homepage.scss
  src/scss/utilities/_wrapper.scss
  src/site/_includes/homepage-next.njk
Labels: cla: yes

#6605 LearnDesign: Update demos
  src/site/content/en/learn/design/internationalization/index.md
  src/site/content/en/learn/design/intro/index.md
Labels: cla: yes, $-presubmit

#6606 Remove temp patch on reel for courses
  src/scss/compositions/_reel.scss
Labels: cla: yes

#6581 Update to Search SW post
  src/site/content/en/blog/google-search-sw/index.md
Labels: cla: yes

#6586 update scoring criteria in lighthouse dom-size
  src/site/content/en/lighthouse-performance/dom-size/index.md
Labels: cla: yes

#6595 fix dead PWA install link for FF
  src/site/content/en/progressive-web-apps/install-criteria/index.md
Labels: cla: yes

#6525 feat(carousel): implement carousel widget as a new component, fixes #6390
  src/component-library/carousel/carousel.json
  src/component-library/carousel/carousel.md
  src/component-library/carousel/carousel.njk
  src/lib/components/Carousel/index.js
  src/lib/pages/design-system.js
  src/scss/blocks/_carousel.scss
  src/scss/blocks/_prose.scss
  src/scss/next.scss
  src/site/_includes/icons/carat-back.svg
  src/site/_includes/icons/carat-forward.svg
  src/site/content/en/design-system/components-preview.njk
  src/site/content/en/design-system/css-compositions.njk
  src/site/content/en/design-system/css-utilities.md
Labels: cla: no

#6610 Replace temporary carousel with finished reel cards partial in /learn-next
  src/site/content/en/learn-next/index.njk
Labels: cla: yes

#6461 Add a missing semicolon to CSS snippet
  src/site/content/en/learn/css/layout/index.md
Labels: cla: yes, $-presubmit

#6611 fix(CSP): fix CSP from inline JS
  src/site/_includes/partials/theme-script.njk
Labels: cla: yes

#6613 The one in which devnook learns pipe has a meaning
  src/site/content/en/home/index.md
Labels: cla: yes

#6250 Add Layout Patterns
  src/site/content/en/blog/one-line-layouts/index.md
  src/site/content/en/patterns/layout/aspect-ratio-image-card/assets/body.html
  src/site/content/en/patterns/layout/aspect-ratio-image-card/assets/style.css
  src/site/content/en/patterns/layout/aspect-ratio-image-card/demo.md
  src/site/content/en/patterns/layout/aspect-ratio-image-card/index.md
  src/site/content/en/patterns/layout/clamping-card/assets/body.html
  src/site/content/en/patterns/layout/clamping-card/assets/style.css
  src/site/content/en/patterns/layout/clamping-card/demo.md
  src/site/content/en/patterns/layout/clamping-card/index.md
  src/site/content/en/patterns/layout/container-query-card/assets/body.html
  src/site/content/en/patterns/layout/container-query-card/assets/style.css
  src/site/content/en/patterns/layout/container-query-card/demo.md
  src/site/content/en/patterns/layout/container-query-card/index.md
  src/site/content/en/patterns/layout/deconstructed-pancake/assets/body.html
  src/site/content/en/patterns/layout/deconstructed-pancake/assets/style.css
  src/site/content/en/patterns/layout/deconstructed-pancake/demo.md
  src/site/content/en/patterns/layout/deconstructed-pancake/index.md
  src/site/content/en/patterns/layout/holy-grail/assets/body.html
  src/site/content/en/patterns/layout/holy-grail/assets/style.css
  src/site/content/en/patterns/layout/holy-grail/demo.md
  src/site/content/en/patterns/layout/holy-grail/index.md
  src/site/content/en/patterns/layout/index.md
  src/site/content/en/patterns/layout/line-up/assets/body.html
  src/site/content/en/patterns/layout/line-up/assets/style.css
  src/site/content/en/patterns/layout/line-up/demo.md
  src/site/content/en/patterns/layout/line-up/index.md
  src/site/content/en/patterns/layout/pancake-stack/assets/body.html
  src/site/content/en/patterns/layout/pancake-stack/assets/style.css
  src/site/content/en/patterns/layout/pancake-stack/demo.md
  src/site/content/en/patterns/layout/pancake-stack/index.md
  src/site/content/en/patterns/layout/repeat-auto-minmax/assets/body.html
  src/site/content/en/patterns/layout/repeat-auto-minmax/assets/style.css
  src/site/content/en/patterns/layout/repeat-auto-minmax/demo.md
  src/site/content/en/patterns/layout/repeat-auto-minmax/index.md
  src/site/content/en/patterns/layout/sidebar-says/assets/body.html
  src/site/content/en/patterns/layout/sidebar-says/assets/style.css
  src/site/content/en/patterns/layout/sidebar-says/demo.md
  src/site/content/en/patterns/layout/sidebar-says/index.md
  src/site/content/en/patterns/layout/super-centered/assets/body.html
  src/site/content/en/patterns/layout/super-centered/assets/style.css
  src/site/content/en/patterns/layout/super-centered/demo.md
  src/site/content/en/patterns/layout/super-centered/index.md
  src/site/content/en/patterns/layout/twelve-span-grid/assets/body.html
  src/site/content/en/patterns/layout/twelve-span-grid/assets/style.css
  src/site/content/en/patterns/layout/twelve-span-grid/demo.md
  src/site/content/en/patterns/layout/twelve-span-grid/index.md
Labels: cla: yes

#6622 add `siteRender` filter to render as close to site as possible
  .eleventy.js
  package-lock.json
  package.json
  src/lib/patterns.js
  src/site/_filters/minify-js.js
  src/site/_filters/site-render.js
  src/site/_includes/pattern-set.njk
  types/site/_data/patterns.d.ts
Labels: cla: yes

#6624 Make good TBT thresholds consistent
  src/site/content/en/metrics/tbt/index.md
Labels: cla: yes

#6628 Fix minify build, args called in wrong order
  package-lock.json
  package.json
  src/site/_filters/minify-js.js
Labels: cla: yes

#6607 Blockquote adjustments
  src/scss/next.scss
Labels: cla: yes

#6601 A few Learn Forms tweaks
  src/site/content/en/learn/forms/fields/index.md
  src/site/content/en/learn/forms/internationalization/index.md
  src/site/content/en/learn/forms/javascript/index.md
  src/site/content/en/learn/forms/security-privacy/index.md
  src/site/content/en/learn/forms/styling/index.md
  src/site/content/en/learn/forms/testing/index.md
  src/site/content/en/learn/forms/usability-testing/index.md
Labels: cla: yes

#6598 Learn PWA first three modules
  src/site/content/en/learn/pwa/app-design/index.md
  src/site/content/en/learn/pwa/architecture/index.md
  src/site/content/en/learn/pwa/assets-and-data/index.md
  src/site/content/en/learn/pwa/caching/index.md
  src/site/content/en/learn/pwa/capabilities/index.md
  src/site/content/en/learn/pwa/complexity/index.md
  src/site/content/en/learn/pwa/conclusion/index.md
  src/site/content/en/learn/pwa/detection/index.md
  src/site/content/en/learn/pwa/enhancements/index.md
  src/site/content/en/learn/pwa/experimental/index.md
  src/site/content/en/learn/pwa/foundations/index.md
  src/site/content/en/learn/pwa/getting-started/index.md
  src/site/content/en/learn/pwa/index.md
  src/site/content/en/learn/pwa/installation-prompt/index.md
  src/site/content/en/learn/pwa/installation/index.md
  src/site/content/en/learn/pwa/offline-data/index.md
  src/site/content/en/learn/pwa/os-integration/index.md
  src/site/content/en/learn/pwa/progressive-web-apps/index.md
  src/site/content/en/learn/pwa/service-workers/index.md
  src/site/content/en/learn/pwa/serving/index.md
  src/site/content/en/learn/pwa/tools-and-debug/index.md
  src/site/content/en/learn/pwa/update/index.md
  src/site/content/en/learn/pwa/web-app-manifest/index.md
  src/site/content/en/learn/pwa/windows/index.md
  src/site/content/en/learn/pwa/workbox/index.md
Labels: cla: yes

#6632 fix copy nits for launch
  src/site/content/en/home/index.md
  src/site/content/en/measure-psi/index.njk
  src/site/content/en/patterns/layout/aspect-ratio-image-card/index.md
  src/site/content/en/patterns/layout/deconstructed-pancake/index.md
  src/site/content/en/patterns/layout/index.md
Labels: cla: yes

#6633 fix learn pwa description.
  src/site/content/en/learn/pwa/index.md
Labels: cla: yes

#6634 Measure page fixes
  src/lib/components/LighthouseViewer/index.js
  src/scss/pages/_measure.scss
  src/site/content/en/measure-psi/index.njk
Labels: cla: yes

#6637 Apply correct headline markup to learn page
  src/site/content/en/learn-next/index.njk
Labels: cla: yes

#6635 fix responsive design logo / web.dev logo in responsive
  src/images/courses/css/logo.svg
  src/images/courses/design/logo.svg
  src/images/courses/forms/logo.svg
  src/images/courses/pwa/logo.svg
  src/scss/blocks/_breadcrumbs.scss
  src/scss/pages/_course.scss
Labels: cla: yes

#6639 Copy updates
  src/site/content/en/home/index.md
  src/site/content/en/measure-psi/index.njk
Labels: cla: yes

#6641 increase heading font
  src/site/_includes/about-next.njk
Labels: cla: yes

#6640 show most recent case studies
  src/scss/blocks/_card.scss
  src/site/_includes/homepage-next.njk
Labels: cla: yes

#6642 Updates CodePens and links in Learn Design
  src/site/content/en/learn/design/intro/index.md
  src/site/content/en/learn/design/media-queries/index.md
  src/site/content/en/learn/design/micro-layouts/index.md
Labels: cla: yes

#6636 Pattterns copy edit, remove draft status
  src/site/content/en/patterns/layout/aspect-ratio-image-card/demo.md
  src/site/content/en/patterns/layout/aspect-ratio-image-card/index.md
  src/site/content/en/patterns/layout/clamping-card/demo.md
  src/site/content/en/patterns/layout/clamping-card/index.md
  src/site/content/en/patterns/layout/container-query-card/demo.md
  src/site/content/en/patterns/layout/container-query-card/index.md
  src/site/content/en/patterns/layout/deconstructed-pancake/demo.md
  src/site/content/en/patterns/layout/deconstructed-pancake/index.md
  src/site/content/en/patterns/layout/holy-grail/demo.md
  src/site/content/en/patterns/layout/holy-grail/index.md
  src/site/content/en/patterns/layout/index.md
  src/site/content/en/patterns/layout/line-up/demo.md
  src/site/content/en/patterns/layout/line-up/index.md
  src/site/content/en/patterns/layout/pancake-stack/demo.md
  src/site/content/en/patterns/layout/pancake-stack/index.md
  src/site/content/en/patterns/layout/repeat-auto-minmax/demo.md
  src/site/content/en/patterns/layout/repeat-auto-minmax/index.md
  src/site/content/en/patterns/layout/sidebar-says/demo.md
  src/site/content/en/patterns/layout/sidebar-says/index.md
  src/site/content/en/patterns/layout/super-centered/demo.md
  src/site/content/en/patterns/layout/super-centered/index.md
  src/site/content/en/patterns/layout/twelve-span-grid/demo.md
  src/site/content/en/patterns/layout/twelve-span-grid/index.md
  src/site/content/en/patterns/web-vitals-patterns/carousels/index.md
  src/site/content/en/patterns/web-vitals-patterns/fonts/index.md
  src/site/content/en/patterns/web-vitals-patterns/infinite-scroll/index.md
  src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/index.md
  src/site/content/en/patterns/web-vitals-patterns/video/index.md
Labels: cla: yes

#6643 Remove flex none from lh buttons
  src/scss/_rollout.scss
  src/scss/next.scss
Labels: cla: yes

#6583 [URL Protocol Handling] Add launch info, remove origin trial info
  src/site/content/en/blog/url-protocol-handler/index.md
Labels: cla: yes

#6646 Make cards prioritise thumbnails
  src/site/_includes/homepage-next.njk
Labels: cla: yes

#6645 Switch swappie thumb
  src/site/content/en/blog/swappie/index.md
Labels: cla: yes

#6630 Add YouTube video
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes

#6648 update pwa svg
  src/images/courses/pwa/card.svg
Labels: cla: yes

#6647 Sticky tape on assesment button
  src/scss/_rollout.scss
Labels: cla: yes

#6649 [Courses] "Coming Soon" Styles
  src/scss/blocks/_stack-nav.scss
  src/scss/pages/_course.scss
  src/site/_filters/navigation.js
  src/site/_includes/partials/course-index.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/content/en/learn/design/accessibility/index.md
  src/site/content/en/learn/design/icons/index.md
  src/site/content/en/learn/design/interaction/index.md
  src/site/content/en/learn/design/media-features/index.md
  src/site/content/en/learn/design/picture-element/index.md
  src/site/content/en/learn/design/responsive-images/index.md
  src/site/content/en/learn/design/screen-configurations/index.md
  src/site/content/en/learn/design/theming/index.md
  src/site/content/en/learn/design/typography/index.md
  src/site/content/en/learn/design/ui-patterns/index.md
  src/site/content/en/learn/pwa/app-design/index.md
  src/site/content/en/learn/pwa/architecture/index.md
  src/site/content/en/learn/pwa/assets-and-data/index.md
  src/site/content/en/learn/pwa/caching/index.md
  src/site/content/en/learn/pwa/capabilities/index.md
  src/site/content/en/learn/pwa/complexity/index.md
  src/site/content/en/learn/pwa/conclusion/index.md
  src/site/content/en/learn/pwa/detection/index.md
  src/site/content/en/learn/pwa/enhancements/index.md
  src/site/content/en/learn/pwa/experimental/index.md
  src/site/content/en/learn/pwa/installation-prompt/index.md
  src/site/content/en/learn/pwa/installation/index.md
  src/site/content/en/learn/pwa/offline-data/index.md
  src/site/content/en/learn/pwa/os-integration/index.md
  src/site/content/en/learn/pwa/service-workers/index.md
  src/site/content/en/learn/pwa/serving/index.md
  src/site/content/en/learn/pwa/tools-and-debug/index.md
  src/site/content/en/learn/pwa/update/index.md
  src/site/content/en/learn/pwa/web-app-manifest/index.md
  src/site/content/en/learn/pwa/windows/index.md
  src/site/content/en/learn/pwa/workbox/index.md
  types/navigation/navigation-item.d.ts
Labels: cla: yes

#6156 docs(learncss): Add Transitions guide
  src/site/_data/authorsData.json
  src/site/_data/courses/css/toc.yml
  src/site/_data/i18n/authors.yml
  src/site/content/en/learn/css/transitions/index.md
  src/site/content/en/learn/css/transitions/transitions.assess.yml
Labels: cla: yes, $-presubmit

#6615 New design launch review
  src/site/_data/courses/design/meta.yml
  src/site/_data/courses/forms/meta.yml
  src/site/_data/courses/pwa/meta.yml
  src/site/content/en/about/index.md
  src/site/content/en/about/index.njk
  src/site/content/en/home/index.md
  src/site/content/en/index.md
  src/site/content/en/learn-next/index.njk
  src/site/content/en/learn-next/learn-next.11tydata.js
  src/site/content/en/learn/index.njk
  src/site/content/en/measure-psi/index.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/patterns/layout/pancake-stack/index.md
  src/site/content/es/index.md
  src/site/content/ja/index.md
  src/site/content/ko/index.md
  src/site/content/pl/index.md
  src/site/content/pt/index.md
  src/site/content/ru/index.md
  src/site/content/zh/index.md
Labels: cla: yes

#6644 Landing page with Blog implementation
  src/scss/blocks/_card.scss
  src/scss/blocks/_pill.scss
  src/scss/next.scss
  src/scss/pages/_landing-page.scss
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/landing-page.njk
  src/site/_includes/partials/pagination-next.njk
  src/site/content/en/blog/index.njk
Labels: cla: yes

#6654 Remove CDS banner
  src/site/_data/site.js
Labels: cla: yes

#6656 fix hero img
  src/site/content/en/index.md
Labels: cla: yes

#6626 Add initial responsiveness metric draft
  src/site/content/en/blog/responsiveness/index.md
Labels: cla: yes

#6629 Add the initial smoothness metric draft
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/smoothness/index.md
Labels: cla: yes

#6660 add lighthouse-user-flows doc
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/lighthouse-user-flows/index.md
Labels: cla: yes

#6657 Add authors to learn design
  src/site/_data/courses/design/toc.yml
  src/site/content/en/learn/design/conclusion/index.md
  src/site/content/en/learn/design/index.md
Labels: cla: yes

#6658 [Learn Design] MQ Module Videos
  src/site/content/en/learn/design/macro-layouts/index.md
  src/site/content/en/learn/design/media-queries/index.md
Labels: cla: yes

#6665 [Towards an animation smoothness metric article] Some minor improvements and (link) additions
  src/site/content/en/blog/smoothness/index.md
Labels: cla: yes

#6668 Case studies copy updates
  src/site/_data/i18n/header.yml
  src/site/_data/i18n/tags.yml
  src/site/_includes/partials/site-footer.njk
  src/site/_includes/partials/site-header.njk
Labels: cla: yes

#6638 ["Improve article" link] `main` is the new `master`
  src/site/_filters/github-link.js
Labels: cla: yes

#6670 Use the right property for thumbnails...
  src/site/_includes/homepage-next.njk
Labels: cla: yes

#6672 Adds author credit
  src/site/content/en/learn/pwa/conclusion/index.md
  src/site/content/en/learn/pwa/index.md
Labels: cla: yes

#6662 Tooling updates post (PSI, /measure)
  src/site/content/en/blog/whats-new-pagespeed-insights/index.md
Labels: cla: yes

#6674 fix search z-index
  src/scss/_rollout.scss
Labels: cla: yes

#6675 update
  src/site/_data/site.js
  src/site/_includes/partials/banner.njk
  src/site/content/en/index.md
Labels: cla: yes

#6671 [Fugu Status article] Remove stale list of APIs, replace with links to tracker
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#6681 Revert "update"
  src/site/_data/site.js
  src/site/_includes/partials/banner.njk
  src/site/content/en/index.md
Labels: cla: yes

#6684 CDS links post
  src/site/content/en/blog/cds2021-updates/index.md
Labels: cla: yes

#6686 Fix design media queries test
  src/site/content/en/learn/design/media-queries/media-queries.assess.yml
Labels: cla: yes

#6683 Fix typos in 'New capabilities status'.
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#6690 fix(UrlChooser): fix url overflow, fixes #6680
  src/lib/components/UrlChooser/_styles.scss
  src/lib/components/UrlChooser/index.js
Labels: cla: yes

#6691 LearnCSS: Transitions -> update devtools image
  src/site/content/en/learn/css/transitions/index.md
Labels: cla: yes, $-presubmit

#6688 GUI Challenges - split button patch
  src/site/content/en/blog/building-a-split-button-component/index.md
Labels: cla: yes

#6695 Swap out narrow images
  src/site/content/en/learn/design/intro/index.md
Labels: cla: yes

#6697 [Fugu Status article ] Use ID links
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#6699 fix(pagination): fix pagination bug that lets you go past the last page and that sends you to /blog/1 instead of /blog, fixes #6693
  src/site/_includes/partials/pagination-next.njk
Labels: cla: yes

#6678 lighthouse-user-flows: fix URL in the warm-load example
  src/site/content/en/blog/lighthouse-user-flows/index.md
Labels: cla: yes

#6677 Spotted a typo in the feedback section
  src/site/content/en/blog/responsiveness/index.md
Labels: cla: yes

#6701 fix(Subscribe): find correct elements in subscribe form, fixes #6663
  src/lib/components/Subscribe/index.js
  src/site/_includes/homepage-next.njk
  src/site/_includes/partials/subscribe-next.njk
  src/site/_includes/partials/subscribe.njk
  src/styles/components/_subscribe.scss
Labels: cla: yes

#6703 chore(homepage): delete unused homepage layout
  src/site/_includes/homepage.njk
Labels: cla: yes

#6704 refactor(newsletter): simplify newsletter layout
  src/site/_includes/newsletter.njk
  src/site/_includes/partials/newsletter.njk
Labels: cla: yes

#6711 Use the full url instead of fileSlug to find page.data
  src/site/_includes/components/Meta.js
  src/site/_includes/partials/head.njk
Labels: cla: yes

#6706 feat(subscribe): create subscribe FAB using new design system, fixes #6676
  src/scss/blocks/_fab.scss
  src/site/_includes/partials/subscribe-action-next.njk
Labels: cla: yes

#6710 Add Firefox to the list of browsers supporting AVIF
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes, $-presubmit

#6713 Fix typo.
  src/site/content/en/learn/pwa/foundations/index.md
Labels: cla: yes

#6716 simulate a mobile device in /measure tool
  src/lib/psi-service.js
Labels: cla: yes

#6722 Wdi banner
  src/site/_data/site.js
  src/site/_includes/partials/banner.njk
Labels: cla: yes

#6719 Added in a missing not so obvious step to the README
  README.md
Labels: cla: yes, $-presubmit

#6717 Fix broken link to spec draft
  src/site/content/en/blog/compute-pressure/index.md
Labels: cla: yes, $-presubmit

#6714 Correct formatting
  src/site/content/en/learn/pwa/foundations/index.md
Labels: cla: yes

#6709 Update OT timeline
  src/site/content/en/blog/gpu/index.md
Labels: cla: yes

#6726 Include Sam Richard as providing input to Learn PWA
  src/site/content/en/learn/pwa/index.md
Labels: cla: yes, $-presubmit

#6724 Includes new team members to Aurora blog post
  src/site/content/en/blog/introducing-aurora/index.md
Labels: cla: yes, content update

#6728 Minor Corrections
  src/site/content/en/learn/pwa/getting-started/index.md
Labels: cla: yes

#6727 Minor Corrections
  src/site/content/en/learn/pwa/progressive-web-apps/index.md
Labels: cla: yes

#6729 Add alexandrawhite to authors
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
Labels: cla: yes

#6734 Update 404 page
  src/site/_includes/partials/404.njk
  src/site/_includes/partials/text.njk
  src/site/_includes/text.njk
  src/site/content/en/404.md
  src/site/content/es/404.md
  src/site/content/ja/404.md
  src/site/content/ko/404.md
  src/site/content/pl/404.md
  src/site/content/pt/404.md
  src/site/content/ru/404.md
  src/site/content/zh/404.md
Labels: cla: yes

#6732 [File Handling article] Remove OT info
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#6733 [Declarative Link Capturing] Add OT not launching warning
  src/site/content/en/blog/declarative-link-capturing/index.md
Labels: cla: yes

#6743 Update index.md for italic text fixes
  src/site/content/en/blog/image-component/index.md
Labels: cla: yes, $-presubmit

#6442 docs(learncss): add Overflow guide
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/overflow/index.md
  src/site/content/en/learn/css/overflow/overflow.assess.yml
Labels: cla: yes, $-presubmit

#6718 Minor edit to Embed best practices
  src/site/content/en/blog/embed-best-practices/index.md
Labels: cla: yes

#6754 [Window Controls Overlay article] Update article with new screenshots
  src/site/content/en/blog/window-controls-overlay/index.md
Labels: cla: yes

#6759 Add DevTool support info to the bfcache post
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#6758 GUI Challenges "Switch": adds new remix
  src/site/content/en/blog/building-a-switch-component/index.md
Labels: cla: yes

#6757 Remove extraneous closing parenthesis
  src/site/content/en/blog/whats-new-pagespeed-insights/index.md
Labels: cla: yes, $-presubmit

#6766 remove extra ` backtick
  src/site/content/en/learn/design/micro-layouts/index.md
Labels: cla: yes, $-presubmit

#6608 Adjust the compare shortcodes and design system patterns
  src/component-library/compare/compare.njk
  src/component-library/compare/variants/columns/columns.njk
  src/scss/blocks/_compare.scss
  src/site/_includes/components/Compare.js
  src/site/_includes/components/CompareCaption.js
Labels: cla: yes

#6779 Temporary disable of the newsletter subscribe
  src/site/_includes/about-next.njk
  src/site/_includes/homepage-next.njk
  src/site/_includes/index-page.njk
  src/site/_includes/item-page.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/patterns.njk
  src/site/content/en/newsletter/index.njk
Labels: cla: yes

#6712 Adding the Mail.ru case study and author data.
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/mailru-cwv/index.md
Labels: cla: yes, accepted

#6775 Fix spelling mistake in "optimize"
  src/site/content/en/patterns/index.md
Labels: cla: yes, $-presubmit

#6777 fix(typo): s/fromtmatter/frontmatter
  src/site/content/en/handbook/quick-start/index.md
  src/site/content/en/patterns/example-set/full-html-demo/index.md
Labels: cla: yes, $-presubmit

#6760 New toc component
  src/component-library/toc/toc.json
  src/component-library/toc/toc.md
  src/component-library/toc/toc.njk
  src/component-library/web-table-of-contents/web-table-of-contents.json
  src/component-library/web-table-of-contents/web-table-of-contents.md
  src/component-library/web-table-of-contents/web-table-of-contents.njk
  src/scss/blocks/_toc.scss
  src/scss/next.scss
  src/scss/pages/_course.scss
  src/scss/utilities/_over-scroll.scss
  src/site/_includes/course.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/_includes/partials/toc-side.njk
  src/site/content/en/design-system/css-utilities.md
Labels: cla: yes

#6767 fix(typo): fixing a small typo
  src/site/content/en/media/media-frameworks/index.md
Labels: cla: yes

#6780 Enable PSI promo
  src/site/_includes/homepage-next.njk
  src/site/content/en/index.md
Labels: cla: yes

#6763 Add hero image component
  src/component-library/hero-image/hero-image.json
  src/component-library/hero-image/hero-image.md
  src/component-library/hero-image/hero-image.njk
  src/scss/blocks/_hero-image.scss
  src/scss/next.scss
Labels: cla: yes

#6761 Add preserved image component to replace w-screenshot
  src/component-library/fixed-width-img/fixed-width-img.json
  src/component-library/fixed-width-img/fixed-width-img.md
  src/component-library/fixed-width-img/fixed-width-img.njk
  src/component-library/fixed-width-img/variants/prose/prose.json
  src/component-library/fixed-width-img/variants/prose/prose.njk
  src/scss/_rollout.scss
  src/scss/blocks/_fixed-width-img.scss
  src/scss/next.scss
Labels: cla: yes

#6785 Remove the instruction to enable the bfcache experiment
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#6798 Updating screenshot
  src/site/content/en/blog/compat2021/index.md
Labels: cla: yes

#6772 fix(anchor): remove outline on `<a>` on active, fixes #5671
  src/styles/generic/_links.scss
Labels: cla: yes

#6784 Update index.njk
  src/site/content/en/newsletter/index.njk
Labels: cla: yes

#6778 fix(typo): fix GitHub casing
  src/site/content/en/blog/asyncify/index.md
  src/site/content/en/blog/building-a-switch-component/index.md
  src/site/content/en/blog/compress-images-avif/index.md
  src/site/content/en/blog/introducing-model-viewer/index.md
  src/site/content/en/blog/lighthouse-ci/index.md
  src/site/content/en/blog/lighthouse-whats-new-6.0/index.md
  src/site/content/en/blog/logical-property-shorthands/index.md
  src/site/content/en/blog/speculative-prerendering/index.md
  src/site/content/en/fast/codelab-extract-and-inline-critical-css/index.md
  src/site/content/en/fast/incorporate-performance-budgets-into-your-build-tools/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
  src/site/content/en/handbook/quick-start/index.md
  src/site/content/en/handbook/writing-blog-posts/index.md
  src/site/content/en/lighthouse-seo/http-status-code/index.md
  src/styles/generic/_code.scss
Labels: cla: yes, $-presubmit

#6808 Add LearnCSS Background Module
  src/site/content/en/learn/css/backgrounds/index.md
Labels: cla: yes

#6809 Update LearnCSS Background Module
  src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml
  src/site/content/en/learn/css/backgrounds/index.md
Labels: cla: yes

#6806 /measure: adopt lighthouse renderer
  package-lock.json
  package.json
  src/lib/components/LighthouseViewer/_styles.scss
  src/lib/components/LighthouseViewer/index.js
  src/lib/psi-service.js
  src/site/content/en/measure/index.njk
Labels: cla: yes

#6796 Updated WebAuthn codelab link
  src/site/content/en/blog/devices-introduction/index.md
Labels: cla: yes

#6802 Add Learn CSS Backgrounds module
  src/site/_data/authorsData.json
  src/site/_data/courses/css/toc.yml
  src/site/_data/i18n/authors.yml
  src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml
  src/site/content/en/learn/css/backgrounds/index.md
  src/site/content/en/learn/css/conclusion/index.md
Labels: cla: yes

#6819 Update Twitter handle in Learn CSS
  src/site/content/en/learn/css/index.md
Labels: cla: yes, content update

#6818 Add link to LH Viewer
  src/lib/actions.js
  src/lib/components/LighthouseViewer/index.js
  src/lib/components/UrlChooserContainer/index.js
  src/site/content/en/measure/index.njk
Labels: cla: yes

#6811 Fix typo in learn/design/internationalization
  src/site/content/en/learn/design/internationalization/index.md
Labels: cla: yes, $-presubmit

#6822 Update to Photoshop case study
  src/site/content/en/blog/ps-on-the-web/index.md
Labels: cla: yes

#6821 fix(measure): make styling more like previous measure page, fixes #6820
  src/lib/components/LighthouseViewer/_styles.scss
Labels: cla: yes

#6804 refactor(live-posts): rename `livePosts` to `isLive` and add new `livePosts` filter, fixes #6803
  .eleventy.js
  src/site/_collections/authors.js
  src/site/_collections/blog-posts-descending.js
  src/site/_collections/pages.js
  src/site/_collections/posts-with-lighthouse.js
  src/site/_collections/tags.js
  src/site/_filters/is-live.js
  src/site/_filters/live-posts.js
  test/unit/src/site/_filters/index.js
  test/unit/src/site/_filters/is-live.js
Labels: cla: yes

#6731 fix(Snackbar): use new button classes for snackbar, fixes #6705
  src/component-library/button/button.json
  src/lib/components/Snackbar/_styles.scss
  src/lib/components/Snackbar/index.js
  src/scss/mixins/_button-base-styles.scss
  src/styles/components/_buttons.scss
Labels: cla: yes

#6736 Design System: type and spacing references
  src/site/content/en/design-system/spacing.njk
  src/site/content/en/design-system/typography.njk
Labels: cla: yes

#6829 Add SVGcode article
  src/site/content/en/blog/svgcode/index.md
Labels: cla: yes

#6858 Add Cam Bickel to authors in Learn CSS conclusion
  src/site/content/en/learn/css/conclusion/index.md
Labels: cla: yes

#6825 Add user gesture requirement
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#6857 Update links in the footer
  src/site/_data/i18n/footer.yml
  src/site/_includes/partials/footer.njk
  src/site/_includes/partials/site-footer.njk
Labels: cla: yes

#6863 [Declarative Link Capturing article] Remove OT info
  src/site/content/en/blog/declarative-link-capturing/index.md
Labels: cla: yes

#6745 Replace logo with text for smaller viewports
  src/site/_includes/partials/header-course.njk
Labels: cla: yes

#6853 Design system components clean-up
  src/scss/pages/_design-system.scss
  src/site/_includes/design-system.njk
  src/site/_includes/macros/design-system-component.njk
  src/site/content/en/design-system/components.njk
  src/site/content/en/design-system/css-compositions.njk
Labels: cla: yes

#6769 Article type pages design system rollout
  gulp-tasks/sass.js
  package-lock.json
  src/component-library/stats/stats.njk
  src/lib/components/Codelab/index.js
  src/scss/_config.scss
  src/scss/_rollout.scss
  src/scss/blocks/_breadcrumbs.scss
  src/scss/blocks/_compare.scss
  src/scss/blocks/_prose.scss
  src/scss/blocks/_stats.scss
  src/scss/mixins/_button-base-styles.scss
  src/scss/next.scss
  src/scss/utilities/_docked-actions.scss
  src/scss/utilities/_wrapper.scss
  src/scss/web-components/_web-codelab.scss
  src/site/_includes/codelab.njk
  src/site/_includes/components/Aside.js
  src/site/_includes/components/Author.js
  src/site/_includes/handbook.njk
  src/site/_includes/icons/share.svg
  src/site/_includes/partials/course-app-bar.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/post-next.njk
  src/site/_includes/partials/subscribe-action-next.njk
  src/site/_includes/post.njk
  src/site/content/en/blog/eyedropper/index.md
  src/site/content/en/design-system/css-utilities.md
  src/styles/legacy-rollout.scss
Labels: cla: yes

#6860 fix(titles): urls in titles are not linkified, fixes #6474
  src/site/_includes/partials/item.njk
  src/site/_includes/partials/post.njk
Labels: cla: yes

#6851 Remove value judgement from the recommendation
  src/site/content/en/lighthouse-accessibility/heading-order/index.md
Labels: cla: yes

#6870 fix(algolia): use `bytes` rather than `length` to trim Algolia content, fixes #6869
  algolia.js
  package-lock.json
  package.json
Labels: cla: yes

#6876 Hide banner in print mode
  src/scss/blocks/_banner.scss
Labels: cla: yes

#6877 Make w-stats extend the new stats component
  src/component-library/stats/stats.json
  src/scss/blocks/_prose.scss
  src/scss/blocks/_stats.scss
  src/scss/next.scss
Labels: cla: yes

#6874 Table styles reverted to old style
  src/component-library/tables/variants/misc-content-examples/misc-content-examples.json
  src/component-library/tables/variants/misc-content-examples/misc-content-examples.njk
  src/scss/blocks/_table-wrapper.scss
  src/scss/next.scss
  src/scss/pages/_design-system.scss
  src/scss/utilities/_scrollbar.scss
Labels: cla: yes

#6878 Clean out :link selectors and remove from global CSS
  src/scss/blocks/_site-footer.scss
  src/scss/next.scss
  src/scss/pages/_about.scss
Labels: cla: yes

#6789 add service workers to work list
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes
