Repository GoogleChrome/web.dev, pull requests merged in 2021-01, with the labels that each got.

#4424 typo
  src/site/content/en/blog/browser-nativefs/index.md
Labels: cla: yes

#4417 fix: image is cut off on mobile device when specifying .w-screenshot--filled
  src/styles/components/_images.scss
Labels: cla: yes

#4400 [fix] ElementInternals feature detection
  src/site/content/en/blog/more-capable-form-controls/index.md
Labels: cla: yes

#4415 Add HID blocklist file
  src/site/content/en/blog/hid/index.md
Labels: cla: yes

#4389 Add "Deprecating Excalidraw Electron" case study
  src/site/content/en/blog/deprecating-excalidraw-electron/about-excalidraw.png
  src/site/content/en/blog/deprecating-excalidraw-electron/clipboard.png
  src/site/content/en/blog/deprecating-excalidraw-electron/excalidraw-cache.png
  src/site/content/en/blog/deprecating-excalidraw-electron/excalidraw-desktop.png
  src/site/content/en/blog/deprecating-excalidraw-electron/excalidraw-icon.png
  src/site/content/en/blog/deprecating-excalidraw-electron/excalidraw-pwa.png
  src/site/content/en/blog/deprecating-excalidraw-electron/hero.jpg
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
  src/site/content/en/blog/deprecating-excalidraw-electron/install-excalidraw.png
  src/site/content/en/blog/deprecating-excalidraw-electron/menu.png
Labels: DO NOT MERGE, capabilities, cla: yes

#4434 Update third-party facades audit doc
  src/site/content/en/lighthouse-performance/third-party-facades/index.md
Labels: cla: yes

#4130 Corrected syntax error in code example
  src/site/content/en/blog/trusted-types/index.md
Labels: cla: yes

#4177 Add crop filter to GIF -> video FFMPEG commands
  src/site/content/en/fast/replace-gifs-with-videos/index.md
Labels: cla: yes

#4202 Fix removal of links.
  src/site/content/en/blog/min-max-clamp/index.md
Labels: cla: yes

#4198 Stop implying alternative browsers aren't modern
  src/site/content/en/blog/fetch-metadata/index.md
Labels: cla: yes

#4255 Note that Chrome 88 will disavow opener for target=_blank links
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#4206 Update 'What's mixed content' article
  src/site/content/en/secure/what-is-mixed-content/active-mixed-content.jpg
  src/site/content/en/secure/what-is-mixed-content/index.md
  src/site/content/en/secure/what-is-mixed-content/passive-mixed-content.jpg
Labels: cla: yes

#4289 Adding vanilla-lazyload to the scripts at the end of the page
  src/site/content/en/fast/lazy-loading-images/index.md
Labels: cla: yes

#4442 Fix subhead typo in https://web.dev/autowebperf/
  src/site/content/en/blog/autowebperf/index.md
Labels: cla: yes

#4390 [content update] Declarative Shadow DOM: Update to reflect innerHTML changes
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes, content, content update

#4388 Update publish-modern-javascript to add Devolution tool
  src/site/content/en/fast/publish-modern-javascript/index.md
Labels: cla: yes, content, content update

#4399 Privacy Sandbox post: minor tweak to wording
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: cla: yes

#4435 Update browser support info for ::marker
  src/site/content/en/blog/css-marker-pseudo-element/index.md
Labels: cla: yes

#4433 [Post Update] @property Multiple Declarations
  src/site/content/en/blog/at-property/index.md
Labels: cla: yes

#4443 Add links to the Web Vitals Report repo
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
  src/site/content/en/vitals/index.md
Labels: cla: yes

#4064 Convert "Fast Playback with Video Preload" from WebFu
  src/site/_data/paths/fast.json
  src/site/_data/paths/media.json
  src/site/content/en/blog/fast-playback-with-preload/index.md
  src/site/content/en/blog/fast-playback-with-preload/link-preload.svg
  src/site/content/en/blog/fast-playback-with-preload/video-preload.svg
Labels: cla: yes, content update, media

#4456 Fixed typo
  src/site/content/en/fast/use-lighthouse-for-performance-budgets/index.md
Labels: cla: yes

#4455 [Idle Detection article] Add info about new origin trial
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4458 fix missing image for centering codelab on author page
  src/site/content/en/blog/codelab-centering-in-css/hero.png
  src/site/content/en/blog/codelab-centering-in-css/index.md
  src/site/content/en/blog/codelab-centering-in-css/thumb.png
Labels: cla: yes

#4470 Fix incorrect initialism and link on FCP page
  src/site/content/en/metrics/fcp/index.md
Labels: cla: yes

#4461 Fix duplicate IDs
  src/site/content/en/blog/hid-examples/index.md
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes

#4459 [Media Session article] Update position state section
  src/site/content/en/blog/media-session/chrome-os-lock-screen-media-controls.jpg
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes, content update

#4479 Change verb tense to match current time.
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4494 Fix wording re: LCP calcuation for video elements
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes

#4019 Add animations collection
  src/images/collections/animations.svg
  src/site/_data/paths/animations.json
  src/site/_data/paths/index.js
  src/site/_filters/remove-drafts.js
  src/site/_includes/partials/item.njk
  src/site/content/en/animations/animations-examples/animations-panel.jpg
  src/site/content/en/animations/animations-examples/firefox-waterfall.jpg
  src/site/content/en/animations/animations-examples/index.md
  src/site/content/en/animations/animations-examples/wizard-summary.jpg
  src/site/content/en/animations/animations-guide/css-triggers.jpg
  src/site/content/en/animations/animations-guide/fps-after.jpg
  src/site/content/en/animations/animations-guide/fps-before.jpg
  src/site/content/en/animations/animations-guide/fps-meter.jpg
  src/site/content/en/animations/animations-guide/index.md
  src/site/content/en/animations/animations-guide/paint-flashing.jpg
  src/site/content/en/animations/animations-guide/summary-after.jpg
  src/site/content/en/animations/animations-guide/summary-before.jpg
  src/site/content/en/animations/animations-overview/index.md
  src/site/content/en/animations/index.njk
  src/site/content/en/learn/learn.11tydata.js
  src/styles/pages/_path.scss
Labels: accepted, cla: yes

#4498 Typo
  src/site/content/en/fast/content-delivery-networks/index.md
Labels: cla: yes

#4436 [Serial API article] Add launched info
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/serial/index.md
Labels: DO NOT MERGE, cla: yes

#4440 [Web NFC article] Add launched info
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/nfc/chrome-flag.jpg
  src/site/content/en/blog/nfc/index.md
Labels: cla: yes

#4441 [WebHID article] Add launched info
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/hid-examples/index.md
  src/site/content/en/blog/hid/index.md
Labels: cla: yes

#4501 Include Chrome DevTools color contrast feature
  src/site/content/en/accessible/color-and-contrast-accessibility/apca.png
  src/site/content/en/accessible/color-and-contrast-accessibility/css-overview.png
  src/site/content/en/accessible/color-and-contrast-accessibility/index.md
Labels: cla: yes

#4403 New Post: Building a sidenav component
  src/site/content/en/blog/building-a-sidenav-component/hero.jpg
  src/site/content/en/blog/building-a-sidenav-component/index.md
  src/site/content/en/blog/building-a-sidenav-component/thumb.png
  src/site/content/en/blog/codelab-building-a-sidenav-component/hero.jpg
  src/site/content/en/blog/codelab-building-a-sidenav-component/index.md
  src/site/content/en/blog/codelab-building-a-sidenav-component/thumb.png
Labels: cla: yes

#4495 Trust Token V2 changes to blog post.
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#4476 Add manifest fields for PWA install bottom sheet
  src/images/screenshot1.png
  src/images/screenshot2.png
  src/images/screenshot3.png
  src/misc/manifest.webmanifest
Labels: cla: yes

#4505 Don't let bugs get closed as stale.
  .github/stale.yml
Labels: cla: yes

#4473 Remove no longer maintained Medium channel from footer
  src/site/_includes/devsite/devsite-footer.njk
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#4503 Update capabilities status
  src/site/content/en/blog/content-indexing-api/index.md
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#4453 Update Idle Detection explainer and specification URLs
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4510 Sidenav blog post community submission patch
  src/site/content/en/blog/building-a-sidenav-component/index.md
Labels: cla: yes

#4511 Centering post community patch
  src/site/content/en/blog/centering-in-css/index.md
Labels: cla: yes

#4513 [Excalidraw article] Add canonical URL, add hero alt text, use lowercase web
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
Labels: cla: yes

#4392 Update Accept-CH format
  src/site/content/en/blog/user-agent-client-hints/index.md
Labels: cla: yes

#4500 Correct metrics content for LCP to include removed elements
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#4521 Add Open Web Docs announcement
  src/site/content/en/blog/open-web-docs/index.md
Labels: cla: yes

#4523 Remove cds banner
  src/site/_data/site.js
Labels: cla: yes

#4499 First draft of blog post: The road to a better layout shift metric for long-lived pages
  src/images/authors/anniesullie.jpg
  src/images/authors/anniesullie@2x.jpg
  src/images/authors/mmocny.jpg
  src/images/authors/mmocny@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/better-layout-shift-metric/hero.webp
  src/site/content/en/blog/better-layout-shift-metric/index.md
Labels: cla: yes

#4527 Update the content review checklist
  src/site/content/en/handbook/content-checklist/index.md
Labels: cla: yes

#4353 New articles: when and how to use local https
  src/site/_data/paths/secure.json
  src/site/content/en/blog/how-to-use-local-https/hero.jpg
  src/site/content/en/blog/how-to-use-local-https/index.md
  src/site/content/en/blog/how-to-use-local-https/mkcert.jpg
  src/site/content/en/blog/how-to-use-local-https/selfSigned.jpg
  src/site/content/en/blog/how-to-use-local-https/thumbnail.jpg
  src/site/content/en/blog/how-to-use-local-https/warnings.jpg
  src/site/content/en/blog/when-to-use-local-https/hero.jpg
  src/site/content/en/blog/when-to-use-local-https/hosts.jpg
  src/site/content/en/blog/when-to-use-local-https/index.md
  src/site/content/en/blog/when-to-use-local-https/when-to-use-local-https.png
Labels: cla: yes

#4493 Update performance.measureMemory after renaming
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/detached-window-memory-leaks/index.md
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/blog/why-coop-coep/index.md
Labels: cla: yes

#4466 Update Audit tab to Lighthouse tab
  src/site/_includes/components/Instruction.js
Labels: cla: yes

#4355 feat(search): add highlighting
  src/lib/components/Search/index.js
Labels: cla: yes

#4524 Sidenav - community submission patch #2
  src/site/content/en/blog/building-a-sidenav-component/index.md
Labels: cla: yes

#4533 Fix typos in how-to-use-local-https
  src/site/content/en/blog/how-to-use-local-https/index.md
Labels: cla: yes

#4534 Headings start at h2 instead of h1
  src/site/content/en/blog/better-layout-shift-metric/index.md
Labels: cla: yes

#4539 Add case study guidelines
  src/site/_data/paths/handbook.json
  src/site/content/en/handbook/case-study-guidelines/index.md
Labels: cla: yes

#4536 Update the LCP post for Chrome 88 changes
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#4540 Updated a spelling mistake in index.md
  src/site/content/en/media/video-and-source-tags/index.md
Labels: cla: yes

#4542 Minor fixes to the HTTPS localhost article
  src/site/content/en/blog/how-to-use-local-https/index.md
  src/site/content/en/blog/when-to-use-local-https/index.md
Labels: cla: yes

#4526 content: Carousel best practices
  src/site/content/en/blog/carousel-best-practices/carousel-example.png
  src/site/content/en/blog/carousel-best-practices/hero.jpg
  src/site/content/en/blog/carousel-best-practices/index.md
Labels: cla: yes

#4537 Add WebRTC announcement
  src/images/authors/huib.jpg
  src/images/authors/huib@2x.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/webrtc-standard-announcement/index.md
Labels: DO NOT MERGE, cla: yes

#4545 Add call-to-action in WebRTC post
  src/site/content/en/blog/webrtc-standard-announcement/index.md
Labels: cla: yes

#4502 Add description and screenshots to manifest article
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#4447 [Post] Maintaining Aspect Ratio in CSS
  src/site/content/en/blog/aspect-ratio/aspect-ratio.jpg
  src/site/content/en/blog/aspect-ratio/aspectratio-current.jpg
  src/site/content/en/blog/aspect-ratio/aspectratio-future.jpg
  src/site/content/en/blog/aspect-ratio/coffees.jpg
  src/site/content/en/blog/aspect-ratio/hero.jpg
  src/site/content/en/blog/aspect-ratio/index.md
Labels: cla: yes

#4525 Web share updates for M89
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#4553 Added localhost warning note
  src/site/content/en/blog/how-to-use-local-https/index.md
  src/site/content/en/blog/when-to-use-local-https/when-to-use-local-https.png
Labels: cla: yes, content update

#4552 [Idle Detection article] Add link to spec at end
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4554 Add `screenshots` criteria
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#4444 Add Stack Pack guidance to Lighthouse docs
  src/site/content/en/lighthouse-performance/critical-request-chains/index.md
  src/site/content/en/lighthouse-performance/dom-size/index.md
  src/site/content/en/lighthouse-performance/efficient-animated-content/index.md
  src/site/content/en/lighthouse-performance/font-display/index.md
  src/site/content/en/lighthouse-performance/offscreen-images/index.md
  src/site/content/en/lighthouse-performance/redirects/index.md
  src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
  src/site/content/en/lighthouse-performance/time-to-first-byte/index.md
  src/site/content/en/lighthouse-performance/total-byte-weight/index.md
  src/site/content/en/lighthouse-performance/unminified-css/index.md
  src/site/content/en/lighthouse-performance/unminified-javascript/index.md
  src/site/content/en/lighthouse-performance/unused-css-rules/index.md
  src/site/content/en/lighthouse-performance/unused-javascript/index.md
  src/site/content/en/lighthouse-performance/user-timings/index.md
  src/site/content/en/lighthouse-performance/uses-long-cache-ttl/index.md
  src/site/content/en/lighthouse-performance/uses-optimized-images/index.md
  src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
  src/site/content/en/lighthouse-performance/uses-rel-preload/index.md
  src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
  src/site/content/en/lighthouse-performance/uses-text-compression/index.md
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes

#4519 [WebHID examples article] Add Joy-Con WebHID demo
  src/site/content/en/blog/hid-examples/index.md
Labels: cla: yes

#4520 Fix the grammar of an article title.
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#4518 [Handbook] Add "use as intended" clause
  src/site/content/en/handbook/content-checklist/index.md
Labels: cla: yes

#4532 [Excalidraw Electron article] Add aside and use more inclusive language
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
Labels: cla: yes

#4547 webrtc: fix gfn brand usage
  src/site/content/en/blog/webrtc-standard-announcement/index.md
Labels: cla: yes
