Repository GoogleChrome/web.dev, pull requests merged in 2021-09, with the labels that each got.

#6081 Fixed link to Scroll Survey Report
  src/site/content/en/blog/2021-scroll-survey-report/index.md
Labels: cla: yes

#6090 Fix broken indentation that is messing up translation PRs
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes

#6076 Adding links to more webcodecs demos
  src/site/content/en/blog/webcodecs/index.md
Labels: cla: yes

#6082 build(cloudbuild): migrate deploy to cloud build
  .cloudbuild/deploy.yaml
  .github/workflows/firebase-hosting-cron.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#6091 fix(write-version): use git to get commit sha
  gulp-tasks/write-version.js
Labels: cla: yes

#6095 [Screen Wake Lock article] Add myself to the acknowledgements aside.
  src/site/content/en/blog/wake-lock/index.md
Labels: cla: yes

#6092 Allow for nested content in course sidebar
  .eleventy.js
  src/site/_filters/navigation.js
  src/site/_filters/pad-start.js
  src/site/_includes/course.njk
  src/site/_includes/partials/course-cards.njk
  src/site/_includes/partials/course-index.njk
  src/site/_includes/partials/course-pagination.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/content/en/handbook/adding-a-course/index.md
  src/styles/components/_drawer-course.scss
  types/navigation/navigation-item.d.ts
Labels: cla: yes

#6096 Add caution about null GPU adapter
  src/site/content/en/blog/gpu/index.md
Labels: cla: yes

#6020 Updates to Privacy Sandbox posts
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#6104 Fixed Attribution Reporting link
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
Labels: cla: yes

#6103 maybe deploy script and split
  .cloudbuild/deploy.yaml
  .cloudbuild/version-check.yaml
  version-check.js
Labels: cla: yes

#6110 fixing typo in Project structure, lifecycle, and bundling blog
  src/site/content/en/mini-apps/mini-app-project-structure-lifecycle-and-bundling/index.md
Labels: cla: yes

#6128 fixing url in learn css Inheritance podcast
  src/site/content/en/learn/css/inheritance/index.md
Labels: cla: yes

#6127 fixing url in A more private way to measure ad conversions, the Event Conversion Measurement API blog
  src/site/content/en/blog/conversion-measurement/index.md
Labels: cla: yes

#6124 fixing url in How can performance improve conversion?
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
Labels: cla: yes

#6123 fixing url in Identify slow third-party JavaScript blog
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
Labels: cla: yes

#6122 fixing url in Using bundlesize with Travis CI blog
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
Labels: cla: yes

#6113 Move GPU compute article from WebFu to web.dev
  src/site/content/en/blog/gpu-compute/index.md
  src/site/content/en/blog/gpu/index.md
Labels: cla: yes

#6120 fixing url in Optimizing Web Vitals using Lighthouse blog
  src/site/content/en/blog/optimize-vitals-lighthouse/index.md
Labels: cla: yes

#6119 fixing url in Well-controlled scrolling with CSS Scroll Snap blog
  src/site/content/en/blog/css-scroll-snap/index.md
Labels: cla: yes

#6118 Fixing Url in Deprecating Excalidraw Electron in favor of the web version blog
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
Labels: cla: yes

#6117 fixing url in The Offline Cookbook blog
  src/site/content/en/reliable/offline-cookbook/index.md
Labels: cla: yes

#6116 fixing typo in Insertable streams for MediaStreamTrack blog
  src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
Labels: cla: yes

#6115 fixing url in Evolving Cumulative Layout Shift in web tooling
  src/site/content/en/blog/cls-web-tooling/index.md
Labels: cla: yes

#6106 Fix Url in Does not have a <meta name="viewport"> tag with width or i…
  src/site/content/en/lighthouse-pwa/viewport/index.md
Labels: cla: yes

#6109 fixing broken link in Programming the mini app way blog
  src/site/content/en/mini-apps/mini-app-programming-way/index.md
Labels: cla: yes

#6111 fixing broken link in Setting up a payment method blog
  src/site/content/en/payments/setting-up-a-payment-method/index.md
Labels: cla: yes

#6132 fixing url in HTML5 landmark elements are used to improve navigation blog
  src/site/content/en/lighthouse-accessibility/use-landmarks/index.md
Labels: cla: yes

#6131 fixing url in Browser errors were logged to the console blog
  src/site/content/en/lighthouse-best-practices/errors-in-console/index.md
Labels: cla: yes

#6017 Leverage prettier and regex to improve output formatting
  package.json
  src/pattern-library/patterns/aside/aside.njk
  src/site/_data/design/patterns.js
Labels: cla: yes

#6121 fixing url in Make your PWA feel more like an app blog
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes

#6125 fixing url in Why you need "cross-origin isolated" for powerful featu…
  src/site/content/en/blog/why-coop-coep/index.md
Labels: cla: yes

#6129 fixing url in learn css Filters podcast
  src/site/content/en/learn/css/filters/index.md
Labels: cla: yes

#6130 fixing url in Setting up a payment method blog
  src/site/content/en/payments/setting-up-a-payment-method/index.md
Labels: cla: yes

#6135 fixing typo in Sign-up form best practices codelab
  src/site/content/en/blog/codelab-sign-up-form-best-practices/index.md
Labels: cla: yes

#6142 fixing url in Remove unused code blog
  src/site/content/en/fast/remove-unused-code/index.md
Labels: cla: yes

#6143 fixing url in What should you measure to improve performance?
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
Labels: cla: yes

#6146 fixing url in Sensors for the web blog
  src/site/content/en/blog/generic-sensor/index.md
Labels: cla: yes

#6147 fixing url in Modern client-side routing: the App History API blog
  src/site/content/en/blog/app-history-api/index.md
Labels: cla: yes

#6138 Change URL for FFMPEG demo
  src/site/content/en/blog/webassembly-threads/index.md
Labels: cla: yes

#6137 Remove flag for screenshots and description
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#6149 [Mini Apps] Add VK mini apps
  src/site/content/en/mini-apps/mini-app-alternative-runtime-environments/index.md
Labels: cla: yes

#6152 Update .gitlocalize.yml
  .gitlocalize.yml
Labels: cla: yes

#6151 Remove unneeded hardcoded i18n strings
  src/site/content/en/blog/blog.11tydata.js
  src/site/content/es/blog/blog.11tydata.js
Labels: cla: yes

#6141 fixing url and removing en-us in Read from and write to a serial port blog
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#6144 fixing url in Preloading responsive images blog
  src/site/content/en/blog/preload-responsive-images/index.md
Labels: cla: yes

#6145 fixing url in Improved Next.js and Gatsby page load performance with granular chunking blog
  src/site/content/en/blog/granular-chunking-nextjs/index.md
Labels: cla: yes

#6148 fixing url in Optimize CSS background images with media queries blog
  src/site/content/en/fast/optimize-css-background-images-with-media-queries/index.md
Labels: cla: yes

#6053 Add post about new URL pattern
  src/site/content/en/blog/bundling-non-js-resources/index.md
Labels: cla: yes

#6161 fixing url in Virtual reality comes to the web, part II blog
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
Labels: cla: yes

#6164 App History API article - Typo fix
  src/site/content/en/blog/app-history-api/index.md
Labels: cla: yes

#6163 [PWAs as URL Handlers article] Clarify this only works for the default browser
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#6155 Updates for URLPattern: shipping in M95
  src/site/content/en/blog/urlpattern/index.md
Labels: cla: yes

#6012 Blog post gui challenge split button
  src/site/content/en/building-a-split-button-component/index.md
Labels: cla: yes, blog

#6168 fixing url in Positioning virtual objects in real-world views
  src/site/content/en/blog/ar-hit-test/index.md
Labels: cla: yes

#6166 fixing url in Project structure, lifecycle, and bundling
  src/site/content/en/mini-apps/mini-app-project-structure-lifecycle-and-bundling/index.md
Labels: cla: yes

#6167 fixing url in Identify slow third-party JavaScript
  src/site/content/en/fast/identify-slow-third-party-javascript/index.md
Labels: cla: yes

#6108 Fixing ImageMagick URL in Using AVIF to compress images on your site blog
  src/site/content/en/blog/compress-images-avif/index.md
Labels: cla: yes

#6170 throw on missing i18n string
  src/site/_filters/i18n.js
  src/site/_includes/partials/navigation-drawer-course.njk
Labels: cla: yes

#6169 Fix small typo in wasm-pack example
  src/site/content/en/blog/bundling-non-js-resources/index.md
Labels: cla: yes

#6134 fixing url in Declarative Shadow DOM blog
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#6162 fixing url in Preparing for AppCache removal article
  src/site/content/en/blog/appcache-removal/index.md
Labels: cla: yes

#6136 Add VirtualKeyboard API article
  src/site/content/en/blog/virtualkeyboard/index.md
Labels: cla: yes

#6165 Replace in css speak: none with speak: never
  src/styles/components/_buttons.scss
  src/styles/components/_details.scss
  src/styles/components/_self-assessment-hint.scss
Labels: cla: yes

#6173 Nit fix
  src/site/content/en/blog/bundling-non-js-resources/index.md
Labels: cla: yes

#6176 Fix grid bug in CH93
  src/styles/components/_code-pattern.scss
  src/styles/pages/_code-patterns.scss
Labels: cla: yes

#6174 Provide more specific link to Parcel docs
  src/site/content/en/blog/bundling-non-js-resources/index.md
Labels: cla: yes

#6160 fixing url in Next-generation web styling blog
  src/site/content/en/blog/next-gen-css-2019/index.md
Labels: cla: yes

#6126 fixing url in SameSite cookie recipes blog
  src/site/content/en/blog/samesite-cookie-recipes/index.md
Labels: cla: yes

#6181 Update webdev infra version
  package-lock.json
  package.json
Labels: cla: yes

#6045 Add eventing article
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/eventing-deepdive/index.md
Labels: cla: yes

#6188 Fixes #6187 - Update UA-CH article content now that M93 is stable
  src/site/content/en/blog/user-agent-client-hints/index.md
Labels: cla: yes

#6191 Eventing Deep Dive: typo fix
  src/site/content/en/blog/eventing-deepdive/index.md
Labels: cla: yes

#6186 Chinese - Fix Incorrect language code and translation
  src/lib/utils/language.js
Labels: cla: yes

#6189 Temporarily removed Igalia link
  src/site/content/en/blog/2021-scroll-survey-report/index.md
Labels: cla: yes

#6185 Remove lint rules
  .remarkrc.js
  tools/linting/no-dash-spaces.js
  tools/linting/no-smart-quotes.js
Labels: cla: yes

#6194 fix(newsletter): use zh-TW for Taiwan, fixes #6193
  src/site/_data/countries.js
Labels: cla: yes

#6196 JavaScript Eventing Deep Dive: Fix 2 live demo links to match the text
  src/site/content/en/blog/eventing-deepdive/index.md
Labels: cla: yes

#6114 Learn forms 1: The Form Element.
  src/site/_data/authorsData.json
  src/site/_data/courses/forms/toc.yml
  src/site/_data/i18n/authors.yml
  src/site/_data/i18n/courses.yml
  src/site/content/en/learn/forms/auto/auto.assess.yml
  src/site/content/en/learn/forms/auto/index.md
  src/site/content/en/learn/forms/example/index.md
  src/site/content/en/learn/forms/form-element/form-element.assess.yml
  src/site/content/en/learn/forms/form-element/index.md
  src/site/content/en/learn/forms/form-fields/form-fields.assess.yml
  src/site/content/en/learn/forms/form-fields/index.md
Labels: DO NOT MERGE, cla: yes

#6197 [Eventing deep dive] Origin of all events is window, not document
  src/site/content/en/blog/eventing-deepdive/index.md
Labels: cla: yes

#6200 feat(tags): automagically add `origin-trials` tag to posts, fixes #3311
  src/site/content/content.11tydata.js
Labels: cla: yes

#6199 Fix typo
  src/site/content/en/fast/serve-modern-code-to-modern-browsers/index.md
Labels: cla: yes

#6204 [Progressive Web Apps as URL Handlers article] Add OT info
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#6209 Fixed link to GDDSGWL in word list
  src/site/content/en/handbook/word-list/index.md
Labels: cla: yes

#6069 build(presubmit): create a presubmit step, fixes #5793
  .github/actions/presubmit/action.yml
  .github/actions/presubmit/index.js
  .github/pull_request_template.md
  .github/workflows/presubmit-workflow.yml
  package-lock.json
  package.json
  src/site/content/en/handbook/pull-requests/index.md
Labels: cla: yes

#6207 Enable no-smart-quotes linter for code samples
  .remarkrc.js
  src/site/content/en/design-system/css-utilities.md
  src/site/content/en/handbook/markup-code/index.md
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/reliable/codelab-building-resilient-search-experiences/index.md
  src/site/content/en/reliable/imperative-caching-guide/index.md
  tools/linting/no-smart-quotes.js
Labels: cla: yes

#6202 refactor(firestore): move firestore backup from GitHub Actions to Firebase Function
  .github/workflows/snapshot-firestore-workflow.yml
  firebase.incl.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/pubsub/scheduled-firestore-export.js
  package.json
Labels: cla: yes

#6213 refactor(workflows): simplify checkout and node setup
  .github/workflows/lighthouse-ci-workflow.yml
  .github/workflows/lint-and-test-workflow.yml
  .github/workflows/percy-workflow.yml
Labels: cla: yes

#6211 Add Swappie case study
  src/site/content/en/blog/swappie/index.md
Labels: cla: yes

#6214 Update Web Vitals Patterns cover image
  src/site/content/en/patterns/web-vitals-patterns/index.md
Labels: cla: yes

#6212 test(presubmit): move some other workflow steps to presubmit workflow, fixes #4612
  .github/workflows/lighthouse-ci-workflow.yml
  .github/workflows/lint-workflow.yml
  .github/workflows/presubmit-workflow.yml
  karma.conf.js
  package.json
  rollup.config.js
  test/integration/build-test.js
  tools/lhci/lighthouserc.js
  tools/lhci/lighthouserc.json
Labels: cla: yes

#6218 Render component helper
  src/scss/blocks/_toggle-switch.scss
  src/site/_data/design/components.js
  src/site/_includes/macros/design-system-component.njk
  src/site/content/en/design-system/components.njk
  src/site/content/en/design-system/pages.njk
Labels: cla: yes

#6219 Remove the auto dark mode for now
  src/scss/blocks/_prose.scss
  src/site/_data/design/themes.js
Labels: cla: yes

#6224 [getInstalledRelatedApps article] Add spec link, update explainer link
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#6221 Update JS eventing post
  src/site/content/en/blog/eventing-deepdive/index.md
Labels: cla: yes

#6216 Add How SPA architectures affect Core Web Vitals post
  src/site/content/en/blog/vitals-spa-faq/index.md
Labels: cla: yes

#6229 Update pattern descriptions
  src/site/content/en/patterns/web-vitals-patterns/carousels/carousel-autoplay/index.md
  src/site/content/en/patterns/web-vitals-patterns/carousels/index.md
  src/site/content/en/patterns/web-vitals-patterns/fonts/font-self-hosted/index.md
  src/site/content/en/patterns/web-vitals-patterns/fonts/fonts-third-party/index.md
  src/site/content/en/patterns/web-vitals-patterns/fonts/index.md
  src/site/content/en/patterns/web-vitals-patterns/images/img-tag/index.md
  src/site/content/en/patterns/web-vitals-patterns/images/responsive-images/index.md
  src/site/content/en/patterns/web-vitals-patterns/infinite-scroll/infinite-scroll/index.md
  src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/notice-animated-footer/index.md
  src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/notice-modal/index.md
  src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/notice-sticky-footer/index.md
  src/site/content/en/patterns/web-vitals-patterns/placeholders/placeholders/index.md
  src/site/content/en/patterns/web-vitals-patterns/video/video-gif/index.md
  src/site/content/en/patterns/web-vitals-patterns/video/video/index.md
Labels: cla: yes

#6201 Learn css image update
  src/images/courses/css/background.svg
  src/images/courses/css/card.svg
  src/images/courses/css/logo.svg
  src/site/_data/courses/css/meta.yml
  src/styles/components/_course-card.scss
  src/styles/components/_drawer-course.scss
  src/styles/components/_header-course.scss
Labels: cla: yes

#6158 Add more course set up instructions
  src/site/content/en/handbook/adding-a-course/index.md
Labels: cla: yes

#6089 Let authors use markdown in course titles and descriptions.
  src/site/_includes/course.njk
  src/styles/generic/_code.scss
Labels: cla: yes

#6184 Update patterns design to use Details zip
  src/site/_data/i18n/patterns.yml
  src/site/_includes/components/CodePattern.js
  src/site/_includes/macros/code-pattern.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/pattern-page.njk
  src/site/_includes/pattern-set.njk
  src/site/_includes/pattern.njk
  src/styles/components/_code-pattern.scss
  src/styles/components/_mastheads.scss
  src/styles/pages/_code-patterns.scss
Labels: cla: yes

#6239 Remove aspect-ratio from patterns
  src/site/content/en/patterns/web-vitals-patterns/carousels/carousel-autoplay/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/carousels/carousel-autoplay/demo.njk
  src/site/content/en/patterns/web-vitals-patterns/placeholders/placeholders/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/placeholders/placeholders/demo.njk
Labels: cla: yes

#6238 Webkit fixes for patterns page
  src/styles/components/_code-pattern.scss
  src/styles/pages/_code-patterns.scss
Labels: cla: yes

#6228 Add translations for i18n strings
  src/site/_data/i18n/authors.yml
  src/site/_data/i18n/browser_compat.yml
  src/site/_data/i18n/common.yml
  src/site/_data/i18n/courses.yml
  src/site/_data/i18n/footer.yml
  src/site/_data/i18n/header.yml
  src/site/_data/i18n/learn.yml
  src/site/_data/i18n/paths/accessible.yml
  src/site/_data/i18n/paths/angular.yml
  src/site/_data/i18n/paths/animations.yml
  src/site/_data/i18n/paths/authors.yml
  src/site/_data/i18n/paths/devices.yml
  src/site/_data/i18n/paths/discoverable.yml
  src/site/_data/i18n/paths/fast.yml
  src/site/_data/i18n/paths/handbook.yml
  src/site/_data/i18n/paths/learn_web_vitals.yml
  src/site/_data/i18n/paths/lighthouse_accessibility.yml
  src/site/_data/i18n/paths/lighthouse_best_practices.yml
  src/site/_data/i18n/paths/lighthouse_performance.yml
  src/site/_data/i18n/paths/lighthouse_pwa.yml
  src/site/_data/i18n/paths/lighthouse_seo.yml
  src/site/_data/i18n/paths/media.yml
  src/site/_data/i18n/paths/metrics.yml
  src/site/_data/i18n/paths/mini_apps.yml
  src/site/_data/i18n/paths/notifications.yml
  src/site/_data/i18n/paths/payments.yml
  src/site/_data/i18n/paths/progressive_web_apps.yml
  src/site/_data/i18n/paths/react.yml
  src/site/_data/i18n/paths/reliable.yml
  src/site/_data/i18n/paths/secure.yml
  src/site/_data/i18n/paths/shows.yml
  src/site/_data/i18n/paths/tags.yml
  src/site/_data/i18n/patterns.yml
  src/site/_data/i18n/post.yml
  src/site/_data/i18n/shows.yml
  src/site/_data/i18n/stackoverflow.yml
  src/site/_data/i18n/subscribe.yml
  src/site/_data/i18n/tags.yml
  src/site/_data/i18n/toc.yml
Labels: cla: no

#6230 Add Envoy SXG Filter to Tooling.
  src/site/content/en/fast/signed-exchanges/index.md
Labels: cla: yes

#6253 remove ref to interface type in App History API post
  src/site/content/en/blog/app-history-api/index.md
Labels: cla: yes

#6254 allow more ram during build (seeing sometimes failures)
  .cloudbuild/deploy.yaml
Labels: cla: yes

#6232 Learn Forms Accessibility
  src/site/content/en/learn/forms/accessibility/index.md
Labels: cla: yes, $-presubmit

#6231 Adds Learn Forms Testing
  src/site/content/en/learn/forms/testing/index.md
  src/site/content/en/learn/forms/testing/testing.assess.yml
Labels: cla: yes, $-presubmit

#6223 Learn Forms Validation module
  src/site/content/en/learn/forms/validation/index.md
  src/site/content/en/learn/forms/validation/validation.assess.yml
Labels: cla: yes, $-presubmit

#6256 Remove autofocus recommendation
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes

#6257 test(presubmit): build a staging version of site to speed up HTML and CSS transforms
  .github/workflows/presubmit-workflow.yml
  src/site/_collections/hooks/utils.js
  src/site/_transforms/minify-html.js
  src/site/_transforms/purify-css.js
Labels: cla: yes

#6262 fix(deploy): properly format NODE_OPTIONS
  .cloudbuild/deploy.yaml
  version-check.js
Labels: cla: yes

#6265 fix(deploy): set NODE_OPTIONS differently
  .cloudbuild/deploy.yaml
Labels: cla: yes

#6263 add tmp to eslintignore
  .eslintignore
Labels: cla: yes

#6269 [File handling article] Add icons
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#6272 PWA summit, registration banner.
  src/site/_data/site.js
Labels: cla: yes

#6268 Add i18n to search component
  src/lib/components/Search/index.js
  src/site/_data/i18n/search.yml
  src/site/_includes/partials/header-default.njk
Labels: cla: yes

#6264 Add speculative prerendering post
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: cla: yes

#6284 Speculative prerendering minor edits
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: cla: yes

#6277 speculative prerendering: fix example code blocks
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: cla: yes, $-presubmit

#6275 Storage Foundation: clarify interop
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/storage-foundation/index.md
Labels: cla: yes

#6290 Minor grammar fixes
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: cla: yes, $-presubmit

#6282 [Pre-rendering API article] Proposed API
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: cla: yes

#6286 Added vanilla-lazyload alongside lozad
  src/site/content/en/fast/lazy-loading-video/index.md
Labels: cla: yes, $-presubmit

#6298 Small update to COOP/COEP
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#6203 Migrate Web Payments from WebFu
  redirects.yaml
  src/site/_data/i18n/paths/payments.yml
  src/site/_data/paths/payments.json
  src/site/_includes/content/payments/browser-compatibility.njk
  src/site/content/en/payments/android-payment-apps-delegation/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/handling-optional-payment-information/index.md
  src/site/content/en/payments/how-payment-ecosystem-works/index.md
  src/site/content/en/payments/how-payment-request-api-works/index.md
  src/site/content/en/payments/life-of-a-payment-transaction/index.md
  src/site/content/en/payments/orchestrating-payment-transactions/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/payments/web-based-payment-apps-overview/index.md
  src/site/content/en/payments/web-payments-overview/index.md
Labels: cla: yes

#6267 Learn Forms design basics
  src/site/_data/courses/forms/toc.yml
  src/site/_data/i18n/courses.yml
  src/site/content/en/learn/forms/design-basics/design-basics.assess.yml
  src/site/content/en/learn/forms/design-basics/index.md
Labels: cla: yes, $-presubmit

#6304 Handle array `support` in browser compat widget
  src/site/_includes/components/BrowserCompat.js
Labels: cla: yes

#6305 Remove locale from mdn link
  src/site/content/en/learn/forms/design-basics/index.md
Labels: cla: yes

#6302 Update Media Session article with WebKit support
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes, $-presubmit

#6291 Add web-tabs to handbook
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#6261 Add i18n string for share
  src/site/_includes/partials/post.njk
Labels: cla: yes

#6259 Add translated-to widget to posts
  .eleventy.js
  shared/locale.js
  src/site/_data/i18n/post.yml
  src/site/_filters/urls.js
  src/site/_includes/components/LanguageList.js
  src/site/_includes/components/Meta.js
  src/site/_includes/partials/post.njk
Labels: cla: yes

#6296 improve toc discoverability
  .eleventy.js
  src/lib/components/TableOfContents/index.js
  src/site/_includes/partials/post.njk
  src/styles/components/_toc.scss
Labels: cla: yes

#6260 Add i18n string for appears_in
  src/site/_data/i18n/post.yml
  src/site/_includes/components/SignPosts.js
  src/site/_includes/show.njk
Labels: cla: yes

#6247 Move platform-specific SXG tooling to the top.
  src/site/content/en/fast/signed-exchanges/index.md
Labels: cla: yes, $-presubmit

#6308 dont open toc automatically
  src/site/_includes/partials/post.njk
Labels: cla: yes

#6295 Fixed spelling mistake
  src/site/content/ru/metrics/fid/index.md
Labels: cla: yes, $-presubmit

#6258 maskable icons: fix small typo
  src/site/content/en/lighthouse-pwa/maskable-icon-audit/index.md
Labels: cla: yes

#6252 Clarify pattern docs
  src/site/content/en/patterns/example-set/example-pattern/demo.md
  src/site/content/en/patterns/example-set/example-pattern/index.md
  src/site/content/en/patterns/example-set/full-html-demo/assets/body.html
  src/site/content/en/patterns/example-set/full-html-demo/assets/script.js
  src/site/content/en/patterns/example-set/full-html-demo/demo.md
  src/site/content/en/patterns/example-set/full-html-demo/index.md
  src/site/content/en/patterns/example-set/image-demo/assets/sample.html
  src/site/content/en/patterns/example-set/image-demo/assets/sample.njk
  src/site/content/en/patterns/example-set/image-demo/demo.md
  src/site/content/en/patterns/example-set/image-demo/index.md
  src/site/content/en/patterns/example-set/index.md
Labels: cla: yes

#6301 Add identity section
  src/images/collections/identity.svg
  src/site/_data/i18n/paths/identity.yml
  src/site/_data/paths/identity.json
  src/site/_data/paths/index.js
  src/site/content/en/identity/change-password-url/index.md
  src/site/content/en/identity/index.njk
  src/site/content/en/identity/sign-in-form-best-practices/index.md
  src/site/content/en/identity/sign-up-form-best-practices/index.md
  src/site/content/en/identity/sms-otp-form/index.md
  src/site/content/en/identity/web-otp/index.md
  src/site/content/en/learn/learn.11tydata.js
  src/site/content/es/es.11tydata.js
  src/site/content/ja/ja.11tydata.js
  src/site/content/ko/ko.11tydata.js
  src/site/content/pl/pl.11tydata.js
  src/site/content/pt/pt.11tydata.js
  src/site/content/ru/ru.11tydata.js
  src/site/content/zh/zh.11tydata.js
Labels: cla: yes

#6303 [Web Transport article] Update DevTools bug
  src/site/content/en/blog/webtransport/index.md
Labels: cla: yes
