Repository GoogleChrome/web.dev, pull requests merged in 2021-02, with the labels that each got.

#4562 Sidenav: community remix addition patch
  src/site/content/en/blog/building-a-sidenav-component/index.md
Labels: cla: yes

#4564 fix(meta): replace lt/gt sign with single l/r pointing angle quotation mark
  src/site/_filters/strip.js
  src/site/_includes/components/Meta.js
Labels: cla: yes

#4448 Add Origin-Agent-Cluster article
  src/site/content/en/blog/origin-agent-cluster/hero.jpg
  src/site/content/en/blog/origin-agent-cluster/index.md
Labels: cla: yes

#4563 Sidenav post: community submission patch #4
  src/site/content/en/blog/building-a-sidenav-component/index.md
Labels: cla: yes

#4567 fix(canoical) use page data from source to generate canonical URLs, fixes #4504
  src/site/_includes/components/Meta.js
Labels: cla: yes

#4560 Update screenshots requirements
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#4568 [Origin-Agent-Cluster article] Typo and minor nit fix
  src/site/content/en/blog/origin-agent-cluster/index.md
Labels: cla: yes

#4544 Rename browser-nativefs to browser-fs-access
  src/site/content/_redirects.yaml
  src/site/content/en/blog/browser-fs-access/caniuse.png
  src/site/content/en/blog/browser-fs-access/chrome-modify.png
  src/site/content/en/blog/browser-fs-access/chrome-oversave.png
  src/site/content/en/blog/browser-fs-access/chrome-save-as.png
  src/site/content/en/blog/browser-fs-access/hero.jpg
  src/site/content/en/blog/browser-fs-access/index.md
  src/site/content/en/blog/browser-fs-access/iphone-original.png
  src/site/content/en/blog/browser-fs-access/save-save-as.png
  src/site/content/en/blog/browser-fs-access/save.png
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/read-files/index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
Labels: cla: yes

#4549 [Idle Detection] Refine OT info
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#4477 Minor tweaks to index.md
  src/site/content/en/blog/streams/index.md
Labels: cla: yes

#4569 Fix the typo in COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: no

#4574 Remove unnecessary interpolation escape
  src/site/content/en/angular/faster-angular-change-detection/index.md
  src/site/content/en/angular/virtualize-lists-with-angular-cdk/index.md
Labels: cla: yes

#4566 Update end date for AppCache origin trial
  src/site/content/en/blog/appcache-removal/index.md
Labels: cla: yes

#4528 [Text Fragments article] Add ::target-text
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#4559 Update Trust Tokens post to include DevTools information
  src/site/content/en/blog/trust-tokens/images/devtools-application-tab.jpg
  src/site/content/en/blog/trust-tokens/images/devtools-network-tab.jpg
  src/site/content/en/blog/trust-tokens/images/hero.jpg
  src/site/content/en/blog/trust-tokens/images/thumbnail.jpg
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#4561 Promote json extension instead of webmanifest for manifest
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#4592 update codeowners to include approvers team
  .github/CODEOWNERS
Labels: cla: yes

#4572 Add a note about `registrationStrategy`
  src/site/content/en/angular/creating-pwa-with-angular-cli/index.md
Labels: cla: yes

#4550 [File System Access article] Add serialization instructions
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4594 [Animation examples] Fix typo
  src/site/content/en/animations/animations-examples/index.md
Labels: cla: yes

#4600 Remove the threshold recommendation for FCP
  src/site/content/en/metrics/fcp/index.md
Labels: cla: yes

#4597 Fix hidden caution on mobile
  src/site/content/en/blog/how-to-use-local-https/index.md
Labels: cla: yes

#4604 Fix Netlify CDN reference link
  src/site/content/en/blog/love-your-cache/index.md
Labels: cla: yes

#4602 Improve body banner and list styles
  src/site/content/en/blog/how-to-use-local-https/index.md
  src/styles/components/_banner.scss
  src/styles/generic/_lists.scss
Labels: cla: yes

#4576 Update the PR template to mention the proposal form and draft mode
  .github/pull_request_template.md
Labels: cla: yes

#4585 A guide to enable cross-origin isolation
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#4590 Rename Serial API to Web Serial API
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/serial/index.md
Labels: cla: yes, content update

#4608 Trust Tokens docs: clean up a few syntax errors, and add context to a…
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#4589 Add instructions for Gatsby stack
  src/site/content/en/lighthouse-performance/uses-responsive-images/index.md
Labels: cla: yes

#4587 Add an instruction to set up a reporting endpoint to COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/coop-coep/reporting-endpoint.png
Labels: cla: yes

#4607 Updated link to canonical source
  src/site/content/en/fast/why-speed-matters/index.md
Labels: cla: yes

#4616 Remove link to Raw Clipboard design doc
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#4497 Update share and share target articles for M89 support.
  src/site/content/en/blog/web-share-target/index.md
  src/site/content/en/blog/web-share/index.md
Labels: Chrome 89, beta related, cla: yes, content update

#4617 [File System Access article] Write origin private file system without dash
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4627 feat(redirects): send all requests to `en/*` to `*`
  redirects.yaml
Labels: cla: yes

#4628 Escape HTML titles/descriptions when displaying them as search results
  src/lib/components/Search/index.js
  src/lib/utils/escape-html.js
Labels: cla: yes

#4613 Remove SPA and service worker
  .eleventy.js
  .eslintrc.js
  build.js
  compile-css.js
  gulp-tasks/sass.js
  gulpfile.js
  package-lock.json
  package.json
  rollup.config.js
  src/build/common.js
  src/build/hash.js
  src/build/minify-js.js
  src/build/resource-path.js
  src/lib/app.js
  src/lib/bootstrap.js
  src/lib/components/Search/index.js
  src/lib/fb.js
  src/lib/loader.js
  src/lib/pages/content.js
  src/lib/pages/default.js
  src/lib/pages/newsletter.js
  src/lib/sw.js
  src/lib/utils/firebase-loader.js
  src/lib/utils/sw-match.js
  src/lib/webcomponents-config.js
  src/site/_data/helpers.js
  src/site/_data/lib/hash.js
  src/site/_data/process.js
  src/site/_data/resource.js
  src/site/_includes/codelab.njk
  src/site/_includes/handbook.njk
  src/site/_includes/layout.njk
  src/site/_includes/newsletter.njk
  src/site/_includes/partials/analytics.njk
  src/site/_includes/post.njk
  src/site/_transforms/minify-html.js
  src/site/_transforms/purify-css.js
  src/site/content/en/live/index.njk
  src/site/content/en/measure/index.njk
  src/styles/main.scss
  sw-manifest.js
  test/integration/build-test.js
  test/unit/src/lib/utils/firebase-loader.js
  types/modules/webdev_entrypoint/index.d.ts
Labels: cla: yes

#4622 Minor updates to PWA IA & code cleanup
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/progressive-web-apps/customize-install/index.md
  src/site/content/en/progressive-web-apps/install-criteria/index.md
Labels: cla: yes

#4646 feat(imigix): add `Img` and `Video` shortcodes
  .eleventy.js
  .eslintrc.js
  package-lock.json
  package.json
  src/site/_data/site.js
  src/site/_includes/components/Img.js
  src/site/_includes/components/Video.js
  src/site/content/en/handbook/markup-media/index.md
  types/site/_includes/components/Img.d.ts
  types/site/_includes/components/Video.d.ts
Labels: cla: yes

#4626 Clarify support matrix for `getInstalledRelatedApps`
  src/site/content/en/blog/get-installed-related-apps/index.md
Labels: cla: yes

#4623 Updates to storage doc
  src/site/content/en/blog/storage-for-the-web/devtools-storage-panel.png
  src/site/content/en/blog/storage-for-the-web/index.md
  src/site/content/en/blog/storage-for-the-web/storage-test-tool.png
Labels: cla: yes

#4654 Make browser compatibility info up to date
  src/site/content/en/fast/preload-critical-assets/index.md
Labels: cla: yes

#4472 [Post] Accessing hardware devices on the web
  src/site/_data/paths/devices.json
  src/site/content/en/blog/devices-introduction/hero.jpg
  src/site/content/en/blog/devices-introduction/index.md
  src/site/content/en/blog/devices-introduction/thumbnail.jpg
Labels: cla: yes

#4658 Remove thumbnail
  src/site/content/en/blog/devices-introduction/index.md
  src/site/content/en/blog/devices-introduction/thumbnail.jpg
Labels: cla: yes

#4652 Sign-up and sign-in form articles: added sentence to each
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/sign-up-form-best-practices/index.md
Labels: cla: yes

#4414 Updated article "Using conversion measurement"
  src/site/content/en/blog/using-conversion-measurement/index.md
Labels: DO NOT MERGE, cla: yes

#4631 Updated encoding and conversiondestination definition
  src/site/content/en/blog/conversion-measurement/index.md
Labels: cla: yes, content update

#4662 [Img component] Prevent markup bloat
  src/site/_includes/components/Img.js
Labels: cla: yes

#4666 Remove approvers team to cut down on spam.
  .github/CODEOWNERS
Labels: cla: yes

#4673 move nuke SW script
  src/misc/sw.js
  test/integration/build-test.js
Labels: cla: yes

#4656 Add a link to COOP/COEP guide, embed two videos
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#4661 Synchronize LanguageSelect element state with real language of the page
  src/lib/actions.js
  src/lib/app.js
  src/lib/components/LanguageSelect/index.js
  src/lib/urls.js
  src/lib/utils/language.js
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#4674 [Video component] The `autoplay` attribute needs to go along with `playsinline` for iOS
  src/site/_includes/components/Video.js
Labels: cla: yes

#4625 Don't show lastmod if we don't have a date or updated.
  src/site/content/sitemap.xml.njk
Labels: cla: yes

#4651 Minor updates to installable PWA codelab
  src/site/content/en/progressive-web-apps/codelab-make-installable/index.md
Labels: cla: yes

#4682 Add pullapprove config file.
  .pullapprove.yml
Labels: cla: yes

#4664 Fixes #4663 - Use correct value for Sec-CH-UA-Arch example
  src/site/content/en/blog/user-agent-client-hints/index.md
Labels: cla: yes

#4678 Temporary redirect for CORS-RFC1918 guidance
  redirects.yaml
Labels: cla: yes

#4668 New Post: GUI Challenges - Tabs
  src/site/content/en/blog/building-a-tabs-component/hero.png
  src/site/content/en/blog/building-a-tabs-component/index.md
  src/site/content/en/blog/building-a-tabs-component/thumb.png
Labels: cla: yes

#4689 Fixes missing thumbnail for Tabs post
  src/site/content/en/blog/building-a-tabs-component/index.md
Labels: cla: yes

#4690 Refine pullapprove groupings based on feedback from pullapprove team.
  .pullapprove.yml
Labels: cla: yes

#4691 Remove codeowners file.
  .github/CODEOWNERS
Labels: cla: yes

#4694 Add max dpr multiplier
  src/site/_includes/components/Img.js
Labels: cla: yes

#4695 Minor updates to the Create React App article
  src/site/content/en/react/add-manifest-react/index.md
Labels: cla: yes

#4659 [Screen Wake Lock article] Add task manager video
  src/site/content/en/blog/wake-lock/index.md
Labels: cla: yes

#4669 Changes color-scheme meta tag link URL from W3C draft to Whatwg
  src/site/content/en/blog/color-scheme/index.md
Labels: cla: yes

#4603 Migrate and update "Generic Sensor API" article from WebFu
  src/images/authors/alexshalamov.jpg
  src/site/_data/authorsData.json
  src/site/content/en/blog/generic-sensor/index.md
Labels: cla: yes

#4697 [Generic Sensor article] Fix hero image
  src/site/content/en/blog/generic-sensor/hero.jpg
  src/site/content/en/blog/generic-sensor/index.md
Labels: cla: yes

#4701 Feat/courses basic
  src/site/_includes/base.njk
  src/site/_includes/codelab.njk
  src/site/_includes/course.njk
  src/site/_includes/default.njk
  src/site/_includes/handbook.njk
  src/site/_includes/homepage.njk
  src/site/_includes/layout.njk
  src/site/_includes/newsletter.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/header.njk
  src/site/_includes/partials/side-nav.njk
  src/site/_includes/path.njk
  src/site/_includes/post.njk
  src/site/_includes/text.njk
  src/site/content/en/404.md
  src/site/content/en/about/index.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/learn/css/index.md
  src/site/content/en/learn/index.njk
  src/site/content/en/live/index.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/newsletter/index.njk
  src/site/content/en/offline.md
  src/site/content/en/podcasts/index.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
  src/site/content/pl/404.md
  src/site/content/pl/offline.md
Labels: cla: yes

#4672 Initial commit on removing the OT information and updating the article
  src/site/content/en/blog/hands-on-portals/index.md
Labels: cla: yes

#4693 Improve cross-origin isolation related documents
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#4686 [Device Introduction article] Update generic sensor link
  src/site/content/en/blog/devices-introduction/index.md
Labels: cla: yes

#4378 Add Streams article
  src/site/content/en/blog/streams/hero.jpg
  src/site/content/en/blog/streams/index.md
  src/site/content/en/blog/streams/streams.svg
Labels: capabilities, cla: yes, new content

#4706 [Streams article] Fix hero, move inline image to CDN
  src/site/content/en/blog/streams/hero.jpg
  src/site/content/en/blog/streams/index.md
  src/site/content/en/blog/streams/streams.svg
Labels: cla: yes

#4698 [File System Access API article] Add directory serialization example
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4707 fix(images): use image cdn for meta tags and rss feeds
  .eleventy.js
  src/site/_includes/components/Img.js
  src/site/_includes/components/Meta.js
  src/site/content/en/authors/feed.njk
Labels: cla: yes

#4681 Add instructions re: SXGs using Web Packager
  src/site/content/en/fast/signed-exchanges-webpackager/index.md
Labels: cla: yes

#4705 Add an update note about COOP/COEP articles changes
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#4712 Updated source link based on changed url structure for caniuse.com
  src/site/content/en/blog/browser-fs-access/index.md
Labels: cla: yes

#4714 Correct a link that 404s
  src/site/content/en/blog/trusted-types/index.md
Labels: cla: yes

#4717 [Offline Fallback Page article] Add automatic reload feature
  src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
Labels: cla: yes

#4719 Remove alex
  .github/workflows/alex-workflow.yml
Labels: cla: yes

#4709 Improve CLS on Authors page regression
  src/site/content/en/authors/individual.njk
  src/styles/pages/_author.scss
Labels: cla: yes

#4715 [File System Access API article] Document random access
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#4736 Courses layout
  .sasslintrc
  src/build/output-permalink.js
  src/site/_includes/base.njk
  src/site/_includes/course.njk
  src/site/_includes/default.njk
  src/site/content/en/learn/css/index.md
  src/styles/components/_all.scss
  src/styles/components/_app-bar.scss
  src/styles/components/_skip-link.scss
  src/styles/components/_youtube.scss
  src/styles/overrides/_spacing.scss
  src/styles/pages/_all.scss
  src/styles/pages/_course.scss
Labels: cla: yes

#4728 Add authors for Y!J case study
  src/site/_data/authorsData.json
Labels: cla: yes

#4741 Add course flag
  src/site/content/en/learn/css/css.11tydata.js
  src/site/content/en/learn/css/index.md
Labels: cla: yes

#4713 [Streams article] Various fixes
  src/site/content/en/blog/streams/index.md
Labels: cla: yes

#4722 [Tagged: Capabilities articles] Linkify and check all hashtags
  src/site/content/en/blog/badging-api/index.md
  src/site/content/en/blog/contact-picker/index.md
  src/site/content/en/blog/content-indexing-api/index.md
  src/site/content/en/blog/file-handling/index.md
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/get-installed-related-apps/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/idle-detection/index.md
  src/site/content/en/blog/local-fonts/index.md
  src/site/content/en/blog/multi-screen-window-placement/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/notification-triggers/index.md
  src/site/content/en/blog/serial/index.md
  src/site/content/en/blog/shape-detection/index.md
  src/site/content/en/blog/usb/index.md
  src/site/content/en/blog/wake-lock/index.md
  src/site/content/en/blog/web-otp/index.md
  src/site/content/en/blog/webcodecs/index.md
  src/site/content/en/blog/websocketstream/index.md
  src/site/content/en/blog/webtransport/index.md
Labels: cla: yes

#4679 Add Tabbed Application Mode article
  src/site/content/en/blog/tabbed-application-mode/hero.jpg
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#4675 Add `display_override` article
  src/site/_data/tagsData.json
  src/site/content/en/blog/display-override/hero.jpg
  src/site/content/en/blog/display-override/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#4749 [Display Override article] Fix hero image
  src/site/content/en/blog/display-override/hero.jpg
  src/site/content/en/blog/display-override/index.md
Labels: cla: yes

#4748 [Tabbed Application Mode article] Fix hero image
  src/site/content/en/blog/tabbed-application-mode/hero.jpg
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#4751 feat(images): migrate images from `site/content/en/a*` to storage bucket
  src/site/content/en/accessible/accessible-responsive-design/index.md
  src/site/content/en/accessible/accessible-responsive-design/udacity-100.jpg
  src/site/content/en/accessible/accessible-responsive-design/udacity-400.jpg
  src/site/content/en/accessible/accessible-tap-targets/firefox-layout.jpg
  src/site/content/en/accessible/accessible-tap-targets/index.md
  src/site/content/en/accessible/color-and-contrast-accessibility/accessibility-audit.png
  src/site/content/en/accessible/color-and-contrast-accessibility/apca.png
  src/site/content/en/accessible/color-and-contrast-accessibility/contrast-ratios.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/css-overview.png
  src/site/content/en/accessible/color-and-contrast-accessibility/emulate.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/fastpass-contrast.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/high-contrast.jpg
  src/site/content/en/accessible/color-and-contrast-accessibility/index.md
  src/site/content/en/accessible/color-and-contrast-accessibility/input-form1.png
  src/site/content/en/accessible/color-and-contrast-accessibility/input-form2.png
  src/site/content/en/accessible/color-and-contrast-accessibility/tab-contrast.png
  src/site/content/en/accessible/content-reordering/a11y-insights.jpg
  src/site/content/en/accessible/content-reordering/index.md
  src/site/content/en/accessible/headings-and-landmarks/headings.png
  src/site/content/en/accessible/headings-and-landmarks/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/devtools-name.png
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/promo-offers.png
  src/site/content/en/accessible/labels-and-text-alternatives/self-assessment.assess.yml
  src/site/content/en/accessible/labels-and-text-alternatives/vo.jpg
  src/site/content/en/accessible/semantics-and-screen-readers/a11y-devtools.png
  src/site/content/en/accessible/semantics-and-screen-readers/index.md
  src/site/content/en/accessible/semantics-and-screen-readers/teapot.png
  src/site/content/en/angular/accessible-angular-with-codelyzer/editor-template.png
  src/site/content/en/angular/accessible-angular-with-codelyzer/index.md
  src/site/content/en/angular/accessible-angular-with-codelyzer/ng-lint.png
  src/site/content/en/angular/creating-pwa-with-angular-cli/home.png
  src/site/content/en/angular/creating-pwa-with-angular-cli/icon.png
  src/site/content/en/angular/creating-pwa-with-angular-cli/index.md
  src/site/content/en/angular/faster-angular-change-detection/app.png
  src/site/content/en/angular/faster-angular-change-detection/component-sub-tree-cd.png
  src/site/content/en/angular/faster-angular-change-detection/component-tree.png
  src/site/content/en/angular/faster-angular-change-detection/index.md
  src/site/content/en/angular/faster-angular-change-detection/profiling.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-calculator.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/budget-failure.png
  src/site/content/en/angular/performance-budgets-with-the-angular-cli/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/index.md
  src/site/content/en/angular/precaching-with-the-angular-service-worker/sample-app.png
  src/site/content/en/angular/route-level-code-splitting-in-angular/code-splitting-network-tab.png
  src/site/content/en/angular/route-level-code-splitting-in-angular/index.md
  src/site/content/en/animations/animations-examples/animations-panel.jpg
  src/site/content/en/animations/animations-examples/firefox-waterfall.jpg
  src/site/content/en/animations/animations-examples/index.md
  src/site/content/en/animations/animations-examples/wizard-summary.jpg
  src/site/content/en/animations/animations-guide/css-triggers.jpg
  src/site/content/en/animations/animations-guide/fps-after.jpg
  src/site/content/en/animations/animations-guide/fps-before.jpg
  src/site/content/en/animations/animations-guide/fps-meter.jpg
  src/site/content/en/animations/animations-guide/index.md
  src/site/content/en/animations/animations-guide/paint-flashing.jpg
  src/site/content/en/animations/animations-guide/summary-after.jpg
  src/site/content/en/animations/animations-guide/summary-before.jpg
Labels: cla: yes

#4753 [Tabbed Application Mode article] Linkify the hashtag
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#4754 Post: Tabs linkback
  src/site/content/en/blog/building-a-tabs-component/index.md
Labels: cla: yes

#4758 [Web Bluetooth article] Add hashtag
  src/site/content/en/blog/bluetooth/index.md
Labels: cla: yes

#4761 [Performance Scoring article] Prevent horizontal overflow
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
Labels: cla: yes

#4762 [Tabbed Application Mode article] Add missing tag
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#4757 Sign-in best practices: updates and fixes
  src/site/content/en/blog/sign-in-form-best-practices/index.md
Labels: cla: yes
