Repository GoogleChrome/web.dev, pull requests merged in 2021-08, with the labels that each got.

#5902 CSS layout compositions
  src/scss/_config.scss
  src/scss/compositions/_auto-grid.scss
  src/scss/compositions/_cluster.scss
  src/scss/compositions/_repel.scss
  src/scss/compositions/_sidebar.scss
  src/scss/compositions/_switcher.scss
  src/scss/next.scss
  src/site/content/en/design-system/css-compositions.njk
  src/site/content/en/design-system/temp-styleguide.njk
Labels: cla: yes

#5867 [File System Access article] Document gotcha
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#5863 Add User Preference Media Features Client Hints Headers article
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/blog/user-preference-media-features-headers/index.md
Labels: cla: yes

#5892 New Post: 2021 Scroll Survey Report
  src/site/content/en/blog/2021-scroll-survey-report/index.md
Labels: cla: yes

#5909 feat(virtual-collections): promote better discovery of virtual collections
  src/site/_collections/shows.js
  src/site/_data/i18n/paths/authors.yml
  src/site/_data/i18n/paths/shows.yml
  src/site/_data/i18n/paths/tags.yml
  src/site/_includes/authors-individual.njk
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/macros/show-card.njk
  src/site/_includes/show.njk
  src/site/_includes/shows-individual.njk
  src/site/_includes/tags-individual.njk
  src/styles/components/_author.scss
Labels: cla: yes

#5917 [User Preference Client Hints article] Close code block
  src/site/content/en/blog/user-preference-media-features-headers/index.md
Labels: cla: yes

#5900 [Local Fonts article] Remove OT info
  src/site/content/en/blog/local-fonts/index.md
Labels: cla: yes

#5831 [Async Clipboard article] Document dealing with pasted files
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#5779 Mention share target works on desktop
  src/site/content/en/blog/web-share-target/index.md
Labels: cla: no

#5921 [Window Controls Overlay article] Update OT link
  src/site/content/en/blog/window-controls-overlay/index.md
Labels: cla: yes

#5908 Theme switcher
  src/lib/components/ThemeToggle/index.js
  src/lib/components/base.js
  src/scss/blocks/_theme-toggle.scss
  src/scss/next.scss
  src/site/_data/design/themes.js
  src/site/_data/design/tokens.json
  src/site/_includes/partials/head.njk
  src/site/content/en/design-system/temp-styleguide.njk
Labels: cla: yes

#5922 Update index.md
  src/site/content/en/blog/fetch-metadata/index.md
Labels: cla: yes

#5928 Small updates
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/blog/why-coop-coep/index.md
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
  src/site/content/en/secure/security-headers/index.md
Labels: cla: yes

#5934 [File System Access article] Add browser support paragraph
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#5935 [Window Controls Overlay article ] Correct OT date
  src/site/content/en/blog/window-controls-overlay/index.md
Labels: cla: yes

#5932 LearnCSS: fixes broken link in focus article
  src/site/content/en/learn/css/focus/index.md
Labels: cla: yes

#5929 [PWAs as URL handler article] Make same origin rules clearer
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#5938 fix(share): fix author titles in share component, fixes #5924
  src/site/_filters/expand-authors.js
  src/site/_includes/partials/course-app-bar.njk
  src/site/_includes/partials/post.njk
Labels: cla: yes

#5923 Add the workflow article: publish 2021-08-09
  src/site/content/en/blog/vitals-tools-workflow/index.md
Labels: cla: yes

#5937 Basic design system UI
  src/lib/components/FrameSizer/index.js
  src/lib/pages/design-system.js
  src/pattern-library/patterns/brand/brand.json
  src/pattern-library/patterns/brand/brand.md
  src/pattern-library/patterns/brand/brand.njk
  src/pattern-library/patterns/stack-nav/stack-nav.json
  src/pattern-library/patterns/stack-nav/stack-nav.md
  src/pattern-library/patterns/stack-nav/stack-nav.njk
  src/pattern-library/patterns/toggle-switch/toggle-switch.json
  src/pattern-library/patterns/toggle-switch/toggle-switch.md
  src/pattern-library/patterns/toggle-switch/toggle-switch.njk
  src/scss/_config.scss
  src/scss/_prototype.scss
  src/scss/blocks/_brand.scss
  src/scss/blocks/_skip-link.scss
  src/scss/blocks/_stack-nav.scss
  src/scss/blocks/_theme-toggle.scss
  src/scss/blocks/_toggle-switch.scss
  src/scss/mixins/_vertically-align-label.scss
  src/scss/next.scss
  src/scss/pages/_design-system.scss
  src/scss/utilities/_focus-ring.scss
  src/site/_data/design/themes.js
  src/site/_filters/md.js
  src/site/_includes/design-system.njk
  src/site/_includes/macros/design-system-pattern.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/standard-theme-toggle.njk
  src/site/_includes/partials/theme-script.njk
  src/site/content/en/design-system/colors.njk
  src/site/content/en/design-system/css-compositions.njk
  src/site/content/en/design-system/css-methodology.md
  src/site/content/en/design-system/design-system.11tydata.json
  src/site/content/en/design-system/pages.11tydata.js
  src/site/content/en/design-system/pages.njk
  src/site/content/en/design-system/patterns-preview.njk
  src/site/content/en/design-system/patterns.11tydata.js
  src/site/content/en/design-system/patterns.njk
  src/site/content/en/design-system/typography.njk
  src/site/content/en/design-system/welcome.njk
Labels: cla: yes

#5925 Clarifications about baseURLs when using URLPattern
  src/site/content/en/blog/urlpattern/index.md
Labels: cla: yes

#5948 Update twitter and chrome developers link in footer.
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#5953 Add jarhar to authors
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
Labels: cla: yes

#5930 Add patterns data structure (pseudo-collection)
  .eleventy.js
  .eslintignore
  package.json
  src/lib/patterns.js
  src/site/_data/patterns.js
  src/site/_filters/urls.js
  src/site/_includes/demo.njk
  src/site/_includes/pattern-suite.njk
  src/site/_includes/pattern.njk
  src/site/content/en/patterns/example-pattern-suite/example-pattern/assets/script.js
  src/site/content/en/patterns/example-pattern-suite/example-pattern/assets/style.css
  src/site/content/en/patterns/example-pattern-suite/example-pattern/demo.md
  src/site/content/en/patterns/example-pattern-suite/example-pattern/index.md
  src/site/content/en/patterns/example-pattern-suite/index.md
  src/site/content/en/patterns/example-pattern/assets/body.html
  src/site/content/en/patterns/example-pattern/assets/script.js
  src/site/content/en/patterns/example-pattern/assets/style.css
  src/site/content/en/patterns/example-pattern/demo.md
  src/site/content/en/patterns/example-pattern/index.md
  src/site/content/en/patterns/index.njk
  types/site/_data/patterns.d.ts
Labels: cla: yes

#5956 Correct link markup in Web Vitals Tools article
  src/site/content/en/blog/vitals-tools-workflow/index.md
Labels: cla: yes

#5959 Edited antoinebisch in authorsData.json
  src/site/_data/authorsData.json
Labels: cla: yes

#5951 Add CodePattern shortcode
  .eleventy.js
  package-lock.json
  src/site/_includes/components/CodePattern.js
  src/site/_includes/pattern-suite.njk
  src/site/_includes/pattern.njk
  src/site/_includes/patterns.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/patterns/example-pattern-suite/example-pattern/assets/script.js
  src/site/content/en/patterns/example-pattern-suite/example-pattern/demo.md
  src/site/content/en/patterns/example-pattern-suite/example-pattern/index.md
  src/site/content/en/patterns/example-pattern-suite/index.md
  src/site/content/en/patterns/example-pattern/index.md
  src/styles/components/_all.scss
  src/styles/components/_code-pattern.scss
Labels: cla: yes

#5952 New post: CSS `accent-color`
  src/site/content/en/blog/accent-color/index.md
Labels: cla: yes

#5931 Blog gui challenges switch
  src/site/content/en/blog/building-a-switch-component/index.md
Labels: cla: yes

#5972 migrates the scroll snap article
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/css-scroll-snap/index.md
Labels: cla: yes

#5982 fixes #5957
  src/site/content/en/learn/css/box-model/index.md
Labels: cla: yes

#5545 Refactoring and expanding the Media section
  redirects.yaml
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/_data/i18n/paths/media.yml
  src/site/_data/paths/media.json
  src/site/content/en/media/add-media/index.md
  src/site/content/en/media/bitrate/index.md
  src/site/content/en/media/containers-and-codecs/index.md
  src/site/content/en/media/media-accessibility/index.md
  src/site/content/en/media/media-application-basics/index.md
  src/site/content/en/media/media-cheat-sheet/index.md
  src/site/content/en/media/media-conversion/index.md
  src/site/content/en/media/media-encryption/index.md
  src/site/content/en/media/media-experience/index.md
  src/site/content/en/media/media-file-basics/index.md
  src/site/content/en/media/media-frameworks/index.md
  src/site/content/en/media/media-streaming-basics/index.md
  src/site/content/en/media/prepare-media/index.md
  src/site/content/en/media/pwa-with-offline-streaming/index.md
  src/site/content/en/media/resolution/index.md
  src/site/content/en/media/video-and-source-tags/index.md
Labels: cla: yes

#5984 Fix links in serial port article.
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#5986 Fix Debian install instructions
  src/site/content/en/blog/how-to-set-up-signed-http-exchanges/index.md
Labels: cla: yes

#5983 [GUI Challenges] community submission addition patch
  src/site/content/en/blog/building-a-switch-component/index.md
Labels: cla: yes

#5970 @devnook Implement PatternSets
  src/lib/components/Tabs/_styles.scss
  src/lib/patterns.js
  src/site/_data/i18n/patterns.yml
  src/site/_data/patterns.js
  src/site/_includes/components/CodePattern.js
  src/site/_includes/demo.njk
  src/site/_includes/macros/breadcrumbs.njk
  src/site/_includes/macros/patterns-card.njk
  src/site/_includes/pattern-page.njk
  src/site/_includes/pattern-set.njk
  src/site/_includes/pattern-suite.njk
  src/site/_includes/pattern.njk
  src/site/_includes/patterns.njk
  src/site/content/en/patterns/example-pattern-suite/example-pattern/demo.md
  src/site/content/en/patterns/full-html-demo/assets/body.html
  src/site/content/en/patterns/full-html-demo/assets/script.js
  src/site/content/en/patterns/full-html-demo/assets/style.css
  src/site/content/en/patterns/full-html-demo/demo.md
  src/site/content/en/patterns/full-html-demo/index.md
  src/site/content/en/patterns/index.md
  src/site/content/en/patterns/index.njk
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/body.html
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/body.html
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/demo.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/index.md
  src/site/content/en/patterns/web-vitals-patterns/index.md
  src/styles/components/_code-pattern.scss
  src/styles/components/_layouts.scss
  src/styles/pages/_all.scss
  src/styles/pages/_code-patterns.scss
  types/site/_data/patterns.d.ts
Labels: cla: yes

#5966 Optimize CLS - add to dynamic content section
  src/site/content/en/blog/optimize-cls/index.md
Labels: cla: yes

#5996 Optimize CLS - dynamic content caption fix
  src/site/content/en/blog/optimize-cls/index.md
Labels: cla: yes

#5939 Add CSS module scripts blog post
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/css-module-scripts/index.md
Labels: cla: yes

#5999 [learn css] pseudo-element correction patch
  src/site/content/en/learn/css/pseudo-elements/index.md
Labels: cla: yes, content update

#5989 Add lab vs field data post
  src/site/_data/paths/learn-web-vitals.json
  src/site/content/en/learn-web-vitals/lab-and-field-data-differences/index.md
Labels: cla: yes

#5967 add includeRaw shortcode
  .eleventy.js
  src/lib/components/CourseLinks/index.js
  src/site/_includes/components/includeRaw.js
  src/site/_includes/course.njk
  src/site/_includes/design-system.njk
  src/site/_includes/macros/icon.njk
  src/site/_includes/partials/course-app-bar.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/header-course.njk
  src/site/_includes/partials/navigation-drawer-course.njk
Labels: cla: yes

#5991 Make codePattern demo and sample stackable
  src/styles/components/_code-pattern.scss
Labels: cla: yes

#5665 Add caniuse.com compat table
  .eleventy.js
  .gitignore
  package-lock.json
  package.json
  src/images/icons/chrome.svg
  src/images/icons/edge.svg
  src/images/icons/firefox.svg
  src/images/icons/safari_24x24.png
  src/site/_includes/components/BrowserCompat.js
  src/site/_utils/browserCompat.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/components/_all.scss
  src/styles/components/_browser-compat.scss
  test/unit/src/site/_utils/browserCompat.js
  test/unit/src/site/_utils/index.js
Labels: cla: yes

#5981 Remove feedback widget from post.njk
  src/lib/pages/content.js
  src/site/_includes/partials/post.njk
Labels: cla: yes

#5990 Add customizable codePattern height + resizeable
  src/lib/components/Tabs/_styles.scss
  src/site/_includes/components/CodePattern.js
  src/site/_includes/demo.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/index.md
  src/styles/components/_code-pattern.scss
  types/site/_data/patterns.d.ts
Labels: cla: yes

#6004 @devnook Add patterns that do not have a parent PatternSet to the pattern-set page
  src/site/_data/i18n/patterns.yml
  src/site/_includes/pattern-set.njk
Labels: cla: yes

#6001 Improve aria and i18n in BrowserCompat
  package-lock.json
  package.json
  src/site/_data/i18n/browser_compat.yml
  src/site/_includes/components/BrowserCompat.js
  src/site/_utils/browserCompat.js
Labels: cla: yes

#6010 Add csp filter
  src/site/_includes/demo.njk
Labels: cla: yes

#5994 Add image demo to codePattern
  src/site/_includes/demo.njk
  src/site/content/en/patterns/image-demo-example/assets/sample.html
  src/site/content/en/patterns/image-demo-example/assets/sample.njk
  src/site/content/en/patterns/image-demo-example/demo.md
  src/site/content/en/patterns/image-demo-example/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/demo.md
Labels: cla: yes

#6002 Move example patterns to one set
  src/lib/patterns.js
  src/site/_includes/pattern-set.njk
  src/site/_includes/patterns.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/patterns/example-pattern/demo.md
  src/site/content/en/patterns/example-pattern/index.md
  src/site/content/en/patterns/example-set/example-pattern/assets/body.html
  src/site/content/en/patterns/example-set/example-pattern/assets/script.js
  src/site/content/en/patterns/example-set/example-pattern/assets/style.css
  src/site/content/en/patterns/example-set/example-pattern/demo.md
  src/site/content/en/patterns/example-set/example-pattern/index.md
  src/site/content/en/patterns/example-set/full-html-demo/assets/body.html
  src/site/content/en/patterns/example-set/full-html-demo/assets/script.js
  src/site/content/en/patterns/example-set/full-html-demo/assets/style.css
  src/site/content/en/patterns/example-set/full-html-demo/demo.md
  src/site/content/en/patterns/example-set/full-html-demo/index.md
  src/site/content/en/patterns/example-set/image-demo/assets/sample.html
  src/site/content/en/patterns/example-set/image-demo/assets/sample.njk
  src/site/content/en/patterns/example-set/image-demo/demo.md
  src/site/content/en/patterns/example-set/image-demo/index.md
  src/site/content/en/patterns/example-set/index.md
  src/site/content/en/patterns/full-html-demo/assets/body.html
  src/site/content/en/patterns/full-html-demo/assets/script.js
  src/site/content/en/patterns/full-html-demo/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/body.html
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/example-pattern/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set-2/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern-2/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/body.html
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/script.js
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/assets/style.css
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/demo.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/example-pattern/index.md
  src/site/content/en/patterns/web-vitals-patterns/example-pattern-set/index.md
  src/site/content/en/patterns/web-vitals-patterns/index.md
Labels: cla: yes

#6019 [File system access article] Use new compat widget
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#6028 Add minifyjs
  src/site/_includes/demo.njk
Labels: cla: yes

#6016 Add CodePatterns docs
  src/site/_includes/pattern-set.njk
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/patterns/example-set/index.md
Labels: cla: yes

#6029 docs: fix broken link
  src/site/content/en/lighthouse-pwa/viewport/index.md
Labels: cla: yes

#6009 Updated web.dev/trust-tokens
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#6030 docs: tweak copy to correspond with image (makes it a little bit easier)
  src/site/content/en/learn/css/grid/index.md
Labels: cla: yes

#6031 docs: add missing periods
  src/site/content/en/blog/new-responsive/index.md
  src/site/content/en/blog/urlpattern/index.md
  src/site/content/en/blog/webrtc-standard-announcement/index.md
  src/site/content/en/learn/css/logical-properties/index.md
Labels: cla: yes

#6034 [MediaStreamTrack article] Update for launch
  src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
Labels: cla: yes

#6035 Update content-visibilty to fix typo
  src/site/content/en/blog/content-visibility/index.md
Labels: cla: yes

#6036 Fix typo in lab vs field post
  src/site/content/en/learn-web-vitals/lab-and-field-data-differences/index.md
Labels: cla: yes

#6040 disable filter
  src/site/_includes/pattern-set.njk
Labels: cla: yes

#6041 [File System Access] Fix gotchas aside
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#6033 [Idle Detection article] Update for launch
  src/site/content/en/blog/idle-detection/index.md
Labels: cla: yes

#6059 Add /si => /speed-index
  redirects.yaml
Labels: cla: yes

#6046 GUI Challenge Patch: adds work from @chris-kruining
  src/site/content/en/blog/building-a-color-scheme/index.md
Labels: cla: yes

#6060 Update Babylon.js playground link
  src/site/content/en/blog/gpu/index.md
Labels: cla: yes

#6058 Clarify drag and drop article handleDrop
  src/site/content/en/blog/drag-and-drop/index.md
Labels: cla: yes

#6061 Add windows version of command.
  src/site/content/en/media/media-application-basics/index.md
Labels: cla: yes

#6077 fix(card): fix card layout for bp md by setting content to none, fixes #5961
  src/styles/components/_card-base.scss
Labels: cla: yes
