Repository GoogleChrome/web.dev, pull requests merged in 2021-12, with the labels that each got.

#6824 Learn PWA modules 4 and 5
  src/site/content/en/learn/pwa/app-design/index.md
  src/site/content/en/learn/pwa/assets-and-data/index.md
Labels: cla: yes

#6921 Fix double words.
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
  src/site/content/en/blog/truebil-lite/index.md
Labels: cla: yes

#6906 Add Designcember card
  src/site/content/en/index.md
Labels: cla: yes

#6918 Enable post-next for new posts
  src/site/_includes/post.njk
Labels: cla: yes

#6922 Fix double words.
  src/site/content/en/blog/storage-foundation/index.md
  src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml
Labels: cla: yes

#6911 Updated vitals measurement best practices post with guidance on avoiding averages.
  package-lock.json
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
Labels: cla: yes, content, $-presubmit

#6923 Update bug info and code example for the responsiveness post
  src/site/content/en/blog/responsiveness/index.md
Labels: cla: yes

#6614 refactor(course-cards-next): use carousel
  src/lib/components/Carousel/index.js
  src/lib/pages/home.js
  src/lib/pages/learn.js
  src/site/_includes/partials/course-cards-next.njk
Labels: cla: yes

#6848 Update _card-base-styles.scss for card header overflow
  src/scss/mixins/_card-base-styles.scss
Labels: cla: yes, $-presubmit

#6938 fix(youtube): fix youtube video alignment, fixes #6907
  src/styles/components/_youtube.scss
Labels: cla: yes

#6948 Deprecate postsWithLighthouse library
  .eleventy.js
  src/site/_collections/posts-with-lighthouse.js
  test/integration/index.js
  test/integration/src/site/_collections/eleventy.js
  test/integration/src/site/_collections/fixtures/test-1.md
  test/integration/src/site/_collections/fixtures/test-2.md
  test/integration/src/site/_collections/fixtures/test-3.md
  test/integration/src/site/_collections/fixtures/test-4.md
  test/integration/src/site/_collections/fixtures/test-5.md
  test/integration/src/site/_collections/fixtures/test-6.md
  test/integration/src/site/_collections/fixtures/test-7.md
  test/integration/src/site/_collections/index.js
  test/integration/src/site/_collections/posts-with-lighthouse/collection.md
  test/integration/src/site/_collections/posts-with-lighthouse/dev.js
  test/integration/src/site/_collections/posts-with-lighthouse/prod.js
  test/integration/src/site/_collections/runEleventy.js
  test/unit/src/site/_collections/index.js
  test/unit/src/site/_collections/posts-with-lighthouse.js
Labels: cla: yes

#6939 fix(hero): remove `loading="lazy"` from all images in `.hero` elements, fixes #6895
  src/component-library/hero/hero.njk
  src/site/_includes/homepage-next.njk
Labels: cla: yes

#6912 Unify patterns, blog and index-page to all inherit from landing-page
  src/site/_includes/blog.njk
  src/site/_includes/index-page.njk
  src/site/_includes/landing-page.njk
  src/site/_includes/patterns.njk
  src/site/content/en/blog/index.njk
Labels: cla: yes

#6934 Convert posts that used w-stats to new layout
  src/site/_drafts/_template-post/index.md
  src/site/content/en/blog/2021-scroll-survey-report/index.md
  src/site/content/en/blog/ads-case-study-stale-while-revalidate/index.md
  src/site/content/en/blog/agrofy/index.md
  src/site/content/en/blog/betty-crocker/index.md
  src/site/content/en/blog/blibli/index.md
  src/site/content/en/blog/clipchamp/index.md
  src/site/content/en/blog/gravit-designer/index.md
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md
  src/site/content/en/blog/mailru-cwv/index.md
  src/site/content/en/blog/mainline-mensware/index.md
  src/site/content/en/blog/ndtv/index.md
  src/site/content/en/blog/netzwelt/index.md
  src/site/content/en/blog/shopping-for-speed-on-ebay/index.md
  src/site/content/en/blog/swappie/index.md
  src/site/content/en/blog/telegraph/index.md
  src/site/content/en/blog/tokopedia/index.md
  src/site/content/en/blog/truebil-lite/index.md
  src/site/content/en/blog/vodafone/index.md
  src/site/content/en/blog/yahoo-japan-news/index.md
  src/site/content/en/blog/zalando/index.md
  src/site/content/en/handbook/author-profile/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/yaml-front-matter/index.md
Labels: cla: yes

#6949 fix test
  test/integration/build-test.js
Labels: cla: yes

#6940 fix(renderAuthorsDate): remove `reverse` from author images if `isDesignSystem`, fixes #6897
  src/site/_includes/components/AuthorsDate.js
Labels: cla: yes

#6945 fix(algolia): add landing pages and prioritize them, fixes #4027
  algolia.js
  src/site/_filters/algolia-item.js
  src/site/_includes/base.njk
  src/site/_includes/blog.njk
  src/site/_includes/index-page.njk
  src/site/_includes/item-page.njk
  src/site/_includes/path.njk
  types/eleventy/collection-item.d.ts
  types/utils/algolia.d.ts
Labels: cla: yes

#6944 fix(percy): update percy to use new CLI/SDK, fixes #6943
  package-lock.json
  package.json
  tools/percy/.percy.conf.yml
  tools/percy/snapshots.js
Labels: cla: yes

#6950 Hotfix: Add missing 'worse' compare box treatment to two compare blocks in CSS Backgrounds module
  src/site/content/en/learn/css/backgrounds/index.md
Labels: cla: yes

#6951 Scrollbar & carousel styles update
  src/scss/blocks/_carousel.scss
  src/scss/utilities/_scrollbar.scss
  src/site/_includes/partials/course-cards-next.njk
Labels: cla: yes

#6916 Wrong attribut used in Learn content
  src/site/content/en/learn/forms/address/index.md
Labels: cla: yes

#6926 Adds two more Learn PWA modules
  src/site/content/en/learn/pwa/caching/index.md
  src/site/content/en/learn/pwa/service-workers/index.md
Labels: cla: yes

#6957 [Notification Triggers article] Add no longer pursued warning
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#6960 [File Handling article] More robust feature detection
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#6835 fix(BaseResponseElement): scroll to selected option when option is correct, fixes #6463
  src/lib/components/BaseResponseElement/index.js
Labels: cla: yes

#6927 Interview with Bramus
  src/site/content/en/blog/community-highlight-bramus/index.md
Labels: cla: yes

#6969 Fix the link to Bramus's twitter
  src/site/content/en/blog/community-highlight-bramus/index.md
Labels: cla: yes, $-presubmit

#6970 Adds UI Fund article
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/ui-fund/index.md
Labels: cla: yes

#6974 Add a max width to course TOC
  src/scss/pages/_course.scss
Labels: cla: yes

#6744 Account for stacked headings in prose rules
  src/scss/blocks/_prose.scss
Labels: cla: yes

#6976 Quick css fixes
  src/scss/blocks/_fab.scss
  src/scss/blocks/_prose.scss
  src/scss/blocks/_table-wrapper.scss
  src/scss/mixins/_button-base-styles.scss
Labels: cla: yes

#6964 New Post: GUI Challenges - Building a toast component
  src/site/content/en/blog/building-a-toast-component/index.md
Labels: cla: yes

#6962 [Case study] Kapwing
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/kapwing/index.md
Labels: cla: yes, content

#6689 Fix Russian language translation
  shared/locale.js
  src/lib/utils/language.js
  src/site/_includes/components/LanguageList.js
Labels: cla: yes, $-presubmit

#6900 [Learn Design][Designcember] Adding the next five modules
  src/site/content/en/learn/design/icons/icons.assess.yml
  src/site/content/en/learn/design/icons/index.md
  src/site/content/en/learn/design/index.md
  src/site/content/en/learn/design/picture-element/index.md
  src/site/content/en/learn/design/picture-element/picture.assess.yml
  src/site/content/en/learn/design/responsive-images/images.assess.yml
  src/site/content/en/learn/design/responsive-images/index.md
  src/site/content/en/learn/design/theming/index.md
  src/site/content/en/learn/design/theming/theming.assess.yml
  src/site/content/en/learn/design/typography/index.md
  src/site/content/en/learn/design/typography/typography.assess.yml
Labels: DO NOT MERGE, cla: yes

#6936 attempt at inline figure
  src/component-library/figure/figure.json
  src/component-library/figure/figure.md
  src/component-library/figure/figure.njk
  src/component-library/figure/variants/float/float.json
  src/component-library/figure/variants/float/float.njk
  src/scss/blocks/_aside.scss
  src/scss/blocks/_callout.scss
  src/scss/blocks/_figure.scss
  src/scss/blocks/_prose.scss
  src/scss/next.scss
  src/scss/utilities/_wrapper.scss
  src/scss/web-components/_web-copy-code.scss
Labels: cla: yes

#6935 Update examples with Sec-CH-UA-Full-Version-List
  src/site/content/en/blog/user-agent-client-hints/index.md
Labels: cla: yes

#6814 Update UrlChooser component to prefer https as default
  src/lib/components/UrlChooser/index.js
Labels: cla: yes, $-presubmit

#6961 Adds the QuintoAndar case study
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/quintoandar/index.md
Labels: cla: no, content, $-presubmit

#6956 refactor(paths): update leaning paths to use new design system, fixes #6917
  src/images/icons/done.svg
  src/scss/next.scss
  src/scss/pages/_path.scss
  src/site/_includes/partials/item.njk
  src/site/_includes/partials/topic.njk
  src/site/_includes/path.njk
  src/styles/pages/_all.scss
  src/styles/pages/_path.scss
Labels: cla: yes

#6243 Embed Privacy Sandbox videos
  src/site/content/en/blog/digging-into-the-privacy-sandbox/index.md
  src/site/content/en/blog/trust-tokens/index.md
Labels: cla: yes

#7002 Maintenance: fix broken links
  src/site/content/en/blog/designcember-calculator/index.md
Labels: DO NOT MERGE

#7021 Fix incorrect link
  src/site/content/en/blog/speculative-prerendering/index.md
Labels: content update, $-presubmit

#6989 Add warning about forced layouts, info about auto
  src/site/content/en/blog/content-visibility/index.md
Labels: $-presubmit

#6958 Design system tabs
  src/component-library/tabs/tabs.json
  src/component-library/tabs/tabs.md
  src/component-library/tabs/tabs.njk
  src/lib/components/Tabs/_styles.scss
  src/lib/components/Tabs/index.js
  src/lib/pages/design-system.js
  src/scss/_rollout.scss
  src/scss/_unresolved.scss
  src/scss/blocks/_table-wrapper.scss
  src/scss/mixins/_overflow-shadow.scss
  src/scss/next.scss
  src/scss/web-components/_web-tabs.scss
Labels: cla: yes

#7017 Adds the last set of Learn Design modules
  src/site/_data/courses/design/toc.yml
  src/site/content/en/learn/design/accessibility/accessibility.assess.yml
  src/site/content/en/learn/design/accessibility/index.md
  src/site/content/en/learn/design/conclusion/index.md
  src/site/content/en/learn/design/index.md
  src/site/content/en/learn/design/interaction/index.md
  src/site/content/en/learn/design/media-features/index.md
  src/site/content/en/learn/design/media-features/media-features.assess.yml
  src/site/content/en/learn/design/screen-configurations/index.md
  src/site/content/en/learn/design/screen-configurations/screen-configurations.assess.yml
  src/site/content/en/learn/design/ui-patterns/index.md
Labels: DO NOT MERGE

#6908 Add launch handler article
  src/site/content/en/blog/declarative-link-capturing/index.md
  src/site/content/en/blog/launch-handler/index.md
Labels: cla: yes

#7053 Updates case study guidelines
  src/site/content/en/handbook/case-study-guidelines/index.md
Labels: handbook, $-presubmit

#7058 fix(building-a-toast-component): Fix broken link
  src/site/content/en/blog/building-a-toast-component/index.md
Labels: $-presubmit

#6898 Terra dark mode case study
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/terra-dark-mode/index.md
Labels: cla: yes, $-presubmit

#6920 Adds CWV case study for The Economic Times.
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/economic-times-cwv/index.md
Labels: cla: yes, content, $-presubmit

#7089 Removes hero and thumbnail images for the economic times case study.
  src/site/content/en/blog/economic-times-cwv/index.md
Labels: content, $-presubmit

#7090 Fixes a typo in the description for the economic times case study.
  src/site/content/en/blog/economic-times-cwv/index.md
Labels: content, $-presubmit

#7093 fix: content overflow of code-pattern.scss component
  src/styles/components/_code-pattern.scss
Labels: $-presubmit
