Repository GoogleChrome/web.dev, pull requests merged in 2021-03, with the labels that each got.

#4767 [WebHID article] Use correct character casing for brands
  src/site/content/en/blog/hid/index.md
Labels: cla: yes

#4763 Fix title
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#4771 Update streams/index.md
  src/site/content/en/blog/streams/index.md
Labels: cla: yes

#4760 Migrate IntersectionObserver v2 article
  src/site/content/en/blog/intersectionobserver-v2/index.md
Labels: cla: yes

#4766 Style Courses overflows
  src/site/_includes/course.njk
  src/styles/components/_toc.scss
  src/styles/generic/_tables.scss
  src/styles/main.scss
  src/styles/pages/_course.scss
  src/styles/utilities/_all.scss
  src/styles/utilities/_scrollbars.scss
  src/styles/utilities/_visually-hidden.scss
  tools/percy/snapshots.js
Labels: cla: yes

#4773 [Handbook update] Add instructions for inlcuding image captions
  src/site/content/en/handbook/markup-media/index.md
Labels: cla: yes

#4798 Tabs post patch: adds missing alt text
  src/site/content/en/blog/building-a-tabs-component/index.md
Labels: cla: yes

#4764 WebPackager updates
  src/site/content/en/fast/signed-exchanges-webpackager/index.md
Labels: cla: yes

#4776 Update the close port example in the serial article
  src/site/content/en/blog/serial/index.md
Labels: cla: yes

#4800 Update tooling info in SXG article
  src/site/content/en/fast/signed-exchanges/index.md
Labels: cla: yes

#4808 Fixed minor glitch: changed 'the the feature' to 'the feature'
  src/site/content/en/blog/origin-trials/index.md
Labels: cla: yes

#4816 Fix typo
  src/site/content/en/mini-apps/mini-app-about/index.md
Labels: cla: yes

#4812 Chore/courses toc
  .eleventy.js
  .github/workflows/lighthouse-ci-workflow.yml
  .github/workflows/lint-and-test-workflow.yml
  .github/workflows/percy-workflow.yml
  .github/workflows/translation-status-workflow.yml
  .nvmrc
  .sasslintrc
  package-lock.json
  package.json
  src/site/_data/lib/hash.js
  src/site/_includes/course.njk
  src/site/_includes/icons/arrow-right.svg
  src/site/_includes/macros/icon.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/toc-inner.njk
  src/site/_includes/partials/toc-side.njk
  src/site/content/en/learn/css/borders/index.md
  src/styles/components/_all.scss
  src/styles/components/_course-toc.scss
  src/styles/generic/_page.scss
  src/styles/globals/_functions.scss
  src/styles/globals/_gorko.scss
  src/styles/globals/gorko/_config.scss
  src/styles/main.scss
  src/styles/pages/_course.scss
  src/styles/settings/_global.scss
  src/styles/tools/_functions.scss
  src/styles/utilities/_all.scss
  src/styles/utilities/_flow.scss
Labels: cla: yes

#4810 Tabs post: bucket swap patch
  src/site/content/en/blog/building-a-tabs-component/index.md
Labels: cla: yes

#4806 fix linter and remove all smart quote styles
  src/site/content/en/blog/codelab-address-form-best-practices/index.md
  src/site/content/en/blog/fetch-upload-streaming/index.md
  src/site/content/en/blog/link-prefetch/index.md
  src/site/content/en/blog/min-max-clamp/index.md
  src/site/content/en/blog/preconnect-and-dns-prefetch/index.md
  src/site/content/en/fast/prioritize-resources/index.md
  src/site/content/en/handbook/grammar/index.md
  src/site/content/en/newsletter/archive/2020/03/index.njk
  src/site/content/en/newsletter/archive/2020/06/index.njk
  src/site/content/en/progressive-web-apps/define-install-strategy/index.md
  src/site/content/en/reliable/broadcast-updates-guide/index.md
  src/site/content/en/reliable/imperative-caching-guide/index.md
  src/site/content/en/reliable/instant-navigation-experiences/index.md
  src/site/content/en/reliable/two-way-communication-guide/index.md
  tools/linting/no-dash-spaces.js
  tools/linting/no-smart-quotes.js
Labels: cla: yes

#4750 feat(Img): add test to see if images passed into shortcode have correct syntax from uploader
  src/site/_includes/components/Img.js
Labels: cla: yes

#4827 [Display Override article] Correctly name mode
  src/site/content/en/blog/display-override/index.md
Labels: cla: yes

#4721 Add Stack Overflow tag component
  .eleventy.js
  src/site/_drafts/_template-post/index.md
  src/site/_includes/components/StackOverflow.js
  src/site/_includes/partials/post.njk
  src/site/content/en/blog/bluetooth/index.md
  src/site/content/en/blog/build-for-webusb/index.md
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/usb/index.md
  src/site/content/en/handbook/yaml-front-matter/index.md
Labels: cla: yes

#4813 Removed many conditionals required before Chrome 89 from the COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#4718 Article on JavaScript `this`
  src/site/content/en/blog/javascript-this/index.md
Labels: cla: yes

#4819 feat(handbook): move handbook images to gcp bucket
  src/site/content/en/handbook/author-profile/index.md
  src/site/content/en/handbook/author-profile/lockup.png
  src/site/content/en/handbook/resolving-glitch-issues/index.md
  src/site/content/en/handbook/resolving-glitch-issues/suspended-project.png
  src/site/content/en/handbook/web-dev-components/image-screenshot.png
  src/site/content/en/handbook/web-dev-components/image-small.png
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/handbook/yaml-front-matter/blog.jpg
  src/site/content/en/handbook/yaml-front-matter/codelab.jpg
  src/site/content/en/handbook/yaml-front-matter/codelabs.jpg
  src/site/content/en/handbook/yaml-front-matter/covid19.jpg
  src/site/content/en/handbook/yaml-front-matter/date-updated.jpg
  src/site/content/en/handbook/yaml-front-matter/description.jpg
  src/site/content/en/handbook/yaml-front-matter/draft.jpg
  src/site/content/en/handbook/yaml-front-matter/index.md
  src/site/content/en/handbook/yaml-front-matter/post.jpg
  src/site/content/en/handbook/yaml-front-matter/related-post.jpg
  src/site/content/en/handbook/yaml-front-matter/subhead-blog.jpg
  src/site/content/en/handbook/yaml-front-matter/subhead.jpg
  src/site/content/en/handbook/yaml-front-matter/web-vitals.jpg
Labels: cla: yes

#4774 Add Yahoo Japan News case study
  src/site/content/en/blog/yahoo-japan-news/index.md
Labels: cla: yes

#4772 Add Agrofy case study
  src/site/content/en/blog/agrofy/index.md
Labels: cla: yes

#4837 [Post Update] Content-visibility
  src/site/content/en/blog/content-visibility/index.md
Labels: cla: yes

#4852 Add i18n filter for templates
  .eleventy.js
  package-lock.json
  package.json
  src/site/_data/i18n/footer.yml
  src/site/_filters/i18n.js
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#4839 fix(en): copy default locale's (en) content to i18n folder on prod builds, fixes #4642
  gulpfile.js
  package.json
  src/site/content/en/handbook/sandbox/article-header/houssein.jpg
  src/site/content/en/handbook/sandbox/article-header/index.njk
  src/site/content/en/handbook/sandbox/article-navigation/index.njk
  src/site/content/en/handbook/sandbox/asides/index.njk
  src/site/content/en/handbook/sandbox/author/houssein.jpg
  src/site/content/en/handbook/sandbox/author/index.njk
  src/site/content/en/handbook/sandbox/blockquote/index.njk
  src/site/content/en/handbook/sandbox/breadcrumbs/index.njk
  src/site/content/en/handbook/sandbox/buttons/index.njk
  src/site/content/en/handbook/sandbox/card/index.njk
  src/site/content/en/handbook/sandbox/chips/index.njk
  src/site/content/en/handbook/sandbox/code/index.md
  src/site/content/en/handbook/sandbox/codelabs-callout/index.njk
  src/site/content/en/handbook/sandbox/columns/index.njk
  src/site/content/en/handbook/sandbox/columns/sandbox/a.jpg
  src/site/content/en/handbook/sandbox/columns/sandbox/hero.jpg
  src/site/content/en/handbook/sandbox/columns/sandbox/image-inline.png
  src/site/content/en/handbook/sandbox/columns/sandbox/image-screenshot.png
  src/site/content/en/handbook/sandbox/columns/sandbox/image-small.png
  src/site/content/en/handbook/sandbox/columns/sandbox/img1.png
  src/site/content/en/handbook/sandbox/columns/sandbox/img2.png
  src/site/content/en/handbook/sandbox/compare/index.md
  src/site/content/en/handbook/sandbox/cross-links/index.njk
  src/site/content/en/handbook/sandbox/details/index.njk
  src/site/content/en/handbook/sandbox/grid/index.njk
  src/site/content/en/handbook/sandbox/images/index.njk
  src/site/content/en/handbook/sandbox/images/sandbox/a.jpg
  src/site/content/en/handbook/sandbox/images/sandbox/hero.jpg
  src/site/content/en/handbook/sandbox/images/sandbox/image-inline.png
  src/site/content/en/handbook/sandbox/images/sandbox/image-screenshot.png
  src/site/content/en/handbook/sandbox/images/sandbox/image-small.png
  src/site/content/en/handbook/sandbox/images/sandbox/img1.png
  src/site/content/en/handbook/sandbox/images/sandbox/img2.png
  src/site/content/en/handbook/sandbox/instruction/index.md
  src/site/content/en/handbook/sandbox/lists/index.njk
  src/site/content/en/handbook/sandbox/lists/sandbox/image-screenshot.png
  src/site/content/en/handbook/sandbox/numbered-header/index.njk
  src/site/content/en/handbook/sandbox/page-header/index.njk
  src/site/content/en/handbook/sandbox/path-card/index.njk
  src/site/content/en/handbook/sandbox/path-card/path-card.11tydata.js
  src/site/content/en/handbook/sandbox/post-card/index.njk
  src/site/content/en/handbook/sandbox/stats/index.njk
  src/site/content/en/handbook/sandbox/tables/index.njk
  src/site/content/en/handbook/sandbox/typography/index.njk
  src/site/content/en/handbook/sandbox/youtube/index.md
Labels: cla: yes

#4841 Wix case study
  src/site/_data/authorsData.json
  src/site/content/en/blog/wix/index.md
Labels: cla: yes

#4868 Sw codelab typo
  src/site/content/en/reliable/codelab-service-workers/index.md
Labels: cla: yes

#4871 Added aside warning about different uploaders
  src/site/content/en/handbook/markup-media/index.md
Labels: cla: yes

#4872 Simplify Aside and use i18n filter on it
  src/site/_data/i18n/common.yml
  src/site/_filters/i18n.js
  src/site/_includes/components/Aside.js
  types/eleventy/page.d.ts
Labels: cla: yes

#4878 fix(svg): prevent svg from being rasterized unless we specifically want it to
  src/site/_includes/components/Img.js
  types/site/_includes/components/Img.d.ts
Labels: cla: yes

#4877 Add translations to _data/paths
  .pullapprove.yml
  src/site/_data/i18n/paths/accessible.yml
  src/site/_data/i18n/paths/angular.yml
  src/site/_data/i18n/paths/animations.yml
  src/site/_data/i18n/paths/devices.yml
  src/site/_data/i18n/paths/discoverable.yml
  src/site/_data/i18n/paths/fast.yml
  src/site/_data/i18n/paths/handbook.yml
  src/site/_data/i18n/paths/learn_web_vitals.yml
  src/site/_data/i18n/paths/lighthouse_accessibility.yml
  src/site/_data/i18n/paths/lighthouse_best_practices.yml
  src/site/_data/i18n/paths/lighthouse_performance.yml
  src/site/_data/i18n/paths/lighthouse_pwa.yml
  src/site/_data/i18n/paths/lighthouse_seo.yml
  src/site/_data/i18n/paths/media.yml
  src/site/_data/i18n/paths/metrics.yml
  src/site/_data/i18n/paths/mini_apps.yml
  src/site/_data/i18n/paths/notifications.yml
  src/site/_data/i18n/paths/payments.yml
  src/site/_data/i18n/paths/progressive_web_apps.yml
  src/site/_data/i18n/paths/react.yml
  src/site/_data/i18n/paths/reliable.yml
  src/site/_data/i18n/paths/secure.yml
  src/site/_data/paths/accessible.json
  src/site/_data/paths/angular.json
  src/site/_data/paths/animations.json
  src/site/_data/paths/devices.json
  src/site/_data/paths/discoverable.json
  src/site/_data/paths/fast.json
  src/site/_data/paths/handbook.json
  src/site/_data/paths/learn-web-vitals.json
  src/site/_data/paths/lighthouse-accessibility.json
  src/site/_data/paths/lighthouse-best-practices.json
  src/site/_data/paths/lighthouse-performance.json
  src/site/_data/paths/lighthouse-pwa.json
  src/site/_data/paths/lighthouse-seo.json
  src/site/_data/paths/media.json
  src/site/_data/paths/metrics.json
  src/site/_data/paths/mini-apps.json
  src/site/_data/paths/notifications.json
  src/site/_data/paths/payments.json
  src/site/_data/paths/progressive-web-apps.json
  src/site/_data/paths/react.json
  src/site/_data/paths/reliable.json
  src/site/_data/paths/secure.json
  src/site/_includes/components/PathCard.js
  src/site/_includes/partials/topic.njk
  src/site/_includes/path.njk
Labels: cla: yes

#4869 Update 'uses-http2' article to be more accurate
  src/site/content/en/lighthouse-best-practices/uses-http2/index.md
Labels: cla: yes

#4865 Update name
  src/site/_data/authorsData.json
  src/site/content/en/blog/multi-origin-pwas/index.md
Labels: cla: yes

#4863 Add translation strings
  src/site/_data/i18n/header.yml
  src/site/_data/i18n/post.yml
  src/site/_data/i18n/subscribe.yml
  src/site/_data/i18n/toc.yml
  src/site/_includes/partials/header.njk
  src/site/_includes/partials/post.njk
  src/site/_includes/partials/side-nav.njk
  src/site/_includes/partials/subscribe-action.njk
  src/site/_includes/partials/subscribe.njk
  src/site/_includes/partials/toc-inner.njk
  src/site/_includes/partials/toc-side.njk
Labels: cla: yes

#4876 Add i18n to Compare component
  src/site/_data/i18n/common.yml
  src/site/_includes/components/Compare.js
  src/site/_includes/components/CompareCaption.js
Labels: cla: yes

#4870 Add 'Debugging layout shifts' post
  src/site/content/en/fast/debugging-layout-shifts/index.md
Labels: cla: yes

#4889 Make sure Asides and Compare widgets dont break markdown-it
  src/site/_includes/components/Aside.js
  src/site/_includes/components/Compare.js
  src/site/_includes/components/CompareCaption.js
Labels: cla: yes

#4888 SignPosts should be translated
  src/site/_includes/components/SignPosts.js
Labels: cla: yes

#4894 Fix article title typo
  src/site/content/en/blog/preload-optional-fonts/index.md
Labels: cla: yes

#4895 Fixing typo
  src/site/content/en/media/video-and-source-tags/index.md
Labels: cla: yes

#4899 Fix blog wrong typo in some pages
  src/site/content/en/blog/advancing-framework-ecosystem-cds-2019/index.md
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/blog/backdrop-filter/index.md
  src/site/content/en/blog/cache-api-quick-guide/index.md
  src/site/content/en/blog/camera-pan-tilt-zoom/index.md
Labels: cla: yes

#4746 Fix Axis Praxis movie in Variable Fonts article
  src/site/content/en/blog/variable-fonts/index.md
Labels: cla: yes

#4902 Clarify that the Core Web Vitals thresholds are inclusive
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#4862 Strict CSP article for web.dev
  src/site/_includes/components/Glitch.js
  src/site/content/en/blog/strict-csp/index.md
Labels: cla: yes

#4901 Update aspect ratio details in Yahoo Japan case study
  src/site/content/en/blog/yahoo-japan-news/index.md
Labels: cla: yes

#4904 Remove empty bullet point in Strict CSP article (#4862)
  src/site/content/en/blog/strict-csp/index.md
Labels: cla: yes

#4906 Removes a broken audit link
  src/site/content/en/lighthouse-pwa/offline-start-url/index.md
  src/site/content/en/lighthouse-pwa/works-offline/index.md
Labels: cla: yes

#4883 Update handbook to include info on paths translations.
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes

#4908 Update cross-origin isolation guide message
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#4843 Variable fonts updates
  src/site/content/en/blog/variable-fonts/index.md
Labels: cla: yes

#4887 Change relative path to assets path for actions CTAs
  src/styles/components/_actions.scss
Labels: cla: yes

#4882 Add foolip to authors
  src/site/_data/authorsData.json
Labels: cla: yes

#4861 [Web Share article] Add StackOverflow tag
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#4910 Add one more reporting api service to COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#4911 Fix analysis anchor in cross origin isolation guide
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#4855 Post gui challenges building settings
  src/site/content/en/blog/building-a-settings-component/index.md
Labels: cla: yes

#4916 Fix SyntaxError in example of steams
  src/site/content/en/blog/streams/index.md
Labels: cla: yes

#4857 Add Vodafone case study
  src/site/content/en/blog/vodafone/index.md
Labels: cla: yes

#4917 Fix typo in various pages
  src/site/content/en/blog/devices-introduction/index.md
  src/site/content/en/blog/granular-chunking-nextjs/index.md
  src/site/content/en/blog/introducing-model-viewer/index.md
  src/site/content/en/blog/introducing-tooling-report/index.md
  src/site/content/en/blog/lighthouse-ci/index.md
  src/site/content/en/blog/module-workers/index.md
  src/site/content/en/blog/perception-toolkit/index.md
  src/site/content/en/blog/periodic-background-sync/index.md
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
  src/site/content/en/blog/use-thumbor/index.md
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/vr-comes-to-the-web/index.md
  src/site/content/en/blog/web-on-android/index.md
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#4918 Add articles to /learn-web-vitals
  src/site/_data/i18n/paths/learn_web_vitals.yml
  src/site/_data/paths/learn-web-vitals.json
Labels: cla: yes

#4925 Fit up to three columns in the Columns component
  src/styles/components/_columns.scss
Labels: cla: yes

#4920 adding link to MDN.
  src/site/content/en/secure/cross-origin-resource-sharing/index.md
Labels: cla: yes

#4932 Fix info on video lazy loading
  src/site/content/en/fast/lazy-loading-video/index.md
Labels: cla: yes

#4933 Update webpackager instructions
  src/site/content/en/fast/signed-exchanges-webpackager/index.md
Labels: cla: yes

#4931 Post patch: Building a Settings component
  src/site/content/en/blog/building-a-settings-component/index.md
Labels: cla: yes

#4928 Fix inaccuracy in Lighthouse 3P facades article
  src/site/content/en/lighthouse-performance/third-party-facades/index.md
Labels: cla: yes

#4927 Update strict CSP article Lighthouse section
  src/site/content/en/blog/strict-csp/index.md
Labels: cla: yes

#4935 Match link href with anchor name on "Optimize First Input Delay" page
  src/site/content/en/blog/optimize-fid/index.md
Labels: cla: yes

#4921 [WIP] Compat2021
  src/site/content/en/blog/compat2021/index.md
  src/site/content/en/blog/developer-satisfaction/index.md
Labels: DO NOT MERGE, cla: yes

#4936 Add note on tags usage
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes

#4943 [Compat2021 article] Linkify hashtag
  src/site/content/en/blog/compat2021/index.md
Labels: cla: yes

#4945 Fix `aspect-ratio` link
  src/site/content/en/blog/compat2021/index.md
Labels: cla: yes

#4924 fix(blog): fix images in post
  src/site/content/en/blog/sign-up-form-best-practices/images/federated-login.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-account-switching.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-activity.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/gmail-sign-up-create-account.jpg
  src/site/content/en/blog/sign-up-form-best-practices/images/obvious-sign-in.jpg
  src/site/content/en/blog/sign-up-form-best-practices/index.md
Labels: cla: yes

#4939 Translate Stackoverflow component
  src/site/_data/i18n/stackoverflow.yml
  src/site/_includes/components/StackOverflow.js
Labels: cla: yes

#4947 fix(windows): remove language filtering and use specific path for `dir` input to get windows to build, fixes #3672 fixes #4891
  .eleventy.js
Labels: cla: yes

#4950 Simplify language around flex image sizing bugs
  src/site/content/en/blog/compat2021/index.md
Labels: cla: yes

#4954 Update link in content review checklists page
  src/site/content/en/handbook/content-checklist/index.md
Labels: cla: yes

#4951 [DevSat article] Minor corrections
  src/site/content/en/blog/developer-satisfaction/index.md
Labels: cla: yes

#4949 allow strikethrough
  tools/linting/no-repeat-punctuation.js
Labels: cla: yes

#4938 Adding Lowe's case study
  src/site/_data/authorsData.json
  src/site/content/en/blog/lowes/index.md
Labels: cla: yes

#4958 Correct the performance gain explanation
  src/site/content/en/blog/variable-fonts/index.md
Labels: cla: yes

#4956 [Offline Fallback Page article] Add comment about unused variable
  src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
Labels: cla: yes

#4961 Changing terminology
  src/site/content/en/blog/compat2021/index.md
Labels: cla: yes

#4962 Edit the authors note on Lowe's case study
  src/site/content/en/blog/lowes/index.md
Labels: cla: yes

#4965 Add now playing widget screenshot to media session sample
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes, content update

#4831 Add social tags content to path landing pages.
  src/site/_data/paths/accessible.json
  src/site/_data/paths/angular.json
  src/site/_data/paths/animations.json
  src/site/_data/paths/devices.json
  src/site/_data/paths/discoverable.json
  src/site/_data/paths/fast.json
  src/site/_data/paths/handbook.json
  src/site/_data/paths/learn-web-vitals.json
  src/site/_data/paths/lighthouse-accessibility.json
  src/site/_data/paths/lighthouse-best-practices.json
  src/site/_data/paths/lighthouse-performance.json
  src/site/_data/paths/lighthouse-pwa.json
  src/site/_data/paths/lighthouse-seo.json
  src/site/_data/paths/media.json
  src/site/_data/paths/metrics.json
  src/site/_data/paths/mini-apps.json
  src/site/_data/paths/payments.json
  src/site/_data/paths/progressive-web-apps.json
  src/site/_data/paths/react.json
  src/site/_data/paths/reliable.json
  src/site/_data/paths/secure.json
  src/site/_includes/components/Meta.js
  src/site/_includes/components/PathCard.js
  src/site/_includes/path.njk
  src/site/content/en/blog/web-dev-io-2019/index.md
  src/site/content/en/learn/2d-barcode.jpg
  src/site/content/en/learn/douyin-permission.png
  src/site/content/en/learn/screen-brightness.png
  src/site/content/en/learn/super-app-ui.jpg
  src/site/content/en/learn/ui-components.png
  src/site/content/en/learn/walmart.png
  src/site/content/en/learn/wxapkg-cache.png
Labels: cla: yes

#4967 Add author andy bell
  src/site/_data/authorsData.json
Labels: cla: yes

#4971 feat(subscribe): add subscribe partial to home page
  src/site/_includes/homepage.njk
  src/site/content/en/index.md
  src/site/content/pl/index.md
Labels: cla: yes

#4964 render compare caption with md
  src/site/_includes/components/CompareCaption.js
  src/site/_includes/components/Details.js
Labels: cla: yes

#4842 Add codepen shortcode
  .eleventy.js
  src/site/_includes/components/Codepen.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/learn/css/borders/index.md
  types/site/_includes/components/Codepen.d.ts
Labels: cla: yes

#4985 [Read Files article] Add pointers to the new File System Access API throughout
  src/site/content/en/blog/read-files/index.md
Labels: cla: yes

#4892 Learn css side nav
  .editorconfig
  .eleventy.js
  src/images/courses/learn-css.svg
  src/lib/actions.js
  src/lib/components/BaseModalElement/_styles.scss
  src/lib/components/Header/index.js
  src/lib/components/NavigationDrawer/index.js
  src/lib/components/SideNav/_styles.scss
  src/lib/components/SideNav/index.js
  src/lib/components/base.js
  src/lib/store.js
  src/site/_data/courses/css/meta.yml
  src/site/_data/i18n/common.yml
  src/site/_data/i18n/courses.yml
  src/site/_data/i18n/header.yml
  src/site/_filters/pad-start.js
  src/site/_includes/course.njk
  src/site/_includes/default.njk
  src/site/_includes/homepage.njk
  src/site/_includes/icons/arrow-right.svg
  src/site/_includes/icons/close.svg
  src/site/_includes/icons/done.svg
  src/site/_includes/icons/menu.svg
  src/site/_includes/partials/course-gradient-title.njk
  src/site/_includes/partials/header-course.njk
  src/site/_includes/partials/header-default.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/_includes/partials/navigation-drawer-default.njk
  src/site/_includes/partials/side-nav.njk
  src/site/_includes/partials/toc-inner.njk
  src/site/_includes/partials/toc-side.njk
  src/site/_transforms/responsive-images/index.js
  src/styles/components/_all.scss
  src/styles/components/_app-bar.scss
  src/styles/components/_buttons.scss
  src/styles/components/_course-toc.scss
  src/styles/components/_drawer-course.scss
  src/styles/components/_drawer-default.scss
  src/styles/components/_gradient-text.scss
  src/styles/components/_header-course.scss
  src/styles/components/_header-default.scss
  src/styles/components/_header.scss
  src/styles/components/_hero-banner.scss
  src/styles/components/_icon.scss
  src/styles/components/_web-header.scss
  src/styles/components/_web-navigation-drawer.scss
  src/styles/generic/_main.scss
  src/styles/globals/gorko/_config.scss
  src/styles/pages/_course.scss
  src/styles/tools/_breakpoints.scss
Labels: cla: yes

#4941 Warn developers about absolute/relative UVC controls
  src/site/content/en/blog/camera-pan-tilt-zoom/index.md
Labels: cla: yes, content update

#4987 Added Chrome OS support for app shortcuts
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes, content update

#4994 Fix typo: unrequired comma
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#4995 Adding ajara as author in web.dev
  src/site/_data/authorsData.json
Labels: cla: yes

#4996 Fix broken Assessment shortcode
  src/lib/components/BaseResponseElement/index.js
  src/site/_drafts/_template-self-assessment/index.md
  src/site/_includes/components/Assessment.js
  src/site/_includes/course.njk
  src/site/content/en/accessible/control-focus-with-tabindex/index.md
  src/site/content/en/accessible/labels-and-text-alternatives/index.md
  src/site/content/en/accessible/use-semantic-html/index.md
  src/site/content/en/handbook/self-assessment-components/index.md
  src/site/content/en/secure/same-origin-policy/index.md
  types/site/_includes/components/Assessment/TargetAssessment.d.ts
  types/site/_includes/components/Assessment/TargetAssessmentOption.d.ts
  types/site/_includes/components/Assessment/TargetAssessmentQuestion.d.ts
Labels: cla: yes

#4998 set overflow hidden on body, not html
  src/lib/actions.js
Labels: cla: yes

#5000 Add cookie notice article to /learn-web-vitals
  src/site/_data/paths/learn-web-vitals.json
Labels: cla: yes

#4992 Update PWA screenshots ratio requirements to be at most 2.3:1
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#5005 Fix typo
  src/site/content/en/fast/cookie-notice-best-practices/index.md
Labels: cla: yes

#5003 Link to rendered WebPageTest documentation
  src/site/content/en/fast/cookie-notice-best-practices/index.md
Labels: cla: yes

#4975 Gravity sensor: Adding release estimation date
  src/site/content/en/blog/generic-sensor/index.md
Labels: cla: yes

#5002 [Local Font article] Update to reflect API changes
  src/site/content/en/blog/local-fonts/index.md
Labels: cla: yes

#5006 Specify Chrome version for now playing widget
  src/site/content/en/blog/media-session/index.md
Labels: cla: yes

#5004 [FLoC article] A lot of small suggestions and fixes
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5009 Anonymize IPs in google analytics.
  src/site/_includes/partials/analytics.njk
Labels: cla: yes
