Repository GoogleChrome/web.dev, pull requests merged in 2021-06, with the labels that each got.

#5483 [Notification triggers article] Remove tag
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#5482 [Declarative link capturing article] Add missing tag
  src/site/content/en/blog/declarative-link-capturing/index.md
Labels: cla: yes

#5497 Make copy an async function
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#5334 Add supports to WebLayer
  src/site/content/en/payments/android-payment-apps-delegation/index.md
Labels: cla: yes

#5474 Gravity sensor: Remove release estimation date.
  src/site/content/en/blog/generic-sensor/index.md
Labels: cla: yes

#5475 New Post - CSS `:is()` and `:where()`
  src/site/content/en/blog/css-is-and-where/index.md
Labels: blog, cla: yes

#5500 Fix minor typo
  src/site/content/en/blog/css-is-and-where/index.md
Labels: cla: yes

#5484 fix(expand-authors): allow function to continue if no author is present yet, fixes #5452
  src/site/_filters/expand-authors.js
  src/site/_includes/components/Author.js
Labels: cla: yes

#5499 Update CLS definition
  src/site/content/en/metrics/cls/index.md
Labels: cla: no

#5389 "Building multiple Progressive Web Apps on the same domain" article.
  src/site/_data/authorsData.json
  src/site/_data/paths/progressive-web-apps.json
  src/site/content/en/blog/building-multiple-pwas-on-the-same-domain/index.md
Labels: DO NOT MERGE, cla: yes

#5468 replace "the the" with "the"
  src/site/content/en/blog/keyboard-lock/index.md
  src/site/content/en/blog/multi-screen-window-placement/index.md
  src/site/content/en/blog/video-basics/index.md
  src/site/content/en/blog/vr-comes-to-the-web-pt-ii/index.md
  src/site/content/en/handbook/audience/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/lighthouse-pwa/themed-omnibox/index.md
Labels: cla: no

#5478 Update code examples to address edge cases
  src/site/content/en/blog/debug-web-vitals-in-the-field/index.md
Labels: cla: yes

#5502 Remove the tooling updates aside until published
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#5472 Add `chrome://` scheme lint rule
  .remarkrc.js
  tools/linting/no-chrome-scheme.js
Labels: cla: yes

#5504 Add recommended thresholds for FCP
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fcp/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#5498 Adds evolving web tooling blog post
  src/site/content/en/blog/cls-web-tooling/index.md
Labels: cla: yes

#5503 Re-add the CLS tooling updates aside
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#5396 CSS for CWV blog post
  src/site/_data/paths/learn-web-vitals.json
  src/site/content/en/blog/css-web-vitals/index.md
Labels: cla: yes

#5511 Update the Evolving CLS post with tooling status
  src/site/content/en/blog/evolving-cls/index.md
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#5512 Correction for PSI
  src/site/content/en/blog/cls-web-tooling/index.md
Labels: cla: yes

#5424 Add PWA URL Handler article
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#5444 [Browser Flags article] Add `about:blank` exception
  src/site/content/en/blog/browser-flags/index.md
Labels: cla: yes

#5515 [PWA as URL Handlers article] Fix typo
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#5493 fix(sitemap): add paginated pages to sitemap, fixes #4504
  src/site/content/en/authors/index.njk
  src/site/content/en/authors/individual.njk
  src/site/content/en/blog/index.njk
  src/site/content/en/newsletter/index.njk
  src/site/content/en/tags/index.njk
  src/site/content/en/tags/individual.njk
Labels: cla: yes

#5518 Add d.c.c. redirects
  redirects.yaml
Labels: cla: yes

#5516 [File Handling article] Address @dway123's remarks
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#5501 Fix \n appearing in path overview.
  src/site/_data/i18n/paths/discoverable.yml
  src/site/_includes/path.njk
  src/styles/pages/_path.scss
Labels: cla: yes

#5421 Compute Pressure API OT
  src/site/content/en/blog/compute-pressure/index.md
Labels: cla: yes

#5524 Add a better ignore script
  .eleventyignore
  .gitignore
  .huskyrc
  README.md
  package-lock.json
  package.json
  src/site/_includes/components/CodelabsCallout.js
  tools/eleventyignore/index.js
  tools/isolate/index.js
Labels: cla: yes

#5526 [URL Handling article] Acknowledge @mandymsft
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#5517 Web on android update
  src/site/content/en/blog/web-on-android/index.md
Labels: cla: yes

#5534 fixing a typo
  src/site/content/en/fast/serve-responsive-images/index.md
Labels: cla: yes

#5533 fixing a little typo
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#5541 disable insights banner
  src/site/_data/site.js
Labels: cla: yes

#5543 Always run fb preview, even for forks.
  .github/workflows/firebase-hosting-pull-request.yml
Labels: cla: yes

#5522 A proposal to fix language confusion with LanguageSelect
  src/lib/components/LanguageSelect/index.js
  src/site/_includes/partials/translation-disclaimer.njk
  src/site/content/es/es.11tydata.js
  src/site/content/es/vitals/index.md
Labels: cla: yes

#5519 The first 3 shortcuts are used on Android, not 4
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes

#5555 [Web Share Target article] Add feedback and hashtag
  src/site/content/en/blog/web-share-target/index.md
Labels: cla: yes

#5554 [Web Share article] Add feedback and hashtag
  src/site/content/en/blog/web-share/index.md
Labels: cla: yes

#5557 [Compute Pressure] Update OT milestone
  src/site/content/en/blog/compute-pressure/index.md
Labels: cla: yes

#5530 Add fonts best practices
  src/site/_data/paths/learn-web-vitals.json
  src/site/content/en/fast/font-best-practices/index.md
Labels: cla: yes

#5550 Use single quotes
  src/site/content/en/blog/commonjs-larger-bundles/index.md
Labels: cla: yes

#5551 Add missing arrow
  src/site/content/en/blog/gamepad/index.md
Labels: cla: yes

#5552 Add missing async
  src/site/content/en/blog/five-ways-airshift-improved-their-react-app/index.md
Labels: cla: yes

#5556 update to article
  src/site/content/en/fast/value-of-speed/index.md
Labels: DO NOT MERGE, cla: yes

#5247 Add es translations to i18n dir
  src/site/_data/i18n/common.yml
  src/site/_data/i18n/courses.yml
  src/site/_data/i18n/footer.yml
  src/site/_data/i18n/header.yml
  src/site/_data/i18n/learn.yml
  src/site/_data/i18n/post.yml
  src/site/_data/i18n/stackoverflow.yml
  src/site/_data/i18n/subscribe.yml
  src/site/_data/i18n/toc.yml
Labels: cla: yes

#5568 [Fugu Status article] Link new codelab
  src/site/content/en/blog/fugu-status/index.md
Labels: cla: yes

#5567 Typo in learn css grid section
  src/site/content/en/learn/css/grid/index.md
Labels: cla: yes

#5548 change .my-element to my.class to match explanation
  src/site/content/en/learn/css/selectors/index.md
Labels: cla: yes

#5544 update metric thresholds for Lighthouse 8
  src/site/content/en/lighthouse-performance/first-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/interactive/index.md
  src/site/content/en/lighthouse-performance/lighthouse-largest-contentful-paint/index.md
  src/site/content/en/lighthouse-performance/lighthouse-total-blocking-time/index.md
  src/site/content/en/lighthouse-performance/performance-scoring/index.md
  src/site/content/en/lighthouse-performance/speed-index/index.md
Labels: cla: yes

#5573 Increase stalebot timeout to 90 days
  .github/stale.yml
Labels: cla: yes

#5507 Add libSquoosh announcement article
  src/site/content/en/blog/introducing-libsquoosh/index.md
Labels: cla: yes

#5339 implement course search results according to the design
  src/lib/components/CourseSearchResults/index.js
  src/lib/components/Search/index.js
  src/lib/components/SearchResults/index.js
  src/lib/pages/course.js
  src/site/_includes/partials/navigation-drawer-course.njk
  src/styles/components/_all.scss
  src/styles/components/_course-search-results.scss
  src/styles/components/_drawer-course.scss
Labels: cla: yes

#5523 New Post: CSS `size-adjust`
  src/site/content/en/blog/css-size-adjust/index.md
Labels: blog, cla: yes

#5569 Design System/Pattern Library prototype
  .eleventy.js
  package-lock.json
  package.json
  src/lib/components/FrameSizer/index.js
  src/lib/pages/design-system.js
  src/pattern-library/patterns/button/button.json
  src/pattern-library/patterns/button/button.md
  src/pattern-library/patterns/button/button.njk
  src/pattern-library/patterns/button/variants/button-secondary/button-secondary.json
  src/pattern-library/patterns/button/variants/button-secondary/button-secondary.njk
  src/pattern-library/patterns/toggle-switch/toggle-switch.json
  src/pattern-library/patterns/toggle-switch/toggle-switch.md
  src/pattern-library/patterns/toggle-switch/toggle-switch.njk
  src/site/_data/patterns.js
  src/site/_filters/md.js
  src/site/_includes/components/BaseCard.js
  src/site/_includes/design-system.njk
  src/site/content/en/design-system/colors.njk
  src/site/content/en/design-system/design-system.11tydata.json
  src/site/content/en/design-system/patterns-preview.njk
  src/site/content/en/design-system/patterns.njk
  src/site/content/en/design-system/typography.njk
  src/site/content/en/design-system/welcome.njk
  src/styles/_prototype.scss
  src/styles/main.scss
Labels: cla: yes

#5577 updating post date to publish date
  src/site/content/en/blog/css-size-adjust/index.md
Labels: cla: yes

#5578 [bugfix] Revert 85f0811
  src/site/content/en/blog/at-property/index.md
Labels: cla: yes

#5536 adds AVIF post
  package-lock.json
  src/site/_data/authorsData.json
  src/site/content/en/blog/compress-images-avif/index.md
Labels: cla: yes

#5579 Remove fb preview
  .github/workflows/firebase-hosting-pull-request.yml
Labels: cla: yes

#5553 Correctly annotate html snippets
  src/site/content/en/blog/fast-playback-with-preload/index.md
Labels: cla: yes

#5561 New Post: Gui Challenges - Building color schemes
  src/site/content/en/blog/building-a-color-scheme/index.md
Labels: blog, cla: yes

#5539 docs(frontend): correct unpacking of `flex: 1` (#5537)
  src/site/content/en/learn/css/flexbox/index.md
Labels: cla: yes

#5584 fix(frontend-learn-css): typo in functions chapter
  src/site/content/en/learn/css/functions/index.md
Labels: cla: yes

#5587 fix(frontend-learn-css): add notes to drop-shadow usage and text-shad…
  src/site/content/en/learn/css/shadows/index.md
  src/site/content/en/learn/css/shadows/shadows.assess.yml
Labels: cla: yes

#5509 Fixes size inaccuracy in box-model breakdown
  src/site/content/en/learn/css/box-model/index.md
Labels: cla: yes

#5592 Add `align-items` and `justify-items` Codepen demo
  src/site/content/en/learn/css/grid/index.md
Labels: bug, cla: yes

#5601 Bug/learn css logical properties minor corrections
  src/site/content/en/learn/css/logical-properties/index.md
Labels: cla: yes

#5605 Tune up pullapprove groups
  .pullapprove.yml
Labels: cla: yes, privacy/security

#5608 Add more content areas to pullapprove
  .pullapprove.yml
Labels: cla: yes

#5596 Telegraph CLS case study
  src/site/_data/authorsData.json
  src/site/content/en/blog/telegraph/index.md
Labels: cla: yes

#5595 [Tabbed Application Mode] Remove warning about `"tabbed"` being a no-op
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#5612 Add missed event type
  src/site/content/en/blog/module-workers/index.md
Labels: cla: yes

#5621 [Content Indexing API article] Fix links
  src/site/content/en/blog/content-indexing-api/index.md
Labels: cla: yes

#5610 [Mini App Conclusions] Fix link
  src/site/content/en/mini-apps/mini-app-conclusion/index.md
Labels: cla: yes

#5538 Adds "Introducing Aurora" post
  redirects.yaml
  src/site/_data/authorsData.json
  src/site/content/en/blog/introducing-aurora/index.md
Labels: cla: yes

#5625 Add Blibli case study.
  src/site/_data/authorsData.json
  src/site/content/en/blog/blibli/index.md
Labels: cla: yes

#5634 Provide better hero image.
  src/site/content/en/blog/blibli/index.md
Labels: cla: yes

#5559 Add Storage Foundation article
  src/site/_data/event.js
  src/site/content/en/blog/ready-player-web/index.md
  src/site/content/en/blog/storage-foundation/index.md
  src/site/content/en/progressive-web-apps/what-are-pwas/index.md
Labels: cla: yes

#5604 font-best-practices/index.md Clarify font terminology and variable font minutia
  src/site/content/en/fast/font-best-practices/index.md
Labels: cla: yes

#5641 fix(frontend-learn-css): link to the animate lesson
  src/site/content/en/learn/css/functions/index.md
Labels: cla: yes

#5628 Remove newline from "Getting started with measuring Web Vitals" title
  src/site/content/en/blog/vitals-measurement-getting-started/index.md
Labels: cla: yes

#5510 Add documentation for Lighthouse CSP XSS audit
  src/site/_data/paths/lighthouse-best-practices.json
  src/site/content/en/lighthouse-best-practices/csp-xss/index.md
Labels: cla: yes

#5639 Add tme so article pos shows it was last published
  src/site/content/en/blog/blibli/index.md
Labels: cla: yes

#5647 Fix a twitter handle.
  src/site/_data/authorsData.json
Labels: cla: yes

#5637 [Post Update] Content-visibility
  src/site/content/en/blog/content-visibility/index.md
Labels: cla: yes

#5590 Add rel=noopener for external links in markdown
  src/site/_plugins/markdown.js
Labels: cla: yes

#5589 Add link to d.c.c in related content in footer.
  src/site/_data/i18n/footer.yml
  src/site/_includes/partials/footer.njk
Labels: cla: yes

#5520 Factor our ScrollSpy from Toc into separate component
  src/lib/components/ScrollSpy/index.js
  src/lib/components/TableOfContents/index.js
  src/lib/pages/content.js
  src/site/_includes/partials/toc-side.njk
  src/styles/components/_course-toc.scss
  src/styles/components/_toc.scss
Labels: cla: yes

#5643 Add draft PR as a separate condition to pullapprove
  .pullapprove.yml
Labels: cla: yes

#5652 fix(frontend-learn-css): typo of property's value
  src/site/content/en/learn/css/animations/index.md
Labels: cla: yes

#5655 [Storage Foundation article] Fix links
  src/site/content/en/blog/storage-foundation/index.md
Labels: cla: yes

#5656 ✏️ Fix typo in Cascade lesson
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#5659 remove banner
  src/site/_data/site.js
Labels: cla: yes

#5646 Remove whitespace from titles in the path topics list
  src/site/_includes/partials/item.njk
  src/site/_includes/partials/post.njk
Labels: cla: yes

#5658 Blog post on new responsiveness metric
  src/site/_data/authorsData.json
  src/site/content/en/blog/better-responsiveness-metric/index.md
Labels: cla: no

#5675 fix(frontend-learn-css): format of properties' values
  src/site/content/en/learn/css/blend-modes/index.md
Labels: cla: yes

#5669 docs(learn-css): extend supported properties for ::marker (#5668)
  src/site/content/en/learn/css/pseudo-elements/index.md
Labels: cla: yes

#5667 Bug/learn css pseudo element typos
  src/site/content/en/learn/css/pseudo-elements/index.md
  src/site/content/en/learn/css/pseudo-elements/pseudo-elements.assess.yml
Labels: cla: yes

#5680 Remove unnecessary head ending
  src/site/_transforms/purify-css.js
Labels: cla: yes

#5686 fix(feeds): trim RSS feed entries' content to just the first paragraph, fixes #5676 and fixes #5663
  .eleventy.js
  src/site/_filters/first-paragraph.js
  src/site/_includes/feed.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#5620 Add media attribute support for meta[name=theme-color]
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
Labels: cla: yes

#5684 Updates Conformance blog post
  src/site/content/en/blog/conformance/index.md
Labels: cla: yes

#5694 fix(rss): includes escaped HTML tags, fixes #5691
  src/site/_filters/first-paragraph.js
  src/site/_includes/feed.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#5692 📝 Update Flexbox assessment
  src/site/content/en/learn/css/flexbox/conclusion.assess.yml
Labels: cla: yes

#5703 ✏️ Add rationale for grid quiz
  src/site/content/en/learn/css/grid/grid.assess.yml
Labels: cla: yes

#5708 ✏️ [Learn CSS] Fix typo in Spacing module
  src/site/content/en/learn/css/spacing/index.md
Labels: cla: yes

#5701 LearnCSS: Functions syntax correct
  src/site/content/en/learn/css/functions/index.md
Labels: cla: yes

#5704 Small typo in handbook
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#5690 Append caution about SAB change in Chrome 92 to COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: cla: yes

#5695 Fixed typo
  src/site/content/en/media/video-and-source-tags/index.md
Labels: cla: yes

#5697 refactor(cards): break up cards into different purposeful macros, fixes #2717
  .eleventy.js
  src/site/_filters/find-tags.js
  src/site/_includes/components/AuthorCard.js
  src/site/_includes/components/BaseCard.js
  src/site/_includes/components/PostCard.js
  src/site/_includes/homepage.njk
  src/site/_includes/macros/author-card.njk
  src/site/_includes/macros/post-card.njk
  src/site/_includes/macros/tag-card.njk
  src/site/_includes/macros/tag-chips.njk
  src/site/_includes/partials/paged.njk
  src/site/_includes/partials/post.njk
  src/site/content/en/authors/index.njk
  src/site/content/en/tags/index.njk
  src/styles/components/_card-base.scss
Labels: cla: yes

#5679 Obfuscate error message
  src/lib/actions.js
Labels: cla: yes

#5712 refactor(feeds): limit feeds to 24 posts rather than truncating the posts
  .eleventy.js
  src/site/_collections/hooks/utils.js
  src/site/_data/site.js
  src/site/_filters/first-paragraph.js
  src/site/_includes/feed.njk
  src/site/content/en/authors/feed.njk
  src/site/content/en/tags/feed.njk
Labels: cla: yes

#5711 ✏️ [Learn CSS] Fix typo in pseudo-classes
  src/site/content/en/learn/css/pseudo-classes/index.md
Labels: cla: yes

#5412 Add New PWA Training blog post
  src/site/content/en/blog/new-pwa-training/index.md
Labels: cla: yes

#5719 Add pwa banner and instructions
  src/site/_data/site.js
  src/site/content/en/handbook/banners/index.md
Labels: cla: yes

#5723 Don't tag milica on dependabot PRs
  .pullapprove.yml
Labels: cla: yes

#5717 Remove double parentheses in link
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
Labels: cla: yes

#5713 Update resource hints for Google Fonts
  src/site/content/en/blog/css-web-vitals/index.md
Labels: cla: no

#5696 Update Lighthouse docs for modern image formats
  src/site/content/en/lighthouse-performance/uses-webp-images/index.md
Labels: cla: yes

#5662 Update index.md
  src/site/content/en/accessible/semantics-and-screen-readers/index.md
Labels: cla: no

#5660 Fix DEMO link and capture_links values
  src/site/content/en/blog/declarative-link-capturing/index.md
Labels: cla: yes

#5653 Change animation to animate
  src/site/content/en/animations/animations-overview/index.md
Labels: cla: yes

#5649 Update CrUX BQ releases in CLS update
  src/site/content/en/blog/cls-web-tooling/index.md
Labels: cla: yes

#5661 fix typo in "Debug Web Vitals in the field"
  src/site/content/en/blog/debug-web-vitals-in-the-field/index.md
Labels: cla: yes

#5222 Update documentation on render-blocking stylesheet
  src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
Labels: cla: yes

#5542 Add note re about:// instead of chrome:// to handbook.
  src/site/content/en/handbook/grammar/index.md
Labels: cla: yes

#4450 Move async article from WebFu.
  src/site/content/en/blog/async-functions/index.md
  src/site/content/en/blog/promises/index.md
Labels: DO NOT MERGE, cla: yes

#5664 [File Handling article] Add OT link
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#5651 [PWAs as URL handerls] Address @mandymsft's remarks
  src/site/content/en/blog/pwa-url-handler/index.md
Labels: cla: yes

#5714 Clarify usage of preconnect for fonts
  src/site/content/en/fast/font-best-practices/index.md
Labels: cla: yes

#5650 [File Handling article] Highlight it's for installed apps only
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#5631 [File System Access API article] Add distinction clarification
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes
