Repository GoogleChrome/web.dev, pull requests merged in 2021-04, with the labels that each got.

#5013 [Notification Triggers article] Update article now that the OT is over
  src/site/content/en/blog/notification-triggers/index.md
Labels: cla: yes

#5007 FLoC: fix to image, flags and OT link
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5010 Add debugging web vitals in the field post
  redirects.yaml
  src/site/_data/paths/learn-web-vitals.json
  src/site/content/en/blog/debug-web-vitals-in-the-field/index.md
  src/site/content/en/fast/debug-layout-shifts/index.md
Labels: cla: yes

#5018 Add next and prev buttons to courses
  src/site/_data/i18n/common.yml
  src/site/_includes/course.njk
  src/site/_includes/icons/arrow-back.svg
  src/site/_includes/icons/arrow-forward.svg
  src/site/_includes/partials/course-pagination.njk
  src/site/content/en/learn/css/borders/index.md
  src/site/content/en/learn/css/shadows/index.md
  src/styles/components/_all.scss
  src/styles/components/_course-pagination.scss
  src/styles/globals/gorko/_config.scss
  src/styles/pages/_course.scss
Labels: cla: yes

#4974 Update index.md
  src/site/content/en/media/media-file-basics/index.md
Labels: cla: yes

#5026 Update Chrome OS milestone for app shortcuts
  src/site/content/en/blog/app-shortcuts/index.md
Labels: cla: yes

#5028 Update index.md - misspelling
  src/site/content/en/fast/why-speed-matters/index.md
Labels: cla: yes

#4990 updates to manifest updates
  src/site/content/en/progressive-web-apps/manifest-updates/index.md
Labels: cla: yes

#5035 [Tabbed Application Mode article] Make the warning more explicit and link to display_override
  src/site/content/en/blog/tabbed-application-mode/index.md
Labels: cla: yes

#5037 Fix minor grammar issues
  src/site/content/en/blog/evolving-cls/index.md
Labels: cla: yes

#5024 Add audio player for courses section
  src/lib/components/AudioFab/index.js
  src/lib/pages/course.js
  src/site/_includes/course.njk
  src/site/_includes/macros/audio-fab.njk
  src/site/_includes/macros/audio-player.njk
  src/site/content/en/learn/css/borders/index.md
  src/site/content/en/learn/css/index.md
  src/styles/components/_all.scss
  src/styles/components/_audio-player.scss
  src/styles/components/_buttons.scss
  src/styles/components/_web-audio-fab.scss
  src/styles/settings/_global.scss
Labels: cla: yes

#5041 Clarify that higher is worse
  src/site/content/en/blog/evolving-cls/index.md
Labels: cla: yes

#5042 Add markdown definition list support.
  .eleventy.js
  package-lock.json
  package.json
  src/site/_plugins/markdown.js
  src/site/content/en/handbook/web-dev-components/index.md
  src/styles/generic/_lists.scss
Labels: cla: yes

#4993 Add rel=alternate hreflang links
  src/site/_includes/components/Meta.js
Labels: cla: yes

#5047 [Meta Description article] Use lowercase attribute value
  src/site/content/en/lighthouse-seo/meta-description/index.md
Labels: cla: yes

#5049 Fix incorrect link
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#5051 fix(optimize-cls): add missing videos, fixes #5050
  src/site/content/en/blog/optimize-cls/index.md
Labels: cla: yes

#5039 Updated information about exclusion/inclusion from FLoC calculation
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5052 Incorporate timer story to why-coop-coep
  src/site/content/en/blog/why-coop-coep/index.md
Labels: cla: yes

#4982 Learn CSS Box Model
  src/site/content/en/learn/css/box-model/index.md
Labels: DO NOT MERGE, cla: yes

#4984 Adding lesson on the cascade
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#4983 Learn CSS Selectors
  src/site/_data/authorsData.json
  src/site/content/en/learn/css/selectors/index.md
Labels: cla: yes

#5056 Add additional CLS info to carousel article
  src/site/content/en/blog/carousel-best-practices/index.md
Labels: cla: yes

#5023 Zalando case study
  src/site/_data/authorsData.json
  src/site/content/en/blog/zalando/index.md
Labels: cla: yes

#5073 Update profile photos for Penny & Pete
  src/site/_data/authorsData.json
Labels: cla: yes

#5074 Move DevSat post
  src/site/content/en/developer-satisfaction/index.md
Labels: cla: yes

#5075 Fix a typo
  src/site/_data/authorsData.json
Labels: cla: yes

#5070 Added information about who runs the back-end FLoC service
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5076 Fixed typo on FLoC overview image
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5079 Rename Web OTP to WebOTP
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/goibibo/index.md
  src/site/content/en/blog/payment-and-address-form-best-practices/index.md
  src/site/content/en/blog/sign-in-form-best-practices/index.md
  src/site/content/en/blog/sign-up-form-best-practices/index.md
  src/site/content/en/blog/sms-otp-form/index.md
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#5085 Fix broken search.
  src/lib/components/Search/_styles.scss
  src/lib/components/Search/index.js
  src/styles/components/_header-course.scss
  src/styles/components/_header-default.scss
  src/styles/components/_web-header.scss
Labels: cla: yes

#5019 Adds specificity lesson
  src/site/content/en/learn/css/specificity/index.md
Labels: cla: yes

#5088 Update Chrome + Edge release status for Declarative Shadow DOM
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#5078 Added font preload content type
  src/site/content/en/lighthouse-performance/font-display/index.md
Labels: cla: yes

#5069 remove install crit change from PWA docs
  src/site/content/en/progressive-web-apps/install-criteria/index.md
Labels: cla: yes

#4655 New Post: 2021 Scroll Survey
  src/site/content/en/blog/2021-scroll-survey/index.md
Labels: cla: yes

#5091 Clarified information about inclusion in FLoC calculation
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5094 fix(subscribe): import subscribe element, fixes #5015
  src/lib/pages/home.js
  src/site/_includes/homepage.njk
  src/site/content/en/newsletter/index.njk
Labels: cla: yes

#5063 Add course card to /learn/ page
  src/images/courses/css/background.svg
  src/images/courses/css/logo.svg
  src/images/courses/css/thumbnail.svg
  src/images/courses/learn-css.svg
  src/site/_data/courses/css/meta.yml
  src/site/_data/helpers.js
  src/site/_data/i18n/courses.yml
  src/site/_data/i18n/learn.yml
  src/site/_data/site.js
  src/site/_includes/macros/icon.njk
  src/site/_includes/partials/course-cards.njk
  src/site/_includes/partials/course-gradient-title.njk
  src/site/_includes/partials/header-course.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/content/en/learn/index.njk
  src/styles/components/_all.scss
  src/styles/components/_card.scss
  src/styles/components/_course-card.scss
  src/styles/components/_drawer-course.scss
  src/styles/components/_gradient-text.scss
  src/styles/components/_header-course.scss
  src/styles/components/_layouts.scss
  src/styles/components/_learn-section.scss
Labels: cla: yes

#5020 Learn CSS Inheritance
  src/site/content/en/learn/css/inheritance/index.md
Labels: cla: yes

#5090 Describe situation in which images without width/height are not lazy-loaded (#4273)
  src/site/content/en/fast/browser-level-image-lazy-loading/index.md
Labels: cla: yes

#5087 Add pointer to Private Network Access update.
  src/site/content/en/blog/cors-rfc1918-feedback/index.md
Labels: cla: yes

#5012 Adds Learn CSS color module
  src/site/content/en/learn/css/color/index.md
Labels: cla: yes

#5105 Remove instances of "master"
  README.md
  src/site/content/en/blog/file-system-access/index.md
  src/site/content/en/blog/more-variable-font-options-in-chromium-83/index.md
  src/site/content/en/blog/zalando/index.md
  src/site/content/en/fast/using-bundlesize-with-travis-ci/index.md
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
Labels: cla: yes

#5103 Remove last remaining instances of "native"
  src/site/_includes/content/lighthouse-accessibility/use-built-in.njk
  src/site/content/en/blog/browser-fs-access/index.md
  src/site/content/en/blog/build-for-webusb/index.md
  src/site/content/en/blog/building-a-settings-component/index.md
  src/site/content/en/blog/building-a-stories-component/index.md
  src/site/content/en/blog/covid19/index.md
  src/site/content/en/blog/iframe-lazy-loading/index.md
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
  src/site/content/en/blog/service-worker-mindset/index.md
  src/site/content/en/blog/shopping-for-speed-on-ebay/index.md
  src/site/content/en/blog/sign-up-form-best-practices/index.md
  src/site/content/en/blog/site-speed-and-business-metrics/index.md
  src/site/content/en/blog/usb/index.md
  src/site/content/en/fast/efficiently-load-third-party-javascript/index.md
  src/site/content/en/fast/lazy-loading-images/index.md
  src/site/content/en/fast/lazy-loading/index.md
  src/site/content/en/fast/rail/index.md
  src/site/content/en/fast/use-lazysizes-to-lazyload-images/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/lighthouse-accessibility/aria-name/index.md
  src/site/content/en/lighthouse-performance/offscreen-images/index.md
  src/site/content/en/mini-apps/mini-app-components/index.md
  src/site/content/en/mini-apps/mini-app-open-source-projects/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
  src/site/content/en/progressive-web-apps/codelab-make-installable/index.md
  src/site/content/en/reliable/offline-cookbook/index.md
Labels: cla: yes

#5095 build(gulp): refactor gulpfile into tasks, fixes #3823
  gulp-tasks/copy-content-assets.js
  gulp-tasks/copy-default-locale.js
  gulp-tasks/copy-fonts.js
  gulp-tasks/copy-global-images.js
  gulp-tasks/copy-misc.js
  gulp-tasks/utils.js
  gulpfile.js
  package-lock.json
  package.json
Labels: cla: yes

#5109 fix(card): improve quality by cropping them, fixes #4738
  src/site/_includes/components/Author.js
  src/site/_includes/components/AuthorCard.js
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/components/BaseCard.js
Labels: cla: yes

#5111 fix(gcb): fix google cloud build
  package-lock.json
  src/lib/components/Assessment/index.js
  src/lib/components/EventTime/index.js
  src/lib/components/LanguageSelect/index.js
  src/lib/components/LighthouseScoresAudits/index.js
  src/lib/components/ProfileSwitcher/index.js
  src/lib/components/SelectGroup/index.js
  src/lib/components/Snackbar/index.js
  src/lib/components/TableOfContents/index.js
  src/site/_includes/components/Assessment.js
  src/site/_includes/components/Author.js
  src/site/_includes/components/AuthorCard.js
  src/site/_includes/components/AuthorsDate.js
  src/site/_includes/components/BaseCard.js
  src/site/_includes/components/Blockquote.js
  src/site/_includes/components/EventTable.js
  src/site/_includes/components/PathCard.js
  src/site/_includes/components/StackOverflow.js
  src/site/content/en/blog/building-a-tabs-component/index.md
Labels: cla: yes

#5101 Update cross-origin isolation related articles
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#5046 Add RSS button
  src/site/content/en/tags/individual.njk
  src/styles/pages/_tags.scss
Labels: cla: yes

#5124 build(staging): add staging environment
  .eleventy.js
  gulp-tasks/copy-default-locale.js
  gulp-tasks/sass.js
  gulp-tasks/utils.js
  rollup.config.js
  src/site/_data/lib/hash.js
  src/site/_filters/strip-query-params-dev.js
Labels: cla: yes

#5115 refactor(shortcodes): use Img and Video shortcode from `webdev-infra` repo
  .eleventy.js
  package-lock.json
  package.json
  src/site/_collections/algolia.js
  src/site/_data/site.js
  src/site/_includes/components/Assessment.js
  src/site/_includes/components/Img.js
  src/site/_includes/components/Meta.js
  src/site/_includes/components/PathCard.js
  src/site/_includes/components/Video.js
  src/site/content/en/handbook/markup-media/index.md
  types/site/_includes/components/Img.d.ts
  types/site/_includes/components/Video.d.ts
Labels: cla: yes

#5086 New article: WebOTP iframe support
  src/site/content/en/blog/web-otp-iframe/index.md
Labels: cla: yes

#5123 Update gitlocalize link
  src/site/_data/site.js
Labels: cla: yes

#5029 Updates for WebTransport OT
  src/site/content/en/blog/webtransport/index.md
Labels: cla: yes

#5125 New post gui challenge split text
  src/site/content/en/blog/building-split-text-animations/index.md
Labels: cla: yes

#5118 Added inclusion aside
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5119 Add progress tracking to course drawer
  src/lib/components/DrawerCourse/index.js
  src/lib/pages/course.js
  src/site/_includes/partials/navigation-drawer-course.njk
Labels: cla: yes

#5128 Course headings
  package-lock.json
  package.json
  src/site/_includes/course.njk
  src/site/_includes/partials/course-app-bar.njk
  src/site/_includes/partials/course-audio.njk
  src/site/content/en/learn/css/index.md
  src/styles/components/_app-bar.scss
  src/styles/components/_course-toc.scss
  src/styles/globals/gorko/_config.scss
  src/styles/pages/_course.scss
  src/styles/tools/_mixins.scss
Labels: cla: yes

#4680 Add Window Controls Overlay article
  src/site/_data/authorsData.json
  src/site/content/en/blog/window-controls-overlay/index.md
Labels: DO NOT MERGE, cla: yes

#5150 Data transfer corrections
  src/site/_data/authorsData.json
  src/site/content/en/blog/datatransfer/index.md
Labels: cla: yes

#5133 [File System Access article] Add info about `startIn`, `suggestedName`, and `id`
  src/site/content/en/blog/file-system-access/index.md
Labels: cla: yes

#5145 third party tags article
  src/site/_data/authorsData.json
  src/site/content/en/blog/controlling-third-party-scripts/index.md
Labels: cla: yes

#5146 `s/Javascript/JavaScript`
  src/site/content/en/blog/building-a-settings-component/index.md
  src/site/content/en/blog/building-a-sidenav-component/index.md
  src/site/content/en/blog/building-a-tabs-component/index.md
  src/site/content/en/blog/building-split-text-animations/index.md
  src/site/content/en/blog/codelab-building-a-sidenav-component/index.md
  src/site/content/en/blog/fast-playback-with-preload/index.md
  src/site/content/en/blog/how-mercadolibre-optimized-web-vitals/index.md
  src/site/content/en/blog/next-gen-css-2019/index.md
  src/site/content/en/blog/preload-responsive-images/index.md
  src/site/content/en/blog/snap-after-layout/index.md
  src/site/content/en/fast/codelab-optimize-third-party-javascript/index.md
  src/site/content/en/fast/how-can-performance-improve-conversion/index.md
  src/site/content/en/fast/what-should-you-measure-to-improve-performance/index.md
  src/site/content/en/fast/your-first-performance-budget/index.md
  src/site/content/en/handbook/audience/index.md
Labels: cla: yes

#5138 Adds box model assessment
  src/site/content/en/learn/css/box-model/box-model.assess.yml
  src/site/content/en/learn/css/box-model/index.md
Labels: cla: yes

#5140 Adds selector assessments
  src/site/content/en/learn/css/selectors/complex-selectors.assess.yml
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/learn/css/selectors/pseudo-selectors.assess.yml
  src/site/content/en/learn/css/selectors/simple-selectors.assess.yml
Labels: cla: yes

#5141 Adds cascade assessments
  src/site/content/en/learn/css/the-cascade/conclusion.assess.yml
  src/site/content/en/learn/css/the-cascade/index.md
  src/site/content/en/learn/css/the-cascade/origin.assess.yml
  src/site/content/en/learn/css/the-cascade/position.assess.yml
Labels: cla: yes

#5126 Add DataTransfer article
  src/site/_data/authorsData.json
  src/site/content/en/blog/datatransfer/index.md
Labels: cla: yes

#5121 Add Mainline Mensware article
  src/site/_data/authorsData.json
  src/site/content/en/blog/mainline-mensware/index.md
Labels: cla: yes

#5130 adding flexbox lesson
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/flexbox/index.md
Labels: cla: yes

#5131 adds learn css logical properties
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/logical-properties/index.md
Labels: cla: yes

#5152 Add learn css reviewers
  .pullapprove.yml
Labels: cla: yes

#5155 Adds specificity assessments
  src/site/content/en/learn/css/specificity/index.md
  src/site/content/en/learn/css/specificity/scoring-advanced.assess.yml
  src/site/content/en/learn/css/specificity/scoring-beginner.assess.yml
  src/site/content/en/learn/css/specificity/visualizing.assess.yml
Labels: cla: yes

#5149 Remove proprietary -webkit-details-marker
  src/styles/components/_course-toc.scss
  src/styles/components/_details.scss
  src/styles/components/_self-assessment-hint.scss
  src/styles/pages/_live.scss
Labels: cla: yes

#5144 fix error
  src/site/content/en/progressive-web-apps/customize-install/index.md
Labels: cla: yes

#5158 Update the status of the Web memory API
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
Labels: cla: yes

#5161 Implement share button
  src/site/_data/i18n/common.yml
  src/site/_includes/icons/share.svg
  src/site/_includes/partials/course-app-bar.njk
  src/styles/components/_app-bar.scss
  src/styles/components/_buttons.scss
Labels: cla: yes

#5162 Add vanity url for learncss
  redirects.yaml
Labels: cla: yes

#5147 Make lighthouse guides open in a new window
  src/lib/components/LighthouseScoresAudits/index.js
Labels: cla: yes

#5165 Remove course tags.
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/color/index.md
  src/site/content/en/learn/css/flexbox/index.md
  src/site/content/en/learn/css/inheritance/index.md
  src/site/content/en/learn/css/logical-properties/index.md
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/learn/css/specificity/index.md
Labels: cla: yes

#5137 build(git): only deploy site if it's a new commit, fixes #3655
  .cloudbuild/deploy.yaml
  gulp-tasks/write-version.js
  gulpfile.js
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#5168 build(logging): log errors on version checks
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#5166 Adds color assessment
  src/site/content/en/learn/css/color/color.assess.yml
  src/site/content/en/learn/css/color/index.md
Labels: cla: yes

#5170 Post patch: community contribution to split text post
  src/site/content/en/blog/building-split-text-animations/index.md
Labels: cla: yes

#4969 Asyncify blog post
  src/site/content/en/blog/asyncify/index.md
Labels: cla: yes

#5142 Updates to SXG article
  src/site/content/en/fast/signed-exchanges/index.md
Labels: cla: yes

#5171 Clarify that the thresholds are inclusive
  src/site/content/en/vitals/index.md
Labels: cla: yes

#5174 build(firebase): set no cache for html
  firebase.incl.json
Labels: cla: yes

#5175 build(firebase): set no cache for html (again)
  firebase.incl.json
Labels: cla: yes

#5148 Updates section on the Quality Criteria
  src/site/content/en/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
Labels: cla: yes, content update

#5159 Add thumbnail for css course
  src/site/_data/courses/css/meta.yml
  src/site/content/en/learn/css/css.11tydata.js
Labels: cla: yes

#5129 Improve the look of the audio player and toc
  src/site/_includes/macros/audio-player.njk
  src/site/_includes/partials/toc-inner.njk
  src/styles/components/_audio-player.scss
  src/styles/components/_course-toc.scss
Labels: cla: yes

#5157 Run eleventy once before starting the server, then watch for changes.
  package.json
Labels: cla: yes

#5008 First pass at using strict CSP
  .eleventy.js
  firebase-config.js
  src/site/_data/lib/hash.js
  src/site/_filters/csp-hash.js
  src/site/_filters/minify-js.js
  src/site/_includes/partials/analytics.njk
  src/site/_includes/partials/head.njk
Labels: cla: yes

#5187 feat(youtube): migrate YouTube shortcode to use `webdev-infra`
  .eleventy.js
  package-lock.json
  package.json
  src/lib/components/LivestreamContainer/index.js
  src/lib/components/base.js
  src/site/_includes/components/YouTube.js
  src/site/content/en/blog/fetch-metadata/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/optimize-cls/index.md
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/en/blog/prefers-color-scheme/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/web-dev-components/index.md
  src/site/content/en/reliable/adaptive-loading-with-service-workers/index.md
  src/site/content/en/reliable/app-shell-ux-with-service-workers/index.md
  src/site/content/en/reliable/instant-navigation-experiences/index.md
  src/site/content/en/reliable/resilient-search-experiences/index.md
  src/styles/components/_youtube.scss
  test/unit/src/lib/components/LivestreamContainer/index.js
Labels: cla: yes

#5195 Add CLS reporting in prod
  .cloudbuild/deploy.yaml
Labels: cla: yes

#5196 build(version-check): set `NODE_ENV` to `production` in order to log errors in version check script
  .cloudbuild/deploy.yaml
Labels: cla: yes

#5186 Preload fonts and fix layout shifts on learn pages.
  src/site/_includes/devsite/devsite-footer.njk
  src/site/_includes/devsite/devsite-header.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/header-default.njk
  src/site/_includes/partials/navigation-drawer-default.njk
  src/styles/components/_drawer-default.scss
  src/styles/components/_header-default.scss
  src/styles/components/_mastheads.scss
  src/styles/fonts/_google-sans.scss
Labels: cla: yes

#5183 Adds flexbox assessments
  src/site/content/en/learn/css/flexbox/conclusion.assess.yml
  src/site/content/en/learn/css/flexbox/flex.assess.yml
  src/site/content/en/learn/css/flexbox/index.md
Labels: cla: yes

#5185 Adds logical properties assessment
  src/site/content/en/learn/css/logical-properties/index.md
  src/site/content/en/learn/css/logical-properties/logical-props.assess.yml
Labels: cla: yes

#5156 Adds inheritance assessments
  src/site/content/en/learn/css/inheritance/conclusion.assess.yml
  src/site/content/en/learn/css/inheritance/index.md
Labels: cla: yes

#5182 Learn CSS flexbox lesson patch
  src/site/content/en/learn/css/flexbox/index.md
Labels: cla: yes

#5077 Adds Learn CSS Sizing
  src/site/content/en/learn/css/sizing/index.md
Labels: cla: yes

#5116 Adding Learn Layout lesson
  src/site/content/en/learn/css/layout/index.md
Labels: cla: yes

#5194 Learn css diagrams
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/color/index.md
  src/site/content/en/learn/css/flexbox/index.md
  src/site/content/en/learn/css/logical-properties/index.md
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/learn/css/specificity/index.md
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#5203 Fix CWV images
  src/site/content/en/blog/optimize-cls/index.md
  src/site/content/en/blog/optimize-fid/index.md
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/en/metrics/cls/index.md
  src/site/content/en/metrics/fid/index.md
  src/site/content/en/metrics/lcp/index.md
  src/styles/globals/gorko/_config.scss
Labels: cla: yes

#5204 [learn-css] [courses] Table of Contents Scroll Bug
  src/styles/components/_course-toc.scss
Labels: bug, cla: yes

#5176 Updated browser overview table
  src/site/content/en/blog/referrer-best-practices/index.md
Labels: cla: yes

#5193 Fix and harmonize links to caniuse for browser-fs-access
  src/site/content/en/blog/browser-fs-access/index.md
Labels: cla: yes

#5181 [Aync Clipboard article] Fix borked link
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#5143 Add SXGs to /optimize-lcp
  src/site/content/en/blog/optimize-lcp/index.md
Labels: cla: yes

#5208 Fix progress bar cls
  src/lib/components/ProgressBar/_styles.scss
Labels: cla: yes

#5206 Remove outdated information about LCP removed elements
  src/site/content/en/metrics/lcp/index.md
Labels: cla: yes

#5201 Add grid lesson
  src/site/content/en/learn/css/grid/grid.assess.yml
  src/site/content/en/learn/css/grid/index.md
Labels: cla: yes

#5192 Update author data
  src/site/_data/authorsData.json
Labels: cla: yes

#5179 Adds pseudo-elements lesson
  src/site/content/en/learn/css/pseudo-elements/index.md
Labels: cla: yes

#5177 Adding Spacing lesson
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/spacing/index.md
Labels: cla: yes
