Repository GoogleChrome/web.dev, pull requests merged in 2021-05, with the labels that each got.

#5221 Adds spacing assessments
  src/site/content/en/learn/css/spacing/conclusion.assess.yml
  src/site/content/en/learn/css/spacing/index.md
  src/site/content/en/learn/css/spacing/margin-collapsing.assess.yml
Labels: cla: yes

#5211 Fix drawer overscroll and add link states.
  src/lib/components/CourseLinks/index.js
  src/lib/pages/course.js
  src/site/_includes/partials/navigation-drawer-course.njk
  src/styles/components/_drawer-course.scss
  src/styles/components/_web-navigation-drawer.scss
Labels: cla: yes

#5225 Adds learn css shadows
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/shadows/index.md
Labels: cla: yes

#5226 Adds learn css z-index
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/z-index/index.md
Labels: cla: yes

#5227 Adds learn css gradients
  src/site/_data/courses/css/toc.yml
  src/site/content/en/learn/css/gradients/index.md
Labels: cla: yes

#5209 Update to reflect current bfcache in CrUX state
  src/site/content/en/blog/bfcache/index.md
Labels: cla: yes

#5200 refactor(images): remove old cdn and image compression stuff
  .eleventy.js
  gulp-tasks/copy-content-assets.js
  gulp-tasks/copy-global-images.js
  gulp-tasks/utils.js
  gulpfile.js
  package-lock.json
  package.json
  src/images/android-chrome-192x192.png
  src/images/android-chrome-512x512.png
  src/images/apple-touch-icon.png
  src/images/favicon-16x16.png
  src/images/favicon-32x32.png
  src/images/podcasts/css-podcast.jpg
  src/images/podcasts/designer-vs-developer.jpg
  src/images/podcasts/state-of-the-web.jpg
  src/site/_data/site.js
  src/site/_includes/components/Meta.js
  src/site/_transforms/responsive-images/helpers.js
  src/site/_transforms/responsive-images/index.js
  src/site/_utils/get-image-path.js
  src/site/_utils/get-srcset-range.js
  src/site/content/robots.njk
  src/site/content/robots.txt
  test/unit/src/site/_transforms/index.js
  test/unit/src/site/_transforms/responsive-images/helpers.js
  test/unit/src/site/_transforms/responsive-images/index.js
  test/unit/src/site/index.js
Labels: cla: yes

#5236 add insights banner
  src/site/_data/site.js
Labels: cla: yes

#5217 Adds learn css focus
  src/site/content/en/learn/css/focus/index.md
Labels: cla: yes

#5092 Add MediaStreamTrack insertable media processing article
  src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
Labels: cla: yes

#5216 Adds the borders lesson
  src/site/content/en/learn/css/borders/index.md
Labels: cla: yes

#5248 [bugfix] Frontmatter RE:4834
  src/site/content/en/learn/css/borders/index.md
Labels: cla: yes

#5251 Make codepens editable
  src/site/_includes/components/Codepen.js
Labels: cla: yes

#5252 Fix flaky percy test
  tools/percy/.percy.conf.yml
Labels: cla: yes

#5120 Add badge for new content in courses
  .eleventy.js
  src/lib/components/CourseLinks/index.js
  src/lib/pages/course.js
  src/site/_data/i18n/common.yml
  src/site/_filters/is-new-content.js
  src/site/_includes/base.njk
  src/site/_includes/course.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/styles/components/_drawer-course.scss
  test/unit/src/site/_filters/index.js
  test/unit/src/site/_filters/is-new-content.js
Labels: cla: yes

#5250 Add OT frontmatter
  src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
Labels: cla: yes

#5238 Adds Learn CSS Animation
  src/site/content/en/learn/css/animations/index.md
Labels: cla: yes

#5249 Edited both conversion measurement articles
  src/site/content/en/blog/conversion-measurement/index.md
  src/site/content/en/blog/using-conversion-measurement/index.md
Labels: cla: yes

#5246 Use full locale to allow for regional language variations
  src/site/_filters/i18n.js
Labels: cla: yes

#5239 Adds Learn CSS Filters
  src/site/content/en/learn/css/filters/index.md
Labels: cla: yes

#5240 Adds learn css blend modes
  src/site/content/en/learn/css/blend-modes/index.md
Labels: cla: yes

#5243 Learn CSS intro content
  src/site/content/en/learn/css/index.md
Labels: cla: yes

#5242 Adds learn css functions
  src/site/content/en/learn/css/functions/index.md
Labels: cla: yes

#5244 Learn CSS outro content
  src/site/content/en/learn/css/conclusion/index.md
Labels: cla: yes

#5262 Revert "[ES] Translation - Web Vitals (#5106)"
  src/site/content/es/vitals/index.md
Labels: cla: yes

#5263 Move es_ES to es/ and readd vitals ES translation
  src/lib/utils/language.js
  src/site/content/es/404.md
  src/site/content/es/es.11tydata.js
  src/site/content/es/feed.njk
  src/site/content/es/index.11tydata.js
  src/site/content/es/index.md
  src/site/content/es/lang.js
  src/site/content/es/offline.md
  src/site/content/es/vitals/index.md
  src/site/content/es_ES/lang.js
Labels: cla: yes

#5257 Add ARIA labels to svg
  package-lock.json
  package.json
  src/site/_includes/macros/icon.njk
  src/site/_includes/partials/course-pagination.njk
  src/site/_includes/partials/header-course.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/_includes/partials/toc-inner.njk
Labels: cla: yes

#5265 hide course tags and authors
  src/site/_includes/components/Meta.js
  src/site/content/en/learn/css/css.11tydata.js
Labels: cla: yes

#5266 Only exclude course content from authors and tags pages.
  src/site/_collections/authors.js
  src/site/_collections/tags.js
  src/site/content/en/learn/css/css.11tydata.js
  types/eleventy/collection-item.d.ts
Labels: cla: yes

#5264 Remove paths from pretranslation service
  .gitlocalize.yml
Labels: cla: yes

#5261 Adds borders assessments
  src/site/content/en/learn/css/borders/borders.assess.yml
  src/site/content/en/learn/css/borders/index.md
Labels: cla: yes

#5220 Adds layout assessments
  src/site/content/en/learn/css/layout/index.md
  src/site/content/en/learn/css/layout/layout.assess.yml
Labels: cla: yes

#5273 fix(algolia): trim text of algolia content
  algolia.js
  package-lock.json
  package.json
Labels: cla: yes

#5276 fix(vitals): fix broken images in spanish vitals page
  src/site/content/es/vitals/index.md
Labels: cla: yes

#5269 Fix course description
  src/styles/pages/_course.scss
Labels: cla: yes

#5267 Add logo to courses
  src/site/_includes/partials/course-app-bar.njk
  src/styles/components/_app-bar.scss
Labels: cla: yes

#5277 chore(image): update all images to use `decoding="async"`
  package-lock.json
  package.json
  src/site/_includes/components/Hero.js
Labels: cla: yes

#5241 Adds podcasts, descriptions, and tidies things up
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/color/index.md
  src/site/content/en/learn/css/flexbox/index.md
  src/site/content/en/learn/css/gradients/index.md
  src/site/content/en/learn/css/grid/index.md
  src/site/content/en/learn/css/inheritance/index.md
  src/site/content/en/learn/css/layout/index.md
  src/site/content/en/learn/css/logical-properties/index.md
  src/site/content/en/learn/css/pseudo-classes/index.md
  src/site/content/en/learn/css/pseudo-elements/index.md
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/learn/css/shadows/index.md
  src/site/content/en/learn/css/sizing/index.md
  src/site/content/en/learn/css/spacing/index.md
  src/site/content/en/learn/css/specificity/index.md
  src/site/content/en/learn/css/the-cascade/index.md
  src/site/content/en/learn/css/z-index/index.md
Labels: cla: yes

#5280 Adds z-index assessments
  src/site/content/en/learn/css/z-index/index.md
  src/site/content/en/learn/css/z-index/z-index.assess.yml
Labels: cla: yes

#5279 Adds focus assessments
  src/site/content/en/learn/css/focus/focus.assess.yml
  src/site/content/en/learn/css/focus/index.md
Labels: cla: yes

#5275 Adds shadows assessments
  src/site/content/en/learn/css/shadows/index.md
  src/site/content/en/learn/css/shadows/shadows.assess.yml
Labels: cla: yes

#5219 Adds sizing assessment
  src/site/content/en/learn/css/sizing/index.md
  src/site/content/en/learn/css/sizing/sizing.assess.yml
Labels: cla: yes

#5232 Adds pseudo-element assessment
  src/site/content/en/learn/css/pseudo-elements/index.md
  src/site/content/en/learn/css/pseudo-elements/pseudo-elements.assess.yml
Labels: cla: yes

#5278 Courses author bubble stack
  src/site/_data/authorsData.json
  src/site/_data/courses/css/toc.yml
  src/site/_includes/partials/author-stack.njk
  src/site/content/en/learn/css/conclusion/index.md
  src/styles/globals/gorko/_config.scss
  src/styles/utilities/_all.scss
  src/styles/utilities/_list-separator.scss
Labels: cla: yes

#5282 [Window Controls Overlay article] Link to Edge’s docs
  src/site/content/en/blog/window-controls-overlay/index.md
Labels: cla: yes

#5281 Add background color and fix toc without contents.
  src/site/_data/i18n/toc.yml
  src/site/_includes/partials/toc-inner.njk
  src/site/_includes/partials/toc-side.njk
  src/styles/components/_course-toc.scss
Labels: cla: yes

#5291 Adds filters assessment
  src/site/content/en/learn/css/filters/filters.assess.yml
  src/site/content/en/learn/css/filters/index.md
Labels: cla: yes

#5293 Adds blend mode assessments
  src/site/content/en/learn/css/blend-modes/blend-modes.assess.yml
  src/site/content/en/learn/css/blend-modes/index.md
Labels: cla: yes

#5292 Remove search from courses
  src/site/_includes/partials/navigation-drawer-course.njk
Labels: cla: yes

#5286 [learn-css] Demo visualization adjustments
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/color/index.md
  src/site/content/en/learn/css/flexbox/index.md
  src/site/content/en/learn/css/grid/index.md
  src/site/content/en/learn/css/inheritance/index.md
  src/site/content/en/learn/css/layout/index.md
  src/site/content/en/learn/css/selectors/index.md
  src/site/content/en/learn/css/sizing/index.md
  src/site/content/en/learn/css/specificity/index.md
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#5294 add stuck state to course-app-bar
  src/site/_includes/course.njk
  src/styles/components/_app-bar.scss
Labels: cla: yes

#5296 Fix app bar squish and pagination colors.
  src/styles/components/_app-bar.scss
  src/styles/components/_course-pagination.scss
  src/styles/pages/_course.scss
Labels: cla: yes

#5233 Adds psuedo-classes assessments
  src/site/content/en/learn/css/pseudo-classes/index.md
  src/site/content/en/learn/css/pseudo-classes/pseudo-classes.assess.yml
Labels: cla: yes

#5290 Adds animations assessments
  src/site/content/en/learn/css/animations/animations.assess.yml
  src/site/content/en/learn/css/animations/index.md
Labels: cla: yes

#5288 Adds gradient assessments
  src/site/content/en/learn/css/gradients/gradients.assess.yml
  src/site/content/en/learn/css/gradients/index.md
Labels: cla: yes

#5270 Update SAB related articles on restriction delay
  src/site/content/en/blog/coop-coep/index.md
  src/site/content/en/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#5304 soft launch learn css
  redirects.yaml
  src/site/_data/courses/css/meta.yml
  src/site/_data/site.js
  src/site/_includes/partials/course-cards.njk
  src/site/content/en/learn/css/css.11tydata.js
Labels: cla: yes

#5284 Disable translation banner
  src/site/content/es/es.11tydata.js
Labels: cla: yes

#5311 feat(redirect): add vitals redirect
  firebase-config.js
  redirects.yaml
Labels: cla: yes

#5313 Don't apply 'new' badge to course launch content.
  src/site/_data/courses/css/meta.yml
  src/site/_includes/partials/navigation-drawer-course.njk
Labels: cla: yes

#5191 Add URL Protocol Handler article
  src/site/content/en/blog/url-protocol-handler/index.md
Labels: DO NOT MERGE, cla: yes

#5228 [Text Fragment article] Add info about link generation and analytics, remove OT info
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#5299 [Async Clipboard article] Document Safari's special way
  src/site/content/en/blog/async-clipboard/index.md
Labels: cla: yes

#5298 Incorporate cross-origin iframe support in WebOTP
  src/site/content/en/blog/web-otp/index.md
Labels: cla: yes

#5229 Decouple search and search results
  src/lib/components/Search/_styles.scss
  src/lib/components/Search/index.js
  src/lib/components/SearchResults/_styles.scss
  src/lib/components/SearchResults/index.js
  src/lib/components/base.js
  src/site/_includes/partials/header-default.njk
  src/site/_includes/partials/navigation-drawer-course.njk
  src/site/content/en/learn/css/css.11tydata.js
  src/styles/components/_drawer-course.scss
  src/styles/components/_header-default.scss
  types/lib/components/SearchResults.d.ts
Labels: cla: yes

#5139 Add Orange case study
  src/site/_data/authorsData.json
  src/site/content/en/blog/orange/index.md
Labels: cla: yes

#5324 fix(authorsData): set some descriptions from `description` to `descriptions`
  src/site/_data/authorsData.json
Labels: cla: yes

#5316 Disable drawer touch events
  src/lib/components/NavigationDrawer/index.js
Labels: DO NOT MERGE, cla: yes

#5326 refactor(firebase): build site in `staging` mode
  .github/workflows/firebase-hosting-pull-request.yml
Labels: cla: yes

#5303 Enforce CSP
  firebase-config.js
Labels: cla: yes

#5237 Adds optimizing CWV with Lighthouse (fixes #5062)
  src/site/content/en/blog/optimize-vitals-lighthouse/index.md
Labels: cla: yes

#5271 Add manufacturer data filter to bluetooth article
  src/site/content/en/blog/bluetooth/index.md
Labels: cla: yes

#5300 Add Excalibur article
  src/site/content/en/blog/excalidraw-and-fugu/index.md
Labels: cla: yes

#5329 Some learn css fixes.
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/index.md
Labels: cla: yes

#5310 [new post] GUI Challenges media scroller
  src/site/content/en/blog/building-a-media-scroller-component/index.md
Labels: cla: yes

#5332 Boost cookie banner z-index
  src/lib/components/SnackbarContainer/_styles.scss
Labels: cla: yes

#5333 Fix pre tag overflow on course pages.
  src/styles/pages/_course.scss
Labels: cla: yes

#5336 Make course header sticky. Partial fix for focus bug.
  src/lib/components/Header/index.js
  src/styles/components/_app-bar.scss
  src/styles/components/_header-course.scss
Labels: cla: yes

#5338 fix(meta): rasterize svgs for images in `<head>`
  src/site/_data/courses/css/meta.yml
  src/site/_includes/components/Meta.js
Labels: cla: yes

#5302 WebTransport OT interface updates
  src/site/content/en/blog/webtransport/index.md
Labels: cla: yes

#5346 Fix broken link.
  src/site/content/en/learn/css/selectors/index.md
Labels: cla: yes

#5341 Fix typo
  src/site/content/en/learn/css/box-model/index.md
Labels: cla: yes

#5348 grammar
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#5349 lch() link fix
  src/site/content/en/learn/css/color/index.md
Labels: cla: yes

#5354 Updated title
  src/site/content/en/blog/floc/index.md
Labels: cla: yes

#5361 Update /secure
  src/site/_data/paths/secure.json
Labels: cla: yes

#5343 ES modules in service workers post
  src/site/content/en/blog/es-modules-in-sw/index.md
Labels: cla: yes

#5360 [Text Fragments article] Add spec draft link
  src/site/content/en/blog/text-fragments/index.md
Labels: cla: yes

#5301 Add Handwriting Recognition article
  src/site/_data/authorsData.json
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/handwriting-recognition/index.md
Labels: DO NOT MERGE, cla: yes

#5351 Add imgix query param to improve the webperf
  src/site/_includes/components/Img.js
Labels: cla: yes

#5370 refactor(collections): clean up logic for authors and tags
  src/site/_collections/authors.js
  src/site/_collections/tags.js
  types/site/_collections/authors.d.ts
  types/site/_collections/tags.d.ts
Labels: cla: yes

#5367 doc(drag-and-drop): fixed indentation
  src/site/content/en/blog/drag-and-drop/index.md
Labels: cla: yes

#5307 Remove CLS from the sign in element in /measure
  src/site/content/en/measure/index.njk
  src/styles/components/_page-header.scss
  src/styles/pages/_measure.scss
Labels: cla: yes

#5377 Add io banner.
  src/site/_data/site.js
  src/site/_includes/homepage.njk
  src/site/content/en/index.md
  src/site/content/es/index.md
  src/site/content/pl/index.md
Labels: cla: yes

#5178 Initial commit of Security Headers Cheat Sheet
  redirects.yaml
  src/site/_data/authorsData.json
  src/site/content/en/blog/strict-csp/index.md
  src/site/content/en/secure/security-headers/index.md
Labels: cla: yes

#5379 Add to /secure, add maudn as an author
  src/site/_data/paths/secure.json
  src/site/content/en/secure/security-headers/index.md
Labels: cla: yes

#5380 Add Measure Web Vitals with GA4 and BigQuery post
  src/site/_data/authorsData.json
  src/site/content/en/blog/vitals-ga4/index.md
Labels: cla: yes

#5365 Add Browser Flags article
  src/site/content/en/blog/browser-flags/index.md
Labels: cla: yes

#5393 Remove unnecessary h1
  src/site/content/en/learn/css/layout/index.md
Labels: cla: yes

#5371 Business impact article draft
  src/site/_data/authorsData.json
  src/site/content/en/blog/vitals-business-impact/index.md
Labels: cla: yes

#5330 Add Declarative Link Capturing article
  src/site/content/en/blog/declarative-link-capturing/index.md
Labels: cla: yes

#5400 Migrate to User-Agent Client Hints blog post
  src/site/content/en/blog/migrate-to-ua-ch/index.md
Labels: blog, cla: yes, privacy/security

#5378 [Post] The New Responsive
  src/site/content/en/blog/new-responsive/index.md
Labels: cla: yes

#5404 fix date format on new responsive article
  src/site/content/en/blog/new-responsive/index.md
Labels: cla: yes

#5405 Add missing link
  src/site/content/en/blog/vitals-ga4/index.md
Labels: cla: yes

#5398 Fix incorrect pagination value for next page
  src/site/_includes/partials/course-pagination.njk
Labels: cla: yes

#5406 bump app-bar z-index a bit
  src/styles/components/_app-bar.scss
Labels: cla: yes

#5407 Url typo and redirect.
  redirects.yaml
  src/site/content/en/lighthouse-seo/is-crawlable/index.md
Labels: cla: yes

#5409 Improve passive event listener audit title
  src/site/content/en/lighthouse-best-practices/uses-passive-event-listeners/index.md
Labels: cla: yes

#5410 Add new post to /learn-web-vitals
  src/site/_data/paths/learn-web-vitals.json
  src/site/content/en/blog/vitals-business-impact/index.md
Labels: cla: yes

#5416 "
  src/site/_data/i18n/paths/mini_apps.yml
Labels: cla: yes

#5417 Improve learn css course tracking.
  src/lib/components/CourseLinks/index.js
  src/site/_data/site.js
Labels: cla: yes

#5319 feat(cache-control): give HTML files short life on client, but still use stale content for 10 minutes
  firebase.incl.json
Labels: cla: yes

#5352 Move web-copy-code styles to load synchronously to avoid FOUC
  src/lib/components/CopyCode/_styles.scss
  src/lib/components/CopyCode/index.js
  src/styles/components/_all.scss
  src/styles/components/_web-copy-code.scss
Labels: cla: yes

#5383 Update Lighthouse aspect ratio description
  src/site/content/en/lighthouse-best-practices/image-aspect-ratio/index.md
Labels: cla: yes

#5289 <video class="lazy" ... >
  src/site/content/en/fast/lazy-loading-video/index.md
Labels: cla: yes

#5422 fix to sizing units
  src/site/content/en/learn/css/sizing/index.md
Labels: cla: yes

#5426 Use new content form.
  .github/ISSUE_TEMPLATE/propose-new-content.md
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes

#5428 Fix link to CSS Podcast for The Cascade article.
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes

#5433 Fix bug in pseudo-classes markdown.
  src/site/content/en/learn/css/pseudo-classes/index.md
Labels: cla: yes

#5432 fix minor typos in Check your understanding sections
  src/site/content/en/learn/css/flexbox/conclusion.assess.yml
  src/site/content/en/learn/css/functions/functions.assess.yml
  src/site/content/en/learn/css/spacing/conclusion.assess.yml
Labels: cla: yes

#5435 Fixed Typo
  src/site/content/en/lighthouse-accessibility/document-title/index.md
Labels: cla: yes

#5392 Make capitalization of 'web app manifest' match the handbook.
  src/site/content/en/blog/deprecating-excalidraw-electron/index.md
  src/site/content/en/blog/display-override/index.md
  src/site/content/en/blog/excalidraw-and-fugu/index.md
  src/site/content/en/blog/file-handling/index.md
  src/site/content/en/blog/load-faster-like-proxx/index.md
  src/site/content/en/blog/mainline-mensware/index.md
  src/site/content/en/blog/maskable-icon/index.md
  src/site/content/en/blog/tabbed-application-mode/index.md
  src/site/content/en/blog/url-protocol-handler/index.md
  src/site/content/en/blog/window-controls-overlay/index.md
  src/site/content/en/progressive-web-apps/customize-install/index.md
  src/site/content/en/progressive-web-apps/install-criteria/index.md
  src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
  src/site/content/en/react/add-manifest-react/index.md
Labels: cla: yes

#5362 Add a link to Quirks Mode spec
  src/site/content/en/lighthouse-best-practices/doctype/index.md
Labels: cla: yes

#5420 Mention and add reference to attribute selectors
  src/site/content/en/learn/css/specificity/index.md
Labels: cla: yes

#5438 A few small fixes
  src/site/content/en/learn/css/box-model/index.md
  src/site/content/en/learn/css/flexbox/conclusion.assess.yml
  src/site/content/en/learn/css/selectors/index.md
Labels: cla: yes

#5441 Update banner to use WebDev Insights
  src/site/_data/site.js
Labels: cla: yes

#5414 Bug/scroll padding top header
  src/lib/components/Header/index.js
  src/styles/generic/_shared.scss
Labels: cla: yes

#5440 Update authorsData.json
  src/site/_data/authorsData.json
Labels: cla: yes

#5449 Replace `chrome://` with `about://`
  README.md
  src/site/content/en/blog/a11y-tips-for-web-dev/index.md
  src/site/content/en/blog/app-shortcuts/index.md
  src/site/content/en/blog/appcache-removal/index.md
  src/site/content/en/blog/bluetooth/index.md
  src/site/content/en/blog/building-a-media-scroller-component/index.md
  src/site/content/en/blog/change-password-url/index.md
  src/site/content/en/blog/content-indexing-api/index.md
  src/site/content/en/blog/cors-rfc1918-feedback/index.md
  src/site/content/en/blog/declarative-shadow-dom/index.md
  src/site/content/en/blog/fetch-upload-streaming/index.md
  src/site/content/en/blog/file-handling/index.md
  src/site/content/en/blog/gamepad/index.md
  src/site/content/en/blog/hands-on-portals/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/how-to-distribute-signed-http-exchanges/index.md
  src/site/content/en/blog/idle-detection/index.md
  src/site/content/en/blog/local-fonts/index.md
  src/site/content/en/blog/mediastreamtrack-insertable-media-processing/index.md
  src/site/content/en/blog/monitor-total-page-memory-usage/index.md
  src/site/content/en/blog/multi-screen-window-placement/index.md
  src/site/content/en/blog/new-responsive/index.md
  src/site/content/en/blog/notification-triggers/index.md
  src/site/content/en/blog/periodic-background-sync/index.md
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
  src/site/content/en/blog/samesite-cookies-explained/index.md
  src/site/content/en/blog/schemeful-samesite/index.md
  src/site/content/en/blog/serial/index.md
  src/site/content/en/blog/shape-detection/index.md
  src/site/content/en/blog/speed-at-scale/index.md
  src/site/content/en/blog/url-protocol-handler/index.md
  src/site/content/en/blog/usb/index.md
  src/site/content/en/blog/user-agent-client-hints/index.md
  src/site/content/en/blog/using-conversion-measurement/index.md
  src/site/content/en/blog/web-bundles/index.md
  src/site/content/en/blog/window-controls-overlay/index.md
  src/site/content/en/fast/browser-level-image-lazy-loading/index.md
  src/site/content/en/mini-apps/mini-app-about/index.md
  src/site/content/en/mini-apps/mini-app-devtools/index.md
  src/site/content/en/progressive-web-apps/add-manifest/index.md
  src/site/content/en/progressive-web-apps/manifest-updates/index.md
Labels: cla: yes

#5451 fix(angular): fix broken videos, fixes #5442
  src/site/content/en/angular/route-preloading-in-angular/index.md
Labels: cla: yes

#5454 CLS update
  src/site/content/en/fast/debug-layout-shifts/index.md
  src/site/content/en/metrics/cls/index.md
Labels: cla: yes

#5453 Fixes #5450 - Update name of #reduce-user-agent flag
  src/site/content/en/blog/user-agent-client-hints/index.md
Labels: cla: yes

#5455 dix(deploy): add args to `cancelWorkflowRun`
  .github/workflows/firebase-hosting-cron.yml
  version-check.js
Labels: cla: yes

#5447 Update explanation to match css example.
  src/site/content/en/learn/css/sizing/index.md
Labels: cla: yes

#5456 fix(deploy): reorganize the steps
  .github/workflows/firebase-hosting-cron.yml
  gulp-tasks/write-version.js
Labels: cla: yes

#5439 Fix JavaScript code sample for userAgentData.brands
  src/site/content/en/blog/migrate-to-ua-ch/index.md
Labels: cla: yes

#5234 Declarative Shadow DOM: FOUC avoidance update
  src/site/content/en/blog/declarative-shadow-dom/index.md
Labels: cla: yes

#5461 Handbook updates
  src/site/_includes/partials/topic.njk
  src/site/content/en/handbook/author-profile/index.md
  src/site/content/en/handbook/content-checklist/index.md
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/quick-start/index.md
Labels: cla: yes

#5463 [The New Responsive article] Add links to `/prefers-color-scheme/` and `/color-scheme/`
  src/site/content/en/blog/new-responsive/index.md
Labels: cla: yes

#5469 refactor(version-check): skip steps instead of stopping build
  .github/workflows/firebase-hosting-cron.yml
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#5470 fix(deploy): ensure output is outputted
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#5471 Definition list handbook
  src/site/content/en/handbook/web-dev-components/index.md
Labels: cla: yes

#5390 feat(PagesIndexCollection): refactor algolia collection to pages index collection
  .eleventy.js
  algolia.js
  src/site/_collections/pages.js
  src/site/content/algolia.njk
  src/site/content/pages.njk
  test/integration/build-test.js
  types/site/_collections/pages.d.ts
  types/utils/algolia.d.ts
Labels: cla: yes

#5479 [Offline UX Design Guidelines article] Remove capabilities tag
  src/site/content/en/reliable/offline-ux-design-guidelines/index.md
Labels: cla: yes

#5481 [Display Override article] Add missing tag
  src/site/content/en/blog/display-override/index.md
Labels: cla: yes

#5480 [File Handling article] Add capabilities tag
  src/site/content/en/blog/file-handling/index.md
Labels: cla: yes

#5487 Typo fixes
  src/site/content/en/learn/css/selectors/index.md
Labels: cla: yes

#5492 Replace broken Link
  src/site/content/en/lighthouse-performance/render-blocking-resources/index.md
Labels: cla: yes

#5467 fix(reliable): fix image sizes of some posts
  src/site/content/en/reliable/broadcast-updates-guide/index.md
  src/site/content/en/reliable/imperative-caching-guide/index.md
  src/site/content/en/reliable/two-way-communication-guide/index.md
  src/site/content/en/reliable/workers-overview/index.md
Labels: cla: yes
