Repository GoogleChrome/web.dev, pull requests merged in 2022-01, with the labels that each got.

#6952 test(algolia): add tests for algolia, fixes #2611
  .eslintrc.js
  algolia.js
  package-lock.json
  package.json
  run-algolia.js
  test/unit/algolia/index.js
  test/unit/index.js
  test/unit/src/site/_filters/algolia-item.js
  test/unit/src/site/_filters/index.js
Labels: cla: yes

#6248 Update file handling article.
  src/site/content/en/blog/file-handling/index.md
Labels: DO NOT MERGE, cla: yes

#7128 fix: fix typo
  src/site/content/en/learn/pwa/assets-and-data/index.md
Labels: $-presubmit

#7124 fix: fix typo
  src/site/content/en/learn/forms/form-element/index.md
Labels: $-presubmit

#7125 Exempts the content label from being processed by stalebot.
  .github/stale.yml
Labels: P2, content, writing, eng, $-presubmit

#7120 Update index.md of web.dev/vitals-business-impact
  src/site/content/en/blog/vitals-business-impact/index.md
Labels: $-presubmit

#7135 Updates TTFB links to the canonical guidance instead of the Lighthouse audit page.
  src/site/content/en/blog/load-faster-like-proxx/index.md
  src/site/content/en/blog/ndtv/index.md
  src/site/content/en/blog/optimize-lcp/index.md
  src/site/content/es/blog/optimize-lcp/index.md
  src/site/content/ja/blog/optimize-lcp/index.md
  src/site/content/ko/blog/optimize-lcp/index.md
  src/site/content/pt/blog/optimize-lcp/index.md
  src/site/content/ru/blog/optimize-lcp/index.md
  src/site/content/zh/blog/optimize-lcp/index.md
Labels: content, $-presubmit

#6946 Russian translation for the "Code splitting with React.lazy and Suspense", "Avoid multiple page redirects", "Remove unused code", "Streams—The definitive guide", "Interact with NFC devices on Chrome for Android", "Color and contrast accessibility" articles.
  src/site/content/ru/accessible/color-and-contrast-accessibility/index.md
  src/site/content/ru/blog/nfc/index.md
  src/site/content/ru/blog/streams/index.md
  src/site/content/ru/fast/remove-unused-code/index.md
  src/site/content/ru/lighthouse-performance/redirects/index.md
  src/site/content/ru/react/code-splitting-suspense/index.md
Labels: cla: yes

#7166 Fix broken link
  src/site/content/en/blog/building-a-toast-component/index.md
Labels: $-presubmit

#7154 Update CDN cache config
  firebase.incl.json
  src/site/_data/site.js
Labels: SAFE TO MERGE

#7156 Adds vitals tools workflow doc
  redirects.yaml
  src/site/content/en/blog/vitals-tools-2020/index.md
  src/site/content/en/blog/vitals-tools-workflow/index.md
  src/site/content/en/blog/vitals-tools/index.md
Labels: content, performance, content update, vitals, $-presubmit

#7190 Handbook link updates
  src/site/content/en/handbook/web-dev-components/index.md
Labels: content update

#7155 Conditionally load sign-in to enable bfcache
  src/lib/actions.js
  src/lib/analytics.js
  src/lib/components/ProfileSwitcherContainer/index.js
  src/lib/fb.js
  src/lib/pages/measure.js
  src/site/_data/site.js
  src/site/_includes/partials/analytics.njk
  types/modules/webdev_analytics/index.d.ts
Labels: DO NOT MERGE

#7185 add flex-direction to web-assessment__content
  src/lib/components/Assessment/_styles.scss
Labels: $-presubmit

#6627 Update wrong mention of TBT in Max FID article
  src/site/content/en/lighthouse-performance/lighthouse-max-potential-fid/index.md
Labels: cla: yes, content update, $-presubmit

#7212 Fix typo
  src/site/content/en/learn/design/micro-layouts/index.md
Labels: $-presubmit

#7224 Update index.md
  src/site/content/en/fast/serve-images-webp/index.md
Labels: $-presubmit

#7222 Update index.md of use-imagemin-to-compress-images docs to refactor typo errors
  src/site/content/en/fast/use-imagemin-to-compress-images/index.md
Labels: $-presubmit

#7198 Update index.md of cookie-notice-best-practices for typo error
  src/site/content/en/fast/cookie-notice-best-practices/index.md
Labels: $-presubmit

#7196 Update index.md of tag-best-practices for grammatical error
  src/site/content/en/blog/tag-best-practices/index.md
Labels: $-presubmit

#7204 Little reword to the "fun fact" in USB article
  src/site/content/en/blog/porting-libusb-to-webusb/index.md
Labels: content update

#7216 Update index.md for adding copy-to-clipboard functionality on a command
  src/site/content/en/fast/using-lighthouse-bot-to-set-a-performance-budget/index.md
Labels: $-presubmit

#6928 New snackbar styles
  src/lib/components/Snackbar/index.js
  src/lib/components/SnackbarContainer/index.js
  src/scss/mixins/_button-base-styles.scss
  src/scss/next.scss
  src/scss/web-components/_web-snackbar.scss
Labels: DO NOT MERGE, cla: yes

#7251 Fix internal page link to be root-relative
  src/site/content/en/learn/design/ui-patterns/index.md
Labels: $-presubmit
