Repository GoogleChrome/web.dev, pull requests merged in 2022-05, with the labels that each got.

#7828 Handbook: update copy around captions
  src/site/content/en/handbook/use-media/index.md
Labels: content update

#7832 Add Google ACME cert renewal specific directions.
  src/site/content/en/fast/signed-exchanges-webpackager/index.md
Labels: content update, $-presubmit

#7847 Adds Interaction to Next Paint (INP) doc.
  src/site/_data/authorsData.json
  src/site/content/en/metrics/inp/index.md
Labels: P0, content, vitals, $-presubmit

#7854 Updates to SXG landing page to align with I/O talk narrative
  src/site/content/en/fast/signed-exchanges/index.md
Labels: content update, $-presubmit

#7869 INP doc updates.
  src/site/content/en/metrics/inp/index.md
  src/site/content/en/metrics/ttfb/index.md
Labels: P0, content update, vitals, $-presubmit

#7838 ContentMigrationBatch#SH5R1
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/appcache-beginner/index.md
  src/site/content/en/blog/async-deferred/index.md
  src/site/content/en/blog/audio-quick/index.md
  src/site/content/en/blog/audio-scheduling/index.md
  src/site/content/en/blog/canvas-hidipi/index.md
Labels: $-presubmit

#7831 [Case study] Identity and Yahoo! JAPAN
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/yahoo-japan-identity-case-study/index.md
Labels: content

#7880 Adds INP mentions to relevant docs.
  src/site/_data/paths/metrics.json
  src/site/content/en/blog/better-responsiveness-metric/index.md
  src/site/content/en/blog/optimizing-content-efficiency-javascript-startup-optimization/index.md
  src/site/content/en/blog/responsiveness/index.md
  src/site/content/en/blog/vitals-field-measurement-best-practices/index.md
  src/site/content/en/blog/vitals-spa-faq/index.md
  src/site/content/en/metrics/tbt/index.md
  src/site/content/en/metrics/tti/index.md
  src/site/content/en/metrics/user-centric-performance-metrics/index.md
Labels: P1, metrics, content update, vitals, $-presubmit

#7895 Minor INP doc tweaks.
  src/site/content/en/metrics/inp/index.md
Labels: P2, metrics, content update, vitals, $-presubmit

#7906 ContentMigrationBatch#SH5R5
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/100000stars/index.md
  src/site/content/en/blog/20things-pageflip/index.md
  src/site/content/en/blog/box-dnd-download/index.md
  src/site/content/en/blog/buildwithchrome/index.md
  src/site/content/en/blog/entanglement/index.md
Labels: $-presubmit

#7922 Adds preload scanner post.
  src/site/content/en/blog/preload-scanner/index.md
Labels: P2, content, $-presubmit

#7926 Fixes image sizes in preload scanner article.
  src/site/content/en/blog/preload-scanner/index.md
Labels: P2, content update, $-presubmit

#7872 Blog inp frameworks
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/inp-in-frameworks/index.md
Labels: DO NOT MERGE, $-presubmit

#7920 ContentMigrationBatch#SH5R8
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/html5-in-deviantart-muro/index.md
  src/site/content/en/blog/jamwithchrome-audio/index.md
  src/site/content/en/blog/jamwithchrome-interaction/index.md
  src/site/content/en/blog/mathboard/index.md
  src/site/content/en/blog/movikantirevo/index.md
Labels: $-presubmit

#7932 Fixes a typo in the browser preload scanner article.
  src/site/content/en/blog/preload-scanner/index.md
Labels: P2, content update, $-presubmit

#7921 ContentMigrationBatch#SH5R9
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/racer/index.md
  src/site/content/en/blog/roll-it/index.md
  src/site/content/en/blog/subsonic/index.md
  src/site/content/en/blog/sunlight-streamcongress/index.md
Labels: $-presubmit

#7839 [post] GUI Challenges - Buttons
  src/site/content/en/blog/building-a-button-component/index.md
Labels: P2, content

#7944 ContentMigrationBatch#SH5R12
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/antialiasing-101/index.md
  src/site/content/en/blog/getusermedia-intro/index.md
  src/site/content/en/blog/google-chrome-frame/index.md
  src/site/content/en/blog/indexeddb-uidatabinding/index.md
  src/site/content/en/blog/trip-meter/index.md
Labels: $-presubmit

#7938 Adds quick GOV.UK post.
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/gov-uk-drops-jquery/index.md
Labels: P2, content, $-presubmit

#7949 Blog post: Api fast beautiful web fonts
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/api-for-fast-beautiful-web-fonts/index.md
Labels: $-presubmit

#7806 Fix dead Handlebars link
  src/site/content/en/blog/csp/index.md
Labels: $-presubmit

#7884 Fix 404 Not Found
  src/site/content/en/blog/rendering-on-the-web/index.md
Labels: P2, content update, $-presubmit

#7954 ContentMigrationBatch#SH5R14
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/adobe/index.md
  src/site/content/en/blog/raphael/index.md
  src/site/content/en/blog/sandboxed-iframes/index.md
  src/site/content/en/blog/shapes-getting-started/index.md
  src/site/content/en/blog/speed-animated-gifs/index.md
  src/site/content/en/blog/transport-layer-security/index.md
Labels: $-presubmit

#7740 Use 11ty 1.0.1
  package-lock.json
  package.json
Labels: eng

#8000 ContentMigrationBatch#SH5R15
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/3d-css/index.md
  src/site/content/en/blog/doodles-gamepad/index.md
  src/site/content/en/blog/doodles-lem/index.md
  src/site/content/en/blog/eme-basics/index.md
  src/site/content/en/blog/es7-observe/index.md
Labels: $-presubmit

#8009 ContentMigrationBatch#SH5R19
  src/site/content/en/blog/speed-v8/index.md
  src/site/content/en/blog/streaming-screenshare/index.md
  src/site/content/en/blog/supercharging-your-gruntfile/index.md
  src/site/content/en/blog/svg-mobile-fundamentals/index.md
  src/site/content/en/blog/three-intro/index.md
Labels: $-presubmit

#7997 Adding closing <figcaption> tags
  src/site/content/en/blog/new-responsive/index.md
Labels: $-presubmit

#7998 Add SPC to payments collection
  src/site/_data/i18n/paths/payments.yml
  src/site/_data/paths/payments.json
Labels: content update

#8012 ContentMigrationBatch#SH5R20
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/synchronized-cross-device-testing/index.md
  src/site/content/en/blog/webaudio-fieldrunners/index.md
  src/site/content/en/blog/webaudio-games/index.md
  src/site/content/en/blog/webaudio-intro/index.md
  src/site/content/en/blog/webaudio-positional-audio/index.md
Labels: $-presubmit

#8007 [DO NOT MERGE] Add JA ver, Yahoo JAPAN case study
  src/site/_data/i18n/authors.yml
  src/site/content/ja/blog/yahoo-japan-identity-case-study/index.md
Labels: content update, l18n

#7455 Update the BrowserCompat component to filter against stable browsers
  src/site/_includes/components/BrowserCompat.js
Labels: eng, $-presubmit

#8031 Fix typo in learn/pwa/serving/index.md
  src/site/content/en/learn/pwa/serving/index.md
Labels: $-presubmit

#8033 Delete unwanted dot in learn/pwa/serving/index.md
  src/site/content/en/learn/pwa/serving/index.md
Labels: $-presubmit

#8022 ContentMigrationBatch#SH5R21
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/customelements/index.md
  src/site/content/en/blog/imports/index.md
  src/site/content/en/blog/shadowdom-201/index.md
  src/site/content/en/blog/shadowdom-301/index.md
  src/site/content/en/blog/shadowdom/index.md
Labels: $-presubmit

#8026 ContentMigrationBatch#SH5R23
  src/site/_data/authorsData.json
  src/site/content/en/blog/webgl-fundamentals/index.md
  src/site/content/en/blog/webgl-jsartoolkit-webrtc/index.md
  src/site/content/en/blog/webgl-million-letters/index.md
  src/site/content/en/blog/webgl-shaders/index.md
  src/site/content/en/blog/webgl-typed-arrays/index.md
Labels: $-presubmit
