Repository GoogleChrome/web.dev, pull requests merged in 2022-02, with the labels that each got.

#6861 Remove JS Self Profiling from translations in cross-origin isolation guide article
  src/site/content/es/secure/cross-origin-isolation-guide/index.md
  src/site/content/ja/secure/cross-origin-isolation-guide/index.md
  src/site/content/ko/secure/cross-origin-isolation-guide/index.md
  src/site/content/pt/secure/cross-origin-isolation-guide/index.md
  src/site/content/ru/secure/cross-origin-isolation-guide/index.md
  src/site/content/zh/secure/cross-origin-isolation-guide/index.md
Labels: cla: yes

#7165 Add alt attributes to image
  src/site/content/en/blog/discover-performance-opportunities-with-lighthouse/index.md
Labels: $-presubmit

#7164 Add alt attribute to main image
  src/site/content/en/blog/centering-in-css/index.md
Labels: $-presubmit

#7282 [A11y] Handbook updates for accessibility
  src/site/content/en/handbook/inclusion-and-accessibility/index.md
  src/site/content/en/handbook/markup-media/index.md
  src/site/content/en/handbook/quality/index.md
Labels: P3, writing, content update

#7303 Update Handbook word list
  src/site/content/en/handbook/word-list/index.md
Labels: content update

#7309 Update index.md to correct ortographic error
  src/site/content/es/learn/css/box-model/index.md
Labels: $-presubmit

#7306 Update reduce-webfont-size post for correcting grammatical error
  src/site/content/en/fast/reduce-webfont-size/index.md
Labels: $-presubmit

#7295 Update "Content delivery networks (CDNs)" post for contradicting statements
  src/site/content/en/fast/content-delivery-networks/index.md
Labels: $-presubmit

#7289 Fix off-main-thread Spanish translation
  src/site/content/es/blog/off-main-thread/index.md
Labels: $-presubmit

#7280 [Blog] Add post on HTTP cache and security
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/http-cache-security/index.md
Labels: content

#7315 add missing subhead
  src/site/content/en/blog/http-cache-security/index.md
Labels: content update

#6975 Re-enable dark mode
  package-lock.json
  src/images/courses/css/card.svg
  src/images/courses/forms/card.svg
  src/lib/components/LighthouseViewer/index.js
  src/scss/blocks/_hero.scss
  src/scss/blocks/_pill.scss
  src/scss/blocks/_site-footer.scss
  src/scss/next.scss
  src/scss/pages/_homepage.scss
  src/site/_data/design/themes.js
  src/site/_includes/partials/site-footer.njk
  src/site/_includes/partials/theme-script.njk
Labels: cla: yes

#7333 Updates the priority hints post re: origin trial info.
  src/site/content/en/fast/priority-hints/index.md
Labels: P2, content update, $-presubmit

#7338 Migrates the tree shaking guide from WebFundamentals.
  src/site/content/en/fast/reduce-javascript-payloads-with-tree-shaking/index.md
Labels: P2, content, $-presubmit

#7337 Uses a more conventional version of an idiom.
  src/site/content/en/blog/clipchamp/index.md
Labels: content update

#6255 Update ru grammar on LCP page
  src/site/content/ru/metrics/lcp/index.md
Labels: cla: yes

#7353 Improve fixing-website-speed-cross-functionally post for better readability
  src/site/content/en/fast/fixing-website-speed-cross-functionally/index.md
Labels: $-presubmit

#7270 Update index.md for better wordings
  src/site/content/en/fast/remove-unused-code/index.md
Labels: $-presubmit

#6682 [Learn Responsive Design] change `lang` to `hreflang` in the Internationalization article
  src/site/content/en/learn/design/internationalization/index.md
Labels: cla: yes, $-presubmit

#7129 fix: remove dead link
  src/site/content/en/lighthouse-best-practices/external-anchors-use-rel-noopener/index.md
Labels: $-presubmit

#6855 refactor: clamp expressions can take math functions
  src/site/content/en/learn/css/the-cascade/index.md
Labels: cla: yes, $-presubmit

#6965 Fix wrong Vitals-page to Russian translation
  src/site/content/ru/vitals/index.md
Labels: cla: yes, content, $-presubmit

#7377 pseudo class > :focus-visible typo
  src/site/content/en/blog/web-platform-01-2022/index.md
Labels: $-presubmit

#7299 Add additional html elements course material
  src/site/_data/paths/web-dev-basics-one.json
  src/site/content/en/web-dev-basics-one/additional-html-elements/index.md
Labels: content update

#5745 📝 [Learn CSS] Add Podcast link to conclusion
  src/site/content/en/learn/css/conclusion/index.md
Labels: cla: yes, $-presubmit

#7390 Fixes #7389 for a broken link reported by @MHBahrampour
  src/site/content/en/learn/design/responsive-images/index.md
Labels: P2, content update, $-presubmit

#6828 Change the word "dictionary" to "object"
  src/site/content/en/blog/isinputpending/index.md
Labels: cla: yes, $-presubmit

#7396 Fixes issue from closed PR #6764
  src/site/content/en/fast/priority-hints/index.md
Labels: P2, content update, $-presubmit

#7317 add link to /accessibile from /lighthouse-accessibility
  src/site/_data/i18n/paths/lighthouse_accessibility.yml
  src/site/_data/paths/lighthouse-accessibility.json
Labels: content update

#6810 Update fetch metadata article to state that Firefox supports FM
  src/site/content/en/blog/fetch-metadata/index.md
Labels: cla: yes, $-presubmit

#5230 Adjust order of expected/actual in how to file a bug
  src/site/content/en/blog/how-to-file-a-good-bug/index.md
Labels: cla: yes

#5968 Moving the constructable stylesheets post to web.dev
  src/site/content/en/blog/constructable-stylesheets/index.md
Labels: cla: yes, $-presubmit

#7397 New post for Next.js Script component
  src/site/_data/authorsData.json
  src/site/content/en/blog/script-component/index.md
Labels: P1, content, $-presubmit
