Repository GoogleChrome/web.dev, pull requests merged in 2022-06, with the labels that each got.

#8037 ContentMigrationBatch#SC1
  src/site/content/en/blog/aliexpress/index.md
  src/site/content/en/blog/asda-george/index.md
  src/site/content/en/blog/googleplus/index.md
  src/site/content/en/blog/nikkei/index.md
  src/site/content/en/blog/twitter/index.md
Labels: $-presubmit

#8038 ContentMigrationBatch#SC2
  src/site/content/en/blog/alibaba/index.md
  src/site/content/en/blog/bookmyshow/index.md
  src/site/content/en/blog/flipkart/index.md
  src/site/content/en/blog/land-lines/index.md
  src/site/content/en/blog/service-worker-perf/index.md
Labels: $-presubmit

#8039 ContentMigrationBatch#SC3
  src/site/content/en/blog/eleme/index.md
  src/site/content/en/blog/forbes/index.md
  src/site/content/en/blog/lancome/index.md
  src/site/content/en/blog/make-my-trip/index.md
  src/site/content/en/blog/suumo/index.md
Labels: $-presubmit

#8040 ContentMigrationBatch#SC4
  src/site/content/en/blog/dance-tonite/index.md
  src/site/content/en/blog/iowa2016/index.md
  src/site/content/en/blog/jumia/index.md
  src/site/content/en/blog/service-workers-iowa/index.md
  src/site/content/en/blog/weather-channel/index.md
Labels: $-presubmit

#8042 "WebPack" -> "webpack"
  src/site/content/en/learn/pwa/workbox/index.md
Labels: $-presubmit

#8035 Use correct attribute for image source
  src/site/content/en/blog/preload-responsive-images/index.md
Labels: content update, $-presubmit

#8049 ContentMigrationBatch#SC6
  src/site/content/en/blog/5miles/index.md
  src/site/content/en/blog/beyond-the-rack/index.md
  src/site/content/en/blog/extra/index.md
  src/site/content/en/blog/net-a-porter/index.md
  src/site/content/en/blog/svgomg/index.md
Labels: $-presubmit

#8047 ContentMigrationBatch#SC5
  src/site/content/en/blog/airhorner/index.md
  src/site/content/en/blog/infobae/index.md
  src/site/content/en/blog/little-alchemy/index.md
  src/site/content/en/blog/olx/index.md
  src/site/content/en/blog/within/index.md
Labels: $-presubmit

#8050 ContentMigrationBatch#SC7
  src/site/content/en/blog/babe/index.md
  src/site/content/en/blog/jumia2016/index.md
  src/site/content/en/blog/konga/index.md
  src/site/content/en/blog/santa/index.md
  src/site/content/en/blog/wapo/index.md
Labels: $-presubmit

#8036 ContentMigrationBatch#SH5R25
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/webrtc-basics/index.md
  src/site/content/en/blog/webrtc-datachannels/index.md
  src/site/content/en/blog/webrtc-infrastructure/index.md
  src/site/content/en/blog/websockets-basics/index.md
  src/site/content/en/blog/workers-basics/index.md
Labels: $-presubmit

#8066 Add missing space character in learn/pwa/installation-prompt/index.md
  src/site/content/en/learn/pwa/installation-prompt/index.md
Labels: $-presubmit

#8065 Remove unwanted period in learn/pwa/installation-prompt/index.md
  src/site/content/en/learn/pwa/installation-prompt/index.md
Labels: $-presubmit

#8059 Fix mistake in learn/pwa/installation/index.md
  src/site/content/en/learn/pwa/installation/index.md
Labels: $-presubmit

#8058 Add missing word in learn/pwa/installation/index.md
  src/site/content/en/learn/pwa/installation/index.md
Labels: $-presubmit

#8057 ContentMigrationBatch#SC11
  src/site/content/en/blog/guardian-smart-lock/index.md
  src/site/content/en/blog/hn-premii/index.md
  src/site/content/en/blog/hummingbirdlibrary/index.md
  src/site/content/en/blog/merry-pixmas/index.md
  src/site/content/en/blog/playcanvas/index.md
  src/site/content/en/blog/voot/index.md
Labels: $-presubmit

#8054 ContentMigrationBatch#SC10
  src/site/content/en/blog/adventuremachine/index.md
  src/site/content/en/blog/ali-express-smart-lock/index.md
  src/site/content/en/blog/art-sessions/index.md
  src/site/content/en/blog/chrome-dev-summit/index.md
  src/site/content/en/blog/housing/index.md
Labels: $-presubmit

#8088 Add missing space in /learn/pwa/tools-and-debug/index.md
  src/site/content/en/learn/pwa/tools-and-debug/index.md
Labels: $-presubmit

#8087 Fix mistake in /learn/pwa/tools-and-debug/index.md
  src/site/content/en/learn/pwa/tools-and-debug/index.md
Labels: $-presubmit

#8086 Remove unwanted space in /learn/pwa/tools-and-debug/index.md
  src/site/content/en/learn/pwa/tools-and-debug/index.md
Labels: $-presubmit

#8085 Fix typo in /learn/pwa/experimental/index.md
  src/site/content/en/learn/pwa/experimental/index.md
Labels: $-presubmit

#8082 Add missing space in /learn/pwa/os-integration/index.md
  src/site/content/en/learn/pwa/os-integration/index.md
Labels: $-presubmit

#8073 Fix typo in learn/pwa/update/index.md
  src/site/content/en/learn/pwa/update/index.md
Labels: $-presubmit

#8075 Add missing space in /learn/pwa/enhancements/index.md
  src/site/content/en/learn/pwa/enhancements/index.md
Labels: $-presubmit

#8077 Remove unwanted period in learn/pwa/detection/index.md
  src/site/content/en/learn/pwa/detection/index.md
Labels: $-presubmit

#8081 Add missing space in /learn/pwa/detection/index.md
  src/site/content/en/learn/pwa/detection/index.md
Labels: $-presubmit

#8083 Fix list markdown in /learn/pwa/windows/index.md
  src/site/content/en/learn/pwa/windows/index.md
Labels: $-presubmit

#8074 Fix broken link in learn/pwa/update/index.md
  src/site/content/en/learn/pwa/update/index.md
Labels: $-presubmit

#8089 Capitalize letter in /learn/pwa/architecture/index.html
  src/site/content/en/learn/pwa/architecture/index.md
Labels: $-presubmit

#8090 Add missing bullet in /learn/pwa/capabilities/index.md
  src/site/content/en/learn/pwa/capabilities/index.md
Labels: $-presubmit

#8084 "windows control overlay" => "window controls overlay"
  src/site/content/en/learn/pwa/windows/index.md
Labels: $-presubmit

#8103 Fixes text contrast issue in Animation Smoothness Metric doc.
  src/site/content/en/blog/smoothness/index.md
Labels: P2, $-presubmit

#8078 Sec-Fetch-Site is supported by all modern browsers
  src/site/content/en/secure/same-site-same-origin/index.md
Labels: P0, content update

#8041 Add https://webserial.io
  src/site/content/en/blog/serial/index.md
Labels: $-presubmit

#8094 update sanitizer api article align with current release plan
  src/site/content/en/blog/sanitizer/index.md
Labels: DO NOT MERGE, $-presubmit

#8136 Review 'Offline Fallback'.
  src/site/content/en/progressive-web-apps/offline-fallback-page/index.md
Labels: P2, content update

#8171 Remove outdated information and delete orphan closing tag
  src/site/content/en/blog/howbrowserswork/index.md
Labels: $-presubmit

#8123 Adds lazy loading guidance to Optimize LCP guide.
  src/site/content/en/blog/optimize-lcp/index.md
Labels: P1, content update, vitals, $-presubmit

#8200 Close block code to fix Markdown syntax error
  src/site/content/en/blog/decrease-frontend-size/index.md
Labels: content update, $-presubmit

#8166 [Blog post patch] Add missing backticks for CSS code block
  src/site/content/en/blog/stick-to-compositor-only-properties-and-manage-layer-count/index.md
Labels: content update, $-presubmit

#8132 Fixed broken link referencing to Render-tree Construction page
  src/site/content/en/blog/critical-rendering-path-render-blocking-css/index.md
Labels: content update, $-presubmit

#8167 Updated grammar
  src/site/content/en/learn/design/theming/index.md
Labels: content update, $-presubmit

#8233 Fix links in content efficiency guide
  src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md
Labels: P2, content update, $-presubmit

#8239 Update COOP/COEP article
  src/site/content/en/blog/coop-coep/index.md
Labels: content update

#8101 Article Update: Profiling Web Audio apps in Chrome
  src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
Labels: $-presubmit

#8241 Correcting /customelements title to describe the article correctly
  src/site/content/en/blog/customelements/index.md
Labels: $-presubmit

#8249 webrtc: dont use "stuns:" which is not implemented in any browser
  src/site/content/en/blog/webrtc-basics/index.md
  src/site/content/en/blog/webrtc-infrastructure/index.md
Labels: $-presubmit

#7603 Fix small text threshold explanation
  src/site/content/en/lighthouse-seo/font-size/index.md
Labels: P2, content update, $-presubmit
