Repository GoogleChrome/web.dev, pull requests merged in 2022-03, with the labels that each got.

#7446 Add double quotes to rel=preconnect occurrences
  src/site/content/en/lighthouse-performance/uses-rel-preconnect/index.md
Labels: $-presubmit

#7429 MigratingAuthors
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
Labels: $-presubmit

#7457 ContentMigrationBatch#S1WD
  src/site/content/en/blog/enabling-https-on-your-servers/index.md
  src/site/content/en/blog/indexeddb-best-practices/index.md
  src/site/content/en/blog/registering-a-custom-protocol-handler/index.md
  src/site/content/en/blog/the-amazing-powers-of-css/index.md
  src/site/content/en/blog/what-s-the-CSS-scope-pseudo-class-for/index.md
Labels: $-presubmit

#7472 Adds the link to the CrUX documentation to the responsiveness metric feedback page.
  src/site/content/en/blog/responsiveness/index.md
Labels: content update

#7459 ContentMigrationBatch#S3WD
  src/site/content/en/blog/a11y-for-teams/index.md
  src/site/content/en/blog/embind/index.md
  src/site/content/en/blog/wasm-av1/index.md
  src/site/content/en/blog/wasm-threads/index.md
  src/site/content/en/blog/web-performance-made-easy/index.md
Labels: $-presubmit

#7468 Updated Priority Hints article for Chrome 101 shipping
  src/site/content/en/fast/priority-hints/index.md
Labels: content update

#7458 ContentMigrationBatch#S2WD
  src/site/content/en/blog/introduction-to-fetch/index.md
  src/site/content/en/blog/loading-wasm/index.md
  src/site/content/en/blog/webauthn-credential-management/index.md
  src/site/content/en/blog/webcomponents-org/index.md
Labels: $-presubmit

#7469 ContentMigrationBatch#S5WD
  src/site/content/en/blog/aria-labels-and-relationships/index.md
  src/site/content/en/blog/hiding-and-updating-content/index.md
  src/site/content/en/blog/navigating-content/index.md
  src/site/content/en/blog/semantics-aria/index.md
  src/site/content/en/blog/semantics-builtin/index.md
Labels: $-presubmit

#7491 Add missing space between words on Economic Times CWV post
  src/site/content/en/blog/economic-times-cwv/index.md
Labels: $-presubmit

#7488 ContentMigrationBatch#S9WD
  src/site/content/en/blog/animating-modal-views/index.md
  src/site/content/en/blog/animations-and-performance/index.md
  src/site/content/en/blog/asymmetric-animation-timing/index.md
  src/site/content/en/blog/choosing-the-right-easing/index.md
  src/site/content/en/blog/css-vs-javascript/index.md
Labels: $-presubmit

#7485 ContentMigrationBatch#S6WD
  src/site/content/en/blog/components-examples-overview/index.md
  src/site/content/en/blog/custom-elements-best-practices/index.md.md
  src/site/content/en/blog/custom-elements-v1/index.md
  src/site/content/en/blog/text-alternatives-for-images/index.md
  src/site/content/en/blog/the-accessibility-tree/index.md
Labels: $-presubmit

#7496 Tweak media queries section for accessible tap targets
  src/site/content/en/accessible/accessible-tap-targets/index.md
Labels: $-presubmit

#7494 ContentMigrationBatch#S10WD
  src/site/content/en/blog/custom-easing/index.md
  src/site/content/en/blog/responsive-images/index.md
  src/site/content/en/blog/the-basics-of-easing/index.md
Labels: $-presubmit

#7503 Update front matter for accessible tap targets
  src/site/content/en/accessible/accessible-tap-targets/index.md
Labels: $-presubmit

#7498 Content migration batch 4
  src/site/content/en/blog/media-recording-audio/index.md
  src/site/content/en/blog/media-recording-video/index.md
  src/site/content/en/blog/native-hardware-click-to-call/index.md
  src/site/content/en/blog/native-hardware-device-orientation/index.md
  src/site/content/en/blog/native-hardware-fullscreen/index.md
Labels: $-presubmit

#7505 Content migration batch 6
  src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
  src/site/content/en/blog/push-notifications-common-notification-patterns/index.md
  src/site/content/en/blog/push-notifications-display-a-notification/index.md
  src/site/content/en/blog/push-notifications-how-push-works/index.md
  src/site/content/en/blog/push-notifications-notification-behaviour/index.md
Labels: $-presubmit

#7510 Migrates service worker lifecycle doc from d.g.c.
  src/site/content/en/reliable/service-worker-lifecycle/index.md
Labels: P1, pwa, content, $-presubmit

#7492 Content migration batch 3
  src/site/content/en/blog/manipulating-live-effects/index.md
  src/site/content/en/blog/media-eme-basics/index.md
  src/site/content/en/blog/media-eme/index.md
  src/site/content/en/blog/media-mobile-web-video-playback/index.md
  src/site/content/en/blog/mse-seamless-playback/index.md
Labels: $-presubmit

#7504 Content migration batch 5
  src/site/content/en/blog/native-hardware-user-location/index.md
  src/site/content/en/blog/push-notifications-permissions-ux/index.md
  src/site/content/en/blog/push-notifications-subscribing-a-user/index.md
  src/site/content/en/blog/push-notifications-web-push-protocol/index.md
  src/site/content/en/blog/sending-messages-with-web-push-libraries/index.md
Labels: $-presubmit

#7545 Content migration batch 8
  src/site/content/en/blog/performance-audit-next/index.md
  src/site/content/en/blog/performance-audit-prework/index.md
  src/site/content/en/blog/performance-audit-security/index.md
  src/site/content/en/blog/performance-audit-share/index.md
  src/site/content/en/blog/performance-audit/index.md
Labels: $-presubmit

#7543 Fix table markup in BFCache article
  src/site/content/en/blog/bfcache/index.md
  src/site/content/ja/blog/bfcache/index.md
  src/site/content/ko/blog/bfcache/index.md
  src/site/content/ru/blog/bfcache/index.md
Labels: $-presubmit

#7544 add link
  src/site/content/ja/blog/samesite-cookie-recipes/index.md
Labels: $-presubmit

#7553 Content migration batch 10
  src/site/content/en/blog/critical-rendering-path-measure-crp/index.md
  src/site/content/en/blog/critical-rendering-path-optimizing-critical-rendering-path/index.md
  src/site/content/en/blog/critical-rendering-path-page-speed-rules-and-recommendations/index.md
  src/site/content/en/blog/critical-rendering-path-render-blocking-css/index.md
  src/site/content/en/blog/critical-rendering-path-render-tree-construction/index.md
Labels: $-presubmit

#7586 ContentMigrationBatch#11WD
  src/site/content/en/blog/avoid-large-complex-layouts-and-layout-thrashing/index.md
  src/site/content/en/blog/debounce-your-input-handlers/index.md
  src/site/content/en/blog/optimize-javascript-execution/index.md
  src/site/content/en/blog/reduce-the-scope-and-complexity-of-style-calculations/index.md
  src/site/content/en/blog/rendering-performance/index.md
Labels: $-presubmit

#7551 Content migration batch 9
  src/site/content/en/blog/critical-rendering-path-adding-interactivity-with-javascript/index.md
  src/site/content/en/blog/critical-rendering-path-analyzing-crp/index.md
  src/site/content/en/blog/critical-rendering-path-constructing-the-object-model/index.md
  src/site/content/en/blog/critical-rendering-path/index.md
  src/site/content/en/blog/performance-audit-tools/index.md
Labels: $-presubmit

#7594 Content migration batch 13
  src/site/content/en/blog/optimizing-content-efficiency-javascript-startup-optimization/index.md
  src/site/content/en/blog/optimizing-content-efficiency-loading-third-party-javascript/index.md
  src/site/content/en/blog/optimizing-content-efficiency-optimize-encoding-and-transfer/index.md
  src/site/content/en/blog/optimizing-content-efficiency-save-data/index.md
  src/site/content/en/blog/performance-poor-connectivity/index.md
Labels: $-presubmit

#7609 fix(gh-7608): remove redundant "chapter"
  src/site/content/en/learn/pwa/service-workers/index.md
Labels: $-presubmit
