Repository GoogleChrome/web.dev, pull requests merged in 2022-04, with the labels that each got.

#7613 ContentMigrationBatch#14WD
  src/site/content/en/blog/add-touch-to-your-site/index.md
  src/site/content/en/blog/downloading-resources-in-html5-a-download/index.md
Labels: $-presubmit

#7592 ContentMigrationBatch#13WD
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/decrease-frontend-size/index.md
  src/site/content/en/blog/javascript-async-functions/index.md
  src/site/content/en/blog/monitor-and-analyze/index.md
  src/site/content/en/blog/use-long-term-caching/index.md
Labels: $-presubmit

#7625 Content migration batch 14
  src/site/content/en/blog/emscripting-a-c-library/index.md
Labels: $-presubmit

#7626 ContentMigrationBatch#15WD
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/capturing-images/index.md
  src/site/content/en/blog/push-notifications-faq/index.md
  src/site/content/en/blog/social-discovery/index.md
  src/site/content/en/blog/web-storage/index.md
  src/site/content/en/blog/webapks/index.md
Labels: $-presubmit

#7587 ContentMigrationBatch#12WD
  src/site/_data/authorsData.json
  src/site/content/en/blog/simplify-paint-complexity-and-reduce-paint-areas/index.md
  src/site/content/en/blog/speed-tools/index.md
  src/site/content/en/blog/stick-to-compositor-only-properties-and-manage-layer-count/index.md
  src/site/content/en/blog/webpack-conclusion/index.md
  src/site/content/en/blog/webpack/index.md
Labels: $-presubmit

#7593 Content migration batch 12
  src/site/content/en/blog/optimizing-content-efficiency-eliminate-downloads/index.md
  src/site/content/en/blog/performance-get-started-wrapup-7/index.md
  src/site/content/en/blog/performance-http2/index.md
  src/site/content/en/blog/performance-optimizing-content-efficiency-client-hints/index.md
  src/site/content/en/blog/performance-optimizing-content-efficiency/index.md
Labels: $-presubmit

#7555 Content migration batch 11
  src/site/content/en/blog/performance-get-started-graphicalcontent-4/index.md
  src/site/content/en/blog/performance-get-started-httpcaching-6/index.md
  src/site/content/en/blog/performance-get-started-httprequests-5/index.md
  src/site/content/en/blog/performance-get-started-textcontent-3/index.md
  src/site/content/en/blog/performance-get-started/index.md
Labels: $-presubmit

#7627 ContentMigrationBatch#16WD
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/multi-device-content/index.md
  src/site/content/en/blog/push-notifications-handling-messages/index.md
  src/site/content/en/blog/service-workers-registration/index.md
  src/site/content/en/blog/ux-basics/index.md
  src/site/content/en/blog/welcome-to-immersive/index.md
Labels: $-presubmit

#7487 ContentMigrationBatch#S8WD
  src/site/content/en/blog/animating-between-views/index.md
  src/site/content/en/blog/pwa-install-addressbar/index.md
  src/site/content/en/blog/pwa-install-patterns/index.md
  src/site/content/en/blog/rendering-on-the-web/index.md
Labels: $-presubmit

#7651 Datatransfer
  src/site/content/en/blog/datatransfer/index.md
Labels: content update

#7644 ContentMigrationBatch#S17WD
  src/site/content/en/blog/accessibility/index.md
  src/site/content/en/blog/intro-to-security-terminology/index.md
  src/site/content/en/blog/push-notifications/index.md
  src/site/content/en/blog/web-components/index.md
Labels: $-presubmit

#7655 fix: typo "vice versa"
  src/site/content/en/blog/indexeddb-best-practices/index.md
Labels: $-presubmit

#7656 ContentMigrationBatch#S18WD
  src/site/content/en/blog/csp/index.md
Labels: $-presubmit

#7648 Fix for the Aside component
  src/site/_includes/components/Aside.js
  src/site/content/en/blog/test-post/index.md
Labels: eng - UI

#7639 Treat missing type attribute as type=text in CSS
  src/scss/next.scss
  src/scss/web-components/_web-subscribe.scss
  src/styles/generic/_input.scss
Labels: eng - UI

#7664 ContentMigrationBatch#S19WD
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/Spooktacular-HTML5-Pumpkin/index.md
  src/site/content/en/blog/push-notifications-video/index.md
Labels: $-presubmit

#7683 Fix typo on homepage
  src/site/content/en/index.md
Labels: content update, $-presubmit

#7686 feat: add jhey to authors list
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
Labels: $-presubmit

#7659 New Post - GUI Challenges - Building a dialog component
  src/site/content/en/blog/building-a-dialog-component/index.md
Labels: content

#7713 Fix typo in Building a dialog component post
  src/site/content/en/blog/building-a-dialog-component/index.md
Labels: $-presubmit

#7719 Change order of Learn PWA modules.
  src/site/_data/courses/pwa/toc.yml
Labels: P0, content update

#7722 Add Learn PWA: Part 17, OS integration.
  src/site/content/en/learn/pwa/os-integration/index.md
Labels: P0, content update

#7721 Add Learn PWA: Part 18, Window management.
  src/site/content/en/learn/pwa/windows/index.md
Labels: P0, content update

#7718 Adds RebelMouse case study.
  src/site/_data/authorsData.json
  src/site/_data/i18n/authors.yml
  src/site/content/en/blog/rebelmouse/index.md
Labels: P2, vitals, $-presubmit

#7724 Add Learn PWA: Part 19, Experimental.
  src/site/content/en/learn/pwa/experimental/index.md
Labels: P0, content update

#7725 Add Learn PWA: Part 20, Tools and Debug.
  src/site/content/en/learn/pwa/tools-and-debug/index.md
Labels: P0, content update

#7726 Add Learn PWA: Part 21, Architecture.
  src/site/content/en/learn/pwa/architecture/index.md
Labels: P0, content update

#7727 Add Learn PWA: Part 22, Complexity.
  src/site/content/en/learn/pwa/complexity/index.md
Labels: P0, content update

#7673 use extension
  src/site/content/en/blog/commonjs-larger-bundles/index.md
Labels: P2, content update

#7604 Fixes a typo in the TTFB article.
  src/site/content/en/metrics/ttfb/index.md
Labels: P2, content update, vitals, $-presubmit

#7747 Add the capabilities list to 'Learn PWA'.
  src/site/content/en/learn/pwa/capabilities/index.md
Labels: P0, content

#7748 Adds images tooling report post.
  src/site/_data/authorsData.json
  src/site/content/en/blog/images-tooling-report/index.md
Labels: P1, content, $-presubmit

#7755 Implements changes requested by RebelMouse.
  src/site/content/en/blog/rebelmouse/index.md
Labels: P2, content update, $-presubmit

#7756 Fix URL of MSE article.
  redirects.yaml
  src/site/content/en/blog/media-mse-basics/index.md
Labels: P0, content update

#7763 Small typo
  src/site/content/en/fast/priority-hints/index.md
Labels: $-presubmit

#7779 Migrate `/fugu-status/` to dcc
  redirects.yaml
  src/site/content/en/blog/cds2021-updates/index.md
  src/site/content/en/blog/compute-pressure/index.md
  src/site/content/en/blog/content-indexing-api/index.md
  src/site/content/en/blog/declarative-link-capturing/index.md
  src/site/content/en/blog/eyedropper/index.md
  src/site/content/en/blog/file-handling/index.md
  src/site/content/en/blog/fugu-status/index.md
  src/site/content/en/blog/goibibo/index.md
  src/site/content/en/blog/handwriting-recognition/index.md
  src/site/content/en/blog/hid-examples/index.md
  src/site/content/en/blog/hid/index.md
  src/site/content/en/blog/launch-handler/index.md
  src/site/content/en/blog/live-wrap-up/index.md
  src/site/content/en/blog/multi-screen-window-placement/index.md
  src/site/content/en/blog/new-pwa-training/index.md
  src/site/content/en/blog/nfc/index.md
  src/site/content/en/blog/progressively-enhance-your-pwa/index.md
  src/site/content/en/blog/pwa-url-handler/index.md
  src/site/content/en/blog/serial/index.md
  src/site/content/en/blog/storage-foundation/index.md
  src/site/content/en/blog/tabbed-application-mode/index.md
  src/site/content/en/blog/url-protocol-handler/index.md
  src/site/content/en/learn/pwa/detection/index.md
  src/site/content/en/learn/pwa/experimental/index.md
  src/site/content/en/mini-apps/mini-app-conclusion/index.md
  src/site/content/en/progressive-web-apps/app-like-pwas/index.md
  src/site/content/es/blog/file-handling/index.md
  src/site/content/es/blog/fugu-status/index.md
  src/site/content/es/blog/goibibo/index.md
  src/site/content/es/blog/hid/index.md
  src/site/content/es/blog/multi-screen-window-placement/index.md
  src/site/content/es/blog/progressively-enhance-your-pwa/index.md
  src/site/content/es/progressive-web-apps/app-like-pwas/index.md
  src/site/content/es/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/ja/blog/serial/index.md
  src/site/content/ja/progressive-web-apps/app-like-pwas/index.md
  src/site/content/ko/blog/file-handling/index.md
  src/site/content/ko/blog/fugu-status/index.md
  src/site/content/ko/blog/hid/index.md
  src/site/content/ko/blog/multi-screen-window-placement/index.md
  src/site/content/ko/progressive-web-apps/app-like-pwas/index.md
  src/site/content/ko/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/pt/blog/file-handling/index.md
  src/site/content/pt/blog/fugu-status/index.md
  src/site/content/pt/blog/hid/index.md
  src/site/content/pt/progressive-web-apps/app-like-pwas/index.md
  src/site/content/pt/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/ru/blog/nfc/index.md
  src/site/content/ru/blog/serial/index.md
  src/site/content/ru/progressive-web-apps/app-like-pwas/index.md
  src/site/content/ru/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
  src/site/content/zh/blog/file-handling/index.md
  src/site/content/zh/blog/fugu-status/index.md
  src/site/content/zh/blog/multi-screen-window-placement/index.md
  src/site/content/zh/progressive-web-apps/app-like-pwas/index.md
  src/site/content/zh/progressive-web-apps/using-a-pwa-in-your-android-app/index.md
Labels: DO NOT MERGE

#7793 Add tag for "Aurora project" blog posts
  src/site/_data/i18n/tags.yml
  src/site/content/en/blog/aurora-resource-inlining/index.md
  src/site/content/en/blog/conformance/index.md
  src/site/content/en/blog/image-component/index.md
  src/site/content/en/blog/introducing-aurora/index.md
  src/site/content/en/blog/script-component/index.md
Labels: $-presubmit

#7792 Update quick start instructions for adding a tag
  src/site/content/en/handbook/quick-start/index.md
Labels: $-presubmit

#7788 minor improvements to stale-while-revalidate blog
  src/site/content/en/blog/stale-while-revalidate/index.md
Labels: $-presubmit

#7752 Fix typo
  src/site/content/en/blog/security-credential-management-retrieve-credentials/index.md
Labels: content update, $-presubmit

#7535 src/site/content/en/blog/variable-fonts/index.md
  src/site/content/en/blog/variable-fonts/index.md
  src/site/content/es/blog/variable-fonts/index.md
  src/site/content/pt/blog/variable-fonts/index.md
  src/site/content/ru/blog/variable-fonts/index.md
Labels: $-presubmit

#7771 Upgrade to Lit 2
  package-lock.json
  package.json
  src/lib/components/Assessment/index.js
  src/lib/components/AssessmentQuestion/index.js
  src/lib/components/BaseElement/index.js
  src/lib/components/Codelab/index.js
  src/lib/components/CourseSearchResults/index.js
  src/lib/components/LanguageSelect/index.js
  src/lib/components/LearnFilter/index.js
  src/lib/components/LighthouseViewer/index.js
  src/lib/components/ProfileSwitcher/index.js
  src/lib/components/ProfileSwitcherContainer/index.js
  src/lib/components/ProgressBar/index.js
  src/lib/components/ResponseMultipleChoice/index.js
  src/lib/components/ResponseThinkAndCheck/index.js
  src/lib/components/Search/index.js
  src/lib/components/SearchResults/index.js
  src/lib/components/SelectGroup/index.js
  src/lib/components/SigninButton/index.js
  src/lib/components/Snackbar/index.js
  src/lib/components/SnackbarContainer/index.js
  src/lib/components/Tabs/index.js
  src/lib/components/UrlChooser/index.js
  src/lib/components/UrlChooserContainer/index.js
  src/site/content/en/blog/how-we-build-webdev-and-use-web-components/index.md
  types/utils/npm-dependencies.d.ts
Labels: $-presubmit
