Repository GoogleChrome/web.dev, pull requests merged in 2023-03, with the labels that each got.

#9516 [RU] FID: fix multiple typos
  src/site/content/ru/metrics/fid/index.md
Labels: i18n

#9210 Add presenting slides actions to media session article
  src/site/content/en/blog/media-session/index.md
Labels: DO NOT MERGE, content update

#9593 Add Private Aggregation API testing
  src/site/_includes/partials/head.njk
Labels: eng

#9620 Add css-trig-functions blog post
  src/site/content/en/blog/css-trig-functions/index.md
Labels: DO NOT MERGE, scheduled

#9518 [RU] Optimize FID: multiple typos
  src/site/content/ru/blog/optimize-fid/index.md
Labels: i18n

#9764 feat: clean up old design system `w-tooltip` class
  .eleventy.js
  src/lib/components/CopyCode/index.js
  src/site/_includes/components/Tooltip.js
  src/styles/components/_all.scss
  src/styles/components/_tooltips.scss
Labels: eng

#9766 feat: remove unused Nunjucks files
  .eleventy.js
  src/site/_includes/components/Breadcrumbs.js
  src/site/_includes/components/Hero.js
  src/site/_includes/default.njk
  src/site/_includes/macros/patterns-card.njk
  src/site/_includes/partials/course-cards-next.njk
  src/site/_includes/partials/course-cards.njk
  src/site/_includes/partials/navigation-drawer-default.njk
  src/styles/components/_all.scss
  src/styles/components/_breadcrumbs.scss
  src/styles/components/_images.scss
Labels: eng

#9720 fix: replace old design templates with new design system
  .eleventy.js
  src/site/_data/i18n/common.yml
  src/site/_includes/about.njk
  src/site/_includes/codelab.njk
  src/site/_includes/collection.njk
  src/site/_includes/core.njk
  src/site/_includes/course.njk
  src/site/_includes/default-next.njk
  src/site/_includes/default.njk
  src/site/_includes/explore.njk
  src/site/_includes/handbook.njk
  src/site/_includes/homepage.njk
  src/site/_includes/item-page.njk
  src/site/_includes/landing-page.njk
  src/site/_includes/learn-page.njk
  src/site/_includes/newsletter.njk
  src/site/_includes/partials/footer.njk
  src/site/_includes/partials/head.njk
  src/site/_includes/partials/header-default.njk
  src/site/_includes/pattern-page.njk
  src/site/_includes/pattern-set.njk
  src/site/_includes/post.njk
  src/site/_includes/show.njk
  src/site/_includes/spaces.njk
  src/site/_includes/text.njk
  src/site/_transforms/purify-css.js
  src/site/content/en/chrometober-2022/index.njk
  src/site/content/en/design-system/components-preview.njk
  src/site/content/en/design-system/design-system.11tydata.json
  src/site/content/en/design-system/prototype.njk
  src/site/content/en/measure/index.njk
  src/site/content/en/newsletter/index.njk
  src/site/content/en/offline.md
  src/site/content/en/podcasts/index.njk
  src/site/content/es/offline.md
  src/site/content/ja/offline.md
  src/site/content/ko/offline.md
  src/site/content/pl/offline.md
  src/site/content/pt/offline.md
  src/site/content/ru/offline.md
  src/site/content/zh/offline.md
  src/styles/components/_all.scss
  src/styles/components/_header-default.scss
Labels: eng
