Repository GoogleChrome/web.dev, pull requests merged in 2023-01, with the labels that each got.

#9380 Update payment articles
  src/site/content/en/payments/android-payment-apps-developers-guide/index.md
  src/site/content/en/payments/empowering-payment-apps-with-web-payments/index.md
  src/site/content/en/payments/handling-optional-payment-information/index.md
  src/site/content/en/payments/orchestrating-payment-transactions/index.md
  src/site/content/en/payments/registering-a-web-based-payment-app/index.md
  src/site/content/en/payments/setting-up-a-payment-method/index.md
  src/site/content/en/payments/web-based-payment-apps-overview/index.md
Labels: DO NOT MERGE

#9406 Disable autoplay when using prefers reduced motion
  src/lib/app.js
Labels: eng

#9425 Adds the optimize time to first byte guide.
  src/site/_data/paths/fast.json
  src/site/content/en/blog/optimize-ttfb/index.md
  src/site/content/en/metrics/ttfb/index.md
Labels: P1, content

#9429 Tweaks language around relative TTFB values.
  src/site/content/en/blog/optimize-ttfb/index.md
Labels: P0

#9442 Updates the Optimize INP guide with info on Lighthouse's timespan mode.
  src/site/content/en/blog/optimize-inp/index.md
Labels: P1, content update

#9417 Move to webdev-infra's `{% BrowserCompat %}` widget
  .eleventy.js
  package-lock.json
  package.json
  src/scss/blocks/_browser-compat.scss
  src/scss/next.scss
  src/site/_data/i18n/browser_compat.yml
  src/site/_includes/components/BrowserCompat.js
  src/site/_utils/browserCompat.js
  test/unit/src/site/_includes/components/BrowserCompat.js
  test/unit/src/site/_includes/components/index.js
  test/unit/src/site/_utils/browserCompat.js
  test/unit/src/site/_utils/index.js
Labels: eng
